### ISSUE TITLE
Android Unit test failed when using SqlCipher DB

### ISSUE THREAD

**Issue by sunilmishra** [sqlcipher/android-database-sqlcipher#105]
Hi,

I am facing problem when using sqlcipher in my project.  My project is running fine without UnitTest with Cipher. 

 But when using Cipher, 
09-30 15:53:32.877: I/TestRunner(11663): java.lang.NullPointerException
09-30 15:53:32.877: I/TestRunner(11663):    at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:101)

Can you please suggest me how to resolve this issue.

**Comment by PareshMayani** [comment]
@developernotes when using SQLCipher, can we write test cases using Robolectric? Would it work because Robolectric executes test cases on JVM!

**Comment by developernotes** [comment]
Hello @PareshMayani 

Unfortunately that would not work.  While Robolectric does run its tests on the JVM, SQLCipher for Android contains native libraries that target specific platforms for the Android runtime, thus they would not run on the JVM that is on your desktop.  As an alternative, we have put together a SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) which allows you to run JUnit-esque tests that would run on device/emulator.
