### ISSUE TITLE
Application can not be signed while using SQLCipher

### ISSUE THREAD

**Issue by KinjalDroid** [sqlcipher/android-database-sqlcipher#116]
I am using SQLCipher library to encrypt database in Android.
It works perfectly fine and database is also get encrypted.
But I am using Proguard for better security..so when i am going to sign app, Proguard gives me error like "Proguard returned with error code 1.See console"

And in console, it shows too many warning.. 

 Warning: com.google.common.base.Equivalence: can't find referenced class javax.annotation.Nullable
Warning: com.google.common.base.Objects$ToStringHelper: can't find referenced class javax.annotation.Nullable  
Warning: com.google.common.base.Predicates$AndPredicate: can't find referenced class javax.annotation.Nullable
 Warning: there were 607 unresolved references to classes or interfaces.
 You may need to specify additional library jars (using '-libraryjars').
java.io.IOException: Please correct the above warnings first.

If anyone know,please correct me. 
Thanks..

**Comment by fikr4n** [comment]
It disabled obfuscation/shrinking for sqlcipher :(.
Why exactly sqlcipher cannot be obfuscated? Does it use such a dynamic class/method loading?

**Comment by developernotes** [comment]
Hello @fikr4n 

We provide a sample reference, however you may be able to make adjustments to the ProGuard that still allows for proper execution.  Have you run into a problem removing the `-dontobfuscate` flag?  You will likely need to include something such as `native <methods>;` within a keep clause.

**Comment by fikr4n** [comment]
I mean it works, but disabling the obfuscation. So the point is my question:

> Why exactly sqlcipher cannot be obfuscated? Does it use such a dynamic class/method loading?

Thank you for fast reply :+1:

**Comment by developernotes** [comment]
Hi @fikr4n 

>I mean it works, but disabling the obfuscation.

Did you try removing the `-dontobfuscate` flag and adding the `native <methods>;` within a keep clause? We do not provide ProGuard solutions for all configurations, the included configuration is just a sample.

**Comment by fikr4n** [comment]
Of course `-dontobfuscate` is removed, the main code would be obfuscated, but sqlcipher would not.
