### ISSUE TITLE
SqliteDatabase.java

### ISSUE THREAD

**Issue by otiasj** [sqlcipher/android-database-sqlcipher#142]
I think there is a bug in sqlcipher/.../SQLiteDatabase.java

around line 950 : the 2 openDatabase methods are overriding the parameter flags with CREATE_IF_NECESSARY

    public static SQLiteDatabase openDatabase(String path, String password, CursorFactory factory, int flags) {
      return openDatabase(path, password.toCharArray(), factory, CREATE_IF_NECESSARY, null);
    }

    public static SQLiteDatabase openDatabase(String path, char[] password, CursorFactory factory, int flags) {
      return openDatabase(path, password, factory, CREATE_IF_NECESSARY, null);
    }

this is bad if you are using your own database and want to use the flags for example :
SQLiteDatabase.OPEN_READONLY | SQLiteDatabase.NO_LOCALIZED_COLLATORS

**Comment by brodybits** [comment]
Just issued PR #173 with a solution.
