### ISSUE TITLE
ant ProGuard fail

### ISSUE THREAD

**Issue by 79144876** [sqlcipher/android-database-sqlcipher#146]
[proguard] Initializing...
 [proguard] Warning: net.sqlcipher.DatabaseUtils: can't find referenced class org.apache.commons.codec.binary.Hex
 [proguard] Warning: net.sqlcipher.DatabaseUtils: can't find referenced class org.apache.commons.codec.binary.Hex

**Comment by Virthuss** [comment]
I have exactly the same error, did you manage to fix it?

**Comment by developernotes** [comment]
@Virthuss what version of SQLCipher for Android are you using?  Can you reproduce it with the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by Virthuss** [comment]
I finally succeed to use it without having any error.

I used proguard, with the following, configuration, may it help someone.

                                                 ____

-dontwarn com.google.android.gms.**
-dontwarn com.google.common.**
-dontwarn com.google.common.**
-dontwarn net.sqlcipher.**

-allowaccessmodification
-optimizations !code/simplification/arithmetic
-keepattributes *Annotation*

-keep public class com.google.android.gms.** { public *; }

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keep class net.sqlcipher.** {
    *;
}
-dontwarn android.support.v7.**
-keep class android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }

**Comment by developernotes** [comment]
@Virthuss we are glad to hear it is working well for you, thanks for the update!
