### ISSUE TITLE
I want add the source code to my project's Jni folder

### ISSUE THREAD

**Issue by 79144876** [sqlcipher/android-database-sqlcipher#148]
Hi , i just want add the source code to my project.
I will build sqlcipher by myself.
I have try to use Facebook buck to build my project. so i need do like this:https://github.com/facebook/buck/blob/4528b366500ce64b4295c23f45bf6eed13365b11/test/com/facebook/buck/android/testdata/exopackage-device/jni/one/Android.mk
I mean sqlcipher is one of my jni project.
Which file that i need copy to my jni folder?
I have make init this :https://www.zetetic.net/sqlcipher/sqlcipher-for-android/
(download platform-frameworks-base fail,because this too large.)
Thanks.

**Comment by 79144876** [comment]
I mean:
1.create new android project (name :Demo)
2.create jni folder
3.copy your file to jni folder.
4.run 'ndk-build'
....build demo.apk
How to do this (third step)?
Thanks.

**Comment by developernotes** [comment]
I do not generally directly embed the source to SQLCipher for Android within a project.  Have you tried to just submodule SQLCipher for Android within your project?  You will need to allow for `make init` to complete as it requires all submodules to be present for building.

**Comment by 79144876** [comment]
Thanks. I got it.
