### ISSUE TITLE
openssl update to 1.0.1h

### ISSUE THREAD

**Issue by PeterRosenberg** [sqlcipher/android-database-sqlcipher#149]
When publishing an app using sqlcipher on Google Play, it complains, that the app contains an insecure openssl version what is located in the file libsqlcipher_android.so from sqlcipher.
Please update it to 1.0.1h to remove this security alert.

**Comment by developernotes** [comment]
Hi @PeterRosenberg,

Thanks for the report, we will look into this.

**Comment by PeterRosenberg** [comment]
Thanks @developernotes for that. Any news?

**Comment by developernotes** [comment]
Hi @PeterRosenberg 

Not at this time, however we will update OpenSSL with our next release.

**Comment by PeterRosenberg** [comment]
Perfect, thank you.

**Comment by modan75** [comment]
Hi
Google send us two alert messages about old version OpenSSL (version 1.0.1g), saying that application will be removed if we don't upgrade OpenSSL version.
I have compiled the source, with the new OpenSSL (versions 1.0.1h, 1.0.1i, 1.0.1j) changing in external/android-libs libcrypto.a with the new version. The compilation was successful, it works fine on android 4.x, but on android 2.3 the application stops without any error message at line with SQLiteDatabase.loadLibs(context). Do you have any idea why this could happen?
Thanks

**Comment by developernotes** [comment]
Hi @modan75 

It is difficult to say why your application crashed.  Did you use the script provided within the repo to rebuild OpenSSL?  Could you try using your build with the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) and let us know your results?

**Comment by modan75** [comment]
Hi @developernotes 

Thank you very much, the problem was that I wasn't using the script provided within the repo to compile OpenSSL. Now it works with latest OpenSSL version 1.0.2

**Comment by JgdshSeerm** [comment]
Hi @developernotes,@modan75
  we were also facing the same old version OpenSSL (version 1.0.1g) saying that application will be removed if we don't upgrade OpenSSL versiona as google stated.I didnt find current android-database-sqlcipher is update with OpenSSL version 1.0.2.So please send me the latest .so file if you have or can you guide me in this process

**Comment by developernotes** [comment]
Hi @JgdshSeerm 

The latest release of SQLCipher for Android uses OpenSSL 1.0.2g, you can find out more information about the release [here](https://discuss.zetetic.net/t/sqlcipher-3-4-0-release/1273).
