### ISSUE TITLE
PHONE_NUMBERS_EQUAL no longer works

### ISSUE THREAD

**Issue by stevegryphn** [sqlcipher/android-database-sqlcipher#15]
It seems that the PHONE_NUMBERS_EQUAL function from SQLite no longer works once the database is switched over to SQLCipher.  It's throwing the following error:
info.guardianproject.datbase.sqlcipher.SQLiteException: no such function: PHONE NUMBERS EQUAL
The code was working correctly immediately before being switched to SQLCipher.
This might be an issue with SQLCipher or an issue with an extension that doesn't interact properly with SQLCipher as opposed to SQLite.

**Comment by k-babu** [comment]
Has PHONE_NUMBERS_EQUAL been removed from 3.5.3 as well ? It was working fine with 3.4. Now, I see the following error :
net.sqlcipher.database.SQLiteException: no such function: PHONE_NUMBERS_EQUAL:

**Comment by developernotes** [comment]
Hi @k-babu 

Yes, that was removed during the upgrade of the library to support Android N, [here](https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465) is the release announcement.

**Comment by sahithivaddi** [comment]
Has PHONE_NUMBERS_EQUAL been removed from 3.5.9 as well ? What is the alternative for this  ? what all functions are not supported by SqlCipher compared to android SQLite. Please confirm and let us know if it is already resolved. Thank you .

**Comment by developernotes** [comment]
Hi @sahithivaddi 

This was initially addressed [above](https://github.com/sqlcipher/android-database-sqlcipher/issues/15#issuecomment-239524348) regarding the removal of `PHONE_NUMBERS_EQUAL`. You would likely need to build your own function for handling this using something like [`sqlite3_create_function`](https://www.sqlite.org/c3ref/create_function.html), then load the function via the [extension loading interface](https://www.sqlite.org/lang_corefunc.html#load_extension).
