### ISSUE TITLE
sqlite / sqlcipher API inconsistency 

### ISSUE THREAD

**Issue by alipov** [sqlcipher/android-database-sqlcipher#150]
Hi,

Is there a reason why *SQLiteStatement#executeUpdateDelete()* 's return type is **long**, instead of **int** (as specified in [Android's API](http://developer.android.com/reference/android/database/sqlite/SQLiteStatement.html#executeUpdateDelete()))?

The value in any case comes from *mDatabase.lastChangeCount()*, which is **int** by itself, so I don't understand why to change the type. Could you please elaborate?

Thanks!
Alex.

**Comment by developernotes** [comment]
Hello @alipov 

Thank you for the inquiry, as it turns out, the call to `lastChangeCount()` internally calls SQLite `sqlite3_changes` which returns an `int`.  This is likely a historical mistake, we will correct the return signature.  Thanks!

**Comment by alipov** [comment]
Hi @developernotes 

Half year passed and this issue not yet fixed.
Would you like me to open a pull request?

Alex.

**Comment by developernotes** [comment]
Hello @alipov 

Thank you for the reminder, I have made the change in the following [commit](https://github.com/sqlcipher/android-database-sqlcipher/commit/20cbc60b8a5ad49f6c99f115dae958362171f657).

**Comment by alipov** [comment]
Great, thanks!
