### ISSUE TITLE
Couldn't load sqlcipher_android from loader dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by akashqss** [sqlcipher/android-database-sqlcipher#152]
Hello I am new on android and want to implement this. I have download this and when wanted to run  then it produced below error

java.lang.UnsatisfiedLinkError: Couldn't load sqlcipher_android from loader dalvik.system.PathClassLoader[DexPathList[dexElements=[zip file "/data/app/net.sqlcipher-1.apk"],nativeLibraryDirectories=[/data/app-lib/net.sqlcipher-1, /vendor/lib, /system/lib]]]: findLibrary returned null

Please help me how to resolve this.

**Comment by developernotes** [comment]
Hello @akashqss 

This is likely due to not properly including the native libraries with your application.  [Here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/) is a tutorial on integrating the library with an Android application.
