### ISSUE TITLE
Building the sqlcipher-android on ubuntu fail,ant release fail

### ISSUE THREAD

**Issue by pan2636119599** [sqlcipher/android-database-sqlcipher#153]
Hi !

I try to build sqlcipher -android on ubuntu .

I use git to copy the source code,make init to download the submodule.

It seems all goes well,so I use make command to build the source code,then some eroors occur.

At first ,I can only find 2 so files in dir external/libs ,they are libsqlcipher_android.so and libstlport_shared.so,but I also can find 3 so files in dir obj/local. Is it normal?

Second,no any jar were generated,and some tips like this:

make: execvp: ant: Permission denied

My Machine did not install ant program,so I Install apache-ant-1.9.4 and make again,then i get the tips like this:

ant release
Buildfile: build.xml does not exist!

How I can fix this issue?or If I do something wrong?

thanks so much!

**Comment by developernotes** [comment]
It appears that your `ant` installation is not properly configured.  Could you try running `ant`, or possibly reinstall it from your package manager?

**Comment by pan2636119599** [comment]
Thanks for your answer，but it seems not work。

I try to reinstall ant with the command "apt-get install ant1.7".

after the install were complete,I can see the tips with the command "ant -version"

root@ubuntu:~/android/projects2/android-database-sqlcipher# ant -version
Apache Ant version 1.7.1 compiled on September 3 2011

so I try to make again (project in dir /root//android/projects2/android-database-sqlcipher,and I type make command in dir /root//android/projects2/android-database-sqlcipher too).

Unfortunately,nothing change,i can not get any jar,the tips were the same, like this:

[x86] Install        : libdatabase_sqlcipher.so => jni/libs/x86/libdatabase_sqlcipher.so
[x86] Install        : libstlport_shared.so => jni/libs/x86/libstlport_shared.so
make[1]: Leaving directory `/root/android/projects2/android-database-sqlcipher/jni'
ant release
Buildfile: build.xml does not exist!
Build failed
make: *** [build-java] Error 1

How  can I get the build.xml ?

**Comment by developernotes** [comment]
The build.xml file is generated from executing `make init`.  Please post the output you receive from running that command if running it again does not generate the build.xml file.

**Comment by zaczqs** [comment]
in the Makefile,add "-t android-19":

android update project -p . -t android-19

**Comment by pan2636119599** [comment]
@zaczqs  @developernotes   
I had add -t android -19 and reinstall android simulator,then make again.All goes Well. Thanks you Two so much.
