### ISSUE TITLE
Statically linking libcrypto

### ISSUE THREAD

**Issue by rossimo** [sqlcipher/android-database-sqlcipher#154]
Why is libcrypto statically linked? Are there versions of Android that do not ship with OpenSSL's shared libraries?

**Comment by developernotes** [comment]
Hello @rossimo,

OpenSSL is included within Android, unfortunately given the wide spread of platform devices, the versions of OpenSSL vary quite dramatically.  Including a static link of OpenSSL guarantees we are using the same version within SQLCipher, regardless of the Android platform we are running on.
