### ISSUE TITLE
how many apps Use this?

### ISSUE THREAD

**Issue by Cedybt** [sqlcipher/android-database-sqlcipher#155]
hey 
 am just curious to know this,
can you give me a list of apps Using SQLcipher?

thanks

**Comment by brodybits** [comment]
I made a version of the Cordova sqlite plugin that includes sqlcipher for Android and iOS here: https://github.com/brodysoft/Cordova-sqlcipher-adaptor

**Comment by developernotes** [comment]
Would you mind moving this over to the [SQLCipher](https://discuss.zetetic.net/c/sqlcipher) discuss page?  I would be glad to share on this topic, but would like to keep Github issues open to an area for those to report issues alone.  Thanks!
