### ISSUE TITLE
rawQueryWithFactory does not return the factory type

### ISSUE THREAD

**Issue by Grunthos** [sqlcipher/android-database-sqlcipher#157]
I expect the call:

> rawQueryWithFactory(SOME_FACTORY, sql, args, null);

to return a cursor whose class is the same as the class created by the factory.

It seems to return a CursorWrapper instead.

I could call 'getWrappedCursor()', but obviously fear the possibility I will be trampling on SqlCipher internals.

Can someone shed some light on why my factory type is not being returned?

**Comment by developernotes** [comment]
Hello @Grunthos 

I believe the `CursorWrapper` was introduced to support the `getType()` call on users targeting API < 11.

**Comment by Grunthos** [comment]
Any chance it could be made conditional on the API level?

And...would I be correct in assuming that 'unwrapping' it will have no consequences if my API is >= 11?

**Comment by developernotes** [comment]
Hello @Grunthos 

I would prefer to not introduce divergent behavior based on the API version in that regard.  If you mean by calling `getWrappedCursor()`, that should be fine.
