### ISSUE TITLE
Use SQLCipher with existing database in my app

### ISSUE THREAD

**Issue by aritraroy** [sqlcipher/android-database-sqlcipher#158]
I have my app running on the Play Store. I now want to secure my database with SQLCipher. 

Is there a way to use this library with my existing database?

Any help is really appreciated.

**Comment by developernotes** [comment]
Hello @aritraroy 

You can import an existing plain text SQLite database and encrypt it.  To do so, take a look at the [`sqlcipher_export(…);`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) function within the documentation, specifically example 1.

**Comment by aritraroy** [comment]
Thanks a lot for it. 

1) This will create a new database and encrypt the contents of the original database inside the new one?

2) I am using the original database all over my app? So do I need to update my code in all places for the new database?

3) When I provide the update for my app, should this export method run only once? I should I handle this? 

It would be awesome if I can get some example and help on how can I seamlessly handle this situation of migrating from an unencrypted database to an encrypted one?

Thanks in advance.

**Comment by developernotes** [comment]
Hello @aritraroy 

>1) This will create a new database and encrypt the contents of the original database inside the new one?

The `ATTACH` command will create a database file, if it does not already exist.

>I am using the original database all over my app? So do I need to update my code in all places for the new database?

You would need to make changes to your application if you want all database operations to interface with the SQLCipher database instead.  This would be up to you and the application requirements.

>3) When I provide the update for my app, should this export method run only once? I should I handle this?

You should only need to perform an export once, as the export command will replicate the schema and data from the plain text database into an encrypted database.

For more information regarding use cases, please take a look at the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests).

**Comment by aritraroy** [comment]
Okay thanks a lot for all the help. So the ATTACH command creates a new database and the original database is also there as it is? So I now have one original database with unencrypted data and SQLCipher creates another one with the encrypted data?

Next time when I use SQLCipher, my original database is unchanged and the new database get updates? IS that how it works?

It would be really helpful if I can get some explanation on this.

**Comment by developernotes** [comment]
Hello @aritraroy 

>Okay thanks a lot for all the help. So the ATTACH command creates a new database and the original database is also there as it is? So I now have one original database with unencrypted data and SQLCipher creates another one with the encrypted data?

Correct

>Next time when I use SQLCipher, my original database is unchanged and the new database get updates? IS that how it works?

This entirely depends on the requirements of your application and how you develop it.  It is up to you and your organization what should become of the plain text database.
