### ISSUE TITLE
Update Project README to Reflect Current Status

### ISSUE THREAD

**Issue by commonsguy** [sqlcipher/android-database-sqlcipher#159]
The first couple of paragraphs of the `README` have a couple of problems:

1. The link to the binary download points to SQLCipher for Android 2.1.1, which is rather old

2. The support paragraph cites support through 4.4, when I am pretty sure that SQLCipher for Android supports 5.0 and 5.1

**Comment by developernotes** [comment]
Hi @commonsguy 

Thanks for pointing out some areas which needed updating.  I've updated those above items in the master branch.  Thanks!
