### ISSUE TITLE
attempt to write a readonly database, crashes on android 5.0v devices while using SqlCipher

### ISSUE THREAD

**Issue by praveenb** [sqlcipher/android-database-sqlcipher#161]
Im getting following log on app crash, on android 5.0v devices

Caused by: net.sqlcipher.database.SQLiteException: attempt to write a readonly database
at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2096)
at net.sqlcipher.database.SQLiteDatabase.(SQLiteDatabase.java:1962)
at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:881)
at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:913)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:132)
at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:99)
at PackageName.DBHelperCipher.(DBHelperCipher.java:93)
at PackageName.ProcessDBCipherInitTask.doInBackground(ProcessDBCipherInitTask.java:20)
at PackageName.ProcessDBCipherInitTask.doInBackground(ProcessDBCipherInitTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)

I've submitted a question on StackOverflow, http://stackoverflow.com/q/29988933/341443.
Can you please help on this.

Thank you.

**Comment by developernotes** [comment]
Hello @praveenb 

Are you able to replicate the crash on your 5.0 device when running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by praveenb** [comment]
@developernotes Thank you so much for your kind reply,
I run the test suite on Android 5.0 device, Though I see a crash at some other test condition, I do not see a crash resulting error log given above.  i.e I'm not able to replicate above crash. 

Not sure where im doing mistake in my code. I think i need to investigate further in test suite to handle the issue in my project.

But, I just like to ask,..  you have any other suggestions or guidelines for me on this. 

Thank you.

**Comment by developernotes** [comment]
Hello @praveenb 

Do you have a specific test case that is failing consistently in the test suite?

With regard to your specific scenario though, does the database file exist **right** before you initialize the `DBHelperCipher` instance?

**Comment by praveenb** [comment]
@developernotes, 

there is no database file exist before initialize the class...
Just for clarification, I published app to Play Store, I see app crashes, When I do a fresh install from play store, on a android 5.0v device.

Thanks

**Comment by developernotes** [comment]
Hello @praveenb 

I am wondering if there is an issue within the internals of `getWritableDatabase()`.  As an experiment, could you try invoking `SQLiteDatabase.openOrCreateDatabase(…);` before you initialize your `EventDataSQLHelper` only when the database file does not exist before hand?  Could you let us know your results?  Thanks!

**Comment by praveenb** [comment]
Im getting the same error, invoking SQLiteDatabase.openOrCreateDatabase(…); method

Thanks

**Comment by developernotes** [comment]
Hello @praveenb 

If you can prepare a test within the test suite, I would be glad to take a look at it on a Lollipop device.

**Comment by praveenb** [comment]
Hi @developernotes ,

Please see this link https://github.com/praveenb/sqlcipher-android-tests, I added test class to test suite. Please see committed code changes.

Thank you.

**Comment by chetan1011** [comment]
Hi @developernotes ,

I am getting the same error,error code 8: attempt to write a readonly database

When I am write(Insert) record in databse at this time I am getting this error in lolipo device.

please help me ...


FYI, I see this issue on Lenovo A7000-a, Lollipop device. Please help on this.

**Comment by developernotes** [comment]
Hello @chetan1011 

Can you verify whether the database file exists before you attempt to write to it?

**Comment by praveenb** [comment]
Hi @developernotes ,

You are able to look at the test suit changes that i made at this link https://github.com/praveenb/sqlcipher-android-tests.

Please let me know if you need any other details 

Thank you.

**Comment by chetan1011** [comment]
Hello @developernotes ,

The Database was store in sdcard...
and i take  permission in android manifest "android.permission.WRITE_EXTERNAL_STORAGE"

**Comment by developernotes** [comment]
Hello @chetan1011 

Can you verify whether the database file exists on the SD card prior to any attempts to interact with it via the SQLCipher API?  Thanks!

**Comment by BenPope** [comment]
I'm having a similar problem.
ls -al /storage/emulated/0/Android/data/com.app.name/files/data.db
-rw-rw---- u0_a165  sdcard_r    38912 2015-05-28 21:31 data.db

It's weird.  The app manages to write the database on startup.

It also fails miserably if I try to put it into EXCLUSIVE locking mode, could it somehow be trying to lock the file more than once?

**Comment by chetan1011** [comment]
Hello @developernotes ,

@developernotes Thank you so much for your kind reply,

Yes sir, i check whether the database file is exist or not in sdcard...at that time database is exist in sdcard..

I mean database file is exist in sdcard...

still Im getting the same error, android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.

Please let me know if you need any other details

Thank you.

**Comment by brodybits** [comment]
FYI the same problem (crash with `net.sqlcipher.database.SQLiteException: attempt to write a readonly database`) is also discussed in: https://discuss.zetetic.net/t/sqlcipher-on-android-5-0-x64-emulator-crash/286

> still Im getting the same error, android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.

@chetan1011 looks like it _may_ be the same problem as #139.

**Comment by brodybits** [comment]
According to the documentation in http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html, and also in the Javadoc, it is possible that `SQLiteDatabase.openDatabase` (and `SQLiteDatabase.openOrCreateDatabase()`) can throw a `SQLiteException` if it cannot open the database for some reason. It should be the responsibility of the application to catch and handle this error. I wonder if we should add `throws SQLException` to the declaration of these functions to avoid these crashes?

**Comment by chetan1011** [comment]
Hello brodybits, 
Thank you so much for your kind reply,

I am use following code:
database = SQLiteDatabase.openOrCreateDatabase(db_path, "******",
					null);
SQLiteStatement insertStmt = database.compileStatement(insertQuery);
recordId = insertStmt.executeInsert();

then i got "attempt to write a read only database"

if you hve any solution then please give me your solution ya any sample...

please help me dude...

**Comment by brodybits** [comment]
@chetan1011 can you post the log to show _where_ your application is failing?

**Comment by chetan1011** [comment]
HI @brodybits ,
bellow I post my log where i failing application..

05-29 17:55:20.391: W/System.err(4598): net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
05-29 17:55:20.391: W/System.err(4598): 	at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
05-29 17:55:20.391: W/System.err(4598): 	at net.sqlcipher.database.SQLiteStatement.executeInsert(SQLiteStatement.java:84)
05-29 17:55:20.391: W/System.err(4598): 	at com.esense.topscorer.scratchcard.QueryCreator.insertRecords(QueryCreator.java:94)
05-29 17:55:20.391: W/System.err(4598): 	at com.esense.topscorer.scratchcard.InsertImpl.runQuery(InsertImpl.java:18)
05-29 17:55:20.391: W/System.err(4598): 	at com.esense.topscorer.scratchcard.BaseAsyncDBOperation.doInBackground(BaseAsyncDBOperation.java:56)
05-29 17:55:20.391: W/System.err(4598): 	at com.esense.topscorer.scratchcard.BaseAsyncDBOperation.doInBackground(BaseAsyncDBOperation.java:1)
05-29 17:55:20.391: W/System.err(4598): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
05-29 17:55:20.391: W/System.err(4598): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-29 17:55:20.391: W/System.err(4598): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
05-29 17:55:20.391: W/System.err(4598): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-29 17:55:20.391: W/System.err(4598): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-29 17:55:20.391: W/System.err(4598): 	at java.lang.Thread.run(Thread.java:818)

please help me..

**Comment by brodybits** [comment]
@chetan1011, for some reason your case is different from the OP. In your case, `openOrCreateDatabase()` succeeds but `insertStmt.executeInsert()` is failing. Can you log and post the string value of db_path?

**Comment by chetan1011** [comment]
@brodybits dbpath is valid...

it's database file and it's exist in sdcard...

**Comment by brodybits** [comment]
Just issued PR #174 with fixes to show where `SQLiteDatabase.dbopen` is actually failing. If you are having problems, please try again with these changes and report your results.

**Comment by developernotes** [comment]
@chetan1011 you may want to hold off on #174 right now, there is still some work going on there.

**Comment by brodybits** [comment]
Just reworked the changes in PR #175 to show where `SQLiteDatabase.dbopen()` is actually failing, waiting for review.

**Comment by developernotes** [comment]
@brodybits will check it out shortly, just finishing some work on cleaning up ICU loading.

**Comment by brodybits** [comment]
> @brodybits will check it out shortly, just finishing some work on cleaning up ICU loading.

:+1: Testing #175 uncovered an issue that I reported in #176. I will look further tomorrow night or early next week.

Thanks for integrating my fixes so far!

**Comment by chetan1011** [comment]
@developernotes ,@brodybits good morning,

HI Sir, still I am getting the same error, android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.

how can solve this error..?

please help me

**Comment by brodybits** [comment]
Good morning @chetan1011,

This project has been updated to report a more specific error in the native
code (built from C++). Please get the latest changes from this project, do
`make clean`, and rebuild.

**Comment by developernotes** [comment]
Hello @praveenb @chetan1011 

Please post the path your application is using within the SD card to store/access the database.  There were some [changes](http://android.stackexchange.com/a/77436) introduced around 4.4 to adjust the `WRITE_EXTERNAL_STORAGE` permission on Android that could be the cause depending on the path you are using.

**Comment by praveenb** [comment]
Hi Nick, I see the  changes http://android.stackexchange.com/a/77436, link, that makes sense.

please see this file which i created in from forked test suit,
https://github.com/praveenb/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ExternalPathDatabaseTest.java

i'm following the same code to get external path and to store db file.
please let me know your thoughts on it.

Thank you.

**Comment by praveenb** [comment]
Hi @developernotes ,
For now, I think the only solution is, to move db file to internal storage, which works on >5.0 devices too.

Thank you.

**Comment by mkovalyk** [comment]
Any updates on this issue?

**Comment by ruijun** [comment]
@praveenb  @developernotes How to solve this problem??

**Comment by praveenb** [comment]
@developernotes , My Android application got negative reviews :-1: , for using this library in app. As its not supported on few Android devices. I feel bad for choosing this library. I'm thinking to remove my app from Playstore  and do a new app using normal Sqlite db classes to support all devices.

I don't recommend this to anybody. Though its a free library version, Once you used in app, you'll end up like me. Hope it helps somebody.

**Comment by ahfchan** [comment]
Hi,

Thanks for raising and looking into this issue.

I'm experiencing the same problem, too - using sqlcipher 3.3.0 natively on Android 5.0.  Is there a solution to this problem, besides putting the Db on internal storage?  

Thank you.

**Comment by developernotes** [comment]
Hello @ahfchan 

What is the full path to the database on the SD card that you are unable to write to?  What permissions does your application require?

**Comment by ahfchan** [comment]
Hi @developernotes 

Thanks for the reply. I've tried a few tests and still encountered the same 'attempt to write a readonly database' issue on my Redmi Note 2 device running Android 5.0.2

case 1: no physical sd card inserted (i.e. emulated)

The full path is: /storage/emulated/0/Android/data/<package>/files/MyApp/chat.db  The root dir was retrieved with the Android call Context.getExternalFilesDirs(null) (or getExternalFilesDirs(null)[0] which yields the same result).

case 2: with sd card

The full path is: /storage/sdcard1/Android/data/<package>/files/MyApp/chat.db with getExternalFilesDirs(null)[1] 


Both cases: the db file was created, the app was also able to write to the log file placed in the same directory.  When attempting to insert a record into the db, I get an the error 'attempt to write a readonly database'

Checking the permissions using adb shell on the db file:
-rwxrwx--- u0_a129  sdcard_r

, and the directories <package>, 'files', MyApp':
drwxrwx--- u0_a129  sdcard_r 

The permissions needed by my app are:
**android.permission.WRITE_EXTERNAL_STORAGE**
android.permission.VIBRATE
android.permission.INTERNET
android.permission.ACCESS_NETWORK_STATE
android.permission.GET_ACCOUNTS
android.permission.WAKE_LOCK
android.permission.RECORD_AUDIO
android.permission.MODIFY_AUDIO_SETTINGS
com.google.android.providers.gsf.permission.READ_GSERVICES
android.permission.ACCESS_COARSE_LOCATION
android.permission.ACCESS_FINE_LOCATION
 

Would appreciate any insight you can provide on the issue. Please let me know if I could provide any additional info to assist.

Thanks.

**Comment by developernotes** [comment]
Hello @ahfchan 

Are you able to consistently reproduce the issue?  If so, is it always on the Redmi device, or others?

**Comment by ahfchan** [comment]
Hi @developernotes

Yes I can consistently reproduce what I've reported on my Redmi Note2 which is on Android 5.0.2.

I also had the same issue (consistently reproducable) with an HTC M9 back in May 2015. I believe it was also running Android 5.0.x. The issue no longer appeared after a few months (very likely after upgrading to Android 5.1). The device is now on Android 6 and it's working also.

I have a few more devices at hand: Nexus 7 running 4.4, Samsung galaxy S6 running 5.1, Nexus 5 running 6.1 - all without problems. Unfortunately Redmi is only only 5.0.x  device I have at hand now.

From reading what others have commented on this thread, it appears Android 5.0.x may be the only affected version, which seems consistent with my experience.

Thanks again.

**Comment by linsmalldragon** [comment]
@developernotes  I have the same issue on Redmi Device and can reproduce it every time. The sdk is Android 5.0.2. Other versions is all ok.  Any other solutions except  moving data into internal storage on android 5.0.2?

**Comment by developernotes** [comment]
Hello @linsmalldragon 

Unfortunately I do not have access to that specific device to perform further debugging with it.  I am not aware of another solution at this time.

**Comment by faoiseamh** [comment]
I can confirm this is still an issue. It occurs consistently on the following device / OS  (tried on multiple of these devices):

Device: [LG G Pad X8.3 (VK815)](http://www.lg.com/us/support-mobile/lg-LGVK815)
OS: Android 5.0.2

I don't have access to the devices to do any further testing myself, but the behavior is very consistent.

**Comment by baskar007** [comment]
I can consistently reproduce the same issue on [Mi 4i](http://www.mi.com/in/mi4i/) Android version 5.0.2.

**Comment by eyeled** [comment]
The issue can be reproduced in the 5.0 x86_64 emulator. Key point seems to be that the database is located in the external storage. We've started seeing this issue immediately after upgrading from a >2 years old version of sqlcipher to the current release.
The problem is that fileHasMoved in https://github.com/sqlcipher/sqlcipher/blob/master/src/os_unix.c#L1324 returns TRUE even though the file is still there.
Hardcoding to return 0 fixes the issue in the emulator. Verification that this is also the root cause on acutaly devices is still pending.

**Comment by developernotes** [comment]
Hello @eyeled 

Thank you for your feedback, we look forward to hearing your results on device.

**Comment by atultiwari** [comment]
Hi,
As mentioned in discussion forum, my app is crashing (at least in 2 known mobiles - Mi 4i and Lenovo Phab Plus) soon after it tries to access the database.
After some research and with the help of @developernotes  reply in the discussion forum, I was finally able to get the App Crashing Error from Mi 4i mobile -
It said -

> net.sqlcipher.database.SQLiteException: attempt to write a readonly database: DELETE failed setting locale

The Mi 4i device runs Android 5.0.2
After learning this.. I tried to reciprocate the same in x86_64 emulators of version 5.0.1 and 5.1.1.
Luckily no error is thrown in 5.1.1 and app works absolutely fine for me.

Unfortunately in Android 5.0.1 x86_64 emulator following error is displayed -

> 05-11 19:36:46.931 2995-2995/? D/QuestionBankDBHelper: Count Query =  SELECT COUNT(*) as `count` FROM `qbank`
> 05-11 19:36:46.935 2995-2995/? I/Database: sqlite returned: error code = 28, msg = file renamed while open: /storage/sdcard/Download/mydata.db
> 05-11 19:36:47.071 2995-2995/? I/Database: sqlite returned: error code = 1032, msg = statement aborts at 3: [PRAGMA user_version = 1] 
> 05-11 19:36:47.071 2995-2995/? E/Database: Failure 8 (attempt to write a readonly database) on 0xecf5f208 when executing 'PRAGMA user_version = 1'
> 05-11 19:36:47.072 2995-2995/? I/Database: sqlite returned: error code = 28, msg = file renamed while open: /storage/sdcard/Download/mydata.db

The same database is working fine in 4.2.2, 5.1.1, 6.0.1 etc.

This error appears to be slightly different than what is thrown in Mi 4i phone. But, one thing is sure.. there is some bug that is interfering with SQLCipher to work in Android 5.0.x

How I tested -
I have sqlcipher encrypted database, which is stored in External Storage. The errors are thrown, when being trying to access this database.

**Comment by kibergus** [comment]
Hi! We've encountered the same bug too. atultiwari, thank you very much for finding emulator in which the problem can be easily reproduced. That helped a lot. The error is actually in android headers. For android 19 they have:
'''
android-ndk-r10d/platforms/android-19/arch-x86/usr/include/sys/types.h:typedef __kernel_ino_t       ino_t;
android-ndk-r10d/platforms/android-19/arch-x86/usr/include/asm/posix_types_32.h:typedef unsigned long __kernel_ino_t;
'''
but
'''
struct stat {
...
    unsigned long long  st_ino;
};
'''
So ino_t is 4 bytes and stat.st_ino is 8 bytes wide. Sqlite trims inode number to 4 bytes when stores it and then compares with 8 byte wide inode number in fileHasMoved.

It seems, that in android 21 headers have been fixed:
'''
android-ndk-r10d/platforms/android-21/arch-x86/usr/include/sys/types.h:typedef __kernel_ino_t __ino_t;
android-ndk-r10d/platforms/android-21/arch-x86/usr/include/sys/types.h:typedef __ino_t ino_t;
android-ndk-r10d/platforms/android-21/arch-x86/usr/include/asm-generic/posix_types.h:typedef __kernel_ulong_t __kernel_ino_t;
android-ndk-r10d/platforms/android-21/arch-x86/usr/include/asm/posix_types_x32.h:typedef unsigned long long __kernel_ulong_t;
'''

So currently I see two solutions: good one is to use headers for android 21. But if that's inappropriate, then the problem can be solved by a hack in sqlite by explicitly converting stat.st_ino to (ino_t) in sqlite source.

**Comment by brodybits** [comment]
+1 for using the android-21 headers

**Comment by atultiwari** [comment]
@kibergus thank you for finding out the root cause of this issue. Being a medico, it was hard to understand it comletely, but I did understand some basics about it.
I am curious, if somehow, I can make SQLCipher work with Android 5.0 (as suggested by you - using the android 21 headers), or will I have to wait for developers of SQLCipher to release some kind of patch?
Thanks.

**Comment by YuriZheng** [comment]
I get this issue on my phone, Android 5.0, I see  @kibergus's answer, but i don't know how to deal with it,For using the android-21 headers ? How to do it?

**Comment by developernotes** [comment]
Hi @atultiwari, @YuriZheng,

We will look into making the adjustment to the NDK API 21 within the `android-n-preview` soon.

**Comment by developernotes** [comment]
Hi @atultiwari, @YuriZheng,

We have made some changes in the `android-n-preview` branch which include adjusting the target platform used within the Android NDK. Please feel free to try the `android-n-preview` to see if it addresses the issue you are seeing. Thanks!

**Comment by atultiwari** [comment]
@developernotes thank you for your reply. I will try it in the evening and get back to you. It's 2 a.m. here, feeling very sleepy.
But, on a quick look. I am unable to figure out how to use `android-n-preview`? I mean previously I was using `aar` in Android studio, like - 
compile 'net.zetetic:android-database-sqlcipher:3.4.0@aar'

But it seems, for `android-n-preview` I might have to compile sqlcipher myself, about which I have no idea.

**Comment by developernotes** [comment]
Hello @atultiwari,

Yes, the `android-n-preview` branch is distributed in source only format. If you are interested in a zip build  please feel free to email us at [support@zetetic.net](mailto:support@zetetic.net) with your [Discuss](https://discuss.zetetic.net/c/sqlcipher) account.

**Comment by YuriZheng** [comment]
Hello @developernotes :
     I download the source and build it myself. But it has this issue, I'm a java developer, so i'm poor of c and c++. If you solved this probrem, please let me know!  I'm very worried. Thank you very much !!!

**Comment by umesh289** [comment]
@developernotes I too am facing this issue only on 5.0 devices. 

05-24 15:46:30.494: I/Database(11744): sqlite returned: error code = 28, msg = file renamed while open: /storage/sdcard0/dummy1/db
05-24 15:46:30.503: I/Database(11744): sqlite returned: error code = 1032, msg = statement aborts at 8: [CREATE TABLE IF NOT EXISTS dummy_table1
.....
05-24 15:46:30.503: E/Database(11744): Failure 8 (attempt to write a readonly database) on 0xabb15250 when executing 'CREATE TABLE IF NOT EXISTS dummy_table2(rowid integer default -1, did integer

**Comment by developernotes** [comment]
Hello @YuriZheng 

If you are interested in our `android-n-preview` branch, we have instructions available [here](http://discuss.zetetic.net/t/sqlcipher-for-android-upcoming-changes-for-android-n-and-coordinated-beta-test-request/1315/1) for accessing it.

**Comment by heutschibogdan** [comment]
Hi @developernotes ,

I am facing this problem using the latest version 3.5.4 on a sony device with android 5.0. net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database. Do you have any suggestions what I could try?

**Comment by developernotes** [comment]
Hi @heutschibogdan 

Are you able to create a small reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? If so, we would be happy to look into that further. Thanks!

**Comment by heutschibogdan** [comment]
Hi @developernotes 

I've added a test case for this. It seems the problem is not really related to the sony device, as I've reproduced it on multiple android versions which have x86_64 system image. It seems there is a problem when using an external storage in this cases.

**Comment by gautamshrm3** [comment]
Hi Team,

We are facing the below issue may be the similar as previous 

net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database

This issue we have only got in MI devices.

Please us ASAP.

**Comment by sjlombardo** [comment]
@umesh0492 are you saying that the application works if there is only a single process, but fails when there are multiple processes, even if the database location is the same?

**Comment by ArikYa** [comment]
I'm having the same issue, also seems to be related to multi-processes application. Any update on this?

**Comment by developernotes** [comment]
Hi @ArikYa 

What version of SQLCipher for Android are you currently using?

**Comment by ArikYa** [comment]
I use it through Requery, which uses 3.5.4

**Comment by developernotes** [comment]
Hello @ArikYa 

Please try the latest version of SQLCipher for Android, which is 3.5.7 and let us know your results. Thanks!

**Comment by dotw** [comment]
Hello guys, I'm facing the same issue. I'm using the latest version 3.5.7 now.
```
11-20 17:48:54.719 12073-12218/com.hzqi.sango W/System.err: net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
11-20 17:48:54.719 12073-12218/com.hzqi.sango W/System.err:     at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
11-20 17:48:54.719 12073-12218/com.hzqi.sango W/System.err:     at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
11-20 17:48:54.719 12073-12218/com.hzqi.sango W/System.err:     at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2319)
```

**Comment by dotw** [comment]
Struggling several hours then I found the issue is the database path.
I changed the path from 
```context.getApplicationInfo().dataDir + "/databases/" + DATABASE_NAME```
to
```context.getDatabasePath(DATABASE_NAME).getPath()```
then, the exception is gone.

**Comment by developernotes** [comment]
Hi @dotw 

We are glad to hear you were able to resolve the issue. Thanks!
