### ISSUE TITLE
Database object locked on error

### ISSUE THREAD

**Issue by xrubioj** [sqlcipher/android-database-sqlcipher#162]
While debugging our application which uses SQLCipher for Android v3.3.0, I've found the following constructions in net.sqlcipher.database.SQLiteDatabase (they're also present in other methods):

``` java
    public SQLiteStatement compileStatement(String sql) throws SQLException {
        this.lock();
        if(!this.isOpen()) {
            throw new IllegalStateException("database not open");
        } else {
            SQLiteStatement var2;
            try {
                var2 = new SQLiteStatement(this, sql);
            } finally {
                this.unlock();
            }
            return var2;
        }
    }
```

From my understanding, if you call this with database closed the object will be left locked, as this.unlock() is never called. So, I guess that this function should be rewritten like that:

``` java
    public SQLiteStatement compileStatement(String sql) throws SQLException {
        this.lock();
        try {
            if(!this.isOpen()) {
                throw new IllegalStateException("database not open");
            } else {
                SQLiteStatement var2;
                var2 = new SQLiteStatement(this, sql);
                return var2;
            }
        } finally {
            this.unlock();
        }
    }
```

Probably this is a minor issue, because you should not call this method on a closed DB.

**Comment by developernotes** [comment]
Hello @xrubioj 

Good catch, thanks!  I would agree that is a good approach.  If you are interested in submitting a pull request to adjust this we welcome that, otherwise, I will take a look at adjusting this to be included in the next release.  Thanks!

**Comment by developernotes** [comment]
Hello @xrubioj 

I just wanted to follow up with you on this, are you interested in submitting a pull request?

**Comment by ubuntudroid** [comment]
This seems to be fixed in the codebase and can be closed, right?

**Comment by developernotes** [comment]
Hi @ubuntudroid 

Unfortunately this item has not been addressed yet. We are currently reviewing changes needed for Android N and will take a look at this as well. Thanks for the reminder.

**Comment by developernotes** [comment]
Hello @xrubioj 

Sorry for the late reply, unfortunately this fell through and I have just made the changes now. It will be included in the next release. Thanks!
