### ISSUE TITLE
support ENABLE_WRITE_AHEAD_LOGGING

### ISSUE THREAD

**Issue by driventokill** [sqlcipher/android-database-sqlcipher#163]
Will you guys support this feature as described in the official document? Because it really very common to read while writing some data background. And I really want to use the SQLiteOpenHelper provided by you. I found I can't easily do it by myself cause the SQLiteDatabase#lock is not public.

http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging()

**Comment by developernotes** [comment]
Hello @driventokill 

You have always been able to use WAL mode within SQLCipher, you will just need to manually invoke it via a `PRAGMA` statement, the Java API we originally introduced is now slightly different than the documentation you are referencing above.

**Comment by driventokill** [comment]
@developernotes Thanks.

**Comment by lightai** [comment]
is thread has dedicated SQLiteDatabase instance to enable parallel access sqlite?

**Comment by developernotes** [comment]
Hello @lightai 

You can utilize SQLCipher to access plain text SQLite database files, too. You can either open a dedicated connection without supplying a password, or utilize the [`ATTACH`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#attach) command to access another database with an existing connection.
