### ISSUE TITLE
Proguard obfuscation with gradle

### ISSUE THREAD

**Issue by sgueniot** [sqlcipher/android-database-sqlcipher#164]
Hello, 
gradle already add -libraryjars to proguard so I removed ```-libraryjars libs/sqlcipher.jar```.
App compiles, without "same input jar is specified twice" error, but crashes on start with errors like 
**Throwing new exception 'no "I" field "nStatement" in class "Lnet/sqlcipher/database/SQLiteCompiledSql;" or its superclasses' with unexpected pending exception: java.lang.NoSuchFieldError: no "I" field "nHandle" in class "Lnet/sqlcipher/database/SQLiteCompiledSql;" or its superclasses**

Someone has an idea to  fix this ?
thanks.

```
-dontwarn android.support.v7.**
-keep class android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }

-dontwarn android.support.v4.**
-keep class android.support.v4.** { *; }
-keep interface android.support.v4.** { *; }

# Needed by google-api-client to keep generic types and @Key annotations accessed via reflection
-keepclassmembers class * {
  @com.google.api.client.util.Key <fields>;
}

-keepattributes Signature,RuntimeVisibleAnnotations,AnnotationDefault,*Annotation*

-dontwarn sun.misc.Unsafe



-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*,!code/allocation/variable

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application

-dontwarn javax.annotation.**

-dontwarn android.app.**
-dontwarn android.support.**
-dontwarn android.view.**
-dontwarn android.widget.**

-dontwarn com.google.common.primitives.**

-dontwarn **CompatHoneycomb
-dontwarn **CompatHoneycombMR2
-dontwarn **CompatCreatorHoneycombMR2

-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keepclassmembers class **.R$* {
    public static <fields>;
}

-keep public class net.sqlcipher.** {
    *;
}

-keep public class net.sqlcipher.database.** {
    *;
}
```

**Comment by developernotes** [comment]
Hello @sgueniot 

Could you try using the sample ProGuard file provided in the SQLCipher for Android repo [here](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/proguard-project.txt)?

**Comment by sgueniot** [comment]
Hello,
It's working if I remove
public from
-keep public class net.sqlcipher.** and -keep public class
net.sqlcipher.database.**

in this sample.
Thanks.

**Comment by developernotes** [comment]
Hello @sgueniot 

Glad to hear that resolved it.  Thanks!

**Comment by CCorrado** [comment]
https://github.com/sqlcipher/android-database-sqlcipher/blob/master/proguard-project.txt

Is this still available?

**Comment by developernotes** [comment]
Hi @CCorrado 

You might try [this](https://github.com/sqlcipher/android-database-sqlcipher/blob/v3.4.0/proguard-project.txt). We will look to add this to our upcoming [gradle](https://github.com/sqlcipher/android-database-sqlcipher/tree/gradle).
