### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Couldn't load stlport_shared: findLibrary returned null

### ISSUE THREAD

**Issue by mradlmaier** [sqlcipher/android-database-sqlcipher#165]
Hello,

I am getting java.lang.UnsatisfiedLinkError when I run the demo app.
My directoy structure:
![encrypted](https://cloud.githubusercontent.com/assets/6393479/7621377/aee98fea-f9c6-11e4-9698-7aff83fa76cc.jpg)

I followed the instructions at https://discuss.zetetic.net/t/android-studio-integration/65

Please advice

**Comment by developernotes** [comment]
Hello @mradlmaier,

Can you post the full stack trace and the code that you are using to initialize and execute SQLCipher?

**Comment by mradlmaier** [comment]
Turns out, that by renaming the directory "jni" to "jniLibs" 
the error disappears. However, when I look with the Android Device Monitor in /data/data/com/mradlmaier/encrypted/ I don't see any database file? How do I know my setup is correct?
![data](https://cloud.githubusercontent.com/assets/6393479/7621644/a4396f3c-f9c8-11e4-96f2-da879aa8f291.jpg)

**Comment by developernotes** [comment]
Hello @mradlmaier 

Using `jniLibs` is the correct way to structure the files per the [tutorial](https://discuss.zetetic.net/t/android-studio-integration/65).  Generally speaking, you will want to pull the database file off device and perform a `hexdump -C YourDatabaseFile.db` and validate that the content is not plain text.
