### ISSUE TITLE
why can't I create a table?

### ISSUE THREAD

**Issue by mradlmaier** [sqlcipher/android-database-sqlcipher#166]
I am creating an encrypted table. I can pull it from my device and examine it with the SqliteManager app. But my table is not created. However, I am not getting any error message nor crashes.

Here is my code:

        protected void onCreate(Bundle savedInstanceState) {
              super.onCreate(savedInstanceState);
              setContentView(R.layout.activity_main);

        SQLiteDatabase.loadLibs(this);
        String dbPath = getDatabasePath("my_encrypted_db.sqlite").getPath();

        File dbPathFile = new File (dbPath);
        if (!dbPathFile.exists()){
            dbPathFile.getParentFile().mkdirs();
        }

        SQLiteDatabase database = SQLiteDatabase.openOrCreateDatabase(dbPath, "password", null);
        database.rawQuery("CREATE TABLE  my_table (my_column INT)", null);
        Cursor cursor = database.rawQuery("PRAGMA cipher_version;", null);
        cursor.moveToFirst();
        String version = cursor.getString(0);
        Log.i("MainActivity", String.format("SQLCipher version:%s", version));

        cursor.close();
        database.close();
    }

Any suggestions?

**Comment by developernotes** [comment]
Hello @mradlmaier,

It isn't creating your table because you are executing the following:
```
database.rawQuery("CREATE TABLE  my_table (my_column INT)", null);
```
The `rawQuery` method is used to execute a SELECT statement which returns a `Cursor` representing the results of your query.  Instead, you should consider using `rawExecSQL`.

**Comment by mradlmaier** [comment]
Right, my fault, tx
