### ISSUE TITLE
Samsung S6 (arm64) failing to start app with SqlCipher

### ISSUE THREAD

**Issue by anti43** [sqlcipher/android-database-sqlcipher#167]
Hello, 
are there 64bit native libs available yet?

Fatal Exception: java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xx/base.apk"],nativeLibraryDirectories=[/data/app/xx/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libstlport_shared.so"

Best regards

Andreas

**Comment by developernotes** [comment]
Hello @anti43 

Not officially at this time, however you may wish to read more about issue #151 as you can likely build those binaries yourself should you need them in the interim.
