### ISSUE TITLE
SqlCipher for Spaitalite database

### ISSUE THREAD

**Issue by adolfdsilva** [sqlcipher/android-database-sqlcipher#168]
Hi,

I'm a newbie to android development and I'm currently using a spatialite lib given here: https://github.com/mrenouf/android-spatialite

What I want is to encrypt the spatialite database, but the problem I don't know where to start. 
If I'am not wrong the sqlcipher replaces all the SQLiteDatabase instances, but how do i do this for spatialite.

Any ideas? Thanks!!!

**Comment by developernotes** [comment]
Hello @adolfdsilva 

We do not do anything in particular with spatialite, however there is [this](https://github.com/illarionov/android-sqlcipher-spatialite) project on github, though it does not look like it has been maintained recently.  If you have additional questions about SQLCipher, I would recommend you post them to the [discuss group](https://discuss.zetetic.net/).  Thanks!
