### ISSUE TITLE
Enhancements from Android project to support thread-local database sessions?

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#178]
The Android project made a number of enhancements to support thread-local database sessions in this commit in November 2011: https://github.com/android/platform_frameworks_base/commit/e5360fbf3efe85427f7e7f59afe7bbeddb4949ac

It would be really nice to have this project closer in line with the database classes in the Android project. Right now, every time they add a new interface or fix a major bug we end up "backporting" the changes.

This would be a major undertaking to develop and test. Not sure if this is justified.

**Comment by brodybits** [comment]
As an alternative, I just submitted sqlcipher/sqlcipher#125 to make a simpler version for Android.

**Comment by developernotes** [comment]
>It would be really nice to have this project closer in line with the database classes in the Android project.
>This would be a major undertaking to develop and test. Not sure if this is justified.

Agreed, so far it has become a balancing act to determine the features that people need within their applications.  It becomes very difficult to support everyone's request, some wish the library were smaller (myself included), while others want other integrations/extensions.

**Comment by brodybits** [comment]
Another advantage if we can use the latest changes from the Android project is that almost all of the native functions are off a single object, which could be ported to using SQLiteGlue as discussed in sqlcipher/sqlcipher#125.

**Comment by brodybits** [comment]
I am thinking it is best to start over from the newer SQLite database classes taken from the Android project, as discussed in https://github.com/sqlcipher/sqlcipher/issues/125#issuecomment-110079660
