### ISSUE TITLE
OOM for in-memory database

### ISSUE THREAD

**Issue by narakim** [sqlcipher/android-database-sqlcipher#179]
I'm trying to use in-memory database but I'm worried about possible OOMs. 

Does it throw OOM if it runs out of memory for in-memory database? If so, where should I expect that to be thrown?
Or does it handle OOM in some way?

In Android API, there is SQLiteOutofMemoryException (http://developer.android.com/reference/android/database/sqlite/SQLiteOutOfMemoryException.html) but I didn't see any reference of that in sqlcipher.

**Comment by developernotes** [comment]
Hello @narakim 

That may depend on the hardware specifications on any given device you run your application on.  You might consider using file storage of SQLCipher as an alternative.
