### ISSUE TITLE
Sqlcipher android M

### ISSUE THREAD

**Issue by abalufaske** [sqlcipher/android-database-sqlcipher#180]
Hi, I was testing my app in a nexus 6 with the android version M (beta) and it's crashing because of sqlcipher.
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "EVP_CipherFinal" referenced by "/data/app/com.testtest-1/lib/arm/libsqlcipher_android.so"...

**Comment by developernotes** [comment]
Hi @abalufaske 

What version of SQLCipher for Android are you using for your testing?

**Comment by abalufaske** [comment]
3.1.0

**Comment by developernotes** [comment]
Hi @abalufaske,

Did you build the binaries yourself, or were they provided, either as a community or commercial build?

**Comment by abalufaske** [comment]
Community build

**Comment by karanpopali** [comment]
Android M has removed OpenSSL libraries, therefore its not working. You
need to include libcrypto.so and libssl.so (and load them) in your libs
directory for it to work.

See this link for more info:
http://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by developernotes** [comment]
Hi @karanpopali 

I don't think that is the issue as we perform a static link of OpenSSL when building SQLCipher for Android, so we do not have a system provided dependency on OpenSSL.

**Comment by karanpopali** [comment]
I don't think so. Here's the 3.3 so info:

{code}
$ arm-linux-androideabi-readelf -d
~/Downloads/android-database-sqlcipher-3.3.0/dist/SQLCipherForAndroid-SDK/libs/armeabi/libsqlcipher_android.so
| grep libcrypto
 0x00000001 (NEEDED)                     Shared library: [libcrypto.so]
{code}

**Comment by brodybits** [comment]
I am able to run the `sqlcipher-android-tests` on an Android M (Preview) ARM (armeabi-v7a) simulator on my Windows (8.1) machine, using the libraries from the 3.3.0 build. I imported and ran the `sqlcipher-android-tests` project using Android Studio on my Windows machine.

**Comment by developernotes** [comment]
Hi @karanpopali 

I downloaded the latest community binaries from [here](https://s3.amazonaws.com/sqlcipher/3.3.0/sqlcipher-for-android-community-v3.3.0.zip).  When I unzip them, and read the results from `arm-linux-androideabi-readelf`, I do not see that:

```
./arm-linux-androideabi-readelf -d ~/Desktop/sqlcipher-for-android-v3.3.0/libs/armeabi/libsqlcipher_android.so

Dynamic section at offset 0x25a74c contains 30 entries:
  Tag        Type                         Name/Value
 0x00000003 (PLTGOT)                     0x25bddc
 0x00000002 (PLTRELSZ)                   1072 (bytes)
 0x00000017 (JMPREL)                     0x5ed60
 0x00000014 (PLTREL)                     REL
 0x00000011 (REL)                        0x492e0
 0x00000012 (RELSZ)                      88704 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   10847
 0x00000006 (SYMTAB)                     0x114
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000005 (STRTAB)                     0x18114
 0x0000000a (STRSZ)                      160182 (bytes)
 0x00000004 (HASH)                       0x3f2cc
 0x00000001 (NEEDED)                     Shared library: [libstlport_shared.so]
 0x00000001 (NEEDED)                     Shared library: [liblog.so]
 0x00000001 (NEEDED)                     Shared library: [libutils.so]
 0x00000001 (NEEDED)                     Shared library: [libcutils.so]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so]
 0x00000001 (NEEDED)                     Shared library: [libm.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x0000000e (SONAME)                     Library soname: [libsqlcipher_android.so]
 0x0000001a (FINI_ARRAY)                 0x256448
 0x0000001c (FINI_ARRAYSZ)               8 (bytes)
 0x00000019 (INIT_ARRAY)                 0x25b748
 0x0000001b (INIT_ARRAYSZ)               4 (bytes)
 0x00000010 (SYMBOLIC)                   0x0
 0x0000001e (FLAGS)                      SYMBOLIC BIND_NOW
 0x6ffffffb (FLAGS_1)                    Flags: NOW
 0x00000000 (NULL)                       0x0
```

**Comment by karanpopali** [comment]
Ohhk, I downloaded the zip file from GitHub releases page.

**Comment by abalufaske** [comment]
I will try tomorrow with the amazon ones, I had the ones of github! thank you everyone for the quick answers!

**Comment by danimontoya** [comment]
It worked :)

**Comment by developernotes** [comment]
Hello @abalufaske 

Can you report back on your status of this issue?  Thanks!

**Comment by abalufaske** [comment]
thank you :)
