### ISSUE TITLE
file is encrypted or is not a database

### ISSUE THREAD

**Issue by chetan1011** [sqlcipher/android-database-sqlcipher#183]
Hello @brodybits and @developernotes ,

I have create password protected  sqlite database using c#.net.

we use "system.data.sqlite.dll" for create sqlite database file.

It's working fine in android(4.1.2) and  bellow  varsion.

but, now we have problem facing in android(4.4.2) and above version.

The error is :
07-04 17:11:41.196: E/Database(29720): CREATE TABLE android_metadata failed
07-04 17:11:41.220: E/Database(29720): Failed to setLocale() when constructing, closing the database
07-04 17:11:41.220: E/Database(29720): net.sqlcipher.database.SQLiteException: file is encrypted or is not a database
07-04 17:11:41.220: E/Database(29720):     at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
07-04 17:11:41.220: E/Database(29720):     at net.sqlcipher.database.SQLiteDatabase.setLocale(SQLiteDatabase.java:2096)

FYI, I see this issue on Lenovo A7000-a, Lollipop device. Please help on this.

**Comment by sjlombardo** [comment]
@chetan1011 Are you using the official SQLCipher for ADO.NET commercial edition library, or the basic encryption functionality that comes with the standard system.data.sqlite distribution? If you are using the latter, the encryption used in there is not compatible with SQLCipher.
