### ISSUE TITLE
Document 64-bit compatibility

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#185]
There has been some confusion about getting this project to work with 64-bit systems, for example:
- https://discuss.zetetic.net/t/crashing-when-running-sql-cipher-on-nexus-9/639
- https://discuss.zetetic.net/t/sqlcipher-on-android-5-0-x64-emulator-crash/286

The answer is to make sure you do not have _any_ 64-bit `.so` libraries in your Android app, as described:
- this answer: https://discuss.zetetic.net/t/crashing-when-running-sql-cipher-on-nexus-9/639/15
- http://ph0b.com/android-abis-and-so-files/

Assuming that #151 is not merged anytime soon (apparently because the OpenSSL project does not support 64-bit Android builds), this answer needs to be documented very clearly.

**Comment by developernotes** [comment]
Hi @brodybits 

I think an addendum to the compatibility section of the [README](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/README.org) would be sufficient.  Do you think it should be noted elsewhere?

**Comment by brodybits** [comment]
That would be good. But what about those who just reference your web page at https://www.zetetic.net/sqlcipher/sqlcipher-for-android/ and get the binaries (by following the link to https://www.zetetic.net/sqlcipher/open-source/) without even looking at this github project?

**Comment by developernotes** [comment]
A disclaimer can be added to the tutorial, however I would like to avoid duplicating compatibility information in multiple locations.

**Comment by brodybits** [comment]
Yes a disclaimer would be good, if it is very clear what the issue is and how it can bite someone:)

Someone encountered a similar problem in litehelpers/Cordova-sqlite-storage#284 when combining my sqlite plugin with https://github.com/jbavari/cordova-plugin-video-editor.

**Comment by brodybits** [comment]
Something else. The changes in #151 to support 64-bit targets would cause another minor diversion of the source code from the Android sqlite database source. It would be better to update the source code to match the changes from Android 5.0, if someone wants to make the effort.

**Comment by brodybits** [comment]
Closing in favor of #251

**Comment by amorenew** [comment]
**sql-cipher** require **openssl** which doesn't support 64bit yet

**Comment by developernotes** [comment]
Hi @amorenew 

[SQLCipher core](https://github.com/sqlcipher/sqlcipher) supports multiple crypto providers, OpenSSL being one of them. While SQLCipher for Android has not included 64-bit native libraries, we plan to investigate using OpenSSL 1.1.0 in the next release with the hopes of expanding target architecture support. Previous versions of OpenSSL did not build 64-bit support for Android without build chain modification. In the interim, SQLCipher for Android will run on 64-bit CPU's using the 32-bit native libraries, please see [this note](https://discuss.zetetic.net/t/sqlcipher-for-android-native-library-support/1440).

**Comment by amorenew** [comment]
@developernotes  OpenSSL 1.1.0 not supported 64bit
https://www.openssl.org/news/openssl-1.1.0-notes.htmlyou
i faced the issue of UnsatisfiedLinkError
with https://github.com/Raizlabs/DBFlow
thanks for your effort
well done

**Comment by developernotes** [comment]
Hi @amorenew 

>OpenSSL 1.1.0 not supported 64bit
>https://www.openssl.org/news/openssl-1.1.0-notes.html

That link does not state reference 64-bit or Android. Did you read that somewhere else?

**Comment by amorenew** [comment]
No @developernotes

**Comment by amorenew** [comment]
in this link OpenSSL member https://github.com/openssl/openssl/issues/333#issuecomment-219562413

**Comment by developernotes** [comment]
Hi @amorenew 

Right, @mattcaswell mentioned they have included 64-bit Android support in 1.1.0. We intend to investigate that further with our next release of SQLCipher.
