### ISSUE TITLE
android-database-sqlcipher aar

### ISSUE THREAD

**Issue by smshen** [sqlcipher/android-database-sqlcipher#187]
请问android-database-sqlcipher是否提供aar包?

**Comment by brodybits** [comment]
With help from translate.google.com:
> Will android-database-sqlcipher be offering aar package?

It should be straightforward to add another task to the Makefile to generate the AAR bundle, as described at: http://tools.android.com/tech-docs/new-build-system/aar-format

**Comment by developernotes** [comment]
Hello @smshen,

We will consider this for the future.
