### ISSUE TITLE
Missing build.xml according to build directions & other minor build issues

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#188]
When I followed the build instructions in https://github.com/sqlcipher/android-database-sqlcipher#building on a new system (with Android API 22 installed):
```shell
make init
make
```

it built the native libraries then failed with the following output:
```
ant release
Buildfile: build.xml does not exist!
Build failed
make: *** [build-java] Error 1
```

I was able to actually generate `build.xml` (using the following command):
```shell
android update project -p . -t android-22
```

then finished the build:
```shell
make build-java copy-libs
```

This should be documented.

A couple of other build-related items:

There is a `copy-libs-dist` target, which is never referenced in the `Makefile`, that only copies the jar(s) and `armeabi` native target library:
```make
copy-libs-dist:
	cp ${LIBRARY_ROOT}/*.jar dist/SQLCipherForAndroid-SDK/libs/ && \
	cp ${LIBRARY_ROOT}/armeabi/*.so dist/SQLCipherForAndroid-SDK/libs/armeabi/
```

We should either fix it to copy the other native target libraries or remove it.

We should also add a "super-clean" target that simply removes all generated artifacts. I started working on this in #171 and then put it on hold.

Unfortunately I cannot promise when I may have a chance to issue a fix for these.

*UDPATES* with a couple more minor points:
- add instructions (simply `make build-java`) to rebuild the Java (JAR) only
- add clear instructions to sqlcipher-android-tests how to build and install:
```shell
android update project -p . -t android-22
ant debug install
```

**Comment by developernotes** [comment]
Hi @brodybits

I *believe* when you first run `make init` that an error may have occurred, but possibly didn't bubble up.  During the `make init` process, [this](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/Makefile#L37) line is executed and it should check the [project.properties](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/project.properties) file for the Android target platform to update against.  I am curious, did you happen to have `android-19` available on your system, or did you only have `android-22` available?

With regard to the `copy-libs-dist` target, I believe we should get rid of that as well, along with the `notepadbot` submodule.

**Comment by brodybits** [comment]
I only have `android-22` available on my system and yes, if I do `android update project -p .` on a clean project (`git submodule update --init` already done) I do get the error:
```
Error: The project either has no target set or the target is invalid.
Please provide a --target to the 'android update' command.
```

Here is the procedure that will work for me:
```shell
# only the first time:
android update project -p . -t android-22
make init
# to build native code, Java code, and copy libraries:
make
# to rebuild Java JAR only:
make build-java
```

A couple other minor points before I forget them:
- The "Building" section still makes reference to the `android-7` platform (I should have fixed it when I updated `project.properties` in #170
- I suspect we can drop `platform-frameworks-base` and `platform-system-core` from `external`

**Comment by developernotes** [comment]
>The "Building" section still makes reference to the android-7 platform (I should have fixed it when I updated project.properties in #170

I think updating the README to reflect the current `android-19` requirement should be appropriate, as that is the value currently used within the [project.properties](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/project.properties).

>I suspect we can drop platform-frameworks-base and platform-system-core from external

Include headers are currently searched within both those projects for the JNI build portion of the library.  Were you able to remove them and build the library successfully?

**Comment by brodybits** [comment]
> I think updating the README to reflect the current `android-19` requirement should be appropriate, as that is the value currently used within the project.properties.

Just issued PR #189

> Include headers are currently searched within both those projects for the JNI build portion of the library.

I also discovered this.

> Were you able to remove them and build the library successfully?

Nope. Perhaps we could identify (experimentally) which headers we actually need and include them somewhere in the external tree, similar to String8.cpp and String16.cpp. Especially for `external/platform-frameworks-base` since it takes so long to clone:=)

**Comment by developernotes** [comment]
>Just issued PR #189

Merged! :+1: 

>Perhaps we could identify (experimentally) which headers we actually need and include them somewhere in the external tree, similar to String8.cpp and String16.cpp. Especially for external/platform-frameworks-base since it takes so long to clone:=)

I think that has implications that may introduce further hurdles for future upgrades of both the Java and native library upgrades in the future.
