### ISSUE TITLE
Update SQLCipher's net.sqlcipher classes to match newer revisions of Android's android.database classes

### ISSUE THREAD

**Issue by jdkoren** [sqlcipher/android-database-sqlcipher#191]
Greetings! We are trying to integrate SQLCipher with one of our projects and have encountered some compatibility issues. Our project supports API 14+, but the SQLCipher classes appear to be implementations going back to API 10 or earlier. Below are some of the issues we've found with these older APIs.

Are there any plans to upgrade SqlCipher's classes to better match newer versions of the Android classes?

#### Query arguments can only be bound as Strings

In many cases this problem is masked because SQLite is so flexible with types, but it can have unexpected bugs when working with functions:

```sql
-- returns the first row
select * from table where _id = 1;

-- also returns the first row; this is equivalent to binding args as strings
select * from table where _id = '1';

-- also returns the first row; abs is the absolute value function
select * from table where abs(_id) = 1;

-- this returns no results :(
select * from table where abs(_id) = '1';
```

The above is a contrived example, but the problem becomes worse when you have things like HAVING clauses with functions:

```sql
-- If the ? arg is bound as a String here, the condition will never be true
select * from table group by column having count(distinct other_column) = ?
```

We tried using methods like `bindLong()` in `SQLiteQuery`, but this requires us to work around `SQLiteDirectCursorDriver` binding all the arguments as strings. Additionally, the `requery()` method binds the arguments as strings again; this is because the `bind{type}()` methods first convert the argument to a String and store it in a String[] before forwarding to the superclass `bind{type}()` methods.

Versions of the Android SQLite classes from higher API levels have fixed the behavior and are able to bind arguments as types other than string.

#### SQLiteDatabase.insertWithConflict() behavior with CONFLICT_IGNORE

When using `SQLiteDatabase.insertWithConflict()` with the `CONFLICT_IGNORE` algorithm, SQLCipher returns the rowid of the existing row if a constraint violation occurs, or the rowid of the newly inserted row on success. This makes it difficult to distinguish between a successful insert and a constraint violation.

In recent versions of Android, this method returns -1 if a constraint violation occurs. (Notably, Google has not amended the [documentation](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#insertWithOnConflict(java.lang.String,%20java.lang.String,%20android.content.ContentValues,%20int)) of the method and still states that in this circumstance it will return the rowid of the existing row if using `CONFLICT_IGNORE`)

(cc @sbosley)

**Comment by developernotes** [comment]
Hello @jdkoren,

Thank you for your interest in SQLCipher for Android.  While we are currently looking into what it would take to update the Java API, the effort may be time consuming and thus we can not offer a time frame in which this will occur.  If you organization finds value in SQLCipher, we would be glad to discuss a commercial support agreement to facilitate the Android API update.  Please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net) if you are interested in discussing this option further.  Thanks!
