### ISSUE TITLE
Drop support for older Android versions?

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#193]
If I am not mistaken, the changes in #170 target Android API 19 which matches Android API 4.4 (KitKat), while https://github.com/sqlcipher/android-database-sqlcipher#compatibility specifies a range of 2.1 - 5.01. I have already stopped testing on older versions and suspect some others would have done the same thing.

For a small/medium/large enterprise-grade security product such as this I suspect most serious users would be using at least 4.0, if not 4.2 or 4.4. In addition, I found this article recently: http://www.extremetech.com/mobile/197346-google-throws-nearly-a-billion-android-users-under-the-bus-refuses-to-patch-os-vulnerability

**Comment by developernotes** [comment]
Hi @brodybits 

I don't believe the change in #170 as affected our ability to run on Android 2.1.  At this point in the game, I don't know what advantage we would have in dropping 2.1 support by itself.

**Comment by brodybits** [comment]
> I don't believe the change in #170 as affected our ability to run on Android 2.1.

Agreed.

> At this point in the game, I don't know what advantage we would have in dropping 2.1 support by itself.

How often is this project tested on Android 2.x?

**Comment by developernotes** [comment]
>How often is this project tested on Android 2.x?

I do it whenever we prepare a release of SQLCipher.

**Comment by brodybits** [comment]
Nice!

**Comment by vikasbasawaraj** [comment]
hi when ever i run sqlcipher on kitkat (19) it giving this error 

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: example/EventDataSQLHelper.class


could u pls help me

**Comment by developernotes** [comment]
Hi @vikasbasawaraj 

`EventDataSQLHelper.class` is not part of SQLCipher for Android.
