### ISSUE TITLE
Can't encrypt Database

### ISSUE THREAD

**Issue by safarious** [sqlcipher/android-database-sqlcipher#194]
Hello
I'm facing following problem. On the launch of the App I create a random Password from SecureRandom. The key has a length of 128bit and looks like following: `41qwvJ1KdljERXPAwzQfug==` . The Key is stored in the SharedPreference of my App.

I'll create/use the SQLDatabase like that:
`SQLiteDatabase mDatabase = new DatabaseHelper(mContext).getWritableDatabase(mKeySaver.getKey());`.

If I use the Database for the first time everything works fine. When I close the App and like to use the Database again the app crashes with following Error: `net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: create locale table failed`

I already checked if the Password is the same (and yes it is the same one)  - I do not get why this not working...
I also tested following: `SQLiteDatabase mDatabase = new DatabaseHelper(mContext).getWritableDatabase("TEST");` - This is working fine.

What is the problem here and is there a keyspace for the SQLDatabase Password?

Kind Regards, safarious

**Comment by developernotes** [comment]
Hi @safarious 

Are you able to pull the database off the device/emulator and open the database with your supplied key using the SQLCipher command line tool?

**Comment by safarious** [comment]
Hi @developernotes 
I just pulled of the database from my device and tried to open it with the SQLiteManager -> which told me the key is incorrect...

PS: Where can I find the SQLCipher command line tool for mac?

**Comment by developernotes** [comment]
Hi @safarious 

We have instructions available for building it from source [here](https://www.zetetic.net/sqlcipher/introduction/), alternatively if you use [Homebrew](http://brew.sh/) you can install the shell from there as well, the formula is called `sqlcipher`.

**Comment by safarious** [comment]
Hey @developernotes 

Thank you. I just installed sqlcipher, I did following:
`sqlcipher ivocoreDB.db`
`PRAGMA key = 'keEPM0t6X8y6Op0AY7+rIA==';  <-- This is the Key I generated and used to crypt my db`
`ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';`

I got following error: `Error: file is encrypted or is not a database`

What I understand is that the key isn't correct, but I don't get why because that's the one I used to crypt it. Any Ideas?.

**Comment by developernotes** [comment]
Hi @safarious 

Can you post the exact code you are using to both generate and store the key?

**Comment by safarious** [comment]
Hey @developernotes 

Sure here you go:
### This is used for generating the key
```java
public static SecretKey generateKey() throws NoSuchAlgorithmException {
        // Generate a 128-bit key
        final int outputKeyLength = 128;
        SecureRandom mSecureRandom = new SecureRandom();
        KeyGenerator mKeyGenerator = KeyGenerator.getInstance("AES");
        mKeyGenerator.init(outputKeyLength, mSecureRandom);
        SecretKey key = mKeyGenerator.generateKey();
        return key;
    }
```

### This is how I save/get the key
```java
public boolean setKey(SecretKey key){
        mSharedPrefs = mContext.getSharedPreferences(KeyStore, Context.MODE_PRIVATE);
        mEditor = mSharedPrefs.edit();
        mEditor.putString(KeyStorePassword, Base64.encodeToString(key.getEncoded(), Base64.DEFAULT));
        mEditor.apply();
        Log.d("KeySaver setKey", "Gespeicherter Schlüssel: " + mSharedPrefs.getString(KeyStorePassword, "Kein Schlüssel"));
        return mSharedPrefs.contains(KeyStorePassword);
    }

    public String getKey(){
        mSharedPrefs = mContext.getSharedPreferences(KeyStore, Context.MODE_PRIVATE);
        Log.d("KeySaver getKey", "Gespeicherter Schlüssel: " + mSharedPrefs.getString(KeyStorePassword, "Kein Schlüssel"));
        return mSharedPrefs.getString(KeyStorePassword, "");
    }

**Comment by safarious** [comment]
@developernotes I just wanted to ask if you found a solution yet? Kind Regards safarious

**Comment by developernotes** [comment]
Hello @safarious 

I have not had the opportunity to debug your issue at this time.  If you could prepare a reproducible unit test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) that replicates your issue I would be happy to look into it further.

**Comment by sjlombardo** [comment]
@safarious What version of SQLCipher for Android are you running in your project? You can check this using "PRAGMA cipher_version". It is possible that you are using an older version of SQLCipher in your android project than in the shell.

**Comment by safarious** [comment]
Hi @sjlombardo I've just checked the "PRAGMA cipher_version" it tell's me: 3.3.0.  
Hi @developernotes Alright I will do that as soon as possible.

**Comment by safarious** [comment]
@developernotes I've wrote a new test for the SQLCipher test suite. 

But I'm not able to reproduce the issue, because the test suite clears the database-directory on every launch. However I've attached you the file, I hope it helps. You can find it [here!] (http://we.tl/9kzO0MZSZI)

**Comment by developernotes** [comment]
Hello @safarious 

Please consider forking the test suite and creating the test within the suite, if you bundle the database within the assets directory that will be a good starting place for debugging your scenario.  Thank you.

**Comment by safarious** [comment]
Hi @developernotes 
Allright you'll find the test-suite [here.](https://www.dropbox.com/s/lles2pcueysy1hd/sqlcipher-android-tests.zip?dl=0)

Too reproduce the issue do following steps:
1. Start Test-Suite (Test should Pass)
2. Kill the Test-Suite
3. Start the Test-Suite again (Test should Fail)

Kind Regards, safari

**Comment by safarious** [comment]
Hello @developernotes do you had time yet to look into that problem? Kind Regards, safarious

**Comment by developernotes** [comment]
Hello @safarious 

I haven't had the opportunity to look into this any further yet.  Are you using the community edition of SQLCipher for Android, or do you have a commercial license?

**Comment by safarious** [comment]
Hello @developernotes we're usting the community edition of SQLCipher at the moment. Kind Regards
