### ISSUE TITLE
Support Write-Ahead-Logging mode via Java APIs for SQLCipher

### ISSUE THREAD

**Issue by jayal** [sqlcipher/android-database-sqlcipher#198]
SQLCipher native added support for Write Ahead Logging (WAL) mode which provides concurrency between reads and a single write. Currently the only way to trigger a WAL mode is via <b>`pragma journal_mode=wal`</b>. However, transactions are limited in [being exclusive](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/src/net/sqlcipher/database/SQLiteDatabase.java#L619). 

On the other hand AOSP has added support for WAL mode in SQLite via the addition of [new APIs](http://developer.android.com/intl/zh-cn/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging()) and a new Java layer. This permits full use of the concurrency advantages of WAL. 

Can we update the Java access layers to provide native WAL concurrency capabilities?

**Comment by developernotes** [comment]
Hi @jayal 

We will consider this for a future release.  Thanks!

**Comment by jayal** [comment]
@developernotes Would the recent changes on [android-n-preview](https://github.com/sqlcipher/android-database-sqlcipher/tree/android-n-preview) allow adding this capability?

**Comment by developernotes** [comment]
Hello @jayal 

There has not been a change to the Java API with regard to transaction. Currently you can initiate an immediate or deferred transaction through `rawExecSQL(…)` usage if you do not wish to have an exclusive transaction.
