### ISSUE TITLE
v3.3.1-1 crash, Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), on API 15 x86

### ISSUE THREAD

**Issue by TheNephilim88** [sqlcipher/android-database-sqlcipher#200]
Hey,

with current version 3.3.1-1 of SQLCipher my app is crashing on Android API 15 when running on x86-image. The crash is NOT occurring with previous version 3.3.1!

Tried with different emulator images and thats the result with 3.3.1-1 (all my physical devices do not crash, but all are arm):
API 23 x86_64: 	No Problem!
API 23 x86:		No Problem!
API 23 arm:		No Problem!
API 22 x86:		No Problem!
API 19 x86:		No Problem!
API 17 x86:		No Problem!
API 16 x86:		No Problem!
API 15 x86:		Fail!
API 15 arm:		No Problem!

Thats the log that is shown on API 15 x86 when its crashing:
10-13 15:56:54.830 1859-1859/myapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
10-13 15:56:54.849 1859-1864/myapp D/dalvikvm: GC_CONCURRENT freed 202K, 3% free 13009K/13319K, paused 0ms+0ms
10-13 15:56:54.879 1859-1859/myapp D/gralloc_goldfish: Emulator without GPU emulation detected.
10-13 15:57:03.210 1859-1864/myapp D/dalvikvm: GC_CONCURRENT freed 199K, 3% free 13205K/13511K, paused 0ms+0ms
10-13 15:57:03.350 1859-1864/myapp D/dalvikvm: GC_CONCURRENT freed 322K, 4% free 13274K/13703K, paused 0ms+0ms
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: Trying to load lib /data/data/myapp/lib/libstlport_shared.so 0xb3d0e8c8
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: Added shared lib /data/data/myapp/lib/libstlport_shared.so 0xb3d0e8c8
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: No JNI_OnLoad found in /data/data/myapp/lib/libstlport_shared.so 0xb3d0e8c8, skipping init
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: Trying to load lib /data/data/myapp/lib/libsqlcipher_android.so 0xb3d0e8c8
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: Added shared lib /data/data/myapp/lib/libsqlcipher_android.so 0xb3d0e8c8
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: No JNI_OnLoad found in /data/data/myapp/lib/libsqlcipher_android.so 0xb3d0e8c8, skipping init
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: Trying to load lib /data/data/myapp/lib/libdatabase_sqlcipher.so 0xb3d0e8c8
10-13 15:57:03.369 1859-1933/myapp D/dalvikvm: Added shared lib /data/data/myapp/lib/libdatabase_sqlcipher.so 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp I/Database: JNI_OnLoad called
10-13 15:57:03.379 1859-1933/myapp I/Database: JNI_OnLoad register methods 
10-13 15:57:03.379 1859-1933/myapp D/dalvikvm: Trying to load lib /data/data/myapp/lib/libstlport_shared.so 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp D/dalvikvm: Shared lib '/data/data/myapp/lib/libstlport_shared.so' already loaded in same CL 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp D/dalvikvm: Trying to load lib /data/data/myapp/lib/libsqlcipher_android.so 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp D/dalvikvm: Shared lib '/data/data/myapp/lib/libsqlcipher_android.so' already loaded in same CL 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp D/dalvikvm: Trying to load lib /data/data/myapp/lib/libdatabase_sqlcipher.so 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp D/dalvikvm: Shared lib '/data/data/myapp/lib/libdatabase_sqlcipher.so' already loaded in same CL 0xb3d0e8c8
10-13 15:57:03.379 1859-1933/myapp A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128)

Any ideas?

**Comment by developernotes** [comment]
Hi @TheNephilim88 

Thank you for the report, we will look into this an report back our findings.

**Comment by developernotes** [comment]
Hi @TheNephilim88 

I was able to identify an issue with a call to `cursor.getString(0);` when running on the 4.0.3 x86 emulator.  You didn't mention the specific scenario that was crashing - can you share to confirm we are looking at the same type of issue?  Thanks!

**Comment by TheNephilim88** [comment]
Hey @developernotes 

did a quick look on it and it seems that

*mDatabase = SQLiteDatabase.openOrCreateDatabase(...)*

leads to Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128)

**Comment by developernotes** [comment]
Hello @TheNephilim88 

We have isolated the issue to a compiler optimization in the Android NDK version r10e, also present in r10d.  OpenSSL compiles by default with optimizations set to `-O3`.  Manually adjusting this to `-O2` resolves the issue.  Instead however, we have decided to revert our NDK usage to r9d as this addresses the issue and does not require modification to the OpenSSL build process.  A new SQLCipher for Android release is forthcoming.

**Comment by TheNephilim88** [comment]
Hello @developernotes 

thank you very much, very appreciated :)

**Comment by brodybits** [comment]
Should this be reported to OpenSSL? Just an idea:)

**Comment by developernotes** [comment]
@brodybits 

I don't think this is an OpenSSL issue so much as a problem with the Android NDK.  I am not certain who to report that to however.

**Comment by brodybits** [comment]
@developernotes can you share any pointers how I can reproduce and demonstrate the compiler issue? I would like to save someone else the time it would take to discover, isolate, and diagnose the issue. Thanks!

**Comment by developernotes** [comment]
@brodybits if you build new OpenSSL binaries with the `make build-openssl-libraries` using the Android NDK version r10e or r10d, then run the standard `make` to build SQLCipher for Android the test suite will crash.  Changing the NDK to version r9d, rebuilding the OpenSSL libraries, finally rebuilding SQLCipher for Android resolves the issue.  I will update the README to include a comment about which Android NDK is recommended.

**Comment by brodybits** [comment]
Thanks!

**Comment by developernotes** [comment]
No problem!

**Comment by SachithWanni** [comment]
I am implementing SQLcipher to my android app using AAR. I have added compile 'net.zetetic:android-database-sqlcipher:3.3.1-2@aar' to my build and .aar file to the library folder also. But I am getting a java error - java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.stl.blelogger/com.stl.blelogger.Settings}: java.lang.NullPointerException

This error points to loadLibs method.. How to fix this?
Thanks.

**Comment by developernotes** [comment]
Hello @SachithWanni 

Could you create a [new Github issue](https://github.com/sqlcipher/android-database-sqlcipher/issues/new) and post the entire stack trace?
