### ISSUE TITLE
onCommit and onRollback of SQLiteTransactionListener is not called.

### ISSUE THREAD

**Issue by atomd** [sqlcipher/android-database-sqlcipher#207]
Hi, 
I found that `onCommit` and `onRollback` of `SQLiteTransactionListener` is not called sometimes.

In function `endTransaction`, the `mTransactionListener` will be will be set `null` when `mLock.getHoldCount() > 1`. I think maybe this is the reason.

**Comment by developernotes** [comment]
Hi @atomd 

Is this something that you can replicate with the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?  We would be glad to look into this further provided an example that replicates the issue.  Thanks!
