### ISSUE TITLE
cannot read android encrypted database in linux

### ISSUE THREAD

**Issue by polarbear82** [sqlcipher/android-database-sqlcipher#208]
I have encrypted database on android device using sqlcipher and I'm trying to read  /decrypte  it on ubuntu (14)  by using sqlcipher commandline:

developer@developer-pc:~/workspaces/sandbox$ sqlcipher Database_E.db 
SQLCipher version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key = 'q1uja';
sqlite> ATTACH DATABASE 'plaintext.db' AS plaintext KEY '';
Error: file is encrypted or is not a database
sqlite> 

the encrypted database can be read in android application.

so I beleve I have some compatibility issue

**Comment by developernotes** [comment]
Hello @polarbear82 

Do you know what version of SQLCipher was used to create the SQLCipher database file you pulled off the Android device?

**Comment by polarbear82** [comment]
no I don't  but i cloned the latest from github.
how can I verify on the device the 8nstalled version

**Comment by developernotes** [comment]
Hello @polarbear82 

If you are able to execute code against the SQLCipher for Android library on the Android device/emulator, you can retrieve the version of the library by executing the following command:

```
PRAGMA cipher_version;
```
