### ISSUE TITLE
SQLiteDatabase.loadLibs  UnsatisfiedLinkError on Android 4.0.4 

### ISSUE THREAD

**Issue by suraj9781** [sqlcipher/android-database-sqlcipher#211]
Caused by java.lang.UnsatisfiedLinkError
	
java.lang.Runtime.loadLibrary (Runtime.java:370)
	
java.lang.System.loadLibrary (System.java:535)
	
net.sqlcipher.database.SQLiteDatabase.loadLibs (SQLiteDatabase.java:140)
	
net.sqlcipher.database.SQLiteDatabase.loadLibs (SQLiteDatabase.java:135)
	
xxx.ui.SplashScreenActivity.createDB (SplashScreenActivity.java:85)
	
xxx.ui.SplashScreenActivity.access$100 (SplashScreenActivity.java:23)
	
xxx.ui.SplashScreenActivity$PrefetchData.doInBackground (SplashScreenActivity.java:61)
	
xxx.ui.SplashScreenActivity$PrefetchData.doInBackground (SplashScreenActivity.java:50)

**Comment by developernotes** [comment]
Hello @suraj9781 

The native libraries to SQLCipher for Android were not included in your application.  Please review the integration tutorial for SQLCipher for Android [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android).
