### ISSUE TITLE
asma-1 bt device integration through bluetooth

### ISSUE THREAD

**Issue by mkhan11in** [sqlcipher/android-database-sqlcipher#212]
My app is to interact with asma-1 bt device and receive data. There is a particular protocol to derive the data. However I cannot break the data properly. can anybody please help.

Thanks

**Comment by developernotes** [comment]
If you have a question regarding usage of SQLCipher, the public SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site is a better fit.  Thanks!

**Comment by mkhan11in** [comment]
am sorry to put my question on different section. Actually my question is on bluetooth device integration in android and reading data

**Comment by developernotes** [comment]
No worries @mkhan11in - take care!
