### ISSUE TITLE
Request addition android sqlite cflag

### ISSUE THREAD

**Issue by theBlbDan** [sqlcipher/android-database-sqlcipher#213]
Would you please consider adding the following flag to /external/Android.mk?

SQLITE_ENABLE_FTS3_PARENTHESIS

This flag enables the use of boolean operators with the MATCH operator.

**Comment by developernotes** [comment]
Hi @theBlbDan 

Yes, we can include `SQLITE_ENABLE_FTS3_PARENTHESIS` in the next release.  Thanks!

**Comment by theBlbDan** [comment]
Thanks a bunch.

**Comment by developernotes** [comment]
Hi @theBlbDan 

I just wanted to provide an update on this inquiry.  We have just released a new version of SQLCipher for Android and I have included `SQLITE_ENABLE_FTS3_PARENTHESIS` in the build.

**Comment by theBlbDan** [comment]
Thank you so much. This simplifies my build dramatically.  Already tested and loving it.
```java
compile 'net.zetetic:android-database-sqlcipher:3.4.0@aar'
```

**Comment by developernotes** [comment]
Hi @theBlbDan 

Thank you for your feedback, we are glad to hear everything is working well for you.  Take care!
