### ISSUE TITLE
Some question confused me pls help

### ISSUE THREAD

**Issue by zhEdward** [sqlcipher/android-database-sqlcipher#214]
1:When i use android api to encrypt db (pwd: kk) then export to  PC. use "SqliteDeveloper " sofeware open with original password fail. promote "File is encrypted or no a database" why? 

2:Another question:  if i encrypt  db ,then i want to  cancel  encrypt(mean cancel original pwd ) ,there is any api can do that .

**Comment by developernotes** [comment]
Hi @zhEdward 

>When i use android api to encrypt db (pwd: kk) then export to PC. use "SqliteDeveloper " sofeware open with original password fail. promote "File is encrypted or no a database" why? 

If you are attempting to access a SQLCipher database, you will need to do so via one of the available [management interfaces](http://discuss.zetetic.net/t/management-interfaces-for-sqlcipher-databases/121).

>Another question: if i encrypt db ,then i want to cancel encrypt(mean cancel original pwd ) ,there is any api can do that .

I don't know what you mean by cancel the encryption, however if you are looking to export a plain text version of the database from an encrypted database, take a look at the [`sqlcipher_export(…)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) API.

Please consider using the community  [discuss](https://discuss.zetetic.net/c/sqlcipher) site for these type of questions.  Thanks!
