### ISSUE TITLE
loadLibs error on some devices

### ISSUE THREAD

**Issue by maniacs-engineerica** [sqlcipher/android-database-sqlcipher#215]
Hi, I received a bug report occurring on "loadLibs()" method in SQLiteDatabase.class.
I checked the stack trace and the error is happening specifically in Runtime.loadLibrary(..., ...) (Line 359)

The method is throwing this a java.lang.UnsatisfiedLinkError.

The user is using a Samsung Note 5 with 5.1.1.

Can you help me?
Thanks.

**Comment by developernotes** [comment]
Hello @maniacs-engineerica 

What value does your device report when running:
```
String arch = System.getProperty("os.arch");
```
Are you including any other 3rd party applications?

**Comment by maniacs-engineerica** [comment]
I cannot run that, the device is not mine.
I am using ZBar integration.

**Comment by developernotes** [comment]
Hi @maniacs-engineerica 

From what I have found, the Samsung Note 5 uses a Exynos 7420 Octa chip, which uses the `ARMv8-A` instruction set.  At this time, SQLCipher for Android only supports `armeabi`, `armeabi-v7a`, and `x86` instruction sets.

**Comment by maniacs-engineerica** [comment]
Excellent data, I hadn't read about it.
Thanks for support.
