### ISSUE TITLE
error: SQLiteCursor is not abstract

### ISSUE THREAD

**Issue by JulioV** [sqlcipher/android-database-sqlcipher#217]
Hi,

I tried to generate SQLCipher from the source files. First I was getting an error saying that build.xml didn't exist so before 'make init' I run

    android update project -p . -t android-23

Then when running 'make' I get 3 errors:

    BulkCursorToCursorAdaptor.java:35: error: BulkCursorToCursorAdaptor is not abstract and does not override abstract method setExtras(Bundle) in Cursor
    MatrixCursor.java:29: error: MatrixCursor is not abstract and does not override abstract method setExtras(Bundle) in Cursor
    SQLiteCursor.java:44: error: SQLiteCursor is not abstract and does not override abstract method setExtras(Bundle) in Cursor

**Comment by developernotes** [comment]
Hi @JulioV 

You shouldn't need to issue that command directly.  Please run [`make init`](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/Makefile#L34-L38) which should use the [project.properties](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/project.properties).

**Comment by JulioV** [comment]
Thanks for your answer @developernotes. If I do that I get:

    ant release
    Buildfile: build.xml does not exist!
    Build failed
    Makefile:53: recipe for target 'build-java' failed
    make: *** [build-java] Error 1

I have installed ant 1.96.: "Apache Ant(TM) version 1.9.6 compiled on June 29 2015"

**Comment by developernotes** [comment]
Hi @JulioV 

What is the full output when you run `make init`?

**Comment by JulioV** [comment]
This is the output of `make init` http://pastebin.com/LwULTfAp

**Comment by developernotes** [comment]
Hi @JulioV 

The output shows this causing the issue:

```
android update project -p .
Error: The project either has no target set or the target is invalid.
```
Do you have [API 19](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/project.properties) installed from the `android` tool?  If not, this would explain the behavior you are seeing.

**Comment by JulioV** [comment]
Yes, that was exactly the problem. Does it make sense to open a new issue suggesting to summarize `make init` errors at the end of the script? or mention the Android API requirement in the installation guide?

Thank you very much

**Comment by brodybits** [comment]
> Does it make sense to open a new issue suggesting to summarize make init errors at the end of the script? or mention the Android API requirement in the installation guide?

I think the requirement for Android API 19 should be mentioned as a prerequisite in the **Building** section. (The "installation guide" assumes that you are using a version that has already been built with success.)

It would also be nice to a section that goes through common errors and problems with building from source (like this one).

**Comment by developernotes** [comment]
Hi @JulioV 

I'm glad to hear that addressed the issue.  I think @brodybits is correct in that we should mention the API version as a prerequisite in the [Building](https://github.com/sqlcipher/android-database-sqlcipher/#building) section, will need to think more about having a section for common errors/problems however.  Take care!

**Comment by developernotes** [comment]
Hi @JulioV @brodybits 

As it turns out, the [Building](https://github.com/sqlcipher/android-database-sqlcipher/#building) section already addresses the API 19 requirement for the Android SDK.

**Comment by brodybits** [comment]
Yes:
> To complete the `make init` command, you will need the `android-19` platform installed from the SDK.

My bad!

**Comment by developernotes** [comment]
No worries! :+1:

**Comment by JulioV** [comment]
That one has it but not this one https://www.zetetic.net/sqlcipher/sqlcipher-for-android/

**Comment by developernotes** [comment]
Hello @JulioV 

Correct, the aim of that article is specifically around integrating SQLCipher for Android within an application as a client developer, while it does touch on the basics for building the source, the [README](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/README.org) goes into further detail.
