### ISSUE TITLE
Couldn't load the library in Android

### ISSUE THREAD

**Issue by JulioV** [sqlcipher/android-database-sqlcipher#218]
I don't know what is the cause of this error (maybe the latest version of gradle or the ndk?) which is a duplicate of this one (https://github.com/sqlcipher/android-database-sqlcipher/issues/152) but I solved it by changing the name of the dir 'lib' to 'jniLibs' plus modifying the `compile files` line in the `build.gradle` file.

Error: `java.lang.UnsatisfiedLinkError: Couldn't load stlport_shared from loader ... findLibrary returned null`

It is important to mention that the project I am working on compiles two different projects to create the apk, and so there is a general build.gradle and one specific for each sub-project. Probably, an alternative solution would be to add this to the `build.gradle` file.

```
sourceSets {
        main {
            jniLibs.srcDir file('libs/')
        }
    }
```

I want to share this in case anyone else runs into the same problem.

**Comment by developernotes** [comment]
Hi @JulioV 

Thank you for sharing your feedback with integrating the library.  While we discuss some of this in our write up for utilizing SQLCipher for Android within Android Studio [here](https://discuss.zetetic.net/t/android-studio-integration/65), your scenario is slightly different.  I would ask that you consider moving this to our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) as we try to reserve Github Issues for managing issues with the source of the library itself.  Thanks!
