### ISSUE TITLE
Database migration error 

### ISSUE THREAD

**Issue by Nasir-S** [sqlcipher/android-database-sqlcipher#219]
Hi. I used sqlcipher 3.\* to encrypt my database. it work very well. but now I want to migrate to new database ( Version 2 ). but when I change database version, open database do not work and can not open previous database.

   `myDataBase = SQLiteDatabase.openOrCreateDatabase(DB_PATH,DB_PASS, null);`
Exception occur in this line in class `SQLiteDatabase`
    `this.dbopen(this.mPath, this.mFlags);`
The second problem, is database version. always return 0 .
Thanks

**Comment by developernotes** [comment]
Hello @Nasir-S 

I apologize for the delayed response, were you able to resolve your issue? You can migrate a database utilizing the [`PRAGMA cipher_migrate;`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate) command.

**Comment by Gelacio** [comment]
Hello @developernotes 

I'm having issues to migrate my DB from 2.x to 3.x version. Can you please tell the steps to follow to migrate it?

Thanks

**Comment by sjlombardo** [comment]
@Gelacio Have you tried using the `cipher_migrate` feature mentioned above? The documentation can be found here:

https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate

Basically, you will just need to set the key, then execute `PRAGMA cipher_migrate`. This will upgrade the database from 2.x to 3.x. Migration is a one time step, after you've done it once you can simply open the database as normal. It may be convenient to use an application preference or other method to track the version of the database so you don't need to run migrate multiple times.

**Comment by Gelacio** [comment]
Hi @sjlombardo,
Using the SQLCipher Android demo it's working just fine. The problem is when I use sqlite3 from command line. 
I can migrate a DB using SQLite Android test. Then trying to decrypt that DB from Windows using sqlite3 from command line, it shows the error "File is encrypted or is not a database error".

I realized the sqlite3 version is too old. Where can I get new version?

Thanks


Thanks

**Comment by theBlbDan** [comment]
@Gelacio 
Do you have a copy of [SQLite Expert](http://www.sqliteexpert.com/)?  I have compiled the 32bit dll for use with this, if you'd like.  It's built from sqlcipher-master-3.3.0.

**Comment by sjlombardo** [comment]
@Gelacio are you trying to run the export with a standard sqlite3 prompt, or with one built from the SQLCipher code. You would need to be using a Windows client that is built with SQLCipher support. This page has a few options, in addition to the one mentioned by @theBlbDan:

https://discuss.zetetic.net/t/management-interfaces-for-sqlcipher-databases/121

**Comment by Gelacio** [comment]
Thanks so much for your support and info. I have successfully compiled SqlCipher for Windows.

**Comment by sjlombardo** [comment]
@Gelacio excellent, glad to hear that you are up and running!
