### ISSUE TITLE
On Using SQLCipher with Nexus 6 on Android N, there are issues coming up related to retrieving values from database.

### ISSUE THREAD

**Issue by erankitarora** [sqlcipher/android-database-sqlcipher#221]
Issues:

1.) There were invalid strings coming up: (Logs below)

03-29 08:45:10.714: E/AndroidRuntime(27012): Caused by: java.lang.NumberFormatException: For input string: "瑕汩⁳⁼湅整敲業牧瑡䙥汩獥਍"
03-29 08:45:10.714: E/AndroidRuntime(27012):  at java.lang.Integer.parseInt(Integer.java:521)
03-29 08:45:10.714: E/AndroidRuntime(27012):  at java.lang.Integer.valueOf(Integer.java:611)

2.) There were other errors coming up related to jni libraries: (Logs below)

03-30 18:29:13.334: A/libc(4684): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4684 (ra.sqlcipherapp)
03-30 18:29:13.415: A/DEBUG(4709): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-30 18:29:13.415: A/DEBUG(4709): Build fingerprint: 'google/shamu/shamu:N/NPC56P/2659757:user/release-keys'
03-30 18:29:13.415: A/DEBUG(4709): Revision: '0'
03-30 18:29:13.415: A/DEBUG(4709): ABI: 'arm'
03-30 18:29:13.415: A/DEBUG(4709): pid: 4684, tid: 4684, name: ra.sqlcipherapp  >>> com.example.aarora.sqlcipherapp <<<
03-30 18:29:13.416: A/DEBUG(4709): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-30 18:29:13.416: A/DEBUG(4709):     r0 00000000  r1 00000000  r2 00000000  r3 94f80000
03-30 18:29:13.416: A/DEBUG(4709):     r4 00000000  r5 94f85613  r6 966beb30  r7 b31ad008
03-30 18:29:13.416: A/DEBUG(4709):     r8 00000002  r9 00000000  sl beb47910  fp b2684f00
03-30 18:29:13.416: A/DEBUG(4709):     ip ab644cc0  sp beb47870  lr ab6390f1  pc ab637d52  cpsr 800f0030
03-30 18:29:13.422: A/DEBUG(4709): backtrace:
03-30 18:29:13.422: A/DEBUG(4709):     #00 pc 0000dd52  /system/lib/libutils.so (android::SharedBuffer::acquire() const+3)
03-30 18:29:13.422: A/DEBUG(4709):     #01 pc 0000f0ed  /system/lib/libutils.so
03-30 18:29:13.423: A/DEBUG(4709):     #02 pc 0000f15f  /system/lib/libutils.so (android::String16::String16(char const*, unsigned int)+8)
03-30 18:29:13.423: A/DEBUG(4709):     #03 pc 000087cf  /data/app/com.example.aarora.sqlcipherapp-2/lib/arm/libdatabase_sqlcipher.so
03-30 18:29:13.423: A/DEBUG(4709):     #04 pc 001209f9  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
03-30 18:29:13.424: A/DEBUG(4709):     #05 pc 00000983  /dev/ashmem/dalvik-jit-code-cache (deleted)
03-30 18:29:13.787: I/BootReceiver(905): Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
03-30 18:29:13.945: D/GraphicsStats(905): Buffer count: 4
03-30 18:29:13.945: I/WindowManager(905): WIN DEATH: Window{e0cc6b5 u0 com.example.aarora.sqlcipherapp/com.example.aarora.sqlcipherapp.MainActivity}
03-30 18:29:13.948: I/Zygote(398): Process 4684 exited due to signal (11)
03-30 18:29:13.952: I/ActivityManager(905): Process com.example.aarora.sqlcipherapp (pid 4684) has died
03-30 18:29:13.953: W/ActivityManager(905): Force removing ActivityRecord{8543d90 u0 com.example.aarora.sqlcipherapp/.MainActivity t159}: app died, no saved state
03-30 18:29:13.957: I/WindowManager(905): Destroying surface Surface(name=com.example.aarora.sqlcipherapp/com.example.aarora.sqlcipherapp.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:1738 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:816 com.android.server.wm.WindowState.removeLocked:1343 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2302 
03-30 18:29:13.961: D/ActivityManager(905): finishRunningVoiceLocked()  >>>>

**Comment by developernotes** [comment]
Hello @erankitarora 

Thank you for your report.  We are already tracking an active issue with running SQLCipher for Android on the Android N preview build #216.
