### ISSUE TITLE
Crash with cannot load library

### ISSUE THREAD

**Issue by Tapchicoma** [sqlcipher/android-database-sqlcipher#222]
This crash happens when my app tries to load libdatabase_sqlcipher.so on devices with android 4.0.3:

`

```
java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1285]:   138 cannot locate '__gnu_thumb1_case_uqi'...

at java.lang.Runtime.loadLibrary(Runtime.java:370)
at java.lang.System.loadLibrary(System.java:535)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:141)
at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:135)
```

'

Any other android versions (minSdk is 14) work fine.

**Comment by developernotes** [comment]
Hi @Tapchicoma 

What version of SQLCipher for Android are you using within your application?

**Comment by Tapchicoma** [comment]
@developernotes the latest one from bintray - 3.3.1-2

**Comment by developernotes** [comment]
Hi @Tapchicoma,

What specific devices are you running 4.0.3 that causes the error?  Would you try running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on those devices and report your results?  Thanks!

**Comment by Tapchicoma** [comment]
Hi @developernotes, the devices that has this crash is:
- HTC Sensation Z710E
- LG P700 L7
I will try to do it on LG P700 L7 as soon as get access to it.

**Comment by Tapchicoma** [comment]
Hi @developernotes.

So I can get access to the device that is crashing.
It is still happens with recently released version 3.4.0, but I've run test suite and it finishes without errors.

Few more notes:

- We have 2 app variants that uses shared library that contains this sqlcipher so files - first variant is smaller one and it works fine on this 4.0.3 device, the second one is a huge app that uses multidex and it crashes.

- One more - I've tried to compile sqlcipher for android using [crystax ndk](https://www.crystax.net/) and it works ok in both applications on this device, but this ndk has problems with android 6.0

**Comment by developernotes** [comment]
Hi @Tapchicoma 

>We have 2 app variants that uses shared library that contains this sqlcipher so files - first variant is smaller one and it works fine on this 4.0.3 device, the second one is a huge app that uses multidex and it crashes.

Are you using ProGuard in either of these scenarios? If so, would you try disabling that to see if the behavior is the same or changes?

**Comment by brodybits** [comment]
> I've tried to compile sqlcipher for android using crystax ndk and it works ok in both applications on this device, but this ndk has problems with android 6.0

@Tapchicoma did you report this to CrystaX? I would like to start using their NDK but would like to see this get fixed.

**Comment by Tapchicoma** [comment]
@developernotes yes, we are using ProGuard in both scenarios, disabling it doesn't help.

@brodybits problem of CrystaX with android 6.0 is not related to sqlcipher itself, you can track this issue [here](https://tracker.crystax.net/issues/1108)

**Comment by developernotes** [comment]
@Tapchicoma 

Do you have [shrinking](http://developer.android.com/tools/help/proguard.html) enabled for your release build?

**Comment by Tapchicoma** [comment]
@developernotes the large project is still using

    com.android.tools.build:gradle:1.3.1

and for some internal reasons can't upgrade to latest. Smaller one is using 2.0.0.

By default

    minifyEnabled true

but disabling it doesn't help (I disabled all except multidex).

**Comment by developernotes** [comment]
Hi @Tapchicoma 

It sounds as if utilizing multidex may be the cause of the problem. Can you remove some of your additional 3<sup>rd</sup> party libraries such that you wouldn't be required to use multidex to see if you are then able to load SQLCipher for Android within your application?

**Comment by brodybits** [comment]
Off-topic with apologies: Thanks @Tapchicoma for the link to the CrystaX issue. I hope to have a chance to experiment with CrystaX sometime.

**Comment by Tapchicoma** [comment]
Hi @developernotes 

It is a lot of work to remove this 3rd party libraries and I give up on it. For now it is not a critical issue as this shared library disabled on android 4.0.3 devices and I see that CrystaX is fixed the problem with android 6, so I will give it another try.

**Comment by ravisarma** [comment]
Hi @developernotes @Tapchicoma 

We are still observing "cannot load library" crashes on 4.0.x with Sqlcipher 3.5.1. Do you know of any workaround/solution to support sqlcipher in ICS devices. Thanks.

**Comment by sjlombardo** [comment]
@ravisarma are you also using the CrystaX NDK, or is this a different issue? If it is a different issue, it would be helpful for you to start a new Issue with all the relevant details about your situation.
