### ISSUE TITLE
I want encrypt exist no encrypt  sqlite db file

### ISSUE THREAD

**Issue by a137235** [sqlcipher/android-database-sqlcipher#233]
How to do，help me

**Comment by developernotes** [comment]
Hi @a137235 

You will want to take a look at the [`sqlcipher_export(…)`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export) convenience function. You might consider posting any further questions to our [Discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
