### ISSUE TITLE
missing libdatabase_sqlcipher from build on android-n-preview

### ISSUE THREAD

**Issue by tonymet** [sqlcipher/android-database-sqlcipher#235]
I'm working to test the android n preview (thanks!) and builds seem to complete OK--but the build artifacts are missing the `libdatabase_sqlcipher.so`.  Is there a new build flag to generate those libs?

## Artifacts from the android-n-preview branch
```
find libs                               
libs
libs/armeabi
libs/armeabi/libsqlcipher.so
libs/armeabi-v7a
libs/armeabi-v7a/libsqlcipher.so
libs/sqlcipher-javadoc.jar
libs/sqlcipher.jar
libs/x86
libs/x86/libsqlcipher.so
```

## current artifacts from a previous build of android-database-sqlcipher
```
./armeabi/libdatabase_sqlcipher.so
./armeabi/libsqlcipher.so
./armeabi/libsqlcipher_android.so
./armeabi-v7a/libdatabase_sqlcipher.so
./armeabi-v7a/libsqlcipher.so
./armeabi-v7a/libsqlcipher_android.so
./sqlcipher-javadoc.jar
./sqlcipher.jar
./x86/libdatabase_sqlcipher.so
./x86/libsqlcipher.so
./x86/libsqlcipher_android.so
```

**Comment by developernotes** [comment]
Hello @tonymet 

Thanks for taking a look at the `android-n-preview` branch! We have made some significant changes to the build within that branch that also affects the binary output. The new output as you have noted is smaller; we are only creating a single native .so file per platform now. [Here](http://discuss.zetetic.net/t/sqlcipher-for-android-upcoming-changes-for-android-n-and-coordinated-beta-test-request/1315?u=developernotes) are some details regarding the changes.

**Comment by tonymet** [comment]
ok that's great.  i'll work on linking in this new binary and let you guys know if there are any issues /changes.  thanks for all the help.

**Comment by developernotes** [comment]
Hi @tonymet 

Thanks, we look forward to hearing your results!
