### ISSUE TITLE
UnsatisfiedLinkError couldn't find libsqlcipher_android.so with android-pdfview

### ISSUE THREAD

**Issue by slartus** [sqlcipher/android-database-sqlcipher#236]
this error only when i run with project:
compile 'com.joanzapata.pdfview:android-pdfview:1.0.4@aar'

when I **exclude** this library (android-pdfview), it all works

```
..
 sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
..
```

```

\libs\commons-codec.jar
\libs\guava-r09.jar
\libs\armeabi\libdatabase_sqlcipher.so
\libs\x86\libdatabase_sqlcipher.so
\libs\armeabi\libsqlcipher_android.so
\libs\x86\libsqlcipher_android.so
\libs\armeabi\libstlport_shared.so
\libs\x86\libstlport_shared.so
\libs\sqlcipher.jar
```

log error:
`ANDROID_VERSION=5.0.2
PHONE_MODEL=Redmi Note 3
STACK_TRACE=java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.softeg.partscatalog-1/base.apk"],nativeLibraryDirectories=[/data/app/org.softeg.partscatalog-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsqlcipher_android.so"`

**Comment by slartus** [comment]
test project:
https://drive.google.com/open?id=0B8P-k9LJYtyUUGVNVnVweDdRUU0

**Comment by developernotes** [comment]
Hi @slartus 

Since your application is utilizing Gradle, you can just add a compile entry to the dependencies section to include SQLCipher for Android:

```
compile 'net.zetetic:android-database-sqlcipher:3.4.0@aar'
```

**Comment by slartus** [comment]
it still not worked
https://drive.google.com/open?id=0B8P-k9LJYtyUMG9FV2tCSk9TUzA

**Comment by developernotes** [comment]
Hi @slartus 

SQLCipher for Android only includes native library support for armeabi, armeabi-v7a, and x86. You will need to remove any third-party libraries support for other platforms such as arm64 or x86_64.

**Comment by slartus** [comment]
ok, thanks
