### ISSUE TITLE
SQLiteException on a device boot

### ISSUE THREAD

**Issue by elevenetc** [sqlcipher/android-database-sqlcipher#237]
I have pretty standard exception:
> net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: create locale table failed
> at net.sqlcipher.database.SQLiteDatabase.setLocale(SourceFile:2474)
> at net.sqlcipher.database.SQLiteDatabase.native_setLocale(Native Method)
> ...
> at com.mypackage.ServiceX.onCreate(SourceFile:72)

As I know it usually happens because of wrong password. But the problem that the password is right and the exception appears only when device starts. I have `Service` which starts when device is started. Also if I kill my app(`Service`) and start it again there is no exception.

Not sure where start investigations. Is there some possible problems with database/SQLite when device starts?

**Comment by developernotes** [comment]
Hi @elevenetc 

Does this behavior occur after a fresh install of the application only upon startup, or do you experience it every time requiring you to restart your service? Does it occur on multiple devices/OS versions?

**Comment by elevenetc** [comment]
@developernotes hello

It happens on all devices and on all systems. And it doesn't depend on whether app was just installed or it was launched previously and had some cache(SQLCipher database could be created or not, doesn't matter).

The `Service` which triggers this exception extends HostApduService. And it's started by system for listening NFC events.

**Comment by elevenetc** [comment]
Found the problem. I've used `IMEI` to generate `SQLCipher` password. It turns out that `TelephonyManager` could return null on boot:

> It looks like TelephonyManager needs some time to warm up.

https://code.google.com/p/android/issues/detail?id=188179

So on boot password was wrong, but after device is booted `TelephonyManager` return `IMEI` and password generated properly.

**Comment by developernotes** [comment]
Hello @elevenetc 

Thanks for getting back to us, we are glad to hear you were able to address the issue.
