### ISSUE TITLE
Crash in some phones when launch app

### ISSUE THREAD

**Issue by mamingzhang** [sqlcipher/android-database-sqlcipher#240]
07-29 18:00:43.585 22421-22421/com.kinstalk.withu I/MultiDex: VM with version 1.6.0 does not have multidex support
07-29 18:00:43.585 22421-22421/com.kinstalk.withu I/MultiDex: install
07-29 18:00:43.590 22421-22421/com.kinstalk.withu I/MultiDex: MultiDexExtractor.load(/data/app/com.kinstalk.withu-1.apk, false)
07-29 18:00:43.600 22421-22421/com.kinstalk.withu I/MultiDex: loading existing secondary dex files
07-29 18:00:43.600 22421-22421/com.kinstalk.withu I/MultiDex: load found 1 secondary dex files
07-29 18:00:43.605 22421-22421/com.kinstalk.withu I/MultiDex: install done
07-29 18:00:43.615 22421-22421/com.kinstalk.withu E/dalvikvm: dlopen("/data/app-lib/com.kinstalk.withu-1/libsqlcipher.so") failed: dlopen failed: unknown reloc type 160 @ 0x77639a80 (6332)
07-29 18:00:43.615 22421-22421/com.kinstalk.withu W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x415e3c50)

**Comment by mamingzhang** [comment]
SQLCipher 3.5.1

**Comment by gengjiawen** [comment]
I run into the same problem, looks like it has something to do with ndk target android platform, checked [this](http://stackoverflow.com/questions/28740315/android-ndk-getting-java-lang-unsatisfiedlinkerror-dlopen-failed-cannot-loca).

**Comment by developernotes** [comment]
Hi @mamingzhang, @gengjiawen,

From the stack trace, it appears it may be an issue with multidex support. Are you able to reproduce the behavior in an application that is not using multidex?

**Comment by gengjiawen** [comment]
@developernotes I am not using multidex, it still crashes.

**Comment by gengjiawen** [comment]
@developernotes 
```
java.lang.UnsatisfiedLinkError: dlopen failed: unknown reloc type 160 @ 0xef1aca80 (6332)
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:988)
                                                       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:177)
                                                       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:170)
```

**Comment by developernotes** [comment]
Hello @mamingzhang / @gengjiawen 

Would you try the latest binaries I pushed into the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests), I would like to know if it addresses the issue you are seeing. Thanks!

**Comment by mamingzhang** [comment]
Ok, Wait my result!





At 2016-07-06 01:11:29, "Nick Parker" <notifications@github.com> wrote:


Hello @mamingzhang / @gengjiawen

Would you try the latest binaries I pushed into the SQLCipher for Android test suite, I would like to know if it addresses the issue you are seeing. Thanks!

**Comment by gengjiawen** [comment]
@developernotes I passed all 47 tests.

**Comment by mamingzhang** [comment]
Phones below 6.0 will crash when using SQLCipher 3.5.1, you can try it, above 6.0 is OK;

**Comment by mamingzhang** [comment]
Hi,
    Phones below 6.0 will crash when using SQLCipher 3.5.1, you can try it, above 6.0 is OK;





At 2016-07-06 01:11:29, "Nick Parker" <notifications@github.com> wrote:


Hello @mamingzhang / @gengjiawen

Would you try the latest binaries I pushed into the SQLCipher for Android test suite, I would like to know if it addresses the issue you are seeing. Thanks!

**Comment by developernotes** [comment]
Hello @mamingzhang 

Will you try the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) using the included binaries? I have just pushed new binaries and added an additional test, all of which is running on a 2.36 device successfully for me. Thanks!

**Comment by mamingzhang** [comment]
@developernotes 
Using the latest version of 3.5.2, it is ok!

**Comment by developernotes** [comment]
Hi @mamingzhang 

Thank you for getting back to us, we are glad to hear the issue is resolved. Take care!
