### ISSUE TITLE
rawQuery method with CancellationSignal

### ISSUE THREAD

**Issue by r00dY** [sqlcipher/android-database-sqlcipher#243]
Hi,

original API SQLiteDatabase has following method:

https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#rawQuery(java.lang.String, java.lang.String[], android.os.CancellationSignal)

Unfortunately, SQLiteDatabase from sqlcipher doesn't have this method.

What is worse, this method is used by ORMLite. To integrate ORMLite with SQLCipher I'm creating my own instance of ormlite-android in the project and override all imports to net.sqlcipher.* (this method makes project very hard to maintain but still best I've found).

But anyway, project doesn't compile because ormlite-android uses rawQuery with CancellationSingal which is absent in SQLLiteDatabase from sqlcipher.

Cheers!

**Comment by developernotes** [comment]
Hello @r00dY 

SQLCipher for Android does not currently include the `rawQuery` function that accepts a `CancellantionSignal` as the SQLCipher for Android Java API is a historical snapshot which supports Android down to 2.1. The function you refer to was not added until API 16.
