### ISSUE TITLE
Where to download v3.5.2 binary file

### ISSUE THREAD

**Issue by jcb316733855** [sqlcipher/android-database-sqlcipher#250]
Where to download v3.5.2 binary file? the maven dependencies can't be accessed directly in my company, and our network have some limit,and I compile fail in Window system. so how to download aar directly

**Comment by developernotes** [comment]
Hello @jcb316733855 

The community edition is [distributed](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/) via the AAR package. Zip packaging is available to those with commercial licenses.
