### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by sek** [sqlcipher/android-database-sqlcipher#251]
See previous #167 and #151 (and #185)

I was able to compile the code that is the base of the #151 pull request locally (took over an hour to compile on a macbook), but it's based on an old version: 3.3.1-2
https://github.com/gmetal/android-database-sqlcipher

From reading the #151 history, it looks like the hold up was waiting for an openssl release that still may not be ready ( according to: https://www.openssl.org/source/ )

Even when it is ready, the pull request will need to be updated to use the new release version, and then conflicts resolved with subsequent changes to master and merged.  Shouldn't there still be an open issue to resolve once the openssl problem is cleared up? (as opposed to having closed issues?)

With the current prevalence of 64-bit phones, it's not really an option to use this library on any Play Store published app until 64-bit support is available.  Maybe it's better to merge (or at least maintain a 64-bit-enabled branch) with the patch implementation?

Thanks!
-Stan

**Comment by developernotes** [comment]
Hello @sek 

>Shouldn't there still be an open issue to resolve once the openssl problem is cleared up?

Because @gmetal's patch was rejected we plan to adjust our code/build configuration for support 64-bit CPU's once the 1.1.0 version of OpenSSL is released. Our changes will be based on the 1.1.0 changes alone. We do not track roadmap items as issues within Github.

>With the current prevalence of 64-bit phones, it's not really an option to use this library on any Play Store published app until 64-bit support is available.

You can currently deploy SQLCipher for Android on 64-bit CPU Android devices. The only restriction is not bundling any 64-bit native libraries along with it due to the native loading behavior on Android.

**Comment by sek** [comment]
I suppose having another 64-bit library in your app does reduce the number of affected apps.  Unfortunately, I might not be able to remove all 64-bit libraries, but I do agree it's not as dire a problem as it initially seemed.

Obviously, I don't have much input in how you differentiate roadmap vs. bug items in your project. One advantage of having an open issue would be to indicate that it doesn't need to be reported again.

Cheers =)

**Comment by sek** [comment]
We found config to filter all 64-bit libraries that's easy to apply (no need to modify dependent aar files as suggested in some solutions I read).  Might be useful for #185 
http://stackoverflow.com/a/30799825/431296

I also noticed that libsqlcipher.so doesn't have MIPS platform included. Did a couple searches and seems that mips tablets aren't too common and mips-based phones are even rarer.  Seems to make sense to include it though - like the ndk does by default - in case a mips-based device becomes popular.

Is it limited by the same OpenSSL problem or could that be a separate change?

**Comment by developernotes** [comment]
Hi @sek 

As you mentioned, both MIPS-based tablets and phones aren't as common as their ARM and x86 counterparts. If that tide changes we would certainly reconsider, but currently we've received very little interest in supporting MIPS. Do you have a commercial need for MIPS support?
