### ISSUE TITLE
Don't support arm64?

### ISSUE THREAD

**Issue by Wanimal** [sqlcipher/android-database-sqlcipher#253]
`nativeLibraryDirectories=[/data/app/com.microcinema-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsqlcipher.so"`

targetSdkVersion 24

**Comment by developernotes** [comment]
Hi @Wanimal 

Please take a look at [this](https://discuss.zetetic.net/t/sqlcipher-for-android-native-library-support/1440) thread. 64-bit dependencies can not be included with SQLCipher for Android at the moment.

**Comment by mdvacca** [comment]
Hi @developernotes, do you know when SQLCipher is going to fully support 64-bit dependencies?

Thanks!

**Comment by developernotes** [comment]
Hi @mdvacca 

We plan to look into native 64-bit library support with the next release of SQLCipher for Android.
