### ISSUE TITLE
I need create encryption file data base 

### ISSUE THREAD

**Issue by MahmoudAlnouno** [sqlcipher/android-database-sqlcipher#254]
thank you for this code .
but i need create encryption file  not all data 
can you help me please ? and thank you

**Comment by developernotes** [comment]
Hi @MahmoudAlnouno 

SQLCipher fully encrypts the entire database file, both data and schema; it does not support partial encryption.

**Comment by MahmoudAlnouno** [comment]
@developernotes  thank you
