### ISSUE TITLE
get field slot from row 0 col 13 failed

### ISSUE THREAD

**Issue by sharyuke** [sqlcipher/android-database-sqlcipher#255]
get field slot from row 0 col 13 failed
![screenshot from 2016-08-25 10-42-36](https://cloud.githubusercontent.com/assets/10694303/17954889/ae6b2478-6ab0-11e6-9897-e95e920e8a3c.png)

![screenshot from 2016-08-25 10-41-21](https://cloud.githubusercontent.com/assets/10694303/17954867/7de1b6aa-6ab0-11e6-8a1d-691d391989fc.png)

**Comment by sjlombardo** [comment]
Hello @sharyuke. We don't have enough information at this point to determine the cause of this issue. Can you please address the following questions:

1. What version of SQLCipher for Android are you using? If you're not using 3.5.3, can you please upgrade to ensure you are using the latest (there are recent changes to the long type handling there).
2. Are you able to use cursor.getString(13) to retrieve the value? i.e., is the problem limited to using getLong?
3. What is the actual value stored in the database for map_modify_time on that first row returned from your query? 
4.  Can you please provide the table definition (i.e. the full CREATE TABLE statement used to establish the schema) 
5. Can you please provide the code you are using to query and create the cursor
