### ISSUE TITLE
I have a database file，windows 2.1 can open it,but android 3.5.3 can not open it.

### ISSUE THREAD

**Issue by lyqaiym** [sqlcipher/android-database-sqlcipher#258]
I have a database file，windows 2.1 can open it,but android 3.5.3 can not open it.
And I create database on android,windows 2.1 also can  not open it.

**Comment by lyqaiym** [comment]
SQLiteDatabaseHook hook = new SQLiteDatabaseHook() {
            public void preKey(SQLiteDatabase database) {
            }

            public void postKey(SQLiteDatabase database) {
                database.rawExecSQL("PRAGMA cipher_migrate;");  //最关键的一句！！！
            }
        };
android 3.5.3 can not open it.

**Comment by developernotes** [comment]
Hi @lyqaiym 

What is the is result code from your `PRAGMA cipher_migrate;` command? Are there any runtime configuration settings used when opening the database on Windows? What does Windows report when you execute `PRAGMA cipher_version;`?

**Comment by perqin** [comment]
Are you trying to decrypt EnMicroMsg.db? I use another hook and it works:
```
    private static class EnMicroMsgHook implements SQLiteDatabaseHook {
        @Override
        public void preKey(SQLiteDatabase sqLiteDatabase) {}

        @Override
        public void postKey(SQLiteDatabase sqLiteDatabase) {
            sqLiteDatabase.rawExecSQL("PRAGMA cipher_use_hmac = off;");
            sqLiteDatabase.rawExecSQL("PRAGMA kdf_iter = 4000;");
        }
    }
```
You can refer to [微信聊天记录分析](https://blog.slinuxer.com/2015/10/%E5%BE%AE%E4%BF%A1%E8%81%8A%E5%A4%A9%E8%AE%B0%E5%BD%95) for more information (of course this post is not mine :D).
