### ISSUE TITLE
Where do i find the libsqlcipher.so for my Android Project.

### ISSUE THREAD

**Issue by iamvalls** [sqlcipher/android-database-sqlcipher#260]
Hello everyone,

i was using before this three file (libdatabase_sqlcipher.so, libsqlcipher_android.so, and libstlport_shared.so) for my Android project and it worked for me find but now i have an App crash while deploying the app on Android 6. I have seen many Solution for those who use Android Studio. But i'm unsing Eclipse to developpe my App and i read somwhere that i need this libsqlcipher.so librarie since google migrate from OpenSSl to BwSSl.

This is the error i get:

unsatisfiedlinkerror : dlopen failed: cannot locate symbol "EVP_CipherFinal"
![image](https://cloud.githubusercontent.com/assets/12074291/18782118/120c6420-8185-11e6-85f0-d385eb59f18d.png)

Please i need some help i'm very new in Android dev.

**Comment by developernotes** [comment]
Hello @iamvalls 

The latest version of SQLCipher for Android includes support for targeting up to Android OS 7. You can find additional information [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/).
