### ISSUE TITLE
Android 6 crashed with java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by AlexTrotsenko** [sqlcipher/android-database-sqlcipher#264]
When I build current master with latest `android-ndk-r12b` I have app's crash at loading `libsqlcipher.so` :

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/.../lib/arm/libsqlcipher.so"
```

Likely caused by https://github.com/android-ndk/ndk/issues/120.
Work-around would be to update `APP_PLATFORM=android-23` as shown here:
https://github.com/android-ndk/ndk/issues/126

I will suggest pull-request shortly. Could be useful for those, who are building master by themselves.

**Comment by developernotes** [comment]
Hello @AlexTrotsenko 

If you are building SQLCipher for Android from source, you need to use Android NDK r11c. This is covered the the [building](https://github.com/sqlcipher/android-database-sqlcipher#building) section of the README.
