### ISSUE TITLE
no such function: _DELETE_FILE

### ISSUE THREAD

**Issue by yzeaho** [sqlcipher/android-database-sqlcipher#266]
I was taking a look at the system MediaProvider.java class source and noticed this trigger:

db.execSQL("CREATE TRIGGER IF NOT EXISTS thumbnails_cleanup DELETE ON thumbnails " +
                "BEGIN " +
                    "SELECT _DELETE_FILE(old._data);" +
                "END");
which apparently deletes a file referenced by thumbnails._data when a thumbnail item is deleted.
I tried to create a similar trigger in my application, but it didn't work. Any ideas why?
I really have to automate this.
net.sqlcipher.database.SQLiteException: no such function: _DELETE_FILE

**Comment by sjlombardo** [comment]
Hello @yzeaho - _DELETE_FILE appears to be a custom function. It is not part of the base SQLite set. If you want to make the same functionality available to your application using SQLCipher you would need to create a new function (likely with a loadable extension). The documentation for doing so is here:

https://www.sqlite.org/c3ref/create_function.html
