### ISSUE TITLE
Need help on building the binary

### ISSUE THREAD

**Issue by Izu87** [sqlcipher/android-database-sqlcipher#267]
Hello,

i am working on an old android project in eclipse and i have to update sqlcipher to 3.5.4 for the new android version. 

And i am not able to build the binary in eclipse (on windows). Can anybody build the binaries and provide it to me? That would be really nice.

Thank You!

**Comment by developernotes** [comment]
Hello @Izu87 

We distribute a community edition build, currently at 3.5.4. You can read more about integrating it within your application [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/).
