### ISSUE TITLE
SIGILL exception when debugging native with android-database-sqlcipher

### ISSUE THREAD

**Issue by MatthieuFereyre** [sqlcipher/android-database-sqlcipher#269]
Hello,

I have a SIGILL signal exception when starting native debug into Android Studio 2.2.1 (and 2.1.1) with android-database-sqlcipher from version 3.3.1 to 3.5.4.

```
Trace into debugger console : 
Debugger attached to process 6418
Signal: SIGILL (signal SIGILL: illegal instruction)
```

Works fine into Java only debug and normal run.
And it works fine if I comment the following line (I have some problems later but no SIGILL signal) :

``` java
SQLiteDatabase.loadLibs(this);
```

Thanks for your help.

**Comment by developernotes** [comment]
Hi @MatthieuFereyre 

I do not use the native debugging within Android Studio, however the `loadLibs(this);` call loads native libraries for the specific platform your application is running on. Have you built a debug version of SQLCipher for Android?

**Comment by MatthieuFereyre** [comment]
No i did not. I have some other native libraries that I want to debug.
If I call SQLiteDatabase.loadLibs(this); the debug process trigger a SIGILL signal, and if I don't use your library, without changing anything else, it works fine.

I could try to build the lib in debug to see if I find something.

**Comment by developernotes** [comment]
Hi @MatthieuFereyre 

>I could try to build the lib in debug to see if I find something.

I think this would be the next step to see if it addresses your issue.

**Comment by chriswoolfe** [comment]
@developernotes Are the debug binaries available anywhere? I wasn't able to find them and my local build is failing. Thanks!

**Comment by developernotes** [comment]
@chriswoolfe debug binaries are not published. If you are building locally, you can run `make build-debug` for a debug build.

**Comment by chriswoolfe** [comment]
For anybody stumbling upon this thread from the net,
The SIGILL instruction happens even with the debug binaries. The good news is that you can just tap "Resume Program" from the debugger, and it will carry on as usual. Everything works as far as I can tell. In other words, SIGILL traps the debugger, but it is not fatal to the program.
