### ISSUE TITLE
Couldn't load stlport_shared

### ISSUE THREAD

**Issue by Swarnamahesh** [sqlcipher/android-database-sqlcipher#27]
Thank you for providing an open source project for protecting the database, as security is a very important feature in my app. I added the jars and so files as mentioned in the installation guide and made the code changes, but I am getting the following error in loadlibs. Can you please help me with this issue.

11-17 12:18:41.827: ERROR/AndroidRuntime(31107): java.lang.UnsatisfiedLinkError: Couldn't load stlport_shared: findLibrary returned null
11-17 12:18:41.827: ERROR/AndroidRuntime(31107):     at java.lang.Runtime.loadLibrary(Runtime.java:429)
11-17 12:18:41.827: ERROR/AndroidRuntime(31107):     at java.lang.System.loadLibrary(System.java:554)
11-17 12:18:41.827: ERROR/AndroidRuntime(31107):     at info.guardianproject.database.sqlcipher.SQLiteDatabase.loadLibs(SQLiteDatabase.java:104)

Why is it not able to load stlport_shared, should i do any specific compilation for the so files?

**Comment by rammansawala** [comment]
Hi developernotes,

I could not got /system/lib where can i get it?

I have already posted my project details on
 https://discuss.zetetic.net/t/java-lang-unsatisfiedlinkerror-couldnt-find-liblibstlport-shared-so/721

Please see this. I need help.

**Comment by developernotes** [comment]
Hello @rammansawala,

I have replied to your discuss post, please review and provide any further feedback within the discuss post.  Thanks!
