### ISSUE TITLE
Android N libs throws the following exception DexPathList[zip file"/data/app/...

### ISSUE THREAD

**Issue by vravindranath** [sqlcipher/android-database-sqlcipher#275]
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/co.TestApp-1/base.apk"],nativeLibraryDirectories=[/data/app/co.TestApp-1/lib/arm, /data/app/co.TestApp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libstlport_shared.so"

I'm using the new lib files from the test
https://github.com/sqlcipher/sqlcipher-android-tests

As per my understanding, we need new so files for Android N builds. According to below post. we must remove the icudt46l.zip from assets folder and add the new so files per platform. 
My question is how to correct the missing shared.so error? why does this happen? 
According to post we only need one so file but unfortunately i'm stuck in here. I understand the 32 bit and 64 bit compatibility issue. From Android N perspective how to resolve the issue so that the cipher does work on Android N. we are able to build the app targeting Android M. But it fails in Android N. Can you please advise a solution?
https://www.zetetic.net/blog/2016/6/23/sqlcipher-android-release-n-support/

**Comment by developernotes** [comment]
Hi @vravindranath 

If you are using the community edition of SQLCipher for Android, you should move over to the AAR distribution/integration. More details can be found [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android).

**Comment by vravindranath** [comment]
@developernotes 
Hi 
Thanks for the reply.
According to the blog we only need the libsqlcipher.so. I'm getting error for link failure due to missing libencryption-sdk.so file. Any idea on how to resolve the dependency ? I'm i missing something here?

**Comment by developernotes** [comment]
Hi @vravindranath 

>According to the blog we only need the libsqlcipher.so. I'm getting error for link failure due to missing >libencryption-sdk.so file. Any idea on how to resolve the dependency ? I'm i missing something here?

I'm not aware of `libencryption-sdk.so`, my recommendation stands that you should switch over to the AAR distribution.
