### ISSUE TITLE
Cannot load libsqlcipher.so

### ISSUE THREAD

**Issue by Stoff81** [sqlcipher/android-database-sqlcipher#279]
Hi,

I am trying to update to the latest version of this lib. Our previous version was from April 2016. We are not using the .aar, but just the .so files which we are in turn using in a c++ orm library called ODB. I have pulled the latest of this repo and built using make init/make with NDK r11. 

However whenever I load the .so using loadLibrary in java code am run my application I keep getting 
`java.lang.NoClassDefFoundError: net/sqlcipher/CursorWindow` errors.

I dont know why its looking for these classes as I have only used the .so file not the .aar
What would be the correct process to compile the .so lib so that it does not need any java classes? In the previous version of this library this was achieved by entering the external folder and executing ndk-build.
 
Thanks

**Comment by faizol** [comment]
Hi,

 I'm having the same problem trying to run libsqlcipher.so from an Qt application. Any update on how to solve this?

Thanks.

**Comment by developernotes** [comment]
Hi @Stoff81, @faizol 

>I dont know why its looking for these classes as I have only used the .so file not the .aar

SQLCipher for Android is structured such that the Java API is used in conjunction with the native libraries. The native library is checking to make sure Java API is present at runtime as a sanity check. Some developers utilize ProGuard to strip components from their release builds which can cause problems. If you only need SQLCipher compiled for Android architectures I would suggest you consider creating a separate NDK project that compiles the SQLCipher amalgamation separately to avoid including any unnecessary components for your project.
