### ISSUE TITLE
samsung s7 edge: android 7.0 get an error:Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib/libsqlite.so"...

### ISSUE THREAD

**Issue by luhuajcdd** [sqlcipher/android-database-sqlcipher#280]
Error detail info:Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "/system/lib/libsqlite.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1530)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:175)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)

Appearing-Certain ！！！

**Comment by developernotes** [comment]
Hi @luhuajcdd 

Are you using the community distribution of SQLCipher for Android, or are you building your own version? We do not reference libsqlite.so.

**Comment by luhuajcdd** [comment]
thank you for your reply.  we are building Ourselves.

**Comment by developernotes** [comment]
Hello @luhuajcdd 

Unfortunately, custom builds are not officially supported. Is there a particular reason you are building from source yourself?
