### ISSUE TITLE
build.xml missing

### ISSUE THREAD

**Issue by biafra23** [sqlcipher/android-database-sqlcipher#283]
The Makefile contains several `ant` commands which fail (`ant release`, `ant clean` ), because the build.xml file is missing in master. This makes the build with `make` fail. 
What needs to be in this `build.xml`?

**Comment by biafra23** [comment]
This problem was apparently due to platform-19 missing. With platform-19 installed, the build.xml is generated.

**Comment by developernotes** [comment]
Hi @biafra23 

I'm glad to hear you were able to address the issue. Take care!
