### ISSUE TITLE
use sqlcipher lib report this dialog

### ISSUE THREAD

**Issue by XuanJiAndroid** [sqlcipher/android-database-sqlcipher#286]
plase help me fix this issues.I‘m can't control show.
Detected problems with app native libraries...
![screenshot_2017-01-03-12-59-32-107_com cvte cvtalk](https://cloud.githubusercontent.com/assets/21168212/21600437/002e3990-d1b7-11e6-9e07-f78360da7ddf.png)

Android API ：25

**Comment by XuanJiAndroid** [comment]
01-03 13:30:39.334 23961-23961/com.cvte.cvtalk W/linker: /data/app/com.cvte.cvtalk-2/lib/arm/libstlport_shared.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
01-03 13:30:39.345 23961-23961/com.cvte.cvtalk W/linker: library "libutils.so" ("/system/lib/libutils.so") needed or dlopened by "/data/app/com.cvte.cvtalk-2/lib/arm/libsqlcipher_android.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-03 13:30:39.347 23961-23961/com.cvte.cvtalk W/linker: library "libcutils.so" ("/system/lib/libcutils.so") needed or dlopened by "/data/app/com.cvte.cvtalk-2/lib/arm/libsqlcipher_android.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-03 13:30:39.360 23961-23961/com.cvte.cvtalk W/linker: /data/app/com.cvte.cvtalk-2/lib/arm/libsqlcipher_android.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
01-03 13:30:39.373 23961-23961/com.cvte.cvtalk W/linker: library "libnativehelper.so" ("/system/lib/libnativehelper.so") needed or dlopened by "/data/app/com.cvte.cvtalk-2/lib/arm/libdatabase_sqlcipher.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-03 13:30:39.374 23961-23961/com.cvte.cvtalk W/linker: library "libandroid_runtime.so" ("/system/lib/libandroid_runtime.so") needed or dlopened by "/data/app/com.cvte.cvtalk-2/lib/arm/libdatabase_sqlcipher.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-03 13:30:39.375 23961-23961/com.cvte.cvtalk W/linker: library "libbinder.so" ("/system/lib/libbinder.so") needed or dlopened by "/data/app/com.cvte.cvtalk-2/lib/arm/libdatabase_sqlcipher.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
01-03 13:30:39.456 23961-23961/com.cvte.cvtalk W/linker: /data/app/com.cvte.cvtalk-2/lib/arm/libdatabase_sqlcipher.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
01-03 13:30:39.743 23961-23961/com.cvte.cvtalk E/linker: library "libavenhancements.so" ("/system/vendor/lib/libavenhancements.so") needed or dlopened by "/system/lib/libmedia.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.cvte.cvtalk-2/lib/arm:/system/fake-libs:/data/app/com.cvte.cvtalk-2/base.apk!/lib/armeabi", permitted_paths="/data:/mnt/expand:/data/data/com.cvte.cvtalk"]

**Comment by developernotes** [comment]
Hello @XuanJiAndroid 

It appears you are using an older version of SQLCipher for Android. Please upgrade to the latest version, we include instructions for the latest version of the software [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android). Thanks!
