### ISSUE TITLE
Sqlcipher - the application can not be opened again after closing And not working above 6 device

### ISSUE THREAD

**Issue by adarshakshetty** [sqlcipher/android-database-sqlcipher#292]
Error1:  java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: 
 net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

Error2:    java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList

**Comment by developernotes** [comment]
Hi @adarshakshetty 

What version of SQLCipher for Android are you using?
