### ISSUE TITLE
net.sqlcipher.database.SQLiteException: error code 8:

### ISSUE THREAD

**Issue by gautamshrm3** [sqlcipher/android-database-sqlcipher#293]
Hi Team,

We are facing the below issue may be the similar as previous

net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database

This issue we have only got in MI devices.

Please us ASAP.

**Comment by developernotes** [comment]
Hello @gautamshrm3 

Where are you trying to write the database to on that device?

**Comment by gautamshrm3** [comment]
on SD card

**Comment by developernotes** [comment]
Hello @gautamshrm3 

Are you able to replicate this issue consistently with the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by jannisveerkamp** [comment]
We're facing the same problem. It occurs after we delete the database and reinitialize it without an App exit, e.g.
```
User login (create DB & put Data in it) => User logout (delete DB) => User Login => create DB => error
```
We're deleting the database with `context.deleteDatabase("mydatabase.db");` which returns true. The file is also deleted from the file system. It gets even more confuse: I can still get Data out of the Database (via a Content Provider in our case).

However if we quit the App after the User logged out everything works fine!
```
User login (create DB & put Data in it) => User logout (delete DB) => Kill App and open it again => User Login => create DB => everything works
```

Is there any memory State held by SQLCipher?

In our case the Errors seems to be unrelated to the device model.

**Comment by developernotes** [comment]
Hi @jannisveerkamp 

The problem you describe doesn't mention an error attempting to write to a readonly database, do you receive this error? Are you certain your application is deleting the database the content provider is accessing? Can you confirm the file on the filesystem is deleted and attempt to read the database following your call to `deleteDatabase()`. If your error is unrelated to the above, we would ask you to create a separate ticket. Thanks!

**Comment by gautamshrm3** [comment]
Tried to change the database location

**Comment by developernotes** [comment]
Hello @gautamshrm3 

>Tried to change the database location

Were you able to resolve your issue? If not, are you able to create a test within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) that reproduces the issue you are experiencing?

**Comment by jannisveerkamp** [comment]
Sorry. Yes I get the same Error/Exception.
Yes I am certain the database is deleted (the file isn't present in the filesystem anymore and the delete method returns true) and I try to access it afterwards.

I thought my issue is related to this one. I can open another issue if you want.

**Comment by developernotes** [comment]
Hello @jannisveerkamp 

Please feel free to open a new ticket, we would be happy to investigate further with a provided reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Thanks!

**Comment by developernotes** [comment]
Hello @gautamshrm3,

Since we have not heard back, I am going to close this ticket. If you still experiencing an issue we would be happy to investigate this further. Please fee free to open a new ticket and provide supporting information regarding your issue, preferably with a reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Thanks!
