### ISSUE TITLE
SQLiteProgram should check for input SQL length

### ISSUE THREAD

**Issue by noties** [sqlcipher/android-database-sqlcipher#294]
The line in question: https://github.com/sqlcipher/android-database-sqlcipher/blob/master/src/net/sqlcipher/database/SQLiteProgram.java#L69

`String prefixSql = mSql.substring(0, 6);`

It's a bit odd to assume that all SQL statements are no less than 6 characters. For example `BEGIN` (which starts deferred transaction) has 5. `END` has 3. And of cause there is possible junk submitted by a user.

I think it's better to execute a check for an input length before *substringing* it.

**Comment by theBlbDan** [comment]
Since it is only interested in caching CRUD statements, prefixSql is examining if the statement is of the CRUD type, which deferred transactions are not, thus your BEGIN falls into he block and gets freshly compiled.

**Comment by noties** [comment]
Well, stacktrace is tend to differ:
```
java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=6
at java.lang.String.startEndAndLength(String.java:298)
at java.lang.String.substring(String.java:1087)
at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:69)
at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1556)
```

whilst executing:
```java
final SQLiteDatabase database = /* obtain database */;
database.compileStatement("begin")
        .execute();
```

**Comment by theBlbDan** [comment]
I agree, it should be more resilient, but a bare 'BEING' is going nowhere in the END.  ;)

**Comment by developernotes** [comment]
Hi @noties 

Thanks for pointing out the missing string length check, I will include a fix in the next release.
