### ISSUE TITLE
rawQuery with nonsense SQL statement throws StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#295]
As reproduced in sqlcipher/sqlcipher-android-tests#16: calling SQLiteDatabase.rawQuery with a nonsense statement such as "101" or "false" would cause a StringIndexOutOfBoundsException to be thrown. According to the API I would expect some form of a SQLiteException to be thrown.

This has been fixed in AOSP quite a few years ago. I am not sure how easy it is to incorporate the fix due to the divergence in code.

**Comment by developernotes** [comment]
Hi @brodybits 

The StringIndexOutOfBoundsException should no longer occur with the 3.5.5 release, can you confirm?

**Comment by brodybits** [comment]
On Feb 9, 2017 10:25 PM, "Nick Parker" <notifications@github.com> wrote:
>
> Hi @brodybits
>
> The StringIndexOutOfBoundsException should no longer occur with the 3.5.5
release, can you confirm?

I will take a look tomorrow or early next week.

**Comment by brodybits** [comment]
When I try the nonsense SQL test with "101" and "false" I get the correct SQLiteException in case of SQLCipher (for Android) 3.5.5.

**Comment by developernotes** [comment]
Thanks for confirming @brodybits!
