### ISSUE TITLE
Native method not found: net.sqlcipher.database.SQLiteDatabase.dbopen

### ISSUE THREAD

**Issue by mahirekici** [sqlcipher/android-database-sqlcipher#303]
I have some problems

Exception java.lang.UnsatisfiedLinkError: Native method not found: net.sqlcipher.database.SQLiteDatabase.dbopen

Device Info

Android OS: 4.4.2

Gradle

  compile 'net.zetetic:android-database-sqlcipher:3.5.4@aar'

**Comment by developernotes** [comment]
Hi @mahirekici 

You may wish to try that latest SQLCipher for Android package, which is currently 3.5.6. Also, are you using ProGuard, if so, can you disable it temporarily to see if the behavior changes?

**Comment by mahirekici** [comment]
Hi @developernotes Ok
Now testing app. Thanks
