### ISSUE TITLE
'Like' Raw Query stop function properly with upper/lower case chars after upgrading from "3.3.1-2" to "3.5.6"

### ISSUE THREAD

**Issue by teoxant** [sqlcipher/android-database-sqlcipher#305]
Hello,
I am using "sqlcipher:3.3.1-2" with "ormlite-android:4.48" in Android. Application's database has Greek data. At some point user types a name in an EditText and I make a raw query like this:

"select CUSTOMER.FIRST_NAME from CUSTOMER where CUSTOMER.FIRST_NAME like '%" + queryText + "%' or CUSTOMER.LAST_NAME like '%" + queryText + "%'".

Query works fine and if user types "geo",  a result "GEORGE" comes as a suggestion. The record that comes as a result is in uppercase chars inside database.
But after updating to 3.5.6, user must type "GEO" with uppercase chars to get the same result. If he types "geo" with lowercase chars, he didn't get a result. This also happens with every version after 3.3.1-2 (3.4.0, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.5.6).

P.S. Database has Greek data, but i used an english name as an example.

**Comment by developernotes** [comment]
Hello @teoxant 

Are you able to create a reproducible test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? SQLCipher for Android no longer includes ICU support starting with 3.5.0.

**Comment by teoxant** [comment]
_"SQLCipher for Android no longer includes ICU support starting with 3.5.0"_. I didn't knew this. Ok it's not an issue then. Thank you very much!
