### ISSUE TITLE
Encrypt an already created DB

### ISSUE THREAD

**Issue by khawarraza-netsoltech** [sqlcipher/android-database-sqlcipher#307]
Hello, I have a scenario where I download a pre-built database file and place it into db folder and open it using default SQLite helper classes. The downloaded db has pre-populated tables with data. My question is: can SQLCipher be used in that case?

**Comment by developernotes** [comment]
Hello @khawarraza-netsoltech 

Thank you for your interest in SQLCipher. SQLCipher can read and operate on plain text SQLite database files (when the password is provided blank), or SQLCipher encrypted database files.
