### ISSUE TITLE
make init fails - the android command is no longer available

### ISSUE THREAD

**Issue by wongk** [sqlcipher/android-database-sqlcipher#309]
[user android-database-sqlcipher:master *]$ make init
git submodule update --init
android update project -p /Users/user/path/to/android-database-sqlcipher
The android command is no longer available.
For manual SDK and AVD management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
make: *** [init-environment] Error 1

**Comment by developernotes** [comment]
Hi @wongk 

You need to download the Android SDK [command line tools](https://developer.android.com/studio/index.html#downloads) and the Android NDK before you will be able to build this project.

**Comment by wongk** [comment]
@developernotes so having Android Studio and the NDK is not enough? Just want to confirm because the Android Studio page says the following:

"Android Studio includes all the tools you need to build apps for Android."

I have downloaded the NDK and all the necessary SDK components through Android Studio, as well as set my ANDROID_NDK_ROOT environment variable.

**Comment by wongk** [comment]
Also, it does say in the error message: "For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager"

**Comment by developernotes** [comment]
Hi @wongk 

The Makefile is trying to invoke the `android` tool [here](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/Makefile#L24) which is part of the Android SDK. This is available when you download the Android SDK command line tools distribution.

**Comment by wongk** [comment]
Confirmed the command line tools functions differently than the SDK tools included with Android Studio. This would be good information to include in your README.md.

**Comment by wongk** [comment]
Also, it is required that the SDK for API level 23 be installed in this environment. The README still says 19.

**Comment by developernotes** [comment]
Hi @wongk 

>Confirmed the command line tools functions differently than the SDK tools included with Android Studio. This would be good information to include in your README.md.

We accept that there are now alternative installation routines for acquiring the Android SDK, we will try to clarify this a bit in the README.

>Also, it is required that the SDK for API level 23 be installed in this environment. The README still says 19.

This was a recent change with the latest release, we will update the README.
