### ISSUE TITLE
Open read/write external sd card

### ISSUE THREAD

**Issue by Bezzu** [sqlcipher/android-database-sqlcipher#310]
Hi Team,
I want to create and write a SqlCipher database on the external SD card. With Android 5 Google has made access to the SD card quite restricted. Using the File class I can't write anything on SD Card. 
Searching on Internet I found that I must launch the following intent to take write permission on the SD card:

``
Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
``

After taking the SD card write permission, I can manage files using the DocumentFile class, but the sqlcipher library doesn't handle it.

How can I fix this issue?
Is there an other way to do this?

Thank you in advance.

**Comment by Tapchicoma** [comment]
I think the only way is to implement your custom `SQLiteOpenHelper` and use one of `openDatabase()` methods there, for example: `SQLiteDatabase#openDatabase(String path, String password, CursorFactory factory, int flags)` where the path will be the DB file on external SD card.

**Comment by developernotes** [comment]
Hi @Bezzu 

We have an [example test](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/ReadWriteDatabaseToExternalStorageTest.java) that shows writing to external storage within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests).

**Comment by Bezzu** [comment]
Hi Team,
thank you for your answer, but the example test doesn't show writing on removable SDCard. To do this must use the Storage Access Framework, that manages the file system as a Provider and accesses to files using the DocumentFile class and streams of byte (InputStream or OutputStream). The openDatabase() function of the sqlcipher library only accepts a String (path) or a File and not a stream of bytes.

Is it possible to open a database using an InputStream?

Thank you in advance.

**Comment by sjlombardo** [comment]
Hello @Bezzu, there is no way to open a database using a file stream.

**Comment by Chullian** [comment]
did you find any solution?

**Comment by developernotes** [comment]
Hi @Chullian 

Please see both [this](https://github.com/sqlcipher/android-database-sqlcipher/issues/310#issuecomment-308227917) and [this](https://github.com/sqlcipher/android-database-sqlcipher/issues/310#issuecomment-341704090) comment. Thanks!
