### ISSUE TITLE
no such module: fts5

### ISSUE THREAD

**Issue by andyken** [sqlcipher/android-database-sqlcipher#314]
I use the sqlcipher for android 3.5.4
I try to add fts5 virtual table by calling "CREATE VIRTUAL TABLE email USING fts5(sender, title, body);"
But the error is "no such module: fts5"
I checked the makefile of 3.5.4.It has already added the -DSQLITE_ENABLE_FTS5.
Why is there the error?

**Comment by developernotes** [comment]
Hello @andyken 

I am not sure why you are experiencing that, are you using the community build? Would you try using the latest 3.5.6 release? I recently added an [FTS5 test](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/src/main/java/net/zetetic/tests/FTS5Test.java) to the suite.
