### ISSUE TITLE
build-openssl-libraries.sh fails

### ISSUE THREAD

**Issue by oliveriobw** [sqlcipher/android-database-sqlcipher#315]
The  build-openssl-libraries.sh script fails due to the make-standalone-toolchain.sh step which tries to install to the same directory for each architecture.  This fails if the temporary directory is already there, so fix this with --force:

        ${ANDROID_NDK_ROOT}/build/tools/make-standalone-toolchain.sh \
                           --platform=${ANDROID_PLATFORM_VERSION} \
                           --install-dir=${ANDROID_TOOLCHAIN_DIR} \
                           --arch=${TOOLCHAIN_ARCH} \
                           --force

**Comment by developernotes** [comment]
Hi @oliveriobw 

Is it failing to complete the build in your scenario? The reason I ask is we blow away the toolchain directory after each platform build [here](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/build-openssl-libraries.sh#L114).

**Comment by oliveriobw** [comment]
It had either failed or I terminated the script early.

**Comment by developernotes** [comment]
Hello @oliveriobw 

I made a small change to the script, moving the deletion of the toolchain directory before the creation process so it is a bit more explicit. Please feel free to try the latest in master. Thanks!
