### ISSUE TITLE
Size too big

### ISSUE THREAD

**Issue by Aiuspaktyn** [sqlcipher/android-database-sqlcipher#317]
My APK:

with 3.5.4 is 5,05 MB
with 3.5.6 is 9,31 MB

+4,26 MB

Is it ok?

**Comment by developernotes** [comment]
Hello @Aiuspaktyn 

SQLCipher for Android added 64-bit CPU support in the 3.5.5 release. The size difference is likely due to the native `libsqlcipher.so` for `x86_64` and `arm64-v8a`.

**Comment by developernotes** [comment]
@Aiuspaktyn 

For reference, the [release notes for 3.4.1])(https://discuss.zetetic.net/t/sqlcipher-3-4-1-release/1962?u=developernotes) of SQLCipher core mention the additional 64-bit support in SQLCipher for Android.

**Comment by Aiuspaktyn** [comment]
Thanks!
