### ISSUE TITLE
ICU support

### ISSUE THREAD

**Issue by DerinMavi** [sqlcipher/android-database-sqlcipher#320]
We had a working code with earlier version(really old version) of SQLCipher that calls:
`
SQLiteDatabase.setICURoot(icuRootPath);`

With latest version we are getting the following error during runtime(but compilation works fine):

> 03-21 12:57:22.688: E/net.sqlcipher.database.SQLiteDatabase(15013): SQLiteDatabase java.lang.UnsatisfiedLinkError: No implementation found for void net.sqlcipher.database.SQLiteDatabase.setICURoot(java.lang.String) (tried Java_net_sqlcipher_database_SQLiteDatabase_setICURoot and Java_net_sqlcipher_database_SQLiteDatabase_setICURoot__Ljava_lang_String_2)
> 03-21 12:57:22.688: E/StackTrace(15013): StackTrace net.sqlcipher.database.SQLiteDatabase.setICURoot(Native Method)

I checked from the 'SQLiteDatabase.java' source code and found out that setICURoot() implementation has been commented out. There is another method 'loadICUData()' but that one is private and not called from anywhere.

What are the reasons for these changes? How can we support ICU with our databases?

Thanks in advance.

**Comment by developernotes** [comment]
Hello @DerinMavi 

As part of the update to SQLCipher for Android in supporting Android N, ICU support was removed from the library. The release notes can be found [here](https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465). Also, [here](https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515/2?u=developernotes) is a discussion for a workaround.
