### ISSUE TITLE
the zip file doesn't include necessary files

### ISSUE THREAD

**Issue by unosbaghaie** [sqlcipher/android-database-sqlcipher#321]
I want to integrate Greendao and Sqlcipher in android studio to have an encrypted db. I use [sqlcipher-for-android](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/)

which I added these to my app/build.gradle

`compile 'org.greenrobot:greendao:3.2.0'
compile 'org.greenrobot:greendao-generator:3.2.0'
compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'`

I downloaded v3.5.6 from [Here ](https://codeload.github.com/sqlcipher/android-database-sqlcipher/zip/v3.5.6)in the second step I have to execute these commands

`% unzip sqlcipher-for-android-v3.5.6.zip
% mkdir -p app/libs
% cp sqlcipher-for-android-v3.5.6/sqlcipher.jar app/libs
% cp -r sqlcipher-for-android-v3.5.6/armeabi \
    sqlcipher-for-android-v3.5.6/armeabi-v7a \
    sqlcipher-for-android-v3.5.6/x86
    sqlcipher-for-android-v3.5.6/x86_64 \
    sqlcipher-for-android-v3.5.6/arm64_v8a app/src/main/jniLibs/`

but there is not any sqlcipher.jar, armeabi, armeabi-v7a, x86 and ... in the zip file

Am I missing something or doing wrong ?

**Comment by developernotes** [comment]
Hello @unosbaghaie 

The link you have pointed to for SQLCipher for Android is a zip of the 3.5.6 tag in source only format. Your compile statement will include the AAR distribution of SQLCipher for Android directly within the application. The zip distribution of the binary package is only available through commercial licensing, otherwise you would need to utilize the AAR packaging.

**Comment by unosbaghaie** [comment]
Thanks @developernotes 

So could you give me a clue how I can use community edition with AAR distribution ?
Just adding  below line to app/build.gradle ? 

`compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'`

**Comment by developernotes** [comment]
@unosbaghaie 

Correct, adding that line will include the Java and native components within your application.

**Comment by unosbaghaie** [comment]
@developernotes  
And using this code to integrate it with Greendao ? 

`File path = new File(Environment.getExternalStorageDirectory(), "path/DBNamedb");
path.getParentFile().mkdirs();
DaoMaster.DevOpenHelper helper = new DaoMaster.DevOpenHelper(context, path.getAbsolutePath() ,  null);
Database db = helper.getEncryptedWritableDb("password");
return new DaoMaster(db).newSession();`

Am I right ?

**Comment by developernotes** [comment]
@unosbaghaie 

I am not familiar with Greendao integration. You might consider reaching out to them [directly](https://github.com/greenrobot/greenDAO/issues/new).

**Comment by unosbaghaie** [comment]
@developernotes  
Ok thanks .
