### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 

### ISSUE THREAD

**Issue by suraj9781** [sqlcipher/android-database-sqlcipher#325]
After upgrading library to 3.5.6 app crashes while loading huge data

Fatal signal 11 (SIGSEGV), code 1, fault addr 0xa0e9f5e4 in tid 13409 (AsyncTask #4)
03-31 11:25:24.955 272-272/? I/DEBUG: pid: 13101, tid: 13409, name: AsyncTask #4 >

**Comment by developernotes** [comment]
Hello @suraj9781 

We are currently investigating the issue regarding a crash when querying a large data set. We will post an update when available. Thanks!

**Comment by developernotes** [comment]
Hello @suraj9781 

We have pushed a change to master that we believe may address the crash when loading large data sets. Would you be interested in trying a beta build? If so, please reach out to us at [support@zetetic.net](mailto:support@zetetic.net). Thanks!

**Comment by suraj9781** [comment]
Thanks @developernotes .

**Comment by developernotes** [comment]
Hello @suraj9781 

I wanted to let you know that we have released a new version of SQLCipher for Android 3.5.7 which may address the issue you reported. You can find out more information regarding the release [here](https://discuss.zetetic.net/t/sqlcipher-for-android-3-5-7-release/2086/1). Would you give that a try and let us know your results? Thanks!

**Comment by suraj9781** [comment]
Thanks @developernotes  Issue is fixed now.

**Comment by developernotes** [comment]
Hi @suraj9781 

We are glad to hear the issue has been addressed. Take care!
