### ISSUE TITLE
Crash in cursor.moveToNext()

### ISSUE THREAD

**Issue by isxiaohu** [sqlcipher/android-database-sqlcipher#327]
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9bbfff7c in tid 8472

**Comment by developernotes** [comment]
Hello isxiaohu,

Can you provide some additional information regarding the crash you are reporting above?

- Are you able to reproduce it consistently?
- Does it occur on all devices/emulators, or just a subset?
- What version of SQLCipher for Android are you using?

**Comment by developernotes** [comment]
Hello @isxiaohu 

While we haven't received your response to the questions above, I wanted to let you know that we have released a new version of SQLCipher for Android 3.5.7 which may address the issue you reported. You can find out more information regarding the release [here](https://discuss.zetetic.net/t/sqlcipher-for-android-3-5-7-release/2086/1). Would you give that a try and let us know your results? Thanks!
