### ISSUE TITLE
Error inserting <redacted values> into xxxx

### ISSUE THREAD

**Issue by ruanshanshan** [sqlcipher/android-database-sqlcipher#328]
SQLCipher version: 3.5.4
net.sqlcipher.database.SQLiteException :error code 8:attemp to write a readonly database

i am getting this exception very frequently.
 I am using 2 SQLiteOpenHelper instances to create and manage the database connection.
 db_1.db and db_2.db. I have successfully created both the databases.
 
Problem:
  db_2 has four tables ，it has create three tables successfully,when create the fourth table, error accours  as above

**Comment by developernotes** [comment]
Hello @ruanshanshan 

I have a few follow up questions for you regarding the issue you are reporting:

- Does this issue occur for you when using the latest version of SQLCipher for Android (i.e., 3.5.6)?
- Does this issue occur for you on all emulators/devices, or just a subset?
- Are you able to consistently reproduce this behavior in isolation from your application (i.e., a test within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by ruanshanshan** [comment]
@developernotes 

1.  the version is 3.5.6
2. just a subset

**Comment by developernotes** [comment]
Hello @ruanshanshan 

A few additional questions:

- What Android OS version does this occur on?
- What is the specific device(s) you see this error on?
- Does your application have permission to write to the location you are attempting to?
- Where do these database files exist?

**Comment by zhukovme** [comment]
Hello @developernotes 
I got the same error. This happens after I tried to look at my database using Stetho.
When I access the database from the application only, there is no problem.

**Comment by developernotes** [comment]
Hello @zhukovme 

Are you attempting to view a SQLCipher encrypted database in Stetho, or a plain text SQLite database?

**Comment by zhukovme** [comment]
@developernotes 
I'm attempting to view a SQLCipher encrypted database in Stetho. 
After I did this, any query to the database produces this type of error.

**Comment by developernotes** [comment]
@zhukovme 

Out of curiosity, were you able to view the content of the encrypted database file after providing your key in Stetho?

**Comment by zhukovme** [comment]
@developernotes 

I have not yet tried to provide my key in Stetho.
I migrated from SQLite to SQLCipher and attempted to view a database in Stetho just for test.
If you know how to provide a sqlcipher key in Stetho let me know please :)

**Comment by developernotes** [comment]
Hi @zhukovme 

I am not aware of Stetho supporting SQLCipher directly.

**Comment by developernotes** [comment]
Hello @ruanshanshan 

Are you able to consistently reproduce this behavior in isolation from your application (i.e., a test within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests))?

**Comment by developernotes** [comment]
Hello @ruanshanshan,

Since we have not heard back, I am going to close this ticket. If you still experiencing an issue we would be happy to investigate this further. Please fee free to open a new ticket and provide supporting information regarding your issue, preferably with a reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Thanks!
