### ISSUE TITLE
net.sqlcipher.CrossProcessCursorWrapper cannot be cast to net.sqlcipher.database.SQLiteCursor

### ISSUE THREAD

**Issue by dryganets** [sqlcipher/android-database-sqlcipher#329]
We have it reproducible 100% of application start on Huawai P9 after upgrade to 3.5.6.

Stack trace:
04-04 14:07:10.584 11377 11463 E SQLitePlugin: SQLitePlugin.executeSql[Batch](): failed
04-04 14:07:10.584 11377 11463 E SQLitePlugin: java.lang.ClassCastException: net.sqlcipher.CrossProcessCursorWrapper cannot be cast to net.sqlcipher.database.SQLiteCursor
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin.bindPreHoneycomb(SQLitePlugin.java:972)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin.executeSqlStatementQuery(SQLitePlugin.java:917)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin.executeSqlBatch(SQLitePlugin.java:717)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin.access$100(SQLitePlugin.java:52)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:1052)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-04 14:07:10.584 11377 11463 E SQLitePlugin: 	at java.lang.Thread.run(Thread.java:833)

**Comment by developernotes** [comment]
Hello @dryganets 

Thank you for your report. I have a few follow up questions to better understand the situation:

- `SQLitePlugin.executeSqlBatch` is not part of SQLCipher for Android proper, is that a class of your own?
- Does it the behavior only occur on the  Huawai P9?
- Are you able to reproduce the behavior outside of your application (i.e., within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests))?
- What version of SQLCipher for Android were you using before without issue?

**Comment by brodybits** [comment]
It looks to me like you are running an old version or fork of the Cordova plugin (the package name of SQLitePlugin was changed from org.pgsqlite to io.sqlc 1-2 years ago). You may want to file this along with a reproduction program on whatever Cordova plugin you are using. I suggest you should use the latest Cordova plugin version to get support.

**Comment by dryganets** [comment]
We are using it as a part of the react-native-sqlite-storage now.
And soon will use it as a part of our react-native component.

It was specific to this device.

And my expectation was it should be fixed by this commit:
https://github.com/sqlcipher/android-database-sqlcipher/commit/d15b05edc773a0a7c3016bb6a91deec88f1fa7e7

It used to crash for us with same stack on 3.5.3.

I have mixed reports - some people say it got fixed some not.
I'll double check it.

**Comment by dryganets** [comment]
Well, a guy who reported it yesterday confirmed that it's fixed as well.
Probably he didn't rebuild the react-native dependency or smth like that.

**Comment by dryganets** [comment]
Thanks for the test suite link btw.
Will reference people to it next time.

**Comment by developernotes** [comment]
Hi @dryganets 

Glad to hear everything is working for you. Take care!

**Comment by venik** [comment]
@developernotes @dryganets 
I've experienced 2 crashes in a row during startup, third was successful.  So, I cannot say it's 100% reproducible, but pretty often on my device (HUAWEI_Mate_8 - HUAWEI/NXT-L29/HWNXT:6.0/HUAWEINXT-L29/C636B170:user/release-keys)

please have a look on the log
http://pasted.co/81910fb1

**Comment by brodybits** [comment]
> http://pasted.co/81910fb1

@venik from your log:
>```
>04-06 08:06:40.286 I ReactNativeJS: [#ffffffff-u] [TRACE] [JS.NetworkConnectionStore] _debounceCatchup Fulfilled: Last Status = 3, Actual Status = 2
>04-06 08:06:40.288 I ReactNativeJS: [#ffffffff-u] [TRACE] [JS.NetworkConnectionStore] Catchup: Converged Status = 2
>04-06 08:06:40.580 E SQLitePlugin: SQLitePlugin.executeSql[Batch](): failed
>04-06 08:06:40.580 E SQLitePlugin: net.sqlcipher.CrossProcessCursorWrapper cannot be cast to net.sqlcipher.database.SQLiteCursor
>04-06 08:06:40.580 E SQLitePlugin: 	org.pgsqlite.SQLitePlugin.bindPreHoneycomb(SQLitePlugin.java:972)

It looks like an issue with a React Native plugin for sqlcipher (I cannot tell which one). Please raise an issue on that plugin to get help.

**Comment by dryganets** [comment]
@brodybits you are right.
It's an incorrect handling of another error in https://github.com/andpor/react-native-sqlite-storage.

I cleaned up our fork and will contribute this change back to that plugin.
I think it's time to get rid of pre-honeycomb support.

**Comment by dryganets** [comment]
And here we go:
https://github.com/andpor/react-native-sqlite-storage/pull/147
This is PR for removal of the legacy code.
