### ISSUE TITLE
net.sqlcipher.database.SQLiteFullException: error code 13: database or disk is full

### ISSUE THREAD

**Issue by jcb316733855** [sqlcipher/android-database-sqlcipher#330]
below is the crash log, My log server collect this crash log, and the user's devices is Meitu M4 (4.4.4)
net.sqlcipher.database.SQLiteFullException: error code 13: database or disk is full
	at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
	at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
	at net.sqlcipher.database.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2149)
	at net.sqlcipher.database.SQLiteDatabase.update(SQLiteDatabase.java:2075)

[https://github.com/sqlcipher/android-database-sqlcipher/issues/284](url) and i also met the same crash like this issue.

**Comment by developernotes** [comment]
Hello @jcb316733855 

It appears your device may be out of storage space. Can you confirm how much storage space remains on the device?

**Comment by jcb316733855** [comment]
this crash issue is collected by our log server, not my device...
the storage space which you said is /mnt/sdcard or /data/app/ ?

**Comment by developernotes** [comment]
Hello @jcb316733855 

I do not know where you are storing the database for your application. This type of error would need to be handled within the application itself, monitoring the available storage on device relative to what the application is attempting to store in the database.

**Comment by jcb316733855** [comment]
i don't set path to store database, so maybe it use default path, the default path is /data/?

**Comment by developernotes** [comment]
@jcb316733855 

Are you extending the `SQLiteOpenHelper`, or just calling `openOrCreateDatabase` on the `SQLiteDatabase` class? The former will utilize the `databases` directory within the application install path.
