### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found

### ISSUE THREAD

**Issue by 963997769** [sqlcipher/android-database-sqlcipher#331]
java.lang.UnsatisfiedLinkError: Native method not found: com.nercms.receive.VedioActivity.CreateH264Packer:()J
04-09 16:08:39.030 17707-17707/? W/System.err:     at com.nercms.receive.VedioActivity.CreateH264Packer(Native Method)
04-09 16:08:39.030 17707-17707/? W/System.err:     at com.nercms.receive.VedioActivity.start(VedioActivity.java:88)
04-09 16:08:39.030 17707-17707/? W/System.err:     at com.nercms.receive.VedioActivity.onCreate(VedioActivity.java:114)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.Activity.performCreate(Activity.java:5231)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.os.Looper.loop(Looper.java:136)
04-09 16:08:39.030 17707-17707/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5001)
04-09 16:08:39.030 17707-17707/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-09 16:08:39.030 17707-17707/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
04-09 16:08:39.030 17707-17707/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
04-09 16:08:39.030 17707-17707/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
04-09 16:08:39.030 17707-17707/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by developernotes** [comment]
Hello @963997769 

This report does not appear associated to SQLCipher for Android, the stack trace does not include any reference back to this project. If you have more information to share that associates it to SQLCipher for Android, please provide that for further discussion. Thanks!

**Comment by 963997769** [comment]
问题找到了 原因是 类名与so文件要求类名不符




------------------ 原始邮件 ------------------
发件人: "Nick Parker";<notifications@github.com>;
发送时间: 2017年4月10日(星期一) 晚上11:09
收件人: "sqlcipher/android-database-sqlcipher"<android-database-sqlcipher@noreply.github.com>; 
抄送: "null"<963997769@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sqlcipher/android-database-sqlcipher]java.lang.UnsatisfiedLinkError: Native method not found (#331)




Hello @963997769
 
This report does not appear associated to SQLCipher for Android, the stack trace does not include any reference back to this project. If you have more information to share that associates it to SQLCipher for Android, please provide that for further discussion. Thanks!

**Comment by developernotes** [comment]
Hello @963997769 

Your application is crashing because it is unable to locate a native method at runtime. From the stack trace, it does not appear to be attempting to load SQLCipher for Android. If you have additional information that leads you to believe it is related to SQLCipher for Android, please share that. Thanks!

**Comment by 963997769** [comment]
抱歉 我第一回用 githut 不太明白你说的意思。


------------------ 原始邮件 ------------------
发件人: "Nick Parker";<notifications@github.com>;
发送时间: 2017年4月11日(星期二) 晚上9:51
收件人: "sqlcipher/android-database-sqlcipher"<android-database-sqlcipher@noreply.github.com>; 
抄送: "null"<963997769@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sqlcipher/android-database-sqlcipher]java.lang.UnsatisfiedLinkError: Native method not found (#331)




Hello @963997769
 
Your application is crashing because it is unable to locate a native method at runtime. From the stack trace, it does not appear to be attempting to load SQLCipher for Android. If you have additional information that leads you to believe it is related to SQLCipher for Android, please share that. Thanks!

**Comment by developernotes** [comment]
你好 @963997769，

您的应用程序崩溃，因为它无法在运行时找到本机方法。 从堆栈跟踪，似乎没有尝试加载用于Android的SQLCipher。 如果您有其他信息导致您认为它与Android的SQLCipher相关，请分享。 谢谢！

**Comment by 963997769** [comment]
抱歉 小白一个 仍然懂你说的 但我那个问题就是so文件 内绑定的类名 与我调用的类名不符 导致的 


------------------ 原始邮件 ------------------
发件人: "Nick Parker";<notifications@github.com>;
发送时间: 2017年4月11日(星期二) 晚上9:57
收件人: "sqlcipher/android-database-sqlcipher"<android-database-sqlcipher@noreply.github.com>; 
抄送: "null"<963997769@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sqlcipher/android-database-sqlcipher]java.lang.UnsatisfiedLinkError: Native method not found (#331)




你好 @963997769，
 
您的应用程序崩溃，因为它无法在运行时找到本机方法。 从堆栈跟踪，似乎没有尝试加载用于Android的SQLCipher。 如果您有其他信息导致您认为它与Android的SQLCipher相关，请分享。 谢谢！

**Comment by developernotes** [comment]
你好 @963997769

您是否在Android中使用SQLCipher？

**Comment by 963997769** [comment]
没有。。。


------------------ 原始邮件 ------------------
发件人: "Nick Parker";<notifications@github.com>;
发送时间: 2017年4月11日(星期二) 晚上10:13
收件人: "sqlcipher/android-database-sqlcipher"<android-database-sqlcipher@noreply.github.com>; 
抄送: "null"<963997769@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sqlcipher/android-database-sqlcipher]java.lang.UnsatisfiedLinkError: Native method not found (#331)




你好 @963997769
 
您是否在Android中使用SQLCipher？

**Comment by developernotes** [comment]
由于您没有使用SQLCipher for Android，我们将关闭此机票。

**Comment by 963997769** [comment]
Don't know what a SQLCipher for android




------------------ 原始邮件 ------------------
发件人: "Nick Parker";<notifications@github.com>;
发送时间: 2017年4月12日(星期三) 晚上9:10
收件人: "sqlcipher/android-database-sqlcipher"<android-database-sqlcipher@noreply.github.com>; 
抄送: "null"<963997769@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sqlcipher/android-database-sqlcipher]java.lang.UnsatisfiedLinkError: Native method not found (#331)




由于您没有使用SQLCipher for Android，我们将关闭此机票。

**Comment by developernotes** [comment]
Hi @963997769 

SQLCipher for Android is an encrypted database library that uses SQLCipher on the Android platform.

**Comment by 963997769** [comment]
哥们 有 局域网音频通讯的Demo嘛 感谢


------------------ 原始邮件 ------------------
发件人: "Nick Parker";<notifications@github.com>;
发送时间: 2017年4月13日(星期四) 晚上8:58
收件人: "sqlcipher/android-database-sqlcipher"<android-database-sqlcipher@noreply.github.com>; 
抄送: "I Like All"<963997769@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sqlcipher/android-database-sqlcipher]java.lang.UnsatisfiedLinkError: Native method not found (#331)




Hi @963997769
 
SQLCipher for Android is an encrypted database library that uses SQLCipher on the Android platform.
