### ISSUE TITLE
why jnilib uncompleted

### ISSUE THREAD

**Issue by liuding123D** [sqlcipher/android-database-sqlcipher#332]
I need to know how encrypt DB，so I read you sound code，but it's uncompleted

**Comment by developernotes** [comment]
Hi @liuding123D 

You might consider reading through our SQLCipher for Android [tutorial](https://www.zetetic.net/sqlcipher/sqlcipher-for-android). If you have further questions, our community [discuss](https://discuss.zetetic.net/c/sqlcipher) site is the place to ask. Thanks!
