### ISSUE TITLE
SQLcipher Decrypt file

### ISSUE THREAD

**Issue by ChriCon** [sqlcipher/android-database-sqlcipher#333]
now testing functions for encrypting and decrypting an SQLite database with SQLCipher.
the encryption function is ok, but when I try to decrypt the database I get this error, it seems to be a stupid mistake, but do not understand that.

`  
                                                             net.sqlcipher.database.SQLiteException: table android_metadata already exists
                                                                 at net.sqlcipher.database.SQLiteDatabase.native_rawExecSQL(Native Method)
                                                                 at net.sqlcipher.database.SQLiteDatabase.rawExecSQL(SQLiteDatabase.java:2234)`

and this is my code

`File unencryptedFile = new File("/data/data/" + ctxt.getPackageName() + "/databases/data.db");
        File externalDBEncrypt = new File(Environment.getExternalStorageDirectory(), "db/data.db");

        SQLiteDatabase database = SQLiteDatabase.openOrCreateDatabase(externalDBEncrypt, Variabili.varPass, null);
        if (database.isOpen()) {
            database.rawExecSQL(String.format("ATTACH DATABASE '%s' as plaintext KEY '';",
                    unencryptedFile.getAbsolutePath()));
            database.rawExecSQL("SELECT sqlcipher_export('plaintext');");
            database.rawExecSQL("DETACH DATABASE plaintext;");
            android.database.sqlite.SQLiteDatabase sqlDB = android.database.sqlite.SQLiteDatabase
                    .openOrCreateDatabase(unencryptedFile, null);
            sqlDB.close();
            database.close();
        }

        boolean db = unencryptedFile.delete();`

**Comment by developernotes** [comment]
Hi @ChriCon 

Does `unencryptedFile` already exist on device? While the file itself can exist, it appears it already contains the `android_metadata` table so SQLCipher cannot replicate that table from your encrypted database. What execution line causes the exception above in your sample?

**Comment by ChriCon** [comment]
this line causes the exception:
`database.rawExecSQL("SELECT sqlcipher_export('plaintext');");`

**Comment by sjlombardo** [comment]
@ChriCon it sounds like the database you are trying to export to, `unencryptedFile` already has tables in it. That is causing the export failure. You should export to a database that does not have any of the same tables as the source database. It would probably be easiest to export to a brand new database (i.e. one that doesn't exist).

**Comment by JayeshMohan4** [comment]
Hi Sir,

I get this error after included all the libraries, JniLibs. I get this error after adding this line "SQLiteDatabase.loadLibs(getApplicationContext());" in my main activity. Once I run my app this error will appear and I don't know what it is. Can you please suggest a solution ?

FATAL EXCEPTION: main
             Process: com.iroid.android.gk4success_staffnurse, PID: 16448
             java.lang.UnsatisfiedLinkError: dlopen failed: library "libutils.so" not found
             at java.lang.Runtime.loadLibrary0(Runtime.java:977)
             at java.lang.System.loadLibrary(System.java:1567)
             at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:119)

**Comment by developernotes** [comment]
Hi @JayeshMohan4 

We utilize Github issues for reporting software defects in SQLCipher for Android. Application integration issues are best asked on our SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site.
