### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by brh** [sqlcipher/android-database-sqlcipher#338]
Our app is using this library and another library that has 64 bit support.  So, if I put in the other library unmodified it does not work because android will only look for a library on an equal level.  For example

SQLCipher has 
armeabi
armeabi-v7a
x86

Vidyo library has
arm64-v8a
armeabi-v7a
x86
x86_64

When Android tries load the libraries it will see x86_64 and assume that the sqlcipher has x86_64 which it doesn't so it fails.

**Comment by developernotes** [comment]
Hello @brh 

We added 64-bit support to SQLCipher for Android in our [3.4.1 core](https://discuss.zetetic.net/t/sqlcipher-3-4-1-release/1962) release earlier this year. The latest version of SQLCipher for Android 3.5.7, would you give that a try and let us know if it resolves the issue? Thanks!

**Comment by banghn** [comment]
Hi @developernotes 

You have some files lib: arm64-v8a & x86_64 
I would like to download it but i didn't find when searching

**Comment by developernotes** [comment]
Hi @banghn 

If you are using the community edition of SQLCipher for Android, those files are included in the AAR distribution. More information about integrating that build is available [here]. If you are using the commercial edition, those files are also available, please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net).

[here]: https://www.zetetic.net/sqlcipher/sqlcipher-for-android
