### ISSUE TITLE
Support for Room Persistence Library

### ISSUE THREAD

**Issue by OmkarAmberkar** [sqlcipher/android-database-sqlcipher#339]
Are there any developments to support [Room](https://developer.android.com/topic/libraries/architecture/room.html)? If yes, when can we expect new release of sqlcipher for android with room support?

**Comment by developernotes** [comment]
Hi @OmkarAmberkar 

Thanks for reaching out, this is something we are planning to look into. I will close this ticket here, however feel free to follow the existing discussion thread [here](https://discuss.zetetic.net/t/sqlcipher-for-android-room-and-api-level-16) for further updates. Thanks!
