### ISSUE TITLE
IMMEDIATE transaction support

### ISSUE THREAD

**Issue by k-kagurazaka** [sqlcipher/android-database-sqlcipher#340]
I want to use `IMMEDIATE` transaction like `beginTransactionNonExclusive()` in default Android `SQLiteDatabse`.
Does `sqlcipher-core` support `IMMEDIATE` mode?

Thanks.

**Comment by k-kagurazaka** [comment]
Please let me ask one more question.
If `sqlcipher-core` supports `IMMEDIATE` mode, can I write `beginTransactionNonExclusive()` as following?

```java
database.beginTransactionWithListener(new SQLiteTransactionListener() {
        @Override
        public void onBegin() {
            database.rawExecSQL("ROLLBACK; BEGIN IMMEDIATE;");
        }

        @Override
        public void onCommit() { }

        @Override
        public void onRollback() { }
    });
```

**Comment by developernotes** [comment]
Hello @k-kagurazaka 

Yes, you could use that approach to utilize `BEGIN IMMEDIATE;` within the Java API. You could also define a function that invokes `BEGIN IMMEDIATE;` on your database instance, this would prevent you from needing to rolling back the transaction (i.e., `BEGIN EXCLUSIVE`) that was initiated within the call to `beginTransactionWithListener(…)`.
