### ISSUE TITLE
SQLCipher version from created DB file

### ISSUE THREAD

**Issue by peddiraju211** [sqlcipher/android-database-sqlcipher#343]
How to find used SQLCipher library version from encrypted db file created by SQLCipher ?

**Details from MANIFEST.MF file :**
Manifest-Version: 1.0
Created-By: 1.6.0_65 (Apple Inc.)

Here 1.6.0_65 represents SQLCipher version ?

Regarding attached screen, I tried to migrate the db but am unable. Could you please suggest exact solution ?

![imageedit_2_3795864142](https://user-images.githubusercontent.com/24585829/27867624-e10276bc-61b7-11e7-9ba8-2bd309312f65.jpg)

**Comment by developernotes** [comment]
Hi @peddiraju211 

The SQLCipher file itself cannot tell you what version of the library was used to create it. Executing `PRAGMA cipher_version;` will report the version of the running SQLCipher library itself. If you did not make any runtime adjustments to various configurations such as the kdf_iter, cipher, etc, you can attempt to perform a one-time migration using the [`PRAGMA cipher_migrate`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate) to update the database file format to the latest version (if you are using a SQLCipher 3.x library). If you have more questions about SQLCipher usage, I might direct you to the SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!

**Comment by peddiraju211** [comment]
@developernotes  Thanks for considering my request

One-time migration confusing me because as I have existing users who are using the db and I am not using static db in assets folder. Could you please suggest ?

Is there any sample app for migrate the existing db to 3.x version ?

How to programmatically migrate the existing db ?
