### ISSUE TITLE
Unable to build from source "Invalid or unsupported command

### ISSUE THREAD

**Issue by nikz-dev** [sqlcipher/android-database-sqlcipher#344]
### Expected Behavior
Run Build Successfully 
### Actual Behavior
Throw error Invalid or unsupported command
### Steps to Reproduce
1- git clone https://github.com/sqlcipher/android-database-sqlcipher.git
2- cd android-database-sqlcipher
3- make init

### OUTPUT
git submodule update --init
android update project -p /home/s/e/sqlcipher_for_android/android-database-sqlcipher
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update project -p /home/s/e/sqlcipher_for_android/android-database-sqlcipher"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
make: *** [init-environment] Error 2

**Comment by developernotes** [comment]
Hi @nikz-dev 

We will be making adjustments to the build to address this in the future. This is due to more recent versions of the Android SDK changing, removing ant support specifically.

**Comment by Becca42** [comment]
Is there a timeline for when this issue will be resolved?

**Comment by developernotes** [comment]
Hi @Becca42 

We plan to update the build chain to utilize the newer Android SDK, including gradle, however we do not have an immediate timeline currently. If you have a need to build SQLCipher for Android outside of our community distribution, you can utilize the 25.2.5 `tools` packages from Google which contains the necessary ant support for building from source:

- [Windows 25.2.5 tools package](https://dl.google.com/android/repository/tools_r25.2.5-windows.zip)
- [macOS 25.2.5 tools package](https://dl.google.com/android/repository/tools_r25.2.5-macosx.zip)
- [Linux 25.2.5 tools package](https://dl.google.com/android/repository/tools_r25.2.5-linux.zip)

**Comment by developernotes** [comment]
Hello @Becca42 

We currently have a `gradle` branch that can be utilized with the latest Android SDK/NDK build chain. We will be merging this into master once we release the next version of SQLCipher. I will be closing this issue for now. If you have any further questions, please feel free to post on our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
