### ISSUE TITLE
Does sqlcipher support icu zh_CN tokenizer?

### ISSUE THREAD

**Issue by hanqi-bupt** [sqlcipher/android-database-sqlcipher#345]
### I create a virtual table in the encrypted db, using the sql below,
`CREATE VIRTUAL TABLE IF NOT EXISTS MessageIndex USING fts4(indexId, accountId, messageBody, messageFrom, messageTo, messageCc, messageBcc, messageSubject, messageAttachment, messageTimestamp, indexType, messageAll, tokenize=icu zh_CN); `
but the error log show me that sqlcipher doesn't know icu zh_CN.
so I want to know whether sqlcipher support icu zh_CN or not?

SQLCipher for Android version: 3.5.7

**Comment by developernotes** [comment]
Hi @hanqi-bupt 

As part of the [3.5.x series](https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465) we removed support for ICU. If your organization is looking for a commercially supported solution with ICU support, please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net).
