### ISSUE TITLE
SQLiteDiskIOException: disk I/O error: COMMIT;

### ISSUE THREAD

**Issue by cyxcw1** [sqlcipher/android-database-sqlcipher#346]
### Expected Behavior
Run Build Successfully

### Actual Behavior
Throw [disk I/O error] exception

### Steps to Reproduce
We use SQLCipher in our android project, and we found our app crash in "application" initialization, according the crash data from the bug report platform. But we can not reproduce the crash.
We found it crash mostly in Android 4.4.4, but also crash in Android 4.4.4+ in small probability. The top 5 crash devices is Samsung：
GT-I9195I, SM-E7000, SM-G710K, SM-E500M, SM-E700M

The crash stack trace:
```
java.lang.RuntimeException:Unable to create application kula.publics.objects.KulaApplication: net.sqlcipher.database.SQLiteDiskIOException: disk I/O error: COMMIT;
 android.app.ActivityThread.handleBindApplication(ActivityThread.java:5116)
......
Caused by:
net.sqlcipher.database.SQLiteDiskIOException:disk I/O error: COMMIT;
net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
net.sqlcipher.database.SQLiteDatabase.execSQL(Unknown Source)
net.sqlcipher.database.SQLiteDatabase.endTransaction(Unknown Source)
net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(Unknown Source)
net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(Unknown Source)
kula.third.afinal.b.c(Unknown Source)
kula.third.afinal.b.<init>(Unknown Source)
kula.third.afinal.b.b(Unknown Source)
kula.third.afinal.b.a(Unknown Source)
kula.third.afinal.b.a(Unknown Source)
kula.eric.data.db.FlySubDbManager.getDb(Unknown Source)
kula.eric.data.db.FlyBaseDbManager.<init>(Unknown Source)
kula.eric.data.db.FlySubDbManager.<init>(Unknown Source)
kula.eric.data.db.FlySubDbManager.init(Unknown Source)
kula.eric.data.KulaFlyController.<init>(Unknown Source)
kula.eric.data.KulaFlyController.getInstance(Unknown Source)
```

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
(how to execute the command with SQLCipher for Android?)

SQLCipher for Android version:
3.5.7

**Comment by sjlombardo** [comment]
@cyxcw1 

1. how many crashes are you seeing relative to number of application installations?
2. Is the database access from multiple threads?
3. Where is the database located (i.e. internal vs SD card)?

**Comment by cyxcw1** [comment]
@sjlombardo 
1. About 200+ users, 5000+ crash times.
2. The database could be access from multiple threads, but it crash in the moment that the database is initiating, there is no other thread access at that time.
3. Located in internal.

**Comment by sjlombardo** [comment]
@cyxcw1 how are you determining the path for the database? Are you hard-coding the location, or using Environment? Can you provide a code sample of how you are opening / initializing the database in a gist?

**Comment by developernotes** [comment]
Hi @cyxcw1 

Do you have any follow-ups regarding the questions @sjlombardo asked above? Thanks!

**Comment by cyxcw1** [comment]
@developernotes 
Sorry for lefting the question so long.
I use "mContext.getDatabasePath("dbname")" to determine the path for database. 
We use FinalDb（https://github.com/yangfuhai/afinal, afinal framework for andoird) to init our database.

**Comment by sjlombardo** [comment]
Hello @cyxcw1 how large is the database you are initializing? Is it possible that the devices that are throwing the error don't have sufficient storage space, and are therefore reporting legitimate IO errors?

**Comment by cyxcw1** [comment]
@sjlombardo 
Thank you for answering me.
My database's size is 8MB. I have checked the detail of crash data, the users have sufficient storage space.
We found that not only the database of sqlcipher had the crash, the database of android.database have the crash too. But we don't know if they are the same case.

**Comment by sjlombardo** [comment]
Hello @cyxcw1 - Thank you for getting back to me. Given that you are seeing this with the standard Android Database libraries, it is probably not a problem with SQLCipher. More likely, it is some bug in Android with specific Samsung devices, given that you are only seeing it on a small set of devices. Please see this other ticket for some potentially related information:

https://github.com/chennaione/sugar/issues/583

Unfortunately, without a test or scenario that can reproduce this, there isn't much we can do here. I will close this ticket for now, but if you can provide a reproducible test case or any other actionable information feel free to comment back and we'll re-open it.
