### ISSUE TITLE
File is encrypted or is not a database

### ISSUE THREAD

**Issue by sanjaykumarm** [sqlcipher/android-database-sqlcipher#348]
### Expected Behavior
- Application should not crash
### Actual Behavior
- Application is crashing

### Steps to Reproduce
- Build app with Implementation-Version: v3.3.1, upgrade sql cipher version to 3.5.7. Install old apk first, use it and then overtire with latest apk that has new sql cipher version and open the app. App will be crashed.
SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:
3.5.7
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello sanjaykumarm,

>Build app with Implementation-Version: v3.3.1, upgrade sql cipher version to 3.5.7. Install old apk first, use it and then overtire with latest apk that has new sql cipher version and open the app. App will be crashed.

Unfortunately this is not quite enough information to diagnose further. I was able to create a sample database using SQLCipher 3.3.1, then use SQLCipher for Android 3.5.7 to access it properly within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests).

A few more questions regarding your issue:

- Are you certain you are providing the correct password to the database?
- What are you attempting to perform when you receive the error?
- Does this occur on all Android devices/emulators, or a subset?
- Are you using a community, or commercial edition of SQLCipher for Android?

We would be happy to investigate this further if you can provide a reproducible test that we can review within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests).

**Comment by sanjaykumarm** [comment]
Hello, Thank you for your quick reply. Today I again recheck with signed apk and it is working fine so closing this issue. Appreciate for your time and quick support.
