### ISSUE TITLE
Cannot load other native .so library when using SqlCipher by gradle as dependencies at library module

### ISSUE THREAD

**Issue by baksosapi** [sqlcipher/android-database-sqlcipher#350]
Only happen when sqlcipher load from Library Module. But when it load from Application Module it works perfect.
I use [this repo](https://github.com/baksosapi/AppFace)

### Expected Behavior

- Application load other .so library
```
> adb shell "run-as org.smartregister.myapplication ls lib/"
libsqlcipher.so
[other].so
```
### Actual Behavior

- Application not load other .so library (only **libsqlchiper_*.so** load into lib)
```
> adb shell "run-as org.smartregister.myapplication ls lib/"
libsqlcipher.so
```
### Steps to Reproduce

1. Create Android Application Module name ``` app ```

2. Create Android Library Module name ``` mylibrary ``` that contains .so library , then adding sqlcipher via gradle ```     compile 'net.zetetic:android-database-sqlcipher:3.5.7@aar' ```

3. Load ``` mylibrary ``` from ``` app ``` on gradle with ```compile project (':mylibrary') ```, other .so library not load into device:
checked by ``` adb shell "run-as org.smartregister.myapplication ls lib/" ``` give result  
```
> adb shell "run-as org.smartregister.myapplication ls lib/"
libsqlcipher.so
```
SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version: 
``` net.zetetic:android-database-sqlcipher:3.3.1@aar ``` - ``` net.zetetic:android-database-sqlcipher:3.5.7@aar ```

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @baksosapi 

It sounds as if your project is having difficulties bundling your native library. Have you tried including your library as an AAR artifact (even locally) to see if it is able to be properly bundled?

**Comment by baksosapi** [comment]
Hi @developernotes ,
I have tried including my aar library locally , then my native library perfect load. But no sqlcipher native library loaded. I need both of native loaded.
This is mylibrary ``` build.gradle ```
```
dependencies {
    compile 'net.zetetic:android-database-sqlcipher:3.5.7@aar'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    testCompile 'junit:junit:4.12'

}
```

**Comment by developernotes** [comment]
Hi @baksosapi 

Your sample above does not show a reference to a local AAR package. Please update to show how you are doing this.

**Comment by baksosapi** [comment]
Hi @developernotes ,
I just update my repo [here](https://github.com/baksosapi/AppFace/commit/307ad1c4dfada532d80d523eb941ba3580c95d50). I copied AAR from ```/mylibrary/build/outputs/aar/mylibrary-release.aar``` into ``` /app/libs/mylibrary-release.aar ``` .

**Comment by developernotes** [comment]
HI @baksosapi 

This appears to be a project configuration issue for your application, not an issue with SQLCipher for Android itself. We use Github Issues as a mechanism for reporting issues with the software itself. If you are still facing a project configuration issue, I would suggest opening a ticket on the SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site instead. Thanks!
