### ISSUE TITLE
import sqlcipher and launch app crash

### ISSUE THREAD

**Issue by zhangdshr** [sqlcipher/android-database-sqlcipher#358]
When I add sqlcipher in build.gradle like this "compile 'net.zetetic:android-database-sqlcipher:3.5.7@aar'", The app can build successful, but when I launch my app, it crash ,and I even can not see the error, who meet the same question like me? and I create a new project then add sqlcipher in gradle, it launch successful, the error only occur in my old project.

**Comment by developernotes** [comment]
Hello @zhangdshr 

We utilize Github Issues for reproducible reports of software defects in SQLCipher. This question is an application question that is best suited for our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). You might consider reviewing the logcat output from your application, then feel free to post any detailed follow-up questions on the discuss site. Thanks!
