### ISSUE TITLE
package-info.class is invalid

### ISSUE THREAD

**Issue by gavra0** [sqlcipher/android-database-sqlcipher#359]
The issue is about the invalid class file, in classes.jar in an aar. To verify the issue:
1. download https://mvnrepository.com/artifact/net.zetetic/android-database-sqlcipher/3.5.7 and unzip the aar
2. javap -v -p -cp <path_to_class.jar> net/sqlcipher/package-info
2. javap -v -p -cp <path_to_class.jar> net/sqlcipher/database/package-info

The output contains ACC_INTERFACE flag, but does not have ACC_ABSTRACT set, which is not according to the class specification:

"If the ACC_INTERFACE flag of this class file is set, its ACC_ABSTRACT flag must also be set..." - from https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html.

Thanks for looking into this!

**Comment by developernotes** [comment]
Hi @gavra0 

Does this cause a specific issue for you? We don't really have much [in](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/src/net/sqlcipher/package-info.java) [either](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/src/net/sqlcipher/database/package-info.java) of the files. If you can provide some additional context that would be helpful.

**Comment by gavra0** [comment]
I am working on the Android plugin for Gradle, and because we are doing some bytecode transformations, sanity checks have been added to confirm that classfiles are valid. I've discovered that your jar could not be processed because of malformed packages-info, so I wanted to reach out, and let you know.

**Comment by developernotes** [comment]
Hi @gavra0 

Our next release of SQLCipher for Android will be packages from our [gradle branch](https://github.com/sqlcipher/android-database-sqlcipher/tree/gradle). After creating a new AAR package from that branch, it does not appear to be including the package-info now. Will that be an issue?

**Comment by developernotes** [comment]
Hi @gavra0 

Thanks for the heads up, I'm glad to hear the issue will be addressed in our next release. Take care!
