### ISSUE TITLE
SQLite version?

### ISSUE THREAD

**Issue by ohenepee** [sqlcipher/android-database-sqlcipher#360]
How come there aren't any changelogs in the `Releases` page? No way to know the SQLite version used? I am kinda contemplating between [sqlite-android](https://github.com/requery/sqlite-android) (no encryption tho) and this lib. But not knowing which version of sqlite this lib uses is not helpful, at least not only for my use case.... but in general I believe for compatibility sake, it would be helpful if developers did.

*`sqlite-android` offer performance benefits by using the latest SQLite versions*

**Comment by developernotes** [comment]
Hello @ohenepee 

SQLCipher for Android is a Java client library that wraps [SQLCipher core](https://github.com/sqlcipher/sqlcipher/). We publish release announcements [here](https://discuss.zetetic.net/c/sqlcipher/updates), and maintain a changelog for SQLCipher core [here](https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md). The current version of both SQLCipher, and SQLCipher for Android utilize the SQLite upstream of [3.15.2](https://github.com/sqlcipher/sqlcipher/blob/master/VERSION), though we have a new release that coming soon which will be based on 3.20.1. SQLCipher maintains it's own version, which is currently at 3.4.1. SQLCipher for Android also maintains a separate version, currently at 3.5.7.

If you have any further questions regarding the libraries, I would recommend posting on the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher), as we use Github Issues to track verifiable software defects. Thanks!
