### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by sunO2** [sqlcipher/android-database-sqlcipher#361]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version: 3.5.7

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

My application uses an unfixed password, but I have to repair the password on the top of the production. There are two possible hopes to be helped.

**Comment by developernotes** [comment]
Hello @sunO2 

We only utilize Github Issues to track reproducible defects within SQLCipher for Android source. It sounds as if you have a specific integration issue you are attempting to address. It would be best to post your question over on the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) along with more specific details regarding your situation to see if anyone is able to help. Thanks!
