### ISSUE TITLE
Reduce Library Size.

### ISSUE THREAD

**Issue by AhmadullahSaikat** [sqlcipher/android-database-sqlcipher#362]
Please reduce the library size..
The size is 7.1+ MB.
I don't need to support api<15.
For Api<11 this library uses many codes and libraries.
Which is full of garbage to me.
Please remove the garbage codes and libraries which is used to support api <15.
Or make a library again which will support API >= 15

**Comment by developernotes** [comment]
Hi @AhmadullahSaikat 

>I don't need to support api<15.
For Api<11 this library uses many codes and libraries.
Which is full of garbage to me.
Please remove the garbage codes and libraries which is used to support api <15.

If you take a look at the distribution package, you will find that the Java code itself is only taking up 104kB in total, whereas the various native architecture supports represent the remainder of the package size. Please feel free to bundle the library with as little platform support as you need.

![screen shot 2017-12-08 at 8 40 04 am](https://user-images.githubusercontent.com/3225/33771014-1e0f2142-dbf5-11e7-8f04-9f5de9fcb138.png)
