### ISSUE TITLE
SQLcipher is not reading large UTF-8 strings and considering TEXT data type as BLOB

### ISSUE THREAD

**Issue by kagile** [sqlcipher/android-database-sqlcipher#363]
### Expected Behavior
Sqlcipher should read UTF-8 strings correctly
### Actual Behavior
Getting exception : 
net.sqlcipher.database.SQLiteException: unknown error: Unable to convert BLOB to string
  at net.sqlcipher.CursorWindow.getString_native(Native Method)
   at net.sqlcipher.CursorWindow.getString(CursorWindow.java:385)
 at net.sqlcipher.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
   at android.database.CursorWrapper.getString(CursorWrapper.java:137)
### Steps to Reproduce
Store text with any Indic language such as Gujarati.

SQLCipher for Android version:
3.5.7

**Comment by developernotes** [comment]
Hello @krupalagile 

Can you provide a small reproducible test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? We would be happy to look into this further. Specifically, we would like to see the content that is being insert, how you are inserting it, and finally, the query method used to retrieve the content. Thanks!

**Comment by krupalagile** [comment]
Problem is not while inserting, the problem occurs while getting the text.

**Comment by developernotes** [comment]
Hi @krupalagile 

We are looking for a small reproduction of the issue you are experiencing, so the test case can include inserting specific content that is an issue for you to retrieve in the query. Once we have a reproducible test case, we can examine the issue further. Thanks!

**Comment by theBlbDan** [comment]
@kagile Can you provide a sample string and db schema that will successfully reproduce this issue?

**Comment by developernotes** [comment]
Hi @kagile 

I'm going to close this ticket for inactivity. If this is still an issue please let us know.
