### ISSUE TITLE
file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master

### ISSUE THREAD

**Issue by sunO2** [sqlcipher/android-database-sqlcipher#364]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version: v3.7

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

Third-party libraries do not have the password to read the database lead to the collapse of the database

**Comment by developernotes** [comment]
Hello @sunO2 

>Third-party libraries do not have the password to read the database lead to the collapse of the database

The password of the database is required for accessing all encrypted content. If you have a specific problem with SQLCipher for Android, please provide further details regarding the issue, along with possible reproduction steps and we will look into it further. Without this information, we will close this ticket for now. Please feel free to create a new issue with the pertinent information, or post a follow-up discussion regarding integration on our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
