### ISSUE TITLE
hi    Hello feedback a bug

### ISSUE THREAD

**Issue by sunO2** [sqlcipher/android-database-sqlcipher#365]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version: V3.7

Reading encrypted database using[Android-Debug-Database]( https://github.com/amitshekhariitbhu/Android-Debug-Database)

Caused by:
--
5 net.sqlcipher.database.SQLiteException:file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
6 net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
7 net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
8 net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
9 net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
10 net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
11 net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
12 net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
13 net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
14 net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2486)
15 net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2415)
16 net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1149)
17 net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1212)
18 net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
19 net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
20 org.greenrobot.greendao.database.DatabaseOpenHelper.getEncryptedWritableDb(DatabaseOpenHelper.java:134)

All the time to crash

**Comment by developernotes** [comment]
Hi @sunO2 

Can you provide some additional context regarding the issue you are seeing? Specifically, are you able to reproduce the issue when just using SQLCipher for Android? You reference a debugging library, and your stack trace references a third-party database library. If this is something you can reproduce in isolation using on SQLCipher for Android, we would be happy to review your recreation steps and investigate it further. Thanks!

**Comment by developernotes** [comment]
Hi @sunO2 

I'm going to close this ticket for inactivity. If this is still an issue please let us know.
