### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 1504 (Thread-70)

### ISSUE THREAD

**Issue by penguu8** [sqlcipher/android-database-sqlcipher#366]
我的游戏应用在逍遥模拟器上出现闪退. 其他模拟器上没有出现，暂时还没有找到修改方法.
12-15 19:42:15.886 1451-1504/com.efun.krqq.google A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 1504 (Thread-70)

12-15 19:42:16.002 153-153/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-15 19:42:16.002 153-153/? I/DEBUG: Build fingerprint: 'Huawei/Huawei/DUK-AL20:4.4.4/KTU84P/userdebug/release-keys'
12-15 19:42:16.006 153-153/? I/DEBUG: Revision: '0'
12-15 19:42:16.010 153-153/? I/DEBUG: pid: 1451, tid: 1504, name: Thread-70  >>> com.efun.krqq.google <<<
12-15 19:42:16.010 153-153/? I/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
12-15 19:42:16.246 153-153/? I/DEBUG:     eax 944282a0  ebx 93eb88ec  ecx 944282a0  edx ba437328
12-15 19:42:16.246 153-153/? I/DEBUG:     esi ba437298  edi c426c000
12-15 19:42:16.246 153-153/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
12-15 19:42:16.246 153-153/? I/DEBUG:     eip 935f7e00  ebp 944282a0  esp 94428130  flags 00210282
12-15 19:42:16.258 153-153/? E/Corkscrew: unrecognized dwarf lower part encoding: 0xfa
12-15 19:42:16.258 153-153/? I/DEBUG:     #00  pc 008cde00  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (_ZN7cocos2d8MathUtil14multiplyMatrixEPKDv4_fS3_PS1_+16)
12-15 19:42:16.262 153-153/? I/DEBUG:     #01  pc 00809a7b  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&, cocos2d::Mat4 const&, cocos2d::Mat4*)+43)
12-15 19:42:16.262 153-153/? I/DEBUG:     #02  pc 00809ab7  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&)+39)
12-15 19:42:16.262 153-153/? I/DEBUG:     #03  pc 002e9293  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (wolf::Entity::CalculateL2P()+483)
12-15 19:42:16.266 153-153/? I/DEBUG:          944280f0  b770a800  
12-15 19:42:16.266 153-153/? I/DEBUG:          944280f4  00000000  
12-15 19:42:16.266 153-153/? I/DEBUG:          944280f8  00000041  
12-15 19:42:16.270 153-153/? I/DEBUG:          944280fc  b767721f  /system/lib/libc.so (malloc+31)
12-15 19:42:16.270 153-153/? I/DEBUG:          94428100  0000004e  
12-15 19:42:16.270 153-153/? I/DEBUG:          94428104  ba432df0  [heap]
12-15 19:42:16.270 153-153/? I/DEBUG:          94428108  b7677da9  /system/lib/libc.so (pthread_mutex_lock+9)
12-15 19:42:16.270 153-153/? I/DEBUG:          9442810c  b7677f79  /system/lib/libc.so (pthread_mutex_unlock+25)
12-15 19:42:16.270 153-153/? I/DEBUG:          94428110  00000018  
12-15 19:42:16.274 153-153/? I/DEBUG:          94428114  00000000  
12-15 19:42:16.274 153-153/? I/DEBUG:          94428118  944281b8  [stack:1504]
12-15 19:42:16.274 153-153/? I/DEBUG:          9442811c  b7677f79  /system/lib/libc.so (pthread_mutex_unlock+25)
12-15 19:42:16.274 153-153/? I/DEBUG:          94428120  c2000000  
12-15 19:42:16.274 153-153/? I/DEBUG:          94428124  c2000000  
12-15 19:42:16.274 153-153/? I/DEBUG:          94428128  00000000  
12-15 19:42:16.274 153-153/? I/DEBUG:          9442812c  3f800000  
12-15 19:42:16.274 153-153/? I/DEBUG:     #00  94428130  3f800000  
12-15 19:42:16.278 153-153/? I/DEBUG:          94428134  00000000  
12-15 19:42:16.278 153-153/? I/DEBUG:          94428138  00000000  
12-15 19:42:16.278 153-153/? I/DEBUG:          9442813c  00000000  
12-15 19:42:16.278 153-153/? I/DEBUG:          94428140  00000000  
12-15 19:42:16.282 153-153/? I/DEBUG:          94428144  3f800000  
12-15 19:42:16.282 153-153/? I/DEBUG:          94428148  00000000  
12-15 19:42:16.282 153-153/? I/DEBUG:          9442814c  00000000  
12-15 19:42:16.282 153-153/? I/DEBUG:          94428150  0400002c  
12-15 19:42:16.286 153-153/? I/DEBUG:          94428154  ba432970  [heap]
12-15 19:42:16.286 153-153/? I/DEBUG:          94428158  b770a6a0  
12-15 19:42:16.290 153-153/? I/DEBUG:          9442815c  93533a7c  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&, cocos2d::Mat4 const&, cocos2d::Mat4*)+44)
12-15 19:42:16.290 153-153/? I/DEBUG:          94428160  94428290  [stack:1504]
12-15 19:42:16.290 153-153/? I/DEBUG:          94428164  b98e5910  [heap]
12-15 19:42:16.290 153-153/? I/DEBUG:          94428168  94428290  [stack:1504]
12-15 19:42:16.290 153-153/? I/DEBUG:          9442816c  93533a7c  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&, cocos2d::Mat4 const&, cocos2d::Mat4*)+44)
12-15 19:42:16.290 153-153/? I/DEBUG:     #01  94428170  944282a0  [stack:1504]
12-15 19:42:16.294 153-153/? I/DEBUG:          94428174  ba437328  [heap]
12-15 19:42:16.294 153-153/? I/DEBUG:          94428178  944282a0  [stack:1504]
12-15 19:42:16.294 153-153/? I/DEBUG:          9442817c  93533ab8  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&)+40)
12-15 19:42:16.294 153-153/? I/DEBUG:          94428180  94428290  [stack:1504]
12-15 19:42:16.298 153-153/? I/DEBUG:          94428184  93533a56  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&, cocos2d::Mat4 const&, cocos2d::Mat4*)+6)
12-15 19:42:16.302 153-153/? I/DEBUG:          94428188  93eb88ec  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so
12-15 19:42:16.302 153-153/? I/DEBUG:          9442818c  93533ab8  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&)+40)
12-15 19:42:16.302 153-153/? I/DEBUG:     #02  94428190  944282a0  [stack:1504]
12-15 19:42:16.302 153-153/? I/DEBUG:          94428194  ba437328  [heap]
12-15 19:42:16.302 153-153/? I/DEBUG:          94428198  944282a0  [stack:1504]
12-15 19:42:16.302 153-153/? I/DEBUG:          9442819c  00000000  
12-15 19:42:16.302 153-153/? I/DEBUG:          944281a0  00000000  
12-15 19:42:16.302 153-153/? I/DEBUG:          944281a4  93533a96  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (cocos2d::Mat4::multiply(cocos2d::Mat4 const&)+6)
12-15 19:42:16.302 153-153/? I/DEBUG:          944281a8  93eb88ec  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so
12-15 19:42:16.302 153-153/? I/DEBUG:          944281ac  93013294  /data/app-lib/com.efun.krqq.google-1/libcocos2dlua.so (wolf::Entity::CalculateL2P()+484)
12-15 19:42:16.302 153-153/? I/DEBUG:          944281b0  944282a0  [stack:1504]
12-15 19:42:16.302 153-153/? I/DEBUG:          944281b4  ba437328  [heap]
12-15 19:42:16.302 153-153/? I/DEBUG:          944281b8  00000000  
12-15 19:42:16.302 153-153/? I/DEBUG:          944281bc  944281e0  [stack:1504]
12-15 19:42:16.302 153-153/? I/DEBUG:          944281c0  00000000  
12-15 19:42:16.302 153-153/? I/DEBUG:          944281c4  b98e5910  [heap]
12-15 19:42:16.306 153-153/? I/DEBUG:          944281c8  944281e0  [stack:1504]
12-15 19:42:16.306 153-153/? I/DEBUG:          944281cc  00000000  

12-15 19:42:16.570 355-385/system_process I/BootReceiver: Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
12-15 19:42:16.610 355-385/system_process D/dalvikvm: GC_FOR_ALLOC freed 527K, 18% free 6438K/7816K, paused 34ms, total 36ms
12-15 19:42:16.626 355-1575/system_process W/ActivityManager: Process com.efun.krqq.google has crashed too many times: killing!

**Comment by developernotes** [comment]
Hello @penguu8 

Your stack trace does not appear to reference SQLCipher for Android at all, but rather problems with libcocos2dlua.so. If you have a specific issue related to SQLCipher for Android, please feel free to create a new issue with reproduction steps for further review. Thanks!
