### ISSUE TITLE
problem while updating app

### ISSUE THREAD

**Issue by finesushil** [sqlcipher/android-database-sqlcipher#372]
@developernotes 
### Background
We have been using jar file of sqlcipher in our app since 2013 and now we tried to use maven dependency. But while updating the old app with new app, the app crashes at launch.

### Expected Behavior
smooth running of app after update

### Actual Behavior
once the app with maven dependencies is updated over the old app, the app crashes when we open the updated app

We are not being able to identify what the real problem is. Please help

**Comment by developernotes** [comment]
Hi @finesushil 

If you rollback to your previous SQLCipher for Android install, would you modify your application to run the following SQL command and capture the string output:

```
PRAGMA cipher_version;
```

This will tell us what library your original SQLCipher database was built with. I suspect that you are using an old version and will need to upgrade your database file format as covered [here](https://www.zetetic.net/blog/2013/11/11/sqlcipher-300-release.html) in our blog.

**Comment by developernotes** [comment]
Hello @finesushil 

Since we have not heard back from you, we will close this issue for now. If you experience an issue again, please feel free to open a new issue providing reproduction steps for further review.
