### ISSUE TITLE
Report limit statement bug on android-database-sqlcipher version  v3.5.8  and  v3.5.9

### ISSUE THREAD

**Issue by sanemars** [sqlcipher/android-database-sqlcipher#374]
1.
```java
db.execSQL("CREATE TABLE IF NOT EXISTS " +
                "SUPPLY_ROUTE ( " +
                "ID INTEGER(20) PRIMARY KEY, " +
                "NAME VARCHAR(50), " +
                "RELEVANCE_SUPPLY_ID TEXT)"
        );
```
2. insert value 

```java

mDatabase.beginTransaction();
                try {
                    ContentValues values = new ContentValues();
                    for (int i = 0; i < 30; i++) {
                        values.put("ID", i);
                        values.put("NAME", "NAME " + i);
                        values.put("RELEVANCE_SUPPLY_ID", "R_ID " + i);
                        mDatabase.insert("SUPPLY_ROUTE", null, values);
                        values.clear();
                    }
                    mDatabase.setTransactionSuccessful();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    mDatabase.endTransaction();
                }
```

3.  query one 

```java
mDatabase.rawQuery(
                        "SELECT ID, NAME, RELEVANCE_SUPPLY_ID FROM SUPPLY_ROUTE  ORDER BY ID asc LIMIT 0, 20", null);
```

 query two

```java
mDatabase.rawQuery(
                        "SELECT ID, NAME, RELEVANCE_SUPPLY_ID FROM SUPPLY_ROUTE  ORDER BY ID asc LIMIT 20, 20", null);
```
### Expected Behavior
query one return ID 0\~19
query two return ID 20\~29
### Actual Behavior
on android-database-sqlcipher version  v3.5.8  and  v3.5.9
query one return ID 0\~19
query two return ID 1\~20

on android-database-sqlcipher version  v3.5.7
query one return ID 0\~19
query two return ID 20\~29

### Steps to Reproduce
just test the code

**Comment by developernotes** [comment]
Hi @sanemars 

I just pushed up a test [here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/QueryLimitTest.java) that covers the scenario you describe above. Would you mind running the test suite and letting me know your results? Thanks!

**Comment by sanemars** [comment]
Hi @developernotes 
I'm sorry,my mistake.
here has one more step,add abiFilters 

change model gradle to

```java
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "net.zetetic.sqlcipher.test"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters 'armeabi'// 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64', 'mips', 'mips64'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

```

and I run the test after add abiFilters ,the test failed
![capture](https://user-images.githubusercontent.com/10831818/36824501-aa07f6c2-1d3d-11e8-85f8-94034d4ba686.PNG)

**Comment by developernotes** [comment]
Hello @sanemars 

Thank you for the additional information. We were able to reproduce this and will investigate the issue further.

**Comment by brodybits** [comment]
Any word on this one?

As a side comment NDK r16 gives us a comment that `armeabi` is deprecated, will be removed from NDK r17 according to [[1]](https://github.com/android-ndk/ndk/wiki/Changelog-r16). (NDK r17 will be released in May 2018 according to [[2]](https://github.com/android-ndk/ndk/wiki#ndk-r17).) Time to drop support for `armeabi`?

[1] <https://github.com/android-ndk/ndk/wiki/Changelog-r16>
[2] <https://github.com/android-ndk/ndk/wiki#ndk-r17>

**Comment by developernotes** [comment]
Hi @brodybits, @sanemars 

Unfortunately at this time we do not have a particular solution in place that resolves `armeabi` only deployments. Our current recommendation if you are experiencing this issue is to not perform an ndk filter within Gradle. Again, it appears this issue may resolve itself once the NDK removes `armeabi` support.
