### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 32318

### ISSUE THREAD

**Issue by huanting** [sqlcipher/android-database-sqlcipher#375]
### Expected Behavior
**The error:**
I login on my app, when I logout , it crashed.
The error code is "executeInsert". This error can reproduce.

**The running device:**
I run my app on the device Lenovo K900, android 4.2.1. It's architecture is X86.

**The log:**
(32318): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128), thread 32318 (oid.hengjiaosuo)
03-13 10:09:09.833 I/DEBUG   ( 4967): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-13 10:09:09.833 I/DEBUG   ( 4967): Build fingerprint: 'Lenovo/K900/K900:4.2.2/JDQ39/K900_1_S_2_019_0142_130927:user/releasekey'
03-13 10:09:09.833 I/DEBUG   ( 4967): Revision: '0'
03-13 10:09:09.833 I/DEBUG   ( 4967): pid: 32318, tid: 32318, name: oid.hengjiaosuo  >>> com.evergrande.eif.android.hengjiaosuo <<<
03-13 10:09:09.833 I/DEBUG   ( 4967): signal 11 (SIGSEGV), code 128 (?), fault addr 00000000
03-13 10:09:09.883 I/DEBUG   ( 4967):     eax 00000000  ebx 61f2fdf8  ecx 00000054  edx 61f1f4e0
03-13 10:09:09.883 I/DEBUG   ( 4967):     esi 60a26858  edi 615757b4
03-13 10:09:09.883 I/DEBUG   ( 4967):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
03-13 10:09:09.883 I/DEBUG   ( 4967):     eip 61d1ce07  ebp 61575780  esp bf94d37c  flags 00010206
03-13 10:09:09.893 I/DEBUG   ( 4967): 
03-13 10:09:09.893 I/DEBUG   ( 4967): backtrace:
03-13 10:09:09.893 I/DEBUG   ( 4967):     #00  pc 00140e07  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #01  pc 0004f81d  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #02  pc 0004f256  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #03  pc 00072dcd  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #04  pc 000917e7  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #05  pc 0005e079  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #06  pc 000b44b7  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #07  pc 000c0866  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #08  pc 000fad8e  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #09  pc 000fe692  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #10  pc 0013a479  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #11  pc 00031140  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #12  pc 0008bec8  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #13  pc 00192ead  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #14  pc 00001ff4  /system/lib/libandroidfw.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #15  pc 00044346  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #16  pc 00041e13  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #17  pc 000bcef0  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #18  pc 00088142  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #19  pc 0005ec4b  /system/lib/libandroid_runtime.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #20  pc 0008e2f2  /system/lib/libandroid_runtime.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #21  pc 0008e4e6  /system/lib/libandroid_runtime.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #22  pc 00025d7c  /system/lib/libutils.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #23  pc 0002606c  /system/lib/libutils.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #24  pc 00098bb2  /system/lib/libandroid_runtime.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #25  pc 00031140  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #26  pc 0008bec8  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #27  pc 00000119  /dev/ashmem/dalvik-jit-code-cache (deleted)
03-13 10:09:09.893 I/DEBUG   ( 4967):     #28  pc 00044346  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #29  pc 00041e13  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #30  pc 000be193  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967):     #31  pc 000d1f72  /system/lib/libdvm.so
03-13 10:09:09.893 I/DEBUG   ( 4967): 
03-13 10:09:09.893 I/DEBUG   ( 4967): stack:
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d33c  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d340  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d344  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d348  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d34c  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d350  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d354  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d358  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d35c  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d360  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d364  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d368  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d36c  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d370  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d374  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d378  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):     #00  bf94d37c  615757b4  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d380  00000000  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d384  00000060  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d388  4006a789  /system/lib/libc.so
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d38c  644ec2b8  
03-13 10:09:09.893 I/DEBUG   ( 4967):          bf94d390  40066606  /system/lib/libc.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d394  61f2fdf8  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d398  61f1f4e0  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d39c  00000018  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3a0  64977e88  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3a4  00000100  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3a8  40115ff4  /system/lib/libc.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3ac  60a3afd8  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3b0  4009d1f5  /system/lib/libc.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3b4  61f2fdf8  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d3b8  61d1e428  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          ........  ........
03-13 10:09:09.903 I/DEBUG   ( 4967):     #01  bf94d43c  61575780  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d440  60a26838  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d444  00000020  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d448  61f1f4e0  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d44c  00000000  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d450  61d1e186  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d454  61f2fdf8  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d458  61d18f47  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d45c  644ec2c0  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d460  61e916c0  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d464  bf94d4c4  [stack]
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d468  60a3b3b8  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d46c  61d18f17  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d470  61f2fdf8  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d474  644ec2c0  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d478  e6d4549a  
03-13 10:09:09.903 I/DEBUG   ( 4967):          ........  ........
03-13 10:09:09.903 I/DEBUG   ( 4967):     #02  bf94d49c  60225068  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4a0  60a26838  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4a4  00000020  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4a8  60a3afd8  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4ac  000003e0  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4b0  bf94d4c4  [stack]
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4b4  00000004  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4b8  60a3b3b8  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4bc  60a267c8  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4c0  00000030  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4c4  00000007  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4c8  e6d4549a  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4cc  00000000  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4d0  00000000  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4d4  000003d0  
03-13 10:09:09.903 I/DEBUG   ( 4967):          bf94d4d8  61c4edcd  /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so
03-13 10:09:10.053 E/Parcel  ( 4396): Reading a NULL string not supported here.
03-13 10:09:10.133 E/Parcel  ( 4396): Reading a NULL string not supported here.
03-13 10:09:10.133 E/Parcel  ( 4396): Reading a NULL string not supported here.
03-13 10:09:10.193 E/Parcel  ( 4396): Reading a NULL string not supported here.
03-13 10:09:10.203 I/ActivityManager( 4396): Process com.evergrande.eif.android.hengjiaosuo (pid 32318) has died.
03-13 10:09:10.203 W/ActivityManager( 4396): send smart intent packageName=com.evergrande.eif.android.hengjiaosuo
03-13 10:09:10.203 W/ApplicationContext( 4396): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1038 com.android.server.am.ActivityManagerService.handleAppDiedLocked:2977 com.android.server.am.ActivityManagerService.appDiedLocked:3093 
03-13 10:09:10.203 W/ActivityManager( 4396): Scheduling restart of crashed service com.evergrande.eif.android.hengjiaosuo/com.evergrande.rooban.tools.aidl.HDAIDLRemoteService in 5000ms
03-13 10:09:10.203 W/ActivityManager( 4396): Force removing ActivityRecord{219c5f80 u0 com.evergrande.eif.android.hengjiaosuo/com.evergrande.eif.userInterface.activity.modules.personal.HDSettingEntryActivity}: app died, no saved state
03-13 10:09:10.213 W/InputDispatcher( 4396): channel '2124c120 com.evergrande.eif.android.hengjiaosuo/com.evergrande.eif.userInterface.activity.modules.personal.HDSettingEntryActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

**another log:**

#00 pc 00140e07 /data/app-lib/com.evergrande.eif.android.hengjiaosuo-1/libsqlcipher.so (HMAC_Init_ex+279) [x86]
--
2 java:
3 net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
4 net.sqlcipher.database.SQLiteStatement.executeInsert(SQLiteStatement.java:83)
5 org.greenrobot.greendao.database.EncryptedDatabaseStatement.executeInsert(EncryptedDatabaseStatement.java:46)
6 org.greenrobot.greendao.AbstractDao.executeInsertInTx(AbstractDao.java:294)
7 org.greenrobot.greendao.AbstractDao.insertOrReplaceInTx(AbstractDao.java:250)
8 org.greenrobot.greendao.AbstractDao.insertOrReplaceInTx(AbstractDao.java:268)
9 com.evergrande.eif.dbManagers.HDPublicUserManager.HDPublicUserManager.updateUserGstInfo(HDPublicUserManager.java:77)

### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
3.5.7

SQLCipher for Android version:
android 4.2.1, 17 

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @huanting,

It appears you are using a 3rd party library on top of SQLCipher for Android (i.e., greenDAO). Are you able to reproduce the issue without greenDAO, only using SQLCipher for Android? Would you try running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on that device and report your results? We have steps [here](https://github.com/sqlcipher/sqlcipher-android-tests#creating-a-new-test) for creating a new test in the suite. Thanks!

**Comment by huanting** [comment]
I update the sqlcipher's version from 3.5.7 to 3.5.9. The error can't be reproduced.

**Comment by developernotes** [comment]
Hi @huanting 

We are glad to hear updating the library has resolved the issue for you. Take care!
