### ISSUE TITLE
Multidex exception with sqlcipher library

### ISSUE THREAD

**Issue by Kameswari** [sqlcipher/android-database-sqlcipher#377]
Hi,

I am using SQLCipher 3.5.9 library. I have added the .aar file in the libs folder and using it.
By the time of compilation its working fine, But when I run the code, I am getting the below exception.

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lnet/sqlcipher/database/SQLiteDebug$PagerStats;
Error:com.android.dex.DexException: Multiple dex files define Lnet/sqlcipher/database/SQLiteDebug$PagerStats;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lnet/sqlcipher/database/SQLiteDebug$PagerStats;

I have enabled multidex by extending MultiDexApplication for my application class and enabled the property multiDexEnabled to true in build.gradle

Please help me on how to resolve this issue.

**Comment by developernotes** [comment]
Hi @Kameswari 

Would you try first performing a `Clean Project` operation, then a `Make Project` to see if that resolves the issue?

**Comment by Kameswari** [comment]
Yes I tried. But still issue exists.

**Comment by developernotes** [comment]
Hi @Kameswari 

Are you using the community edition, or the commercial edition of SQLCipher for Android?

**Comment by Kameswari** [comment]
I am using community edition for now. Got the .aar file from https://mvnrepository.com/artifact/net.zetetic/android-database-sqlcipher/3.5.9

I have added this in 'libs' folder and build the application.

**Comment by developernotes** [comment]
Hi @Kameswari 

Since you are using the community edition, would you try integrating the library per these [instructions](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/) (i.e., not copying the AAR package directly, but referencing it by name only)?

**Comment by Kameswari** [comment]
I have downloaded the aar file and added to the libs and added the below line in build.gradle
implementation fileTree(include: ['*.aar', '*.jar'], dir: 'libs')
I am not getting any compile time errors. But while running the app, getting multidex exception.

**Comment by theBlbDan** [comment]
Which looks nothing like the instructions referenced.

compile 'net.zetetic:android-database-sqlcipher:3.5.9@aar'
