### ISSUE TITLE
APK becomes larger,increase about 7M.

### ISSUE THREAD

**Issue by kanshenmekan** [sqlcipher/android-database-sqlcipher#379]
Forgive me for being a novice， is this natural?

**Comment by developernotes** [comment]
Hello @kanshenmekan 

Thank you for your interest in SQLCipher for Android! Yes, SQLCipher for Android includes platform support for 5 different CPU architectures across both 32-bit and 64-bit platforms. The native binaries themselves represent the majority of the file size. If you have further questions, please feel free to direct them to our SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
