### ISSUE TITLE
Possible Feature: Compression

### ISSUE THREAD

**Issue by nappy** [sqlcipher/android-database-sqlcipher#38]
Problem with encrypted data: You cannot compress it efficiently.

In my case, I have a 50 MB database which is only like 10 MB zipped. Obviously this is no longer possible if the database is encrypted.

My suggestion is to add an compression layer which can compress the unencrypted chunks and encrypt it afterwards.

**Comment by ray-pixar** [comment]
I have the same problem and vacuum does not help! is it possible to compress database ?

**Comment by cnting** [comment]
I have the same problem.Anything new?

**Comment by developernotes** [comment]
Hello @nappy, @cnting,

The compression topic has been discussed on our SQLCipher discuss site [here](https://discuss.zetetic.net/t/transparent-compression-support/460/3?u=developernotes). This is not something that we have planned as a community offering, however you are welcome to reach out to [sales@zetetic.net](mailto:sales@zetetic.net) to discuss a commercial engagement for your organization's needs. Thanks!
