### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by prathapbez** [sqlcipher/android-database-sqlcipher#380]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/base.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_dependencies_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_0_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_1_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_2_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_3_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_4_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_5_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_6_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_7_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_8_apk.apk", zip file "/data/app/sg.com.mobileeftpos.paymentapplication-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/sg.com.mobileeftpos.paymentapplication-1/lib/arm, /private2/lib, /vendor/lib, /system/lib]]] couldn't find "libnexgo_sdkemvjni.so"

Getting this issue if I add this library("compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'") for version 5.0
Can any one please help in this

**Comment by developernotes** [comment]
Hi @prathapbez 

What happens if you disable splitting on the APK within your build configuration?

**Comment by developernotes** [comment]
Hello @prathapbez 

As we have not heard back from you, we will close this issue for now. If you experience the issue again, please feel free to open a new issue providing additional details for further analysis.
