### ISSUE TITLE
How do I check If my database is encrypted 

### ISSUE THREAD

**Issue by douglasalipio** [sqlcipher/android-database-sqlcipher#381]
SQLCipher for Android version: 3.5.9

Hello guys,

How do I check If my database is encrypted?

**Comment by theBlbDan** [comment]
@douglasalipio 
Given [Database File Format](https://www.sqlite.org/fileformat.html#the_database_header), you can read the first (n) bytes of the file.  If you know that you're reading what *should* be a database, you can assume that you are either looking at an unencrypted file, or an encrypted one.

If you have any uncertainty, then the best you can know is that you *might* be looking at an unencrypted SQLite3 database file.

Here'd how I approach the issue.
````java
    private void openDb() {
    	if(db != null && db.isOpen()) { return; }
    	synchronized (MyActivity.sDataLock) {
	    	try {
	    		String s = "SQLite format 3";
	    		byte[] b = new byte[s.length()];
                final int bytesRead = FileUtils.openInputStream(new File(DATABASE_PATH)).read(b);
                if(bytesRead == s.length() && s.equals(new String(b))) {
	    			// Unencrypted
		    		db = SQLiteDatabase.openDatabase(DATABASE_PATH, "", null, SQLiteDatabase.OPEN_READWRITE);	// Not an encrypted DB
	    		} else {
		    		// Can we open it with the password?
		    		db = SQLiteDatabase.openDatabase(DATABASE_PATH, "abc123", null, SQLiteDatabase.OPEN_READWRITE);
	    		}
	    	} catch (IOException e) {
	    		crashingCallHome("openDb()", e);
	    		System.exit(0);
			}
    	}
    }

**Comment by douglasalipio** [comment]
@theBlbDan thanks, man. It works well 🗡
