### ISSUE TITLE
Make build error

### ISSUE THREAD

**Issue by llmagicll** [sqlcipher/android-database-sqlcipher#384]
### Expected Behavior
Build successfully

### Actual Behavior
Fatal error

### Steps to Reproduce
make init
make build

`I download the latest version from git and try to make build but keep getting the error like this
 
/<path>/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34726:42: error: use of undeclared identifier 'close'
  { "close",        (sqlite3_syscall_ptr)close,      0  },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34729:42: error: use of undeclared identifier 'access'
  { "access",       (sqlite3_syscall_ptr)access,     0  },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34732:42: error: use of undeclared identifier 'getcwd'
  { "getcwd",       (sqlite3_syscall_ptr)getcwd,     0  },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34752:42: error: use of undeclared identifier 'ftruncate'
  { "ftruncate",    (sqlite3_syscall_ptr)ftruncate,  0  },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34758:42: error: use of undeclared identifier 'read'
  { "read",         (sqlite3_syscall_ptr)read,       0  },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34775:42: error: use of undeclared identifier 'write'
  { "write",        (sqlite3_syscall_ptr)write,      0  },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34804:42: error: use of undeclared identifier 'unlink'; did you mean
      'inline'?
  { "unlink",       (sqlite3_syscall_ptr)unlink,           0 },
                                         ^~~~~~
                                         inline
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34804:42: error: expected expression
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34813:42: error: use of undeclared identifier 'rmdir'
  { "rmdir",        (sqlite3_syscall_ptr)rmdir,           0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34817:42: error: use of undeclared identifier 'fchown'
  { "fchown",       (sqlite3_syscall_ptr)fchown,          0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34823:42: error: use of undeclared identifier 'geteuid'
  { "geteuid",      (sqlite3_syscall_ptr)geteuid,         0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34827:42: error: use of undeclared identifier 'mmap'
  { "mmap",         (sqlite3_syscall_ptr)mmap,            0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34834:42: error: use of undeclared identifier 'munmap'
  { "munmap",       (sqlite3_syscall_ptr)munmap,          0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34841:42: error: use of undeclared identifier 'mremap'
  { "mremap",       (sqlite3_syscall_ptr)mremap,          0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34855:42: error: use of undeclared identifier 'readlink'
  { "readlink",     (sqlite3_syscall_ptr)readlink,        0 },
                                         ^
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34904:22: error: invalid application of 'sizeof' to an incomplete
      type 'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34913:22: error: invalid application of 'sizeof' to an incomplete
      type 'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34940:20: error: invalid application of 'sizeof' to an incomplete
      type 'struct unix_syscall []'
  for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                   ^~~~~~~~~~
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:34957:16: error: invalid application of 'sizeof' to an incomplete
      type 'struct unix_syscall []'
    for(i=0; i<ArraySize(aSyscall)-1; i++){
               ^~~~~~~~~~~~~~~~~~~
/Users/magic/Documents/Projects/android/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/../external/sqlcipher/sqlite3.c:13016:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
`

Could anyone help~~Thx

**Comment by developernotes** [comment]
Hi @llmagicll 

What Android NDK do you have on your `PATH` environment variable?

**Comment by llmagicll** [comment]
Hi @developernotes I use the recommended version r15c

**Comment by developernotes** [comment]
Hi @llmagicll 

Does `make init` report any errors? Do you need to build from source, or can you utilize the community distribution?

**Comment by developernotes** [comment]
Hi @llmagicll 

Were you able to resolve your build errors?

**Comment by developernotes** [comment]
Hi @llmagicll 

We are closing this issue for now, if you are still experiencing an issue please feel free to open a new ticket with additional information about the scenario. Thanks!
