### ISSUE TITLE
Issue on upgrading Android OS 7 to 8.0

### ISSUE THREAD

**Issue by M-Ahmad-sattar** [sqlcipher/android-database-sqlcipher#385]
Cards still authenticate

Developed an Android application in which NFC virtually cards access DB, SQLite with cipher used, working perfectly, a problem occurs, when Android OS upgrade from 7 to 8.0, all cards are disappeared & I can't access the DB as well, it shows they are stored in Database but hide after OS upgrade!

### Steps to Reproduce
there is no glitch in code or DB, using chiper may effect on 8.0 while using 3.5.6.

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by sjlombardo** [comment]
Hello @M-Ahmad-sattar - we are not aware of any issues that would cause a problem accessing a SQLCipher database under Android 8 / Oreo. The test suite runs fine there, and we know of numerous applications that are using SQLCipher without issues on that OS version. 

As a first step, you should try upgrading to the latest SQLCipher for Android, 3.5.9. If that does not work we'd need additional information, including what you mean by the database being "hidden" after upgrade, how you've eliminated the potential for a bug in your code, and ideally a reproducible code sample that demonstrates the problem.

**Comment by M-Ahmad-sattar** [comment]
@sjlombardo Thanks 'll upgrade it on the latest version!

**Comment by developernotes** [comment]
Hello @M-Ahmad-sattar 

Were you able to resolve the issue by upgrading to the latest version of SQLCipher for Android?

**Comment by developernotes** [comment]
Hello @M-Ahmad-sattar 

We are closing this issue for now, if you are still experiencing an issue please feel free to open a new ticket with additional information about the scenario. Thanks!
