### ISSUE TITLE
query offset not work( at version 3.5.8&3.5.9   armeabi/libsqlcipher.so)

### ISSUE THREAD

**Issue by luhuajcdd** [sqlcipher/android-database-sqlcipher#387]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`): 
version = 3.5.8 & 3.5.9 ;
armeabi/libsqlcipher.so; not work

armeabi-v7a/libsqlcipher.so  work fine! 

SQLCipher for Android version: all

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

app.gradle:

android {
    compileSdkVersion 21
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.research.testdb"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        _ndk {
            abiFilters "armeabi"
        }_
    }

test data: 
select count(*)  from user;      result = 7
SELECT * FROM `user` LIMIT 10 OFFSET 0 ;    return 7 items
SELECT * FROM `user` LIMIT 10 OFFSET 5;     return 6 items（error） ;     return 2 times (correct)

**Comment by developernotes** [comment]
Hello @luhuajcdd 

This issue has been reported [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/374), with our current recommended approach [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/374#issuecomment-377319166).
