### ISSUE TITLE
setWriteAheadLoggingEnabled() Does Not Seem to Work

### ISSUE THREAD

**Issue by commonsguy** [sqlcipher/android-database-sqlcipher#388]
### Steps to Reproduce

SQLCipher for Android version: tip of `gradle` branch as of a week ago

Implement this test:

```java
  @Test
  public void directHelperWAL() {
    SQLiteDatabase.loadLibs(InstrumentationRegistry.getTargetContext());

    Helper helper=new Helper(InstrumentationRegistry.getTargetContext());

    helper.setWriteAheadLoggingEnabled(true);

    SQLiteDatabase db=helper.getWritableDatabase("sekrit");

    assertTrue(db.isWriteAheadLoggingEnabled());
  }

  private static final class Helper extends SQLiteOpenHelper {
    Helper(Context ctxt) {
      super(ctxt, "foo", null, 1);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
      // unused
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
      throw new UnsupportedOperationException("Um, wut?");
    }
  }
```

### Expected Behavior

The test to succeed.

### Actual Behavior

The test fails.

**Comment by developernotes** [comment]
Hi @commonsguy 

We have a similar test [here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/SQLiteOpenHelperEnableWriteAheadLogTest.java), however the ordering is flipped on the call to `setWriteAheadLoggingEnabled` and `getWritableDatabase`. I will look into this. Thanks!

**Comment by commonsguy** [comment]
Yeah, the way Room uses this is it calls `setWriteAheadLoggingEnabled()` before trying to get the database. Frankly, I'm not sure why the support database API has two mechanisms for WAL (`setWriteAheadLoggingEnabled()` on the helper and `enableWriteAheadLogging()` on the database).

**Comment by developernotes** [comment]
Hi @commonsguy 

I've just pushed up a fix to the master branch that will allow `setWriteAheadLoggingEnabled` to be called before `getWritableDatabase`, I've also included a test in the suite for it as well. Please let me know if this addresses the issue on your end with SafeRoom. Thanks!

**Comment by commonsguy** [comment]
It'll be a couple of weeks before I can get back to this to confirm, but it sounds promising. Thanks!

**Comment by commonsguy** [comment]
Sorry for the delay in responding, but I can confirm that the current tip of the `gradle` branch works fine on this test.

Many thanks!

**Comment by developernotes** [comment]
Hello @commonsguy 

Excellent, we are happy to hear everything is working well. Thanks!
