### ISSUE TITLE
UnsatisfiedLinkError:dlopen failed: library "libutils.so" not found 

### ISSUE THREAD

**Issue by McLionChan** [sqlcipher/android-database-sqlcipher#391]
### Expected Behavior
load library libutils.so well
### Actual Behavior
when run on Android 7.0, APP crash
### Steps to Reproduce
in Android 7.0，run my app,it crashed. 

I used this lib to do database entryption with xutils,but in Android 7.0,it crashed.I know it's Android 7.0' feature, and targetSdkVersion <= 23 will work，but i don't want to do like this,my targetSdkVersion  is 26 ,How to access private platform API,what shall I do?thank you.

**Comment by sjlombardo** [comment]
Hello @McLionChan - it sounds like you are using a very old version of SQLCipher for Android. You should consider upgrading to the latest version of the library for Android 7 support (SQLCipher for Android 3.5.9 at the time of this writing).

**Comment by McLionChan** [comment]
thanks for reply,when i choose SQLCipher for Android 3.5.9, it worked, I'm so happy, thank you very much!
