### ISSUE TITLE
 java.lang.UnsatisfiedLinkError sqlcipher:3.5.9

### ISSUE THREAD

**Issue by khanhhoilm** [sqlcipher/android-database-sqlcipher#393]
Hi,
Recently, I have a problem same as issues #380 

  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
[DexPathList[[zip file "/data/app/com.example.develop-1/base.apk"],
nativeLibraryDirectories=[/data/app/com.example.develop-1/lib/arm, /private2/lib, /vendor/lib, /system/lib]]] couldn't find "libnexgo_sdkemvjni.so"
   
I have this issues if i add  this library implementation 'net.zetetic:android-database-sqlcipher:3.5.9@aar'

When i don't add library SQLCipher. In directory /data/app/com.example.develop-1/lib/arm i have some file .so same below picture

![image](https://user-images.githubusercontent.com/26219407/43574705-13f42d8a-966f-11e8-823c-b4dfda95934c.png)

But when i add library SQLCipher. In directory /data/app/com.example.develop-1/lib/arm just have only 1 file libsqlcipher.so

The problem still happen when i disable splitting on the APK within your build configuration.

I run in android 5.1.1
I have referenced issues #302 but i can't resolve this problem.

Can any one please help me in this.

**Comment by developernotes** [comment]
Hi @khanhhoilm 

We include compatibility support for the [following](https://github.com/sqlcipher/android-database-sqlcipher#compatibility) architectures. Please make sure the other native libraries your application is including, specifically `libnexgo_sdkemvjni` from the error message also include those platforms.

**Comment by khanhhoilm** [comment]
Hi @developernotes 

I make sure the other native libraries my application is including, specifically libnexgo_sdkemvjni use armeabi-v7a architectures (I got the answer from Nexgo provider).

**Comment by developernotes** [comment]
Hi @khanhhoilm 

You may wish to unpack your apk with [apktool](https://ibotpeaches.github.io/Apktool/) to further evaluate what your project is bundling. From the error message above, it appears to be looking for the `armerabi` version, not `armeabi-v7a`. We utilize Github issues to report software defects. As this is a project configuration issue, I am going to close this ticket. If you have any further questions, please feel free to post the specific details to our community [discuss](shttps://discuss.zetetic.net/c/sqlcipher) site. Thanks!
