### ISSUE TITLE
in x86 system, loadlibs so fatal.

### ISSUE THREAD

**Issue by privacycenter** [sqlcipher/android-database-sqlcipher#394]
art/runtime/check_jni.cc:65]   native: #00 pc 000063eb  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+91)
    art/runtime/check_jni.cc:65]   native: #01 pc 00002f31  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+33)
    art/runtime/check_jni.cc:65]   native: #02 pc 004290ea  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+122)
    art/runtime/check_jni.cc:65]   native: #03 pc 003e4c57  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+263)
    art/runtime/check_jni.cc:65]   native: #04 pc 000f9644  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1588)
    art/runtime/check_jni.cc:65]   native: #05 pc 000fa192  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+98)
    art/runtime/check_jni.cc:65]   native: #06 pc 0010003d  /system/lib/libart.so (art::ScopedCheck::CheckThread(int)+2093)
    art/runtime/check_jni.cc:65]   native: #07 pc 00100a27  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1095)
    art/runtime/check_jni.cc:65]   native: #08 pc 0010eecb  /system/lib/libart.so (art::CheckJNI::FindClass(_JNIEnv*, char const*)+75)
    art/runtime/check_jni.cc:65]   native: #09 pc 001b2e5a  /data/app/eu.siacs.conversations-1/lib/x86/libsqlcipher.so (sqlcipher::register_android_database_SQLiteCompiledSql(_JNIEnv*)+42)
    art/runtime/check_jni.cc:65]   native: #10 pc 001b39a6  /data/app/eu.siacs.conversations-1/lib/x86/libsqlcipher.so (JNI_OnLoad+182)
    art/runtime/check_jni.cc:65]   native: #11 pc 0032693d  /system/lib/libart.so (art::JavaVMExt::LoadNativeLibrary(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, art::Handle<art::mirror::ClassLoader>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+8525)
    art/runtime/check_jni.cc:65]   native: #12 pc 00380c4f  /system/lib/libart.so (art::Runtime_nativeLoad(_JNIEnv*, _jclass*, _jstring*, _jobject*, _jstring*)+847)
    art/runtime/check_jni.cc:65]   native: #13 pc 00093f2a  /data/dalvik-cache/x86/system@framework@boot.oat (Java_java_lang_Runtime_nativeLoad__Ljava_lang_String_2Ljava_lang_ClassLoader_2Ljava_lang_String_2+206)
    art/runtime/check_jni.cc:65]   at java.lang.Runtime.nativeLoad(Native method)
    art/runtime/check_jni.cc:65]   at java.lang.Runtime.doLoad(Runtime.java:428)
    art/runtime/check_jni.cc:65]   - locked <0x36ff60fb> (a java.lang.Runtime)
    art/runtime/check_jni.cc:65]   at java.lang.Runtime.loadLibrary(Runtime.java:369)
    art/runtime/check_jni.cc:65]   at java.lang.System.loadLibrary(System.java:993)
    art/runtime/check_jni.cc:65]   at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:222)
    art/runtime/check_jni.cc:65]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:239)
    art/runtime/check_jni.cc:65]   - locked <0x21ed9e39> (a java.lang.Class<net.sqlcipher.database.SQLiteDatabase>)
    art/runtime/check_jni.cc:65]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:218)
    art/runtime/check_jni.cc:65]   - locked <0x21ed9e39> (a java.lang.Class<net.sqlcipher.database.SQLiteDatabase>)
    art/runtime/check_jni.cc:65]   at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:211)
    art/runtime/check_jni.cc:65]   - locked <0x21ed9e39> (a java.lang.Class<net.sqlcipher.database.SQLiteDatabase>)
    art/runtime/check_jni.cc:65]   at eu.siacs.conversations.persistance.DatabaseBackend.getInstance(DatabaseBackend.java:203)
    art/runtime/check_jni.cc:65]   - locked <0x2d8de0f4> (a java.lang.Class<eu.siacs.conversations.persistance.DatabaseBackend>)
    art/runtime/check_jni.cc:65]   at eu.siacs.conversations.ui.ConversationActivity.onCreate(ConversationActivity.java:59)
    art/runtime/check_jni.cc:65]   at android.app.Activity.performCreate(Activity.java:5990)
    art/runtime/check_jni.cc:65]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    art/runtime/check_jni.cc:65]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
    art/runtime/check_jni.cc:65]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
    art/runtime/check_jni.cc:65]   at android.app.ActivityThread.access$800(ActivityThread.java:151)
    art/runtime/check_jni.cc:65]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
    art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:102)
    art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
    art/runtime/check_jni.cc:65]   at android.app.ActivityThread.main(ActivityThread.java:5254)
    art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
    art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
    art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
    art/runtime/check_jni.cc:65]

**Comment by privacycenter** [comment]
android studio 3.1 + sqlcipher-android-tests-master

**Comment by privacycenter** [comment]
--------- beginning of crash
08-03 06:52:57.287 1732-1732/eu.siacs.conversations A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 1732 (s.conversations)
08-03 06:52:57.292 1747-1747/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'Android/vbox86p/vbox86p:7.1.1/NMF26Q/91:userdebug/test-keys'
    Revision: '0'
    ABI: 'x86'
    pid: 1732, tid: 1732, name: s.conversations  >>> eu.siacs.conversations <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-03 06:52:57.293 1747-1747/? A/DEBUG: Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lnet/sqlcipher/database/SQLiteDatabase;.native_getDbLookaside()I"'
        eax 00000000  ebx 000006c4  ecx 000006c4  edx 00000006
        esi ece6258c  edi ece62534
        xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
        eip ecd8ebb9  ebp ffd49a38  esp ffd499dc  flags 00200296
08-03 06:52:57.366 1747-1747/? A/DEBUG: backtrace:
        #00 pc 00000bb9  [vdso:ecd8e000] (__kernel_vsyscall+9)
        #01 pc 0007a30c  /system/lib/libc.so (tgkill+28)
        #02 pc 00075b55  /system/lib/libc.so (pthread_kill+85)
        #03 pc 0002786a  /system/lib/libc.so (raise+42)
        #04 pc 0001ee46  /system/lib/libc.so (abort+86)
        #05 pc 005184c5  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+565)
        #06 pc 0011a653  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1747)
        #07 pc 00392c25  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+3445)
        #08 pc 00392dc8  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_Pc+120)
        #09 pc 0013e1f2  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+82)
        #10 pc 0013dc29  /system/lib/libart.so (_ZN3art11ScopedCheck11CheckThreadEP7_JNIEnv+569)
        #11 pc 0013c5cb  /system/lib/libart.so (_ZN3art11ScopedCheck22CheckPossibleHeapValueERNS_18ScopedObjectAccessEcNS_12JniValueTypeE+91)
        #12 pc 0013b34e  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+1390)
        #13 pc 00128fb6  /system/lib/libart.so (_ZN3art8CheckJNI9FindClassEP7_JNIEnvPKc+982)
        #14 pc 001b2e5a  /data/app/eu.siacs.conversations-2/lib/x86/libsqlcipher.so (_ZN9sqlcipher43register_android_database_SQLiteCompiledSqlEP7_JNIEnv+42)
        #15 pc 001b39a6  /data/app/eu.siacs.conversations-2/lib/x86/libsqlcipher.so (JNI_OnLoad+182)

**Comment by developernotes** [comment]
Hi @privacycenter 

Are you utilizing the prebuild community edition binaries, the commercial edition binaries, or a local build of the software when you experience this behavior?

**Comment by privacycenter** [comment]
remove proguard.it works

**Comment by developernotes** [comment]
Hi @privacycenter 

Glad to hear you were able to resolve the issue. Take care!
