### ISSUE TITLE
Add AboutLibraries support

### ISSUE THREAD

**Issue by akallabeth** [sqlcipher/android-database-sqlcipher#395]
For automatic detection by https://github.com/mikepenz/AboutLibraries
a few resource strings must be added.

Would be nice to have that to easily present that.

**Comment by developernotes** [comment]
Hi @akallabeth 

Thanks for sharing AboutLibraries, I wasn't aware of that. The modifications [required](https://github.com/mikepenz/AboutLibraries/wiki/HOWTODEV:-Include-in-your-library) for support appear very minimal, we could look to add this with our next release. Thanks!

**Comment by developernotes** [comment]
Hi @akallabeth 

I have just [included support](https://github.com/sqlcipher/android-database-sqlcipher/commit/582f3f4d010f460ce2c5e81089e814841c6424dd) for AboutLibraries which will be included in our next public release. Thanks!
