### ISSUE TITLE
Please update the version of openssl to 1.1.0i or latest version

### ISSUE THREAD

**Issue by ConcurAppSec** [sqlcipher/android-database-sqlcipher#396]
Please update the version of openssl used by android sqlcipher to 1.1.0i or latest version release as there are known vulnerabilities in 1.1.0g.

 https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/version_id-232284/Openssl-Openssl-1.1.0g.html

Thank you!

**Comment by developernotes** [comment]
Hello @ConcurAppSec 

We often update the underlying bundled OpenSSL library used within SQLCipher for Android during new releases. Please note that the CVE's identified in the link you provided are specific to either TLS operations or instruction set architectures that SQLCipher for Android does not target. Thanks!
