### ISSUE TITLE
Sqlcipher query issue! Limit query returned error!

### ISSUE THREAD

**Issue by luinnx** [sqlcipher/android-database-sqlcipher#401]
### Expected Behavior
limit 100,100 Expected returned 100 items。
### Actual Behavior
Actual returned 199 items
### Steps to Reproduce

//cur1 = mSQLiteDatabase.query(SMS.TABLE_NAME, projection, selection, agrs, SMS.NUMBER, null, orderby, " 100 , 100");
cur2 = mSQLiteDatabase.queryT("SELECT max(Time) t, count(1) as num, Number, Name, MsgCenter, Content, Readed, Direction, Deleted FROM SMS WHERE Deleted != '1' GROUP BY Number ORDER BY  t desc, num desc LIMIT 100 , 100", null);
			
Log.i(TAG, "cur1.count: " + cur1.getCount());
Log.i(TAG, "cur2.count: " + cur2.getCount());

05-20 04:41:15.776: I/SMSAdapterData(14580): cur1.count: 199
05-20 04:41:15.778: I/SMSAdapterData(14580): cur2.count: 199

cur1.count、cur2.count result is same

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:
we have been useing android-database-sqlcipher-3.5.9.jar

**Comment by developernotes** [comment]
Hello @luinnx 

Out of curiosity, are you using the `abiFilters` within your gradle configuration?

**Comment by luinnx** [comment]
I use armeabi so with Eclipse.

**Comment by developernotes** [comment]
Hello @luinnx,

So are you filtering to only include armeabi?

**Comment by luinnx** [comment]
Yes ,it’s Android 5.0 
it will be OK when ues sqlite .

**Comment by developernotes** [comment]
Hello @luinnx 

We have previously received a report of this behavior [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/374), along with our current recommendation [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/374#issuecomment-377319166) which is to not perform an abiFilter.
