### ISSUE TITLE
Implement androidx.sqlite.db interfaces

### ISSUE THREAD

**Issue by gabrielittner** [sqlcipher/android-database-sqlcipher#403]
The AndroidX libraries have a set of interfaces that abstract the API of Android's sqlite classes. Other libraries like Room, SqlDelight and SqlBrite build on top of those interface to be independent of the framework implementation. If sqlcipher would implement these inferfaces, we could use any of the mentioned libraries together with it by just passing in another SupportSQLiteOpenHelper.Factory.

**Comment by developernotes** [comment]
Hi @gabrielittner 

We have done [some](https://github.com/sqlcipher/android-database-sqlcipher/commit/2adb82b5dec0aee67a81d018f25862df94182e92) [work](https://github.com/sqlcipher/android-database-sqlcipher/commit/e18ea7b2bc7ee2604636dacbe943bbc918580d96) that will be included in our next release of SQLCipher for Android to help facilitate @commonsguy's [SafeRoom](https://github.com/commonsguy/cwac-saferoom) implementation. Are you aware of specific deficiencies that you need not present within the master branch? We would be happy to consider those in the future, however new proposed changes are unlikely to make it into our upcoming release due to time limitations. We are open to hearing more specifics.

**Comment by developernotes** [comment]
Hello @gabrielittner 

Do you have any feedback regarding my comments above? Now that SQLCipher 4.0.1 is [available](https://www.zetetic.net/blog/2018/12/18/sqlcipher-401-release/) and the changes mentioned above are integrated within SQLCipher for Android, they may fit your needs.

**Comment by gabrielittner** [comment]
Hi @developernotes 
Sorry for not replying, I somehow missed yours. I know of SafeRoom, but think it would be nicer to avoid the wrapping and just have SQLCipher implement the interfaces directly.
As an example here is the commit that did the same for [requery sqlite-android](https://github.com/requery/sqlite-android), which similar to SQLCipher has an API that's very similar to `android.database.sqlite.*`.

**Comment by commonsguy** [comment]
This may or may not work. Java does not let you have two methods with the same name and same parameter list but with different return values. We would need to see if the `SupportSQLite*` classes have any collisions with existing methods in SQLCipher for Android. Running some experiments for that is now on my to-do list.

There would be an incremental cost to SQLCipher for Android users, in the form of the `androidx.sqlite:sqlite` dependency, which contains the `SupportSQLite*` family of interfaces. That's pretty tiny, though.

In addition, Zetetic would need to be interested in having this support baked into SQLCipher for Android, whether it is something they would do themselves or something that would be contributed by others (e.g., me).

I went the SafeRoom wrapper route just to get something out there without interfering with Zetetic's work. Plus, prior to 4.0.0, your approach would have been impractical &mdash; I could barely create the wrapper. Personally, I would be elated to be able to get `SupportSQLiteDatabase` support directly in SQLCipher for Android, as a wrapper or as a direct implementation as you propose.

**Comment by developernotes** [comment]
Hi @gabrielittner,

Just a follow up, in SQLCipher for Android 4.3.0 we shipped support for Room integration through the `androidx.sqlite.db` interfaces with all the heavy lifting by @commonsguy. Would you take a look and let us know if that addresses your need?

**Comment by gabrielittner** [comment]
Nice, I didn't notice that. It totally addresses my needs 👍
