### ISSUE TITLE
Error: file is not a database

### ISSUE THREAD

**Issue by 7763sea** [sqlcipher/android-database-sqlcipher#407]
### Steps to Reproduce
[signal.zip](https://github.com/sqlcipher/android-database-sqlcipher/files/2674404/signal.zip)

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
SQLCipher version 3.25.2 2018-09-25 19:08:10
SQLCipher for Android version:
3.5.9
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

PRAGMA cipher_default_kdf_iter = 1;
PRAGMA cipher_default_page_size = 4096;

//PRAGMA key ="x'fa2abf101a458d0be506e366bfa2d7a9dfe17e8c90d81e5a671eb3f4ed916cd9'";
PRAGMA key ="fa2abf101a458d0be506e366bfa2d7a9dfe17e8c90d81e5a671eb3f4ed916cd9";

//PRAGMA cipher_use_hmac = off;

PRAGMA kdf_iter = '1';
PRAGMA cipher_page_size = 4096;

ATTACH DATABASE 'plaintext.db' AS plaintext KEY "";
SELECT sqlcipher_export('plaintext');
DETACH DATABASE plaintext;

**Comment by developernotes** [comment]
Hello @7763sea 

Would you mind sharing a bit more detail about the problem you are experiencing and what you are trying to do?

**Comment by 7763sea** [comment]
signal.zip uploaded，fa2abf101a458d0be506e366bfa2d7a9dfe17e8c90d81e5a671eb3f4ed916cd9 is encrypt key。"signal.db"  from Signal app(4.30.8)
app source code : https://github.com/signalapp/Signal-Android

**Comment by sjlombardo** [comment]
@7763sea - This is not a defect in SQLCipher. As you know Signal does not use default settings, so there is some combination of PRAGMAs that must be executed when opening a database. This might be different for specific versions of Signal You would really need to either examine the source code for Signal in detail or contact their team to determine exactly what SQLCipher configurations (via PRAGMA) are necessary to open up a database generated by that version of the application.

**Comment by 7763sea** [comment]
android-database-sqlcipher deocode signal.db success！！，use windows sqlcipher decode failed！！

i thoutht windows platform sqlcipher buged。

**Comment by 7763sea** [comment]
`           String key = “fa2abf101a458d0be506e366bfa2d7a9dfe17e8c90d81e5a671eb3f4ed916cd9”;
            String decryptedName = "signal.db";
            SQLiteDatabaseHook hook = new SQLiteDatabaseHook() {
                @Override
                public void preKey(SQLiteDatabase db) {
                    db.rawExecSQL("PRAGMA cipher_default_kdf_iter = 1;");
                    db.rawExecSQL("PRAGMA cipher_default_page_size = 4096;");
                }

                @Override
                public void postKey(SQLiteDatabase db) {
                    db.rawExecSQL("PRAGMA kdf_iter = '1';");
                    db.rawExecSQL("PRAGMA cipher_page_size = 4096;");
                }};

            File databaseFile = getDatabasePath(filePath);
            SQLiteDatabase database = SQLiteDatabase.openOrCreateDatabase(databaseFile,key,null,hook);
            //SQLiteDatabase database = SQLiteDatabase.openDatabase(SDcardPath + encryptedName, key.toCharArray(), null, 1,hook);

            File decrypteddatabaseFile = getDatabasePath(SDcardPath + decryptedName);

            if (decrypteddatabaseFile.exists())
            {
                Toast.makeText(MainActivity.this, "文件已经存在，将覆盖之前解密的文件！！", Toast.LENGTH_LONG).show();
                File new_path = new File(SDcardPath + decryptedName+"-bak");
                decrypteddatabaseFile.renameTo(new_path);
            }
            //deleteDatabase(SDcardPath + decryptedName);

            //连接到解密后的数据库，并设置密码为空
            database.rawExecSQL(String.format("ATTACH DATABASE '%s' as "+ decryptedName.split("\\.")[0] +" KEY '';", decrypteddatabaseFile.getAbsolutePath()));
            database.rawExecSQL("SELECT sqlcipher_export('"+ decryptedName.split("\\.")[0] +"');");
            database.rawExecSQL("DETACH DATABASE "+ decryptedName.split("\\.")[0] +";");

            SQLiteDatabase decrypteddatabase = SQLiteDatabase.openOrCreateDatabase(decrypteddatabaseFile, "", null,hook);
            //decrypteddatabase.setVersion(database.getVersion());
            decrypteddatabase.close();

            database.close();
`

**Comment by developernotes** [comment]
Hi @7763sea,

What version is reported on Windows when you run `PRAGMA cipher_version;`? It's not clear from your original post, but it appears you may be using a newer version of SQLCipher on Windows compared to the version of SQLCipher for Android (3.5.9 in the post above which is not the latest). You may wish to read about the compatibility notes we published with our latest SQLCipher 4 release [here](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/). Please keep in mind that we use GitHub Issues for reporting defects to the software library itself. If you have specific questions regarding SQLCipher otherwise, we ask that you direct those to our public [SQLCipher community discuss site](https://discuss.zetetic.net/c/sqlcipher).
