### ISSUE TITLE
update sqlcipher 3.5.9 to sqlcipher 4.0.0 crash

### ISSUE THREAD

**Issue by koukoucai** [sqlcipher/android-database-sqlcipher#410]
### Expected Behavior
no crash
### Actual Behavior
crash   net.sqlcipher.database.SQLException: file is not a database;
### Steps to Reproduce
I use greendao-encryption:2.2.0 and android-database-sqlcipher:3.5.9 to make an encrypted database.
Then I update greendao to3.2.2 and sqlcipher to 4.0.0 to open the encrypted database.

SQLCipher for Android version:

sqlcipher4.0.0 

How can I resolve this problem.

**Comment by developernotes** [comment]
Hi @koukoucai 

With the [release of SQLCipher 4.0.0](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283) (and the latest being [4.0.1](https://www.zetetic.net/blog/2018/12/18/sqlcipher-401-release/)), many new performance and security enhancements were added. However, the introduction of new default algorithms, increased KDF iterations and a larger page size means that SQLCipher 4 will not open older databases by default.

Please reviewing the [Upgrading to SQLCipher 4](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283) guidance to allow your application to upgrade the databases, or operate in a compatibility mode.
