### ISSUE TITLE
Inserts are very slow on android 7.x with sqlcipher 4.0.1 

### ISSUE THREAD

**Issue by mpelc87** [sqlcipher/android-database-sqlcipher#411]
Hi,

I have an issue with performance of sqlcipher 4.0.1 on Android 7.x
Inserts of big amounts of records in one transactions are ~10 times slower on sqlcipher 4.0.1 then on 3.5.9

Here is my sample app I'm using to measure performance:

`class MainActivity : AppCompatActivity() {
    var database: SQLiteDatabase? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        initSqlCipher()
        createSchema()
        insert()
    }

    fun initSqlCipher() {
        SQLiteDatabase.loadLibs(this)
        val databaseFile = getDatabasePath("demo.db")
        databaseFile.mkdirs()
        databaseFile.delete()

        database = SQLiteDatabase.openOrCreateDatabase(databaseFile, "test123", null)
    }

    private fun insert() {
        val startTime= System.currentTimeMillis()

        database?.execSQL("begin;")
        (1..10000).forEach {
            database?.execSQL("insert into some_table(name, surname) values(?, ?)",
                arrayOf<Any>("one for the money", "two for the show"))

        }
        database?.execSQL("commit;")

        Log.e("SchemaLog", "Inserted in: ${System.currentTimeMillis() - startTime} ms")
    }

    fun createSchema() {
        val startTime= System.currentTimeMillis()

        database?.execSQL("""CREATE TABLE some_table (
                name TEXT,
                surname TEXT)""".trimIndent())

        Log.e("SchemaLog", "Schema created in: ${System.currentTimeMillis() - startTime} ms")
    }
}`

**Comment by developernotes** [comment]
Hi @mpelc87,

I've integrated your test scenario into the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) [here](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/src/main/java/net/zetetic/tests/LoopingInsertTest.java). I ran the same test using the 3.5.9 library 10 times which averaged 393 milliseconds, whereas the 4.0.1 library averaged 373 milliseconds. Would you try running the test yourself and report your findings?

**Comment by raiym** [comment]
@mpelc87 which device you use for tests? 
In my case 4.0.1 works fine on Pixel 2, but takes really long time on Nexus 6P on both Android 8.1 and 7.1.2

**Comment by sjlombardo** [comment]
@raiym - can you try updating to SQLCipher 4.0.1 but then set the compatibility settings (https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283) to use SQLCipher 3 defaults, via `PRAGMA cipher_compatibility = 3;` and let us know the results?

**Comment by mpelc87** [comment]
@developernotes I run your test today and I had times similar to yours. Also my example worked ok today. Its really weird... It looks like sometimes it works really slow, sometimes its fast in that case.
@raiym I'm using simulator with x86 image of android 7.1.1 and also device samsung galaxy s6 with android 7.0. 
Despite that the test and sample code works ok our app still works really slow.
I was debugging it and its using sqLiteStatement.executeInsert() for inserting
I will debug it more tomorrow.
@sjlombardo it looks like nice workaround. I will also try that tomorrow.

**Comment by raiym** [comment]
@sjlombardo did it with the same result. Slower, compared to 3.5.9. 
```java
    @Override
    public void postKey(SQLiteDatabase sqLiteDatabase) {
        Log.d(TAG, "Entering postKey()");
        sqLiteDatabase.rawQuery("PRAGMA cipher_compatibility = 3;", new String[]{});
    }
```

**Comment by raiym** [comment]
@mpelc87 could you be so kind and post same tests for 3.5.9

**Comment by mpelc87** [comment]
On 3.5.9 insert time grows linearly more or less

Here are results of the same tests for 3.5.9
device samsung galaxy s6 android 7.0:

> 10000 records with payload of length: 296 inserted in: 630 ms
10000 records with payload of length: 297 inserted in: 616 ms
10000 records with payload of length: 298 inserted in: 616 ms
10000 records with payload of length: 299 inserted in: 628 ms
10000 records with payload of length: 300 inserted in: 624 ms
10000 records with payload of length: 301 inserted in: 630 ms
10000 records with payload of length: 302 inserted in: 633 ms
10000 records with payload of length: 303 inserted in: 620 ms
10000 records with payload of length: 304 inserted in: 628 ms

simulator android 7.1.1 x86_64:

> 10000 records with payload of length: 296 inserted in: 399 ms
10000 records with payload of length: 297 inserted in: 395 ms
10000 records with payload of length: 298 inserted in: 394 ms
10000 records with payload of length: 299 inserted in: 407 ms
10000 records with payload of length: 300 inserted in: 386 ms
10000 records with payload of length: 301 inserted in: 437 ms
10000 records with payload of length: 302 inserted in: 396 ms
10000 records with payload of length: 303 inserted in: 396 ms
10000 records with payload of length: 304 inserted in: 389 ms
10000 records with payload of length: 305 inserted in: 389 ms

**Comment by raiym** [comment]
@mpelc87 thank you very much. 
It helps a lot

**Comment by TheNephilim88** [comment]
The issue is not limited to inserts. Same issue happens for SELECTS.

3.5.9 is about 10x faster in SELECTing many data.

Even with compatibility mode or manually set cipher defaults to the ones on v3.x

**Comment by TheNephilim88** [comment]
Okay, not 10 times fast, but here are my results comparing v3.5.9 vs v4.0.1

v4.0.1: 13551 ms
v3.5.9: 2319ms

**Comment by developernotes** [comment]
Hi @TheNephilim88 

Thanks for offering up a timing report. It would be helpful to understand the size of the database, the exact query you were performing, and how much data was being retrieved. Were you timing just the cursor retrieval of the data? Would you mind posting some additional details about your scenario?

**Comment by developernotes** [comment]
Hi @mpelc87

Would you try disabling the memory wiping feature that was added in 4.0.0 and run your scenario(s) again? You can do this by executing the following command:

```
database.execSQL("PRAGMA cipher_memory_security = OFF;");
```

We look forward to hearing your results.

**Comment by TheNephilim88** [comment]
@developernotes 
Sure, my data are separated into multiple tables. When loading those data (yes I measured only data reading/cursor retrieval) I do load all at once, but have multiple queries per entry in my main table as further information for them are in referenced via IDs to other tables.
So with reading those data there is a large amount of SELECTs on different tables again and again.

With your question I started investigating and optimizing my queries as they are already quite old and not that intelligent as I would do them today 🤣 


So here are my new measurements, I did multiple runs and added avg here:
App with following settings:
SQLCipher 3.5.9, unoptimized queries: 2702ms
SQLCipher 4.0.1, unoptimized queries: 13136ms
SQLCipher 4.0.1, unoptimized queries, with cipher_memory_security = off: 3584ms

SQLCipher 3.5.9, optimized queries: 1312ms
SQLCipher 4.0.1, optimized queries: 6635ms
SQLCipher 4.0.1, optimized queries, with cipher_memory_security = off: 1583ms



So cipher_memory_security seems to have a huge performance impact. Was it available on 3.5.9 before? Is it safe to turn it off?

**Comment by mpelc87** [comment]
@developernotes 
With that pragma set to OFF, 4.0.1 works as quick (or quicker) as on 3.5.9 

Result on samsung s6 android 7.0
10000 records with payload of length: 296 inserted in: 411 ms
10000 records with payload of length: 297 inserted in: 413 ms
10000 records with payload of length: 298 inserted in: 419 ms
10000 records with payload of length: 299 inserted in: 409 ms
10000 records with payload of length: 300 inserted in: 425 ms
10000 records with payload of length: 301 inserted in: 427 ms
10000 records with payload of length: 302 inserted in: 397 ms
10000 records with payload of length: 303 inserted in: 432 ms
10000 records with payload of length: 304 inserted in: 426 ms
10000 records with payload of length: 305 inserted in: 424 ms

Could you confirm that having PRAGMA cipher_memory_security = OFF;
does not weaken security? (You wrote that its memory wiping feature but I want to be sure because pragma's name looks like some security related feature)

**Comment by developernotes** [comment]
Hello @mpelc87,

Thank you for your patience as we continued our investigation of this report. Given the data loading scenario described above, we have been able to reproduced performance changes at various points utilizing SQLCipher 4.0.1 (with and without memory sanitization enabled), 3.4.2, and the SQLite amalgamation both within the Android platform and a standalone C program. Because the performance characteristics are present in multiple versions and even in the official SQLite release, the observed behavior does not necessarily indicate a regression in SQLCipher itself. Instead, a combination of new features that introduce additional overhead (i.e. memory security enhancements) combined with older and slower hardware likely reduce performance in absolute terms, making the performance changes more visible and readily apparent.

Given the large volume of data operations that appear to be required to trigger a measurable performance deviation, we're not sure that this would widely affect the most common usage scenarios for the library. For scenarios where large amounts of data must be loaded in bulk it is possible to disable the memory security feature as mentioned earlier in this thread. You can reenable memory security after the completion of your data load. An example of disabling memory wiping is below:

```java
database.execSQL("PRAGMA cipher_memory_security = OFF;");
```

While disabling memory wiping does disable a security feature, and thus reduces overall security, this is a new feature in SQLCipher 4. Thus an application would be no less secure than when running SQLCipher 3 which did not have the feature.

Just to close the loop on this, are there any other scenarios where performance issues have been observed outside of extremely large transactions, or where disabling memory security features has not provided a meaningful improvement in performance?
