### ISSUE TITLE
What is the maximum   data size that  can be migrated from sqlcipher 3.x to 4.x  using PRAGMA cipher_migrate;

### ISSUE THREAD

**Issue by manjunath143** [sqlcipher/android-database-sqlcipher#412]
Before migration data size of data stored in database with sqlcipher 3.x was 1062.117376MB but after migrating to  sqlcipher 4.x data size showing as 1029.341184MB.Is it data being lost while migration ?.Any help would be appreciated .

update : But number of records are showing up same before and after migration .What could be reason to show less size ?

**Comment by developernotes** [comment]
Hello @manjunath143 

There were many changes to SQLCipher core with our [4.0.0 release](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/). Included in those changes was an adjustment to the page size from 1024 to 4096. This means we are generating fewer per page HMAC's to store the same amount of data relative to the 3.x series. However, it is also possible that your previous 3.x database was either fragmented, or contained empty, free pages following database content deletion which would not be present in the 4.x database immediately following the migration.

We utilize GitHub Issues for reporting of defects within the database library itself. If you have other specific questions we would ask that you direct those to our SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
