### ISSUE TITLE
error: unrecognized arguments: --unified-headers during make build

### ISSUE THREAD

**Issue by GillesCrebassa** [sqlcipher/android-database-sqlcipher#414]
### Expected Behavior
full compilation
### Actual Behavior
Error:
> Task :android-database-sqlcipher:buildOpenSSL FAILED
Building libcrypto.a for armeabi
usage: make_standalone_toolchain.py [-h] --arch {arm,arm64,x86,x86_64}
                                    [--api API] [--stl STL] [--force] [-v]
                                    [--package-dir PACKAGE_DIR | --install-dir INSTALL_DIR]
make_standalone_toolchain.py: error: unrecognized arguments: --unified-headers
Error executing make_standalone_toolchain.py for arm

FAILURE: Build failed with an exception.
### Steps to Reproduce
export ANDROID_HOME="YourAndroid/sdk"
export ANDROID_NDK_ROOT="YourAndroid/sdk/ndk-bundle/"

ndk-version  18.1.5063045 | Installed

make init
make build

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
PRAGMA cipher_version;
-bash: PRAGMA: command not found
Version from git (2018-01-12)
SQLCipher for Android version:
Version from git (2018-01-12)

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @GillesCrebassa 

We currently recommending using Android NDK r15c in the [`Build`](https://github.com/sqlcipher/android-database-sqlcipher#building) portion of the README. Please adjust your NDK version and try the build again. Thanks!
