### ISSUE TITLE
Open encrypted database on developer machine

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#416]
I pulled encrypted database from Android device and tried to open database on developer machine most recent with "DB Browser for SQLite". I used the password and page size 1024 (right ?)

I was able to open database, but there are no tables included (but I see it on Android app)

My question: 
How to open such a encrypted database ?
What's the best approach, maybe with command line ?

**Comment by developernotes** [comment]
Hi @hannesa2 

There are many options for management interfaces to SQLCipher databases, please review those [here](https://discuss.zetetic.net/t/management-interfaces-for-sqlcipher-databases/121).
