### ISSUE TITLE
New feature: accept db key as byte array 

### ISSUE THREAD

**Issue by iskugor** [sqlcipher/android-database-sqlcipher#417]
### Expected Behavior

I think it makes sense that Android database sqlcipher accepts byte array as password because we sometimes have password as byte array. If we do so, we have to convert byte array to char array and then this library then converts it back to byte array: https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2521

Instead of unnecessary complication, make "openDatabase" method accept byte array:
```
public static SQLiteDatabase openDatabase(String path, byte[] password, CursorFactory factory, int flags, SQLiteDatabaseHook hook) {
    ...
  }
```

### Actual Behavior

Android database sqlcipher only accepts "String" or "char[]" password
https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L1084

https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L1106

**SQLCipher for Android version**: 4.0.1

**Comment by developernotes** [comment]
Hello @iskugor 

Thanks for the suggestion, we agree this would be a helpful interface to expose. I've recently pushed up [support](https://github.com/sqlcipher/android-database-sqlcipher/commit/cd6fed5387d578a9caf95a83f99c2478503c1958) for this. Thanks!

**Comment by iskugor** [comment]
@developernotes cool, thanks!

**Comment by developernotes** [comment]
Hi @iskugor,

We will include this in the next public release of SQLCipher for Android.
