### ISSUE TITLE
Usage of cwac-saferoom makes an error line in logcat on every db open

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#419]
https://github.com/sqlcipher/android-database-sqlcipher/blob/666e050ae8ef0a12fc151a873fe9e690335230fd/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2578

We use a fork of https://github.com/commonsguy/cwac-saferoom, and open a db makes _every time_ an **error** line in **logcat**. This is from technical perspective not critical, because cwac-saferoom tries to open db, and when it fails, it thinks to know it's encrypted.

![image](https://user-images.githubusercontent.com/3314607/52916445-d12d1800-32df-11e9-8aab-d37b03ace95a.png)

So far , so good. But this is not very trustfull, especially for people who don't know this behaviour and only see in Crashlytics this errors in logcat.

### But I want to get rid of this error line !

One idea, is to convert `SQLiteDatabase.java` into Kotlin and introduce a default param for silent open a `SQLiteDatabase.openDatabase()`

Or what do you think, or what's your idea. Any chance, to get such a PR merged ?

**Comment by developernotes** [comment]
Hi @hannesa2 

This issue has been [addressed](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2653-L2657) in our master branch and will be incorporated in the next public release of SQLCipher. Thanks!
