### ISSUE TITLE
Usage of cwac-saferoom makes an error line in logcat on every db open #2

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#420]
https://github.com/sqlcipher/android-database-sqlcipher/blob/cd6fed5387d578a9caf95a83f99c2478503c1958/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2653-L2657

Thank you, what's about a warning, to reduce nevousity for other developers ?

Btw, when you lock https://github.com/sqlcipher/android-database-sqlcipher/issues/419
![image](https://user-images.githubusercontent.com/3314607/52970985-0dcb4300-33b6-11e9-9d6e-ac7db86d3960.png)

you will get more issues

**Comment by developernotes** [comment]
Hi @hannesa2 

You will still receive the exception, which is intentional when the database fails to access the `sqlite_master` table after being keyed, however it will not write the exception to logcat in a release build. We tend to lock Github issues after closing them due to receiving random "drive-by" posts from users who choose not to open a separate ticket. Sorry for any confusion.

**Comment by hannesa2** [comment]
Does your suggested [solution](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2653-L2657) solves this too ?

![image](https://user-images.githubusercontent.com/3314607/53416452-d96a0f00-39d3-11e9-8f29-8e89eec1701d.png)

We see tons of such entries in fabric.io unfortunatelly it reduced the trust of other developers and QA. It wouild be nice, if we could get rid of such messages early

**Comment by developernotes** [comment]
Hello @hannesa2 

The fix that was applied prevents logging of the exception _within_ the library when the library is not able to access the database. The exception is still thrown, so another library or application using SQLCipher for Android may log it. This fix will be included in our next public release, however we do not have a specific date for the release yet.

**Comment by hannesa2** [comment]
Please I want to have a new version without this error logging **soon**, and additional I vote in debug-mode a warning or info `Log.i()` instead of an error.

Btw, build my own lib https://github.com/sqlcipher/android-database-sqlcipher/issues/423 with Travis was not successful because of the way you build native code is not really Android style and I spent too much time by solving crashes and errors with this lib

**Comment by developernotes** [comment]
Hi @hannesa2 

When SQLCipher for Android has been released, we will publish an announcement [here](https://discuss.zetetic.net/c/sqlcipher/updates), you are welcome to subscribe if you wish to receive email notifications.

I'm sorry to hear you experienced an issue building the software. If you would like to report a specific problem, please feel free to open a new GitHub issue. Thanks!
