### ISSUE TITLE
libsqlcipher.so has bad ELF magic

### ISSUE THREAD

**Issue by ashishdimi09** [sqlcipher/android-database-sqlcipher#422]
We are using 'net.zetetic:android-database-sqlcipher:4.0.1@aar' for some devices getting below error :

java.lang.UnsatisfiedLinkError: dlopen failed: "/mnt/asec/com.example.test/lib/libsqlcipher.so" has bad ELF magic
at java.lang.Runtime.loadLibrary()(Runtime.java:364)
at java.lang.System.loadLibrary()(System.java:526)
at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries()(null:-1)
at net.sqlcipher.database.SQLiteDatabase.loadLibs()(null:-1)
at net.sqlcipher.database.SQLiteDatabase.loadLibs()(null:-1)
at net.sqlcipher.database.SQLiteDatabase.loadLibs()(null:-1)
at com.example.MYApplication.onCreate()(null:-1)
at android.app.Instrumentation.callApplicationOnCreate()(Instrumentation.java:1014)
at android.app.ActivityThread.handleBindApplication()(ActivityThread.java:4747)
at android.app.ActivityThread.access$1500()(ActivityThread.java:166)
at android.app.ActivityThread$H.handleMessage()(ActivityThread.java:1343)
at android.os.Handler.dispatchMessage()(Handler.java:102)
at android.os.Looper.loop()(Looper.java:136)
at android.app.ActivityThread.main()(ActivityThread.java:5584)
at java.lang.reflect.Method.invokeNative()(Method.java:-2)
at java.lang.reflect.Method.invoke()(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main()(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main()(NativeStart.java:-2)

Please help me to resolve this issue.

**Comment by ashishdimi09** [comment]
I have raised the issue to android-database-sqlcipher
https://github.com/sqlcipher/android-database-sqlcipher/issues/422
so closing issue from here.

**Comment by ashishdimi09** [comment]
@developernotes Can you please help me to resolve this issue?

**Comment by developernotes** [comment]
Hi @ashishdimi09 

What devices are you experiencing that error on? What CPU architectures does your application bundle support for?

**Comment by ashishdimi09** [comment]
Hi @developernotes 
Please check the below devices info
[Samsung GT-I9060I](https://www.gsmarena.com/samsung_galaxy_grand_neo-5958.php) - ( Android 4.4.4 ) - Quad-core 1.2 GHz Cortex-A7 
[Tango Mobicel](https://www.hi-online.co.za/pdp/mobicel-tango/_/A-270085AADP9) - ( Android 7.0 ) - Quad core 1.3 GHz

**Comment by developernotes** [comment]
Hi @ashishdimi09 

Would you try running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on those devices and report back the behavior?

**Comment by ashishdimi09** [comment]
Hi Nick,

Sorry for late response. I don't have those particular devices with me (its user's device) but I have tried "Samsung SGH-M919 (Galaxy S4) & version 4.4.4)" not getting any issue.
I am trying... Need some more time.

**Comment by developernotes** [comment]
Hello @ashishdimi09 

Thank you, we look forward to hearing your results.

**Comment by ashishdimi09** [comment]
Hi @developernotes 

Please check the below user's device logs

> ava.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.example.banking-bq9lRcJn_HkUafgLSilYZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.banking-bq9lRcJn_HkUafgLSilYZQ==/lib/**arm64**, /data/app/com.example.banking-bq9lRcJn_HkUafgLSilYZQ==/base.apk!/lib/**arm64-v8a**, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libsqlcipher.so".



One more, i am trying to run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests), while building it giving below error

> error: no suitable method found for getWritableDatabase(byte[])
> method SQLiteOpenHelper.getWritableDatabase(String) is not applicable
> (argument mismatch; byte[] cannot be converted to String)
> method SQLiteOpenHelper.getWritableDatabase(char[]) is not applicable
> (argument mismatch; byte[] cannot be converted to char[])

> error: no suitable method found for openOrCreateDatabase(String,byte[],<null>)
> method SQLiteDatabase.openOrCreateDatabase(File,String,CursorFactory) is not applicable
> (argument mismatch; String cannot be converted to File)
> method SQLiteDatabase.openOrCreateDatabase(String,String,CursorFactory) is not applicable
> (argument mismatch; byte[] cannot be converted to String)
> method SQLiteDatabase.openOrCreateDatabase(String,char[],CursorFactory) is not applicable
> (argument mismatch; byte[] cannot be converted to char[])

**Comment by developernotes** [comment]
Hi @ashishdimi09 

I just push a new commit to the test suite which will include a local snapshot of the AAR which will allow those tests to pass. Would you try it again? Thanks!

**Comment by ashishdimi09** [comment]
Hi @developernotes,

We observed issues in this [devices](https://github.com/sqlcipher/android-database-sqlcipher/issues/422#issuecomment-468153757), so can please suggest how can we run test suite for Android v4.4.4 (API level 19) or v7.0 (API level 24) as in SQLCipher's test suite project having [minSdkVersion 26](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/build.gradle#L8)?

**Comment by developernotes** [comment]
Hi @ashishdimi09,

For your purposes, you should be able to just modify the `minSdkVersion` within build.gradle. Would you try that and let us know your results?

**Comment by ashishdimi09** [comment]
Hi @developernotes,

Please check below issue when i have tried to change the minSdkVersion version within SQLCipher test suite's build.gradle.
https://github.com/sqlcipher/sqlcipher-android-tests/issues/29#issue-420333407

**Comment by developernotes** [comment]
Hello @ashishdimi09 

I just replied to your other ticket with details on why we are moving to a minimum Android SDK of 26, and how you can proceed in testing your devices with the suite. Thanks!

**Comment by developernotes** [comment]
Hello @ashishdimi09 

We have released SQLCipher for Android 4.1.3 which rolls back the `minSdkVersion` requirements, would you give the latest a try and let us know your results? Thanks!

**Comment by ashishdimi09** [comment]
Hi @developernotes 

Need more testing to get the above error with new v4.1.3 release. 
For now, I am closing this ticket if we faced the same or any other issue will contact you.

Thank you so much for your support.

**Comment by developernotes** [comment]
Hi @ashishdimi09 

Great, thank you!
