### ISSUE TITLE
Build library by my own

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#423]
When I follow your way
![image](https://user-images.githubusercontent.com/3314607/53495360-1d2a4a80-3aa0-11e9-8eb8-791627ec6f8c.png)

I run into 

![image](https://user-images.githubusercontent.com/3314607/53495553-71cdc580-3aa0-11e9-90e0-f34cb9d2ce3b.png)

Which NDK you use ? Or is it ready to use NDK 19.1.5304403 ?

**Comment by developernotes** [comment]
Hi @hannesa2 

You will currently need to use Android NDK r15c as documented in the [build section](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283/26?u=developernotes) of the README.
