### ISSUE TITLE
Android crashes

### ISSUE THREAD

**Issue by iskugor** [sqlcipher/android-database-sqlcipher#426]
Hello.

I'm seeing two crashes in Google play store. Unfortunately, I cannot reproduce them on devices I have and therefore I don't know what exactly is causing them. I hope you'll know what going on. :)

It seems they are similar, so I'll just report them as one issue, hope that's not a problem.

First issue happens when app changes database password, second one when app migrates from SQLCipher 3.5.9 to 4.0.1

### Expected Behavior

App should open and execute query without crash.

### Actual Behavior

App crashes with stack trace:

```
net.sqlcipher.database.SQLiteException: 
  at net.sqlcipher.database.SQLiteCompiledSql.native_compile (SQLiteCompiledSql.java)
  at net.sqlcipher.database.SQLiteCompiledSql.compile (SQLiteCompiledSql.java:91)
  at net.sqlcipher.database.SQLiteCompiledSql.<init> (SQLiteCompiledSql.java:64)
  at net.sqlcipher.database.SQLiteProgram.<init> (SQLiteProgram.java:89)
  at net.sqlcipher.database.SQLiteQuery.<init> (SQLiteQuery.java:48)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query (SQLiteDirectCursorDriver.java:60)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory (SQLiteDatabase.java:1954)
  at net.sqlcipher.database.SQLiteDatabase.rawQuery (SQLiteDatabase.java:1840)
  at net.sqlcipher.database.SQLiteDatabase.keyDatabase (SQLiteDatabase.java:2571)
  at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal (SQLiteDatabase.java:2502)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase (SQLiteDatabase.java:1204)
  at net.sqlcipher.database.SQLiteDatabase.openDatabase (SQLiteDatabase.java:1144)
  at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase (SQLiteDatabase.java:1288)
```

### Steps to Reproduce

As I said, I cannot reproduce issues, but here's part of code that makes app crash:

```
SQLiteDatabase.loadLibs(context);
File databaseFile = context.getDatabasePath(DATABASE_NAME);
if (databaseFile.exists()) {
    SQLiteDatabase database = SQLiteDatabase.openOrCreateDatabase(databaseFile.getPath(),
            Arrays.copyOf(oldPassword, oldPassword.length), null);
    database.changePassword(Arrays.copyOf(newPassword, newPassword.length));
    database.close();
}
```

```
SQLiteDatabase.loadLibs(context);
File databaseFile = context.getDatabasePath(DATABASE_NAME);
if (databaseFile.exists()) {
    SQLiteDatabase database = SQLiteDatabase.openOrCreateDatabase(databaseFile, password,
            null, new SQLiteDatabaseHook() {
        @Override
        public void preKey(SQLiteDatabase database) {

        }

        @Override
        public void postKey(SQLiteDatabase database) {
            database.rawExecSQL("PRAGMA cipher_migrate;");
        }
    });

    database.close();
}
```

These two parts of code execute when Application is created and I use flag to check if app has been updated with new password and if it's migrated to SQLCipher 4 (so they are not executed twice).

I'm sure old password is correct, so how can this fail on just some devices?

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

4.0.1

SQLCipher for Android version:

4.0.1

**Comment by developernotes** [comment]
Hi @iskugor 

What is the order of the events? Do you attempt to change the password first, then migrate? If so, that is likely the issue if the database file format was originally created with SQLCipher 3.x and the application is now being built with SQLCipher 4.x. You should first open the database and perform your migration with `PRAGMA cipher_migrate`, once that completes successfully, then you can change the password.

**Comment by brodybits** [comment]
I would like to add an extra comment that crash seems to be due to an uncaught exception (`SQLiteException`). I would highly recommend that the application code catches this kind of exception, logs the information, and notifies the user if needed. (I think this point should be emphasized in the documentation.) You may want to consider a tool such as sentry.io to report this kind of an error with some more detailed information.

I would recommend that you follow the comments by @developernotes.

**Comment by iskugor** [comment]
@developernotes good point, I had those in correct order, but recent change got it in wrong order. However, it's weird I couldn't reproduce issue (not even on same device from crash logs). I'll change it to correct order and see if I still get those crash logs. Thanks a lot!

@brodybits thanks, but unfortunately I cannot use sentry.io or any similar solutions due to privacy requirements.
