### ISSUE TITLE
DatabaseObjectNotClosedException with com.commonsware.cwac.saferoom

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#427]
I run into `DatabaseObjectNotClosedException` during an insert. But I don't know the reason, so a search over SO gave me the hint to close the database in `onDestroy()` but Kotlin has no such methods

But record was inserted and app doesn't crash.
This error logging without serious (?) reason is a bad behavior https://github.com/sqlcipher/android-database-sqlcipher/issues/420

### Steps to Reproduce

SQLCipher version `PRAGMA cipher_migrate;`

SQLCipher for Android version: `api "net.zetetic:android-database-sqlcipher:4.0.1@aar"`

> E/Database: close() was never explicitly called on database '/data/user/0/info.xxx.admin.debug/databases/mx.db' 
>     net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
>         at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:2489)
>         at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1203)
>         at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1267)
>         at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
>         at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:158)
>         at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:80)
>         at androidx.room.RoomDatabase.query(RoomDatabase.java:256)
>         at androidx.room.util.DBUtil.query(DBUtil.java:54)
>         at info.xxx.room.CapturedLatLngDao_Impl$5.call(CapturedLatLngDao_Impl.java:234)

Any idea how to get rid of it ?

**Comment by developernotes** [comment]
Hello @hannesa2,

This _may_ be an issue within the SafeRoom wrapper. Do you experience with only SQLCipher for Android (i.e., without using SafeRoom)? In case @commonsguy does not see this, you might want to raise the issue in the [SafeRoom](https://github.com/commonsguy/cwac-saferoom) repo.

**Comment by commonsguy** [comment]
There is no problem, strictly speaking. Room does not close the database automatically. This is fairly typical in Android app development, as we do not necessarily know a good time to close a database.

If you are sure of a good time to close the database, feel free to close it by calling `close()` on the `RoomDatabase`.

This is not an issue with either SQLCipher for Android or SafeRoom.

**Comment by hannesa2** [comment]
When I look into code there is the same behavior like on other places. 

![image](https://user-images.githubusercontent.com/3314607/54176343-c3a62080-448e-11e9-821a-a64463525706.png)

I like to see no error at all, when it works properly. Even in debug.  
eg https://discuss.zetetic.net/t/android-4-0-2-release/3467

I like to see a new release with this log reducing too.
Additional I vote for a warning or info __Log.i()__ in __DEBUG__ instead of an error.

Thank you

**Comment by developernotes** [comment]
Hello @hannesa2 

>I like to see no error at all, when it works properly. 
>Additional I vote for a warning or info Log.i() in DEBUG instead of an error.

In the context of a debug build, reporting that a native resource has not be closed prior to the garbage collector performing a clean up is appropriate. We may revisit this at a later date due to changes in upstream Java versions. You are always welcome to fork the source if your needs dictate otherwise.
