### ISSUE TITLE
Help wanted for build library by my own on Travis

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#428]
I want to get rid of error logs https://github.com/sqlcipher/android-database-sqlcipher/issues/420 so I want to build my own lib #423 with necessary changes 
![image](https://user-images.githubusercontent.com/3314607/54158619-2ece0380-444b-11e9-9411-e1aa3aa0b4b8.png)

with this [branch](https://github.com/hannesa2/android-database-sqlcipher/tree/trust) and a log on [Travis](https://travis-ci.org/hannesa2/android-database-sqlcipher) 

I know, this is more a NDK/Travis issue, but maybe you know what's wrong or you change the way you build this lib with a more recent way to build, to enable others an easier build.

Btw, if you like it, I can make a PR of course too

**Comment by developernotes** [comment]
Hello @hannesa2,

We use GitHub Issues for reporting issues with the SQLCipher for Android library. If you are having specific issues with the build chain, please feel free to report those in detail. If however, you are only looking for assistance with a specific continuous integration system such as Travis and SQLCipher for Android, you might consider posting to the SQLCipher community forum [here](https://discuss.zetetic.net/c/sqlcipher) instead, or reaching out to the Travis CI community [here](https://travis-ci.community/).
