### ISSUE TITLE
file is not a database from JobService

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#429]
As you mention, I want to reduce useless and spamming logcat errors.
But why ?

### Actual Behavior

When I start app with `JobService`I run into this

> Fatal Exception: java.lang.RuntimeExceptionnet.sqlcipher.database.SQLiteException: file is not a > database: , while compiling: select count(*) from sqlite_master;

This happen on several apps, and to be honest I don't know why.
Normal usage of app works (except on spamming logcat error entries !) 

Maybe you can explain it ?
Or what should I observe to get the main reason ?

Thank you !

### Steps to Reproduce

When I start app with `JobService`

SQLCipher version `"PRAGMA cipher_migrate;"`

SQLCipher for Android version: 4.0.1

### Crashlytics:

![image](https://user-images.githubusercontent.com/3314607/54180455-fe628580-449b-11e9-89ce-c0c813d7d408.png)

**Comment by developernotes** [comment]
Hello @hannesa2,

This issue contains insufficient information to narrow down the root cause. Ultimately, you are receiving a `SQLiteException` because you are attempting to use SQLCipher to open a file, possibly a SQLCipher database, and the library is unable to read a `sqlite_master` table after providing the key material. Scenarios that could cause this include, but are not limited to: an invalid password, corrupt database file, and a plain-text database file attempting to be opened with a password. This is more than likely an application logic issue, we would recommend further debugging of the client application for further diagnosis.

**Comment by hannesa2** [comment]
> an invalid password, corrupt database file, and a plain-text database file attempting to be opened with a password

It's not ~~invalid password~~, ~~a plain-text database file attempting to be opened with a password~~, that why it looks like a _corrupt database_ file, which is the worst scenario

Maybe it's related to https://github.com/sqlcipher/android-database-sqlcipher/issues/427 and https://github.com/maskarade/Android-Orma/issues/410

> we would recommend further debugging of the client application for further diagnosis.

I follow your suggestion, but it's not easy when I can't reproduce it, and I see it only in Crashlytics
If I find it, I let you know

**Comment by hannesa2** [comment]
Hey 
<img width="78" alt="image" src="https://user-images.githubusercontent.com/3314607/55260320-5bb25100-5268-11e9-8b79-18b49c833898.png">

issue still exists

**Comment by sjlombardo** [comment]
Hi @hannesa2 - while we appreciate that this issue still exists, as @developernotes mentioned earlier there is not enough information to determine what the problem is (or even if this problem is truly in SQLCipher). Since it is not reproducible there isn't anything else we can do. If you can provide additional details or code to reliably reproduce the issue we can consider looking into it further. Otherwise we're going to close this issue.

**Comment by ravisarma** [comment]
@sjlombardo We have been seeing similar issues that occurs to less than 1% of our users that got migrated to 4.0.1. This is the work-flow - 

1. App upgrades to the version with sqlcipher 4.0.1
2. Sqlcipher cipher_migrate goes through fine, DB is open & queries work.
3. App gets killed, launched after sometime. The DB open fails with "file is not a database"
4. Crashlytics logs confirm that the DB Password has not changed. 

What could be the reasons for corruption during an upgrade ? We were thinking of a another db instance open & writing to database while the upgrade is happening - but we have enough synchronizations in place to prevent that. Any insights from you would be helpful. Thanks.

**Comment by developernotes** [comment]
Hi @ravisarma,

A few additional questions as a follow-up:

- What devices are you seeing the issue reported on?
- What is the result code of your `PRAGMA cipher_migrate` command?
- What version of SQLCipher for Android are you migrating from?
- What Android OS does the crash occur on?
- In the scenario where the database fails to open (post crash), are you able to open it when using `PRAGMA cipher_compatibility = 3;`?

**Comment by ravisarma** [comment]
Thanks for the quick response

1. All sorts of android devices. But more ferquently (>3%) in S9, S10, Pixels. 
2. Result is 0 - successfull. 
3. Migrating from 3.5.9
4. 46% on Android 9.  30% on Android 8.
5. We are not able to reproduce this at will. . Do you recommend us to retry with compatibility in this case ? 

<img width="1152" alt="Screen Shot 2019-05-24 at 3 41 22 PM" src="https://user-images.githubusercontent.com/3171776/58352706-66d5c780-7e3a-11e9-9520-2490a29483c4.png">

**Comment by developernotes** [comment]
Hi @ravisarma,

>We are not able to reproduce this at will. . Do you recommend us to retry with compatibility in this case ?

It would be interesting to verify if you are able to access the database with the compatibility mode set to `3` only when it fails to open the database.

**Comment by ravisarma** [comment]
We would include that retry in our debug builds once we reproduce the issue. Are there any other ways  why we might see the above issue  (other than password being wrong) ?

**Comment by ravisarma** [comment]
We were able to reproduce, the db password is the same as it was before migration. We tried opening in compatibility mode - that failed. I have attached the DB file here and the password that was used to open it. Is there anything you can glean from it ?

**Comment by ravisarma** [comment]
@hannesa2  Are you still seeing the issue reported in crashlytics ?

**Comment by iskugor** [comment]
@developernotes I guess new password function that accepts parameter as byte array wouldn't have this issue? It just takes bytes as they are?

**Comment by developernotes** [comment]
Hello @iskugor,

>I guess new password function that accepts parameter as byte array wouldn't have this issue? It just takes bytes as they are?

No, not all random byte data is valid UTF-8 content. We will be posting additional guidance regarding this soon. Our upcoming release will also assist in this.

**Comment by iskugor** [comment]
@developernotes ok, thanks for you answer. Will that guidance be available within day, or weeks ... ? :)
That would help me plan some things. Thanks!

**Comment by hannesa2** [comment]
@ravisarma sadly yes, the issue still exists

**Comment by sjlombardo** [comment]
@hannesa2 Is your application using a random array of data converted to a string as key material?

**Comment by hannesa2** [comment]
Nope, we use a stable device id and we observe via crashlytics, if it changes or not. It doesn't change !

**Comment by developernotes** [comment]
Hi @iskugor 

We have just published our guidance on [using random values as SQLCipher keys](https://discuss.zetetic.net/t/technical-guidance-using-random-values-as-sqlcipher-keys/3715).

**Comment by iskugor** [comment]
@developernotes cool, thanks!
