### ISSUE TITLE
follow up: DatabaseObjectNotClosedException with com.commonsware.cwac.saferoom

### ISSUE THREAD

**Issue by hannesa2** [sqlcipher/android-database-sqlcipher#430]
This is an additional message to locked https://github.com/sqlcipher/android-database-sqlcipher/issues/427

> In the context of a debug build, reporting that a native resource has not be closed prior to the garbage collector performing a clean up is appropriate

Appropriate : yes, but not as error when an other person wrote in same issue 
> There is no problem, strictly speaking. Room does not close the database automatically. This is fairly typical in Android app development, as we do not necessarily know a good time to close a database.

Btw, this lib or/and (?) SafeRoom loose reputation, when parts are working properly but you see in logcat al lot of error spam.
A company, I working for, decided to get rid of the crypted SQLite SafeRoom+sqlcipher because of this error spam

**Comment by sjlombardo** [comment]
Hello @hannesa2 - As both @developernotes and @commonsguy mentioned on #427 there is no problem here. The library does not close down the connection for you, the application needs to do that explicitly based on appropriate application logic. If there are native resources still allocated at the point the finalizer is run, then it is a problem that needs to be drawn to the developer's attention. That is the purpose of the log.

With respect to the volume of logcat messages, we're sorry to hear you made that decision. As previously mentioned elsewhere, the next release of SQLCipher for Android will significantly reduce the volume of log messages in release builds. You and the company you are working for are quite welcome to re-evaluate at that time. 

Given that this is already addressed in our development pipeline and we have made it clear the change is coming, we would respectfully request that you do not open or log any further duplicate tickets on this subject.
