### ISSUE TITLE
Sqlcipher v4.0.x has compatibility issues on Android 5.1.1

### ISSUE THREAD

**Issue by kexdev** [sqlcipher/android-database-sqlcipher#431]
We found that Sqlcipher v4.0.x is very slow to query on Android 5.1.1. Compared with Sqlcipher v3.5.9, it runs very slowly.
In addition, Sqlcipher v4.0.x initialization time has increased a lot, can be perceived on all platforms.
Thank you very much!

**Comment by developernotes** [comment]
Hello @kexdev,

This issue has been discussed in the #411 report, our recommendations can be found [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/411#issuecomment-454191235). Would you give that a try and let us know your results? Thanks!

**Comment by sjlombardo** [comment]
@kexdev with respect to the initialization time issue you mentioned, if you are opening connections repeatedly, that would be causing repeated key deviation. In addition to the links referenced above, please consult the standard SQLCipher performance optimization guidance here, and try to use long-running connections wherever possible:

https://discuss.zetetic.net/t/sqlcipher-performance-optimization/14

**Comment by kexdev** [comment]
It can be solved in this way.
Thanks.
