### ISSUE TITLE
Error: file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by vithunIROID** [sqlcipher/android-database-sqlcipher#435]
Same code is working on android version less than PIE, for PIE its showing the  error:
file is not a database: , while compiling: select count(*) from sqlite_master;
Am using the same KEY and Database, I had pulled the database from the file explorer and opened with Sqlite Browser, it is opening with the key which  i have been using.
My App crashes of PIE version and there is No crash of Other Android Flavors.  

Please help me to resolve this issue.

**Comment by sjlombardo** [comment]
@vithunIROID As I requested in the other issue, we need you to provide a complete reproducible test case for this. As noted in the other issue you were on, there is not enough information to determine what is happening here based on your report.

**Comment by sgtcoolguy** [comment]
I'm seeing the same issue here. My emulator is an android-28, google_apis, x86 emulator.

The exact same code works fine on an android-23, google_apis_ x86 emulator.

The effective code here is:

```java
File dbPath = getDatabasePath("int_test.db");
SQLiteDatabase db = SQLiteDatabase.openOrCreateDatabase(dbPath, "some-made-up-password", null);
```

Results in:
```
 Error: file is not a database: , while compiling: select count(*) from sqlite_master;
        net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1968)
        net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1854)
        net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2594)
        net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2525)

```

**Comment by developernotes** [comment]
Hi @sgtcoolguy 

Out of curiosity, what does `dbPath.getParentFile().exists()` return in your scenario?

**Comment by sgtcoolguy** [comment]
It returns true (and I had modified the code above before to try `dbPath.mkdirs()` before calling `openOrCreateDatabase` and it still failed)

**Comment by sgtcoolguy** [comment]
ok, I think the sample I saw here https://www.zetetic.net/sqlcipher/sqlcipher-for-android/ made me blindly make a mistake here in trying to workaround the issue. Your hunch was correct, the first time the directory tree was not created, and then when I tried to "fix it" it inadvertently created the file itself as a directory too.

I had tried with `dbPath.mkdirs()` which created the directory tree for me, but also created the database file as a directory! So really the fix here is to do:
```java
File dbPath = getDatabasePath("int_test.db");
dbPath.getParentFile().mkdirs();
SQLiteDatabase db = SQLiteDatabase.openOrCreateDatabase(dbPath, "some-made-up-password", null);
```

**Comment by developernotes** [comment]
Hi @sgtcoolguy 

Great, we are happy to hear you were able to resolve the issue! Ironically, `dbPath` will report `isDirectory()` as `true` after the call to `dbPath.mkdirs()`, however immediately after the call to `SQLiteDatabase.openOrCreateDatabase(...)`, invoking `dbPath.isDirectory()` returns `false`.
