### ISSUE TITLE
yieldIfContendedSafely would commit the transaction

### ISSUE THREAD

**Issue by hshahdoost** [sqlcipher/android-database-sqlcipher#436]
### Expected Behavior
The method `yieldIfContendedSafely` as mentioned in the [android docs](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase#yieldIfContendedSafely()) should allow us to temporarily pause the transaction and allow other queries happen, this should not cause any problem for the running transaction it self, and the transaction shall work after the pause normally as before.

### Actual Behavior
In the **SQLCipher** version of this method, calling `yieldIfContendedSafely` would commit all the changes to that point and creates a new transaction which has nothing to do with the previous changes. So technically after using this method in sqlcipher you can no longer rollback the changes done before  `yieldIfContendedSafely`.

### Steps to Reproduce
Following code is a modified version of android source [SQLiteContentProvider.java](https://android.googlesource.com/platform/packages/providers/CalendarProvider/+/gingerbread/src/com/android/providers/calendar/SQLiteContentProvider.java)
which is suppose to make a bulk insert and then rollback all of the changes but if you try this code with a large enough portion of data and execute queries from another thread in the meantime (since `yieldIfContendedSafely` won't actually start unless there is a queued operation) you can see the that the data would be committed on the database.
```
@Override
public int bulkInsert(Uri uri, ContentValues[] values) {
    int numValues = values.length;
    mDb = mOpenHelper.getWritableDatabase();
    mDb.beginTransaction();
    try {
        for (int i = 0; i < numValues; i++) {
            Uri result = insertInTransaction(uri, values[i]);
            mDb.yieldIfContendedSafely();
        }
    } finally {
        mDb.endTransaction();
    }
    return numValues;
}
```

SQLCipher version (4.1.3)

Also thanks a lot for all your works on the SQLCipher project, it is awesome.

**Comment by developernotes** [comment]
Hello @hshahdoost,

In reviewing the Android documentation for `yieldIfContendedSafely`, it states:  

> Temporarily end the transaction to let other threads run. The transaction is assumed to be successful so far. Do not call setTransactionSuccessful before calling this. When this returns a new transaction will have been created but not marked as successful. 

This contrasts with your comment:

> The method yieldIfContendedSafely as mentioned in the android docs should allow us to temporarily pause the transaction and allow other queries happen, this should not cause any problem for the running transaction it self, and the transaction shall work after the pause normally as before.

The current Android AOSP implementation exists within the `SQLiteSession` class via [`yieldTransaction`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/database/sqlite/SQLiteSession.java#504), where the transaction is [ended](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/database/sqlite/SQLiteSession.java#406) and a new transaction is [initiated](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/database/sqlite/SQLiteSession.java#549). Our [implementation](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L963) also behaves in a similar light.

We do not feel this behavior is inconsistent with the documentation, or the current implementation in Android AOSP.

**Comment by hshahdoost** [comment]
Sorry, My bad, I thought this is a difference in the SQLCipher implementation but it's like that in sqlite too. I wonder why should anyone ever use this method while it destroys the concept of transaction.
