### ISSUE TITLE
Deadlock on SQLiteDatabase/SQLiteOpenHelper

### ISSUE THREAD

**Issue by CreepyMob** [sqlcipher/android-database-sqlcipher#437]
Reached deadlock when start transaction from first thread and close db from second.
If first thread calls `beginTransaction`, SQLiteDatabase invokes lock on internal lock object and if at the next point in time second thread calls `close` which hold monitor of SQLiteOpenHelper.class because SQLiteOpenHelper::close synchronized, `SQLiteOpenHelper::close` under the hood calls `SQLiteDatabase::close` and also locks on internal SQLiteDatabase lock object because transaction also doesn't end. But in the same time transaction now cannot be ended because for end of transaction we need to call `SQLiteOpenHelper::getWritableDatabase::endTransaction` which locks on SQLiteOpenHelper monitor because second thread doesn't end close and also hold SQLiteOpenHelper monitor.

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`): doesn't matter 

SQLCipher for Android version: 4.1.3

**Comment by CreepyMob** [comment]
class SupportSQLiteOpenHelperWrapped(val source: SupportSQLiteOpenHelper) : SupportSQLiteOpenHelper by source {

    private val writableDatabaseLazy: SupportSQLiteDatabaseWrapped by lazy {
        SupportSQLiteDatabaseWrapped(source.writableDatabase)
    }

    override fun getWritableDatabase(): SupportSQLiteDatabase = writableDatabaseLazy

    override fun close() {
        try {
            writableDatabaseLazy.lock.lock()
            source.close()
        } finally {
            writableDatabaseLazy.lock.unlock()
        }
    }
}

class SupportSQLiteDatabaseWrapped(val source: SupportSQLiteDatabase) : SupportSQLiteDatabase by source {

    val lock: ReentrantLock = ReentrantLock(true)

    override fun beginTransaction() {
        lock.lock()
        source.beginTransaction()
    }

    override fun beginTransactionNonExclusive() {
        lock.lock()
        source.beginTransactionNonExclusive()
    }

    override fun beginTransactionWithListener(transactionListener: SQLiteTransactionListener?) {
        lock.lock()
        source.beginTransactionWithListener(transactionListener)
    }

    override fun beginTransactionWithListenerNonExclusive(transactionListener: SQLiteTransactionListener?) {
        lock.lock()
        source.beginTransactionWithListenerNonExclusive(transactionListener)
    }

    override fun endTransaction() {
        try {
            source.endTransaction()
        } finally {
            lock.unlock()
        }
    }
}

class SafeHelperFactoryWrapped(val source: SafeHelperFactory) : SupportSQLiteOpenHelper.Factory {

    override fun create(configuration: SupportSQLiteOpenHelper.Configuration?): SupportSQLiteOpenHelper {
        return SupportSQLiteOpenHelperWrapped(source.create(configuration))
    }
}

**Comment by developernotes** [comment]
Hi @CreepyMob,

Thank you for reaching out. We are currently reviewing your reported issue and will reach out again shortly when we have additional information to share. Thanks!

**Comment by developernotes** [comment]
Hi @CreepyMob,

After reviewing your posted scenario, and your temporary [workaround](https://gist.github.com/CreepyMob/962489974dcc56a8d267690725d082f3), we have decided to take this particular behavior into consideration as we are planning larger modifications to the concurrency support within the library which will be available in a future release of the software.

Does this approach work for you going forward? Thanks!
