### ISSUE TITLE
how to recreate database if encryption key is incorrect?

### ISSUE THREAD

**Issue by ardevd** [sqlcipher/android-database-sqlcipher#440]
I'm playing around with SQLCipher in my Android application and I'm wondering what the recommended way of dealing with lost encryption keys are? Let's say the database encryption key is based on user input and the user would like to change the key. How can I correctly recreate the database with the new encryption key?

**Comment by developernotes** [comment]
Hi @ardevd,

Thank you for your interest in SQLCipher! We utilize GitHub Issues for reporting software defects within the library itself. This type of question is perfectly suitable for our public community SQLCipher discuss site [here](https://discuss.zetetic.net/c/sqlcipher). Please feel free to post this question there. Thanks!
