### ISSUE TITLE
Crash One Plus Device with Android Version 5.0

### ISSUE THREAD

**Issue by sachinchoudhary** [sqlcipher/android-database-sqlcipher#443]
F/libc (12166): Fatal signal 4 (SIGILL), code 1, fault addr 0xa0a88008 in tid 12166 (h.sample:remote)

I/DEBUG ( 239): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG ( 239): Build fingerprint: 'oneplus/bacon/A0001:5.0.2/LRX22G/YNG1TAS2I3:user/release-keys'

I/DEBUG ( 239): Revision: '0'

I/DEBUG ( 239): ABI: 'arm'

I/DEBUG ( 239): pid: 12166, tid: 12166, name: h.sample:remote >>> com.tech.mobile.signalstrength.sample:remote <<<

I/DEBUG ( 239): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xa0a88008

I/DEBUG ( 239): r0 00000002 r1 be88490c r2 00000050 r3 a0b987b4

I/DEBUG ( 239): r4 00000000 r5 ac26edc0 r6 ac26edc0 r7 a23e2a00

I/DEBUG ( 239): r8 00000050 r9 00000010 sl 00000ff0 fp ac247018

I/DEBUG ( 239): ip a0b9580c sp be8848c8 lr a0a81ed8 pc a0a88008 cpsr 200d0010

I/DEBUG ( 239):

I/DEBUG ( 239): backtrace:

I/DEBUG ( 239): #00 pc 000c6008 /data/app/com.tech.mobile.signalstrength.sample-1/lib/arm/libsqlcipher.so

W/h.sample:remote(12166): type=1701 audit(0.0:184): auid=4294967295 uid=10607 gid=10607 ses=4294967295 subj=u:r:untrusted_app:s0 reason="memory violation" sig=4

I/DEBUG ( 239):

I/DEBUG ( 239): Tombstone written to: /data/tombstones/tombstone_03

I/BootReceiver( 776): Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)

E/SharedPreferencesImpl( 776): Couldn't create directory for SharedPreferences file shared_prefs/log_files.xml

**Comment by developernotes** [comment]
Hi @sachinchoudhary 

Unfortunately, this is not enough information to properly debug the issue. Here are some additional questions that would be helpful to analyze your situation:

- What version of SQLCipher for Android are you using?
- What code are you executing that causes this behavior?
- Is this operating an on existing database, or are you creating it?
- Is this database encrypted with SQLCipher, or is it plaintext?
- Do you experience the same issue on other devices/emulators?

**Comment by sachinchoudhary** [comment]
Hello Team,
Thankyou for response.
Please find inline comments for each quires  

- What version of SQLCipher for Android are you using? **[sqlcipher:4.0.1,4.1.3]**
- What code are you executing that causes this behaviour? **We Are using this code inside separate process service(remote service. We just killing and re-starting the service than we observe this crash.)** 
- Is this operating an on existing database, or are you creating it? **[Existing database]**
- Is this database encrypted with SQLCipher, or is it plaintext? **[Encrypted with SQLCipher]**
- Do you experience the same issue on other devices/emulators? **[No, only one device with Android version 5.0.1]**

**Comment by developernotes** [comment]
Hi @sachinchoudhary 

>What code are you executing that causes this behaviour? We Are using this code inside separate process service(remote service. We just killing and re-starting the service than we observe this crash.)

Please provide a code sample that is causing the issue. Are you able to recreate the issue? Possibly using the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by TheNephilim88** [comment]
Same issue happens to some users of mine too. I unfortunately cannot reproduce.
It must happen when loading libraries or when opening database, dont exactly know as I dont have chance to reproduce.

Device of an user that got in contact with me: Coolpad E561_EU, Android 5.1.1 (SDK 22)
