### ISSUE TITLE
Can PRAGMA cipher_migrate cause any issue?

### ISSUE THREAD

**Issue by ashishdimi09** [sqlcipher/android-database-sqlcipher#444]
Hi,

My client reported me the below issue for some devices after using the PRAGMA cipher_migrate. 
I am using 'net.zetetic:android-database-sqlcipher:4.1.3@aar' and in old release build having 3.5.9@aar.

> thread 1 - main:
> net.sqlcipher.database.SQLiteCompiledSql.native_compile()(null:-2)
> net.sqlcipher.database.SQLiteCompiledSql.compile()(null:-1)
> net.sqlcipher.database.SQLiteCompiledSql.<init>()(null:-1)
> net.sqlcipher.database.SQLiteProgram.<init>()(null:-1)
> net.sqlcipher.database.SQLiteQuery.<init>()(null:-1)
> net.sqlcipher.database.SQLiteDirectCursorDriver.query()(null:-1)
> net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory()(null:-1)
> net.sqlcipher.database.SQLiteDatabase.rawQuery()(null:-1)
**> .internal.a.?$?.postKey()(null:-1)**
> net.sqlcipher.database.SQLiteDatabase.keyDatabase()(null:-1)
> net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal()(null:-1)
> net.sqlcipher.database.SQLiteDatabase.openDatabase()(null:-1)
> net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase()(null:-1)
> net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase()(null:-1)
> net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase()(null:-1)
> android.app.Instrumentation.callApplicationOnCreate()(Instrumentation.java:1037)
> android.app.ActivityThread.handleBindApplication()(ActivityThread.java:6496)
> android.app.ActivityThread.access$1800()(ActivityThread.java:229)
> android.app.ActivityThread$H.handleMessage()(ActivityThread.java:1887)
> android.os.Handler.dispatchMessage()(Handler.java:102)
> android.os.Looper.loop()(Looper.java:148)
> android.app.ActivityThread.main()(ActivityThread.java:7406)
> java.lang.reflect.Method.invoke()(Method.java:-2)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()(ZygoteInit.java:1230)
> com.android.internal.os.ZygoteInit.main()(ZygoteInit.java:1120)

This my code 
```
private net.sqlcipher.database.SQLiteOpenHelper getSQLiteOpenHelper(Context context,String dbName,int dbVersion,String dbPassword)
{
		net.sqlcipher.database.SQLiteOpenHelper openHelper=new SQLiteOpenHelper(context,dbName,null,dbVersion,new MySQLiteDatabaseHook())
		{
                   @Override
                    public void onCreate(final SQLiteDatabase db)
		{

		}

                  @Override
                   public void onUpgrade(final SQLiteDatabase db,final int oldVersion,final int newVersion)
		{

		}
		};
	return openHelper;
}

private class MySQLiteDatabaseHook implements SQLiteDatabaseHook
{
	public void preKey(SQLiteDatabase database)
	{

	}

	public void postKey(SQLiteDatabase database)
	{
		Cursor cursor = null;
		try
		{
			cursor = database.rawQuery("PRAGMA cipher_migrate", new String[]{});
			if (cursor != null)
			{
				cursor.moveToFirst();
				try
				{
					String value = cursor.getString(0);
					Log.i(TAG, "MySQLiteDatabaseHook's postKey value : " + value);
				}
				catch (Exception e)
				{
					Log.e(TAG, "Error while getting value in MySQLiteDatabaseHook", e);
				}
			}
		}
		catch (Exception e)
		{
			Log.e(TAG, "Error while in MySQLiteDatabaseHook's postKey", e);
		}
		finally
		{
			if (cursor != null && !cursor.isClosed())
			{
				cursor.close();
			}
		}
	}
}

```

**Comment by developernotes** [comment]
Hi @ashishdimi09 

We have additional questions which will be helpful in debuggint:

- Were you using default settings for accessing the database with SQLCipher 3.5.9? 
- Are you able to replicate this issue? 
- What device/emulator does this issue occur on?
- What Android OS version does this issue occur on?
