### ISSUE TITLE
Difference in release vs debug version

### ISSUE THREAD

**Issue by sahmadsyed** [sqlcipher/android-database-sqlcipher#445]
I was curious to know what the differences are in the two versions. For my use case, I'm trying to get the symbolicated so files so does it make a difference which one I use? Additionally, where exactly would the symbolicated so files be located after it is built? Would src/main/obj/local/ be the right location?

**Comment by developernotes** [comment]
Hi @sahmadsyed 

Thanks for your interest in SQLCipher. We utilize GitHub Issues as a location for reporting issues with the software library itself. I would recommend posting this type of question within the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
