### ISSUE TITLE
ELF built without Stack Protection 

### ISSUE THREAD

**Issue by manjunath143** [sqlcipher/android-database-sqlcipher#450]
We are using libsqlcipher.so file .We found that  there is potential vulnerability of `ELF built without Stack Protection` in `lib/x86/libsqlcipher.so `.We are using sqlcipher 4.x .
May we know if libsqlcipher.so libraries are built with ` -fstack-protector-all` flag ?

**Comment by developernotes** [comment]
Hi @manjunath143 

When we switched over to using Android NDK 15c we identified that clang is using `-fstack-protector-strong` by default, which appears to be a rather [encompassing](http://lists.llvm.org/pipermail/cfe-dev/2017-April/053662.html). Is your organization using the commercial edition of SQLCipher for Android?

**Comment by manjunath143** [comment]
@developernotes  Thanks for the response.Really helpful.
