### ISSUE TITLE
gradle build failed.

### ISSUE THREAD

**Issue by tommybee-dev** [sqlcipher/android-database-sqlcipher#457]
My build information with gradle:
JAVA version : 
###
java version "1.8.0_152-ea"
Java(TM) SE Runtime Environment (build 1.8.0_152-ea-b02)
Java HotSpot(TM) Client VM (build 25.152-b02, mixed mode)
###

Can anyone tell me what i am missing?

I got a error when running a gradlew.bat.

* What went wrong:
A problem occurred configuring root project 'android-database-sqlcipher'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not determine artifacts for org.ec4j.maven:ec4j-lint-api:0.0.7
      > Could not get resource 'https://jcenter.bintray.com/org/ec4j/maven/ec4j-lint-api/0.0.7/ec4j-lint-api-0.0.7.takari-jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/ec4j/maven/ec4j-lint-api/0.0.7/ec4j-lint-api-0.0.7.takari-jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by developernotes** [comment]
Hi @tommybee-dev 

Thank you for your interest in SQLCipher for Android. We utilize GitHub Issues for reporting defects in the software library only. Based on the output you are receiving it appears the java process is unable to  establish a trusted connection over SSL, an environmental issue. You may find [this](https://jfrog.com/knowledge-base/how-to-resolve-unable-to-find-valid-certification-path-to-requested-target-error/) helpful to resolve the issue. We would ask that if you have any further questions about this that you direct those to the [SQLCipher discuss community site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
