### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by FreeTymeKiyan** [sqlcipher/android-database-sqlcipher#463]
### Expected Behavior
No error

### Actual Behavior
java.lang.UnsatisfiedLinkError when using SQLCipher 4.2.0

Stacktrace 
```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
  at java.lang.System.loadLibrary (System.java:1669)
  at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries (SQLiteDatabase.java:6)
  at net.sqlcipher.database.SQLiteDatabase.loadLibs (SQLiteDatabase.java:11)
  at net.sqlcipher.database.SQLiteDatabase.loadLibs (SQLiteDatabase.java:8)
  at net.sqlcipher.database.SQLiteDatabase.loadLibs (SQLiteDatabase.java:7)
  at com.freetymekiyan.apas.model.database.EncryptedDbImpl.<init> (EncryptedDbImpl.java)
```

This is how I initialize DB:
```
  private EncryptedDbImpl(final Context context) {
    SQLiteDatabase.loadLibs(context);
    File databaseFile = context.getDatabasePath(DB_FILE);
    database = SQLiteDatabase.openOrCreateDatabase(databaseFile, DB_PASSWORD, null);
  }
```

I'm using proguard but I excluded all sqlcipher related code
```
# sqlcipher
-keep class net.sqlcipher.** { *; }
```

### Steps to Reproduce
I don't know how to reproduce it yet. I got 9 reports in Google Play for the past 30 days. So it seems to only happen on some devices or systems.

SQLCipher for Android version:
4.2.0: `implementation 'net.zetetic:android-database-sqlcipher:4.2.0@aar'`

**Comment by FreeTymeKiyan** [comment]
let me know if you guys need any other more info. I'd be happy to provide them and figure this issue out.

**Comment by developernotes** [comment]
Hi @FreeTymeKiyan 

This is likely due to project packaging, and not a defect in the software itself. Here are a few items to try ruling out:

- What CPU platform is this error occurring on (note: SQLCipher for Android platform compatibility is covered [here](https://github.com/sqlcipher/android-database-sqlcipher#compatibility))
- Unpack the apk file with [apktool](https://ibotpeaches.github.io/Apktool/) and verify your shipping application contains `libsqlcipher.so` for all relevant platforms
- Disable ProGuard to see if your configuration is causing an issue
- On a device or emulator, use `adb shell ls -l <path>` to check for the native library presence

**Comment by FreeTymeKiyan** [comment]
@developernotes thanks for the reply!

One the 1st bullet: failed on 2 devices that has the following platforms: 
```
YU Yureka
ABI
arm64-v8a
armeabi-v7a
armeabi

sagit
MI6
ABI
arm64-v8a
armeabi-v7a
armeabi
```
Seems all compatible 

On the 2nd bullet: I saw x86_64, x86, arm64_v8a, armeabi, armeabi-v7a. All of them have `ibsqlcipher.so`

On the 3rd bullet: I can't just disable ProGuard since it will deobfuscate all the code and make it available to everyone that has the APK. Unsafe. 

On the 4th bullet: what is the path here?

**Comment by FreeTymeKiyan** [comment]
BTW, it doesn't crash on more than 10k installs, just these 2 devices. So I don't feel it's a packaging problem really.

**Comment by developernotes** [comment]
Hello @FreeTymeKiyan 

Do you have either those devices on hand to test against? Unfortunately, we do not have those devices available, however it would be a good test to determine whether the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) runs on those devices. This will help rule out project configuration issues related to your application.

**Comment by FreeTymeKiyan** [comment]
Unfortunately I don't. Imma try to find an online virtual device maybe, if there is any, to see if the tests can run on that.

**Comment by bartek-wesolowski** [comment]
I'm seeing the same issue in Crashlytics. Here are some more details when it comes to devices and operating systems. I haven't been able to reproduce the issue myself.

![Zrzut ekranu 2019-08-20 o 09 35 50](https://user-images.githubusercontent.com/3972790/63327253-21883f80-c32e-11e9-996c-c5b85b8493b2.png)

![Zrzut ekranu 2019-08-20 o 09 36 00](https://user-images.githubusercontent.com/3972790/63327265-251bc680-c32e-11e9-97ff-4755cb06f522.png)

**Comment by FreeTymeKiyan** [comment]
@bartek Thanks for sharing! Yeah I’m also still being haunted be this issue. There doesn’t seem to be a very good way to deal with it. I wonder if it’s because they don’t support mips architecture

**Comment by developernotes** [comment]
Hi @FreeTymeKiyan 

Are you shipping/supporting your application with SQLCipher for Android for MIPS devices?

**Comment by FreeTymeKiyan** [comment]
@developernotes well I don't. I'm just being suspicious since when I unzip the APK I see the other libraries I use are in mips and mips64 folder, not sql cipher.
