### ISSUE TITLE
Room integration API availability

### ISSUE THREAD

**Issue by tommus** [sqlcipher/android-database-sqlcipher#464]
When you are planning to release a newer version of sqlcipher with Room integration API (like eg. `SupportFactory` class) to Maven Central?

Currently I am unable to fetch it via Jitpack (as a temporary workaround) using `master-SNAPSHOT` nor `-SNAPSHOT` version.

Jitpack has some issues with compilation of newest snapshot and I am not personally interested in compiling library on my own (because of the internal arrangements of the team I am a part of).

Any approximations regarding newer release date?

Thank you.

**Comment by developernotes** [comment]
Hello @tommus 

We have not released a build with Room support via Maven Central yet, it will be included in our next release of SQLCipher core. You would need to build the library yourself at the moment. We utilize GitHub Issues for reporting defects in the software library itself. Please feel free to direct these type of questions to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
