### ISSUE TITLE
Missing Null Check in SupportHelper

### ISSUE THREAD

**Issue by commonsguy** [sqlcipher/android-database-sqlcipher#466]
https://github.com/sqlcipher/android-database-sqlcipher/commit/4731d944dd96a1dc44d6acef3935414e42cd3d74#diff-41939146e7b334cff9bb100c9beeef0eR75-R84

`SupportHelper` needs to cache the passphrase between the time it is created and our opportunity to open the database. In `getWritableDatabase()`, it zeros out that array, so the passphrase is not retained in the clear any longer than is necessary.

However, I think that the passphrase should be `null` if we are trying to open an unencrypted database, and I did not include a `null` check there. I'm getting too spoiled by Kotlin's null safety, I suppose. :-(

I had a report of this problem with SafeRoom, and [this SafeRoom commit implements the `null` check, along with a test to confirm that SafeRoom can open an unencrypted database](https://github.com/commonsguy/cwac-saferoom/commit/f6c9eebd2af5bf29b16797f73978b316558b030f).

**Comment by developernotes** [comment]
Hi @commonsguy 

I apologize for the delay in response. That is a good catch, I've adjusted the `SupportHelper` to include the null check before zeroing the passphrase. Thanks!

**Comment by commonsguy** [comment]
Thanks!
