### ISSUE TITLE
why not find the class "SupportFactory"?

### ISSUE THREAD

**Issue by dpf527** [sqlcipher/android-database-sqlcipher#467]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:4.2.0

why not find the class "SupportFactory"?  Integration implementation 'net.zetetic:android-database-sqlcipher:4.2.0'

**Comment by developernotes** [comment]
Hi @dpf527 

We have not released a version of the library publicly with the androidx support integration. This will be included in our next public release of SQLCipher. Please feel free to build locally if you need it before the release.
