### ISSUE TITLE
 getWritableDatabase() is most time-consuming .

### ISSUE THREAD

**Issue by yanjiepeng** [sqlcipher/android-database-sqlcipher#468]
getWritableDatabase() cost too much times, about 1.5seconds and block main thread 

SQLCipher for Android version: 4.1.3 and 4.2.0 

here is logs fille:

2019-08-14 14:48:21.207 2903-2903/com.tazan.cd.streetlight E/getWritableDatabase time 1：: 1565765301207
2019-08-14 14:48:21.207 2903-2903/com.tazan.cd.streetlight E/getWritableDatabase time 2：: 1565765301207
2019-08-14 14:48:22.718 2903-2903/com.tazan.cd.streetlight E/getWritableDatabase time3：: 1565765302718

between time2 and time3 is method "getWritableDatabase()" 

The database contains about just several hundred pieces of data and five tables.

devices : Huawei Honor 8
             Xiaomi 9

**Comment by commonsguy** [comment]
`getWritableDatabase()` is a blocking call with ordinary `SQLiteOpenHelper`. Do not call `getWritableDatabase()` on the main application thread, whether you are using SQLCipher for Android or not.

And, since SQLCipher's `getWritableDatabase()` is where you provide the passphrase, you want to call that only once per user authentication, not many times.

**Comment by yanjiepeng** [comment]
> `getWritableDatabase()` is a blocking call with ordinary `SQLiteOpenHelper`. Do not call `getWritableDatabase()` on the main application thread, whether you are using SQLCipher for Android or not.
> 
> And, since SQLCipher's `getWritableDatabase()` is where you provide the passphrase, you want to call that only once per user authentication, not many times.

Thanks for your replay.
According to your suggestion，Should I create a singleton of  SQLiteDatabase in my application file?
but will there be any exceptions if I use that singleton for reading or writing data to different tables?

**Comment by commonsguy** [comment]
> Should I create a singleton of SQLiteDatabase in my application file?

I would have a singleton that holds the `SQLiteOpenHelper` and can open the database when you get your the passphrase from the user.

> will there be any exceptions if I use that singleton for reading or writing data to different tables?

There should be no problem with this. You do not need different `SQLiteDatabase` objects for accessing different tables within the same database.

**Comment by yanjiepeng** [comment]
> > Should I create a singleton of SQLiteDatabase in my application file?
> 
> I would have a singleton that holds the `SQLiteOpenHelper` and can open the database when you get your the passphrase from the user.
> 
> > will there be any exceptions if I use that singleton for reading or writing data to different tables?
> 
> There should be no problem with this. You do not need different `SQLiteDatabase` objects for accessing different tables within the same database.

 I'll give it a try. Thank you for your advice.
