### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by Amosss** [sqlcipher/android-database-sqlcipher#471]
### Expected Behavior
sqlcipher to work

### Actual Behavior
On a certain device (Other devices seem to be ok with it), I got the above crash with the following stack trace:

> Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app.appm-oMdSgIjvGcgfbLLnMzQlIw==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.appm-oMdSgIjvGcgfbLLnMzQlIw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libsqlcipher.so"
>        at java.lang.Runtime.loadLibrary0 + 1011(Runtime.java:1011)
>        at java.lang.System.loadLibrary + 1657(System.java:1657)
>        at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries + 223(SQLiteDatabase.java:223)
>        at net.sqlcipher.database.SQLiteDatabase.loadLibs + 240(SQLiteDatabase.java:240)
>        at net.sqlcipher.database.SQLiteDatabase.loadLibs + 219(SQLiteDatabase.java:219)
>        at net.sqlcipher.database.SQLiteDatabase.loadLibs + 212(SQLiteDatabase.java:212)
>        at com.commonsware.cwac.saferoom.Helper.<init> + 39(Helper.java:39)
>        at com.commonsware.cwac.saferoom.SafeHelperFactory.create + 190(SafeHelperFactory.java:190)
>        at com.commonsware.cwac.saferoom.SafeHelperFactory.create + 184(SafeHelperFactory.java:184)
>        at com.app.appm.dbRoom.AppDatabase_Impl.createOpenHelper + 96(AppDatabase_Impl.java:96)
>        at androidx.room.RoomDatabase.init + 159(RoomDatabase.java:159)
>        at androidx.room.RoomDatabase$Builder.build + 852(RoomDatabase.java:852)
>        at com.app.appm.dbRoom.DatabaseClient.<init> + 19(DatabaseClient.java:19)
>        at com.app.appm.dbRoom.DatabaseClient.getInstance + 24(DatabaseClient.java:24)
>        at com.app.appm.MainActivity$2.run + 129(MainActivity.java:129)
>        at android.os.AsyncTask$SerialExecutor$1.run + 245(AsyncTask.java:245)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
>        at java.lang.Thread.run + 764(Thread.java:764)

### Steps to Reproduce
Not sure, it's a crash on a user's device, I guess he just opened the app
Android version: 8.1.0
LGE
nexus 5

Thanks

**Comment by sjlombardo** [comment]
@Amosss if you unpack your APK can you verify that all the sqlcipher.so files are present, including the one for arm64? What version of SQLCipher are you using?

**Comment by Amosss** [comment]
Thanks @sjlombardo , 
I'm less familiar with unpacking APKs, is there an easy way to do so on Windows? 
Unpacking will also tell me the version I'm using?

**Comment by Amosss** [comment]
Unpacking will also tell me the version of SQLCipher?

**Comment by developernotes** [comment]
@Amosss you can use [`apktool`](https://ibotpeaches.github.io/Apktool/) to unpack your application APK file. It will contain folders for the respective ABI platforms as subdirectories within the `lib` folder.

Unpacking the library will not directly tell you what version of SQLCipher you are using. You should be able to locate that within your Gradle references. Alternatively, from code you can query the library version by executing `pragma cipher_version;` and reading the String value returned.

**Comment by Amosss** [comment]
I used apktool. with if params it created a 127.apk file and with d it created a 1.apk file. What am I suppose to do now? 

I don't have any reference to sqlCipher in both gradle references, just to safe room:  implementation 'com.commonsware.cwac:saferoom.x:1.0.5'

**Comment by commonsguy** [comment]
I have a Nexus 5. Both the demo project and the test suite in SafeRoom work fine on it.

If you have a project that reproduces the problem, I can take a look at it, but there does not appear to be a general problem with SQLCipher for Android or SafeRoom on the Nexus 5.

**Comment by Amosss** [comment]
I saw the above report in my Crashlytics. Maybe a combination of some kind caused it or specifically how my apk was built (actually it's aab).  May I ask how can I contact you for your to test it? And ofcourse, I appreciate it very much!

**Comment by commonsguy** [comment]
> May I ask how can I contact you for your to test it?

If it is on the Play Store, post a link. Or, if it is open source, post a link to the repository. 

Or, since this is a Nexus device, it should be in [the Firebase Test Lab](https://firebase.google.com/docs/test-lab/), so you could try running your test suite there.

**Comment by Amosss** [comment]
This is the play store link: https://play.google.com/store/apps/details?id=com.stockdiv.stockdivm
I ran a test in test lab of Firebase that came out good but I don't know what happened behind the scenes. Thanks! 

From the report, it looks like it happened when the app opens up.

**Comment by commonsguy** [comment]
The app starts up fine. I get to the registration screen without issue.

**Comment by Amosss** [comment]
So that brings me back to point 1, what might have happen on that user's mobile

**Comment by commonsguy** [comment]
I have no idea. All that I can say is that it is not a general problem with the Nexus 5.

**Comment by Amosss** [comment]
It might be a combination of some kind. Does the fact that it works on your mobile, change any of the instructions I got before?

**Comment by commonsguy** [comment]
It would not appear to be a direct packaging problem -- otherwise the problem should be reproducible here.

Depending on how your AAB is set up, it's conceivable that the Play Store screwed up delivery to that device and failed to install the part that contains the SQLCipher for Android bits. I avoid AAB at all costs (and any other solution that involves Google signing the binaries), but I don't know if you can switch back to APK-based distribution. If you can, you could try that and see if the problem shows up when you have everything in the one package.

There are one-off possibilities. For example, the user might have a rooted device and has something that interfered with your app's installation.

**Comment by Amosss** [comment]
I don't even know who is he :) I understand that I won't have an easy way to understand what happened on his specific device

**Comment by Amosss** [comment]
Now I got this in Crashlytics, same crash, different user:
Brand: unknown
Model: GCE x86 phone 
Android 9
Unfortunately I have no other information about this

**Comment by Amosss** [comment]
I didn't see this issue again in crashlytics but maybe it's because the relevant users are not using the app anymore because of this bug.

**Comment by developernotes** [comment]
Hello @Amosss 

Would you mind running `apktool` on your application APK file again, using this as the command:

```
apktool decode -o output YourApplication.apk
```

This will generate a folder titled `output` containing the extraction. Please share the full contents of your `output/lib` folder.

**Comment by Amosss** [comment]
C:\Windows\output\lib>dir /s
 Volume in drive C has no label.
 Volume Serial Number is 328E-AC19

 Directory of C:\Windows\output\lib

09/05/2019  07:14 PM    <DIR>          .
09/05/2019  07:14 PM    <DIR>          ..
09/05/2019  07:14 PM    <DIR>          arm64-v8a
09/05/2019  07:14 PM    <DIR>          armeabi
09/05/2019  07:14 PM    <DIR>          armeabi-v7a
09/05/2019  07:14 PM    <DIR>          x86
09/05/2019  07:14 PM    <DIR>          x86_64
               0 File(s)              0 bytes

 Directory of C:\Windows\output\lib\arm64-v8a

09/05/2019  07:14 PM    <DIR>          .
09/05/2019  07:14 PM    <DIR>          ..
09/05/2019  07:14 PM         3,056,544 libsqlcipher.so
               1 File(s)      3,056,544 bytes

 Directory of C:\Windows\output\lib\armeabi

09/05/2019  07:14 PM    <DIR>          .
09/05/2019  07:14 PM    <DIR>          ..
09/05/2019  07:14 PM         1,926,540 libsqlcipher.so
               1 File(s)      1,926,540 bytes

 Directory of C:\Windows\output\lib\armeabi-v7a

09/05/2019  07:14 PM    <DIR>          .
09/05/2019  07:14 PM    <DIR>          ..
09/05/2019  07:14 PM         1,926,548 libsqlcipher.so
               1 File(s)      1,926,548 bytes

 Directory of C:\Windows\output\lib\x86

09/05/2019  07:14 PM    <DIR>          .
09/05/2019  07:14 PM    <DIR>          ..
09/05/2019  07:14 PM         3,426,084 libsqlcipher.so
               1 File(s)      3,426,084 bytes

 Directory of C:\Windows\output\lib\x86_64

09/05/2019  07:14 PM    <DIR>          .
09/05/2019  07:14 PM    <DIR>          ..
09/05/2019  07:14 PM         3,590,600 libsqlcipher.so
               1 File(s)      3,590,600 bytes

     Total Files Listed:
               5 File(s)     13,926,316 bytes
              17 Dir(s)  117,896,478,720 bytes free

**Comment by Amosss** [comment]
If there is anything else I should be adding, please let me know, thanks

**Comment by developernotes** [comment]
Hello @Amosss 

Unfortunately, we are unable to reproduce the behavior you are experiencing. If you have the device present that is causing the issue, you might look at experimenting with providing an alternative `LibraryLoader` [implementation](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L215-L257), possibly by looking on the device to find the actual location of the unpacked .so file and calling `System.load` with an absolute path.
