### ISSUE TITLE
Database corrupt exception

### ISSUE THREAD

**Issue by iskugor** [sqlcipher/android-database-sqlcipher#472]
Hello!

### Expected Behavior

App should not get to corrupted database.

### Actual Behavior

I notice few crashes in Google Play console:

`
net.sqlcipher.database.SQLiteDatabaseCorruptException: 
  at net.sqlcipher.database.SQLiteStatement.native_execute (SQLiteStatement.java)
  at net.sqlcipher.database.SQLiteStatement.executeInsert (SQLiteStatement.java:83)
`

### Steps to Reproduce

I cannot reproduce it.
It seems it happens just on Samsung Galaxy A40 with Android 9. I have other Samsung device with Android 9, but on my device it works fine.

Any idea why this might happen?

SQLCipher for Android version: 4.2.0

**Comment by commonsguy** [comment]
I do not, other than to point out that 99% of the code that you are executing comes from SQLCipher for Android, not from SafeRoom. It is possible that the maintainers of SQLCipher for Android will have some suggestions, so you could try their discussion board.

**Comment by iskugor** [comment]
@developernotes unfortunately, no. I could get A50, but not sure would that help.

**Comment by commonsguy** [comment]
I apologize for my earlier comment on this issue. It was inappropriate in general, doubly so as I thought that this issue was posted to a different repository.

**Comment by developernotes** [comment]
Hi @commonsguy,

No worries at all! 😄

**Comment by TheNephilim88** [comment]
@iskugor Do you have any news here?

Many users with a Samsung J5 that updated to Android 9 are contacting me describing quite similar situation. But for me its only Samsung J5 and only after updating to Android 9 while every other device with Android 9 (even S10, S9, S8...) has no issues at all.

But unfortunately I dont have any crash log here as corruptions are handled within my app.

**Comment by sjlombardo** [comment]
@TheNephilim88 - are you able to reliably reproduce this issue on a  Samsung J5 in your possession?

**Comment by iskugor** [comment]
@TheNephilim88 No, unfortunately I didn't manage to reproduce on Samsung devices I have. As I can see, it only happens on few A40 devices which I don't have.

**Comment by BurningAXE** [comment]
I know quite a lot of time has passed but I'm currently investigating an issue where Samsung A202F devices get net.sqlcipher.database.SQLiteDatabaseCorruptException. Has anyone found more information (and possibly a solution) on this problem?
