### ISSUE TITLE
make build-release fails

### ISSUE THREAD

**Issue by bblackbelt** [sqlcipher/android-database-sqlcipher#473]
Hi,  

  I am trying building the library, using the instructions, on macos. I installed the ndk r15c, exported ANDROID_NDK_ROOT, and run `make install ` and `make build-release
`. After sometime the latter fails with
```

* What went wrong:
Execution failed for task ':android-database-sqlcipher:buildNative'.
> A problem occurred starting process 'command 'ndk-build''
```

running the command manually says

```
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it. 

```

I tried setting it to point to the source folder but keep failing with 
```

Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.    
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file:  Android.mk    
```

Did I miss something? 

Thanks for the help

**Comment by developernotes** [comment]
Hi @bblackbelt 

>A problem occurred starting process 'command 'ndk-build''

Please make sure `ndk-build` is on your path. We reserve GitHub Issues for reporting software defect. If you have any further questions regarding the build process itself, I would recommend posting on the SQLCipher community [discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
