### ISSUE TITLE
The app work slowed down on some devices when upgrading to version 4.2.0

### ISSUE THREAD

**Issue by AntonSavelev** [sqlcipher/android-database-sqlcipher#477]
Our application used version SQL cipher 3.5.3. Due to the requirement of Google to support 64-bit architecture from August 1, 2019, we updated the library to the latest version 4.2.0.
After that, we received some feedback from our users that on their devices the application began to work very slowly, to hang. This is observed on devices MotoG4 Plus (Android 8.1) and Sony Xperia Z3+  (Android 7.1). Please, help solve the problem.

**Comment by R4N** [comment]
Thank you for your interest in SQLCipher! We utilize GitHub Issues for reporting software defects within the library itself. This type of question is perfectly suitable for our public community SQLCipher discuss site. It appears that you already [cross posted](https://discuss.zetetic.net/t/application-work-on-some-devices-slowed-down-when-updating-sqlcipher-to-version-4-2-0/3922) it over there.
