### ISSUE TITLE
Missing SupportFactory Class.

### ISSUE THREAD

**Issue by Xdomino** [sqlcipher/android-database-sqlcipher#478]
Hi thanks for the awesome library at first.
I want to use it in my project with Sqlbrite. I followed the instruction.Then added 4.2.0 dependencies in my gradle file. But there was no supportFactory class in my classpath. And I tried to degrade version to 4.1.3, but still no class. I wonder if there was something wrong with jcenter.

I got a screenshot of my project classpath of android-database-sqlcipher. I don't know why i can't upload img. But above description should be enough for issue.

Best regards.

**Comment by developernotes** [comment]
Hi @Xdomino 

The SupportFactory API has been merged into master, however we have not created a public release yet. At this time, you can build from source, or await a the next public release of SQLCipher which will include it. Thanks!
