### ISSUE TITLE
App is killed when using this sqlcipher 4.* lib on Android 5.0.2 and Qualcomm Snapdragon 410 (MSM8916)

### ISSUE THREAD

**Issue by kuFEAR** [sqlcipher/android-database-sqlcipher#480]
### Expected Behavior
Works well.

### Actual Behavior
I don't see any logs in logcat with crash, but app is unexpected silently quit when called net.sqlcipher.database.SQLiteDatabase#loadLibs(android.content.Context, java.io.File) when were loading native library "sqlciphet.so"

### Steps to Reproduce
Create a simple App with androidx.Room and com.commonsware.cwac:saferoom.x:1.0.0 or up to 1.2.0 
and configure it like this:
```
Room.databaseBuilder(context, SecureDatabase::class.java, "mydb")
        .openHelperFactory(SafeHelperFactory("myPassCode".toCharArray()))
        .build()
```
It crashes only on Android 5.0.2 and Qualcomm Snapdragon 410 (MSM8916) devices (Lenovo s90-a, Asus ZenFone 2 Lazer, and other with the same configuration)

SQLCipher version:
4.2.0

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by commonsguy** [comment]
I tested the SafeRoom test suite on a Wileyfox Swift, which has that CPU, and the tests passed. However, the Swift is running 6.0.1, not 5.0.2.

FWIW, [this page](https://www.kimovil.com/en/list-smartphones-by-processor/qualcomm-snapdragon-410-msm8916) lists a hundred or so device models with that CPU. Personally, I do not appear to have a device (among the ~60 that I own) with that CPU that runs Android 5.x, let alone specifically 5.0.2.

**Comment by kuFEAR** [comment]
Android version (should be 5.0.2) is important in this case.

**Comment by vsietoi** [comment]
Hello, @commonsguy do you have any updates? If you need any additional information about the way how to reproduce please let us know.

**Comment by commonsguy** [comment]
As I indicated, I do not have a device with that very specific OS version and CPU match.

This ticket is basically a duplicate of #469, and there [Zetetic indicated that they were working on acquiring test hardware](https://github.com/sqlcipher/android-database-sqlcipher/issues/469#issuecomment-542701595).
