### ISSUE TITLE
encryption database sqlite reade-made with sql cipher

### ISSUE THREAD

**Issue by sattarsh** [sqlcipher/android-database-sqlcipher#482]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @sattarsh 

We reserve GitHub Issues for reporting defects in the software library itself. If you have a specific question, please submit a detailed post to the public community [SQLCipher discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks
