### ISSUE TITLE
Android 10 Support ?

### ISSUE THREAD

**Issue by Developmc** [sqlcipher/android-database-sqlcipher#484]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @Developmc 

SQLCipher for Android does work on Android 10. Are you reporting an issue?
