### ISSUE TITLE
Sqlcipher is not run on oppo devices

### ISSUE THREAD

**Issue by Baobomb** [sqlcipher/android-database-sqlcipher#493]
Sqlcipher is not run on this company all devices. Please add support for this company devices.
https://www.oppo.com/pk/

native crash occurred on very start of application.

SQLCipher for Android version: 4.1.3

Follow are logs
W/linker: /data/app/a/lib/arm64/libsqlcipher.so: unused DT entry: type 0x6ffffffe arg 0x7810
W/linker: /data/app/a/lib/arm64/libsqlcipher.so: unused DT entry: type 0x6fffffff arg 0x3
WIN DEATH: Window{10656b82 u0

happened on OPPO Android 5

**Comment by developernotes** [comment]
Hello @Baobomb 

What is the exact Oppo device model you are experiencing the issue on?

**Comment by anshulkabramobisy** [comment]
https://github.com/sqlcipher/android-database-sqlcipher/issues/493#issue-563780009

Is there any solution available for this query?


OS | Android 5.1 (Lollipop), ColorOS 3
Chipset | Qualcomm MSM8916 Snapdragon 410 (28 nm)
Models |  A37fw,

App is crashing on start. 
it was working earlier in - "3.5.9@aar" , but it's broken in "4.3.0@aar"

**Comment by anshulkabramobisy** [comment]
> Hello @Baobomb
> 
> What is the exact Oppo device model you are experiencing the issue on?

Hi Nick,

I have added the details, could you please share a work around solution for this, this has very huge impact on user base in india where oppo device uses are high.

**Comment by developernotes** [comment]
Hi @anshulkabramobisy 

We have commented on your separate post [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/469#issuecomment-660197819). Thanks!
