### ISSUE TITLE
Is there a tool/command to decrypt the database file?

### ISSUE THREAD

**Issue by cuiyuming** [sqlcipher/android-database-sqlcipher#495]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @cuiyuming 

Please review the options discussed in [Management Interfaces for SQLCipher Databases](https://discuss.zetetic.net/t/management-interfaces-for-sqlcipher-databases/121). We reserve GitHub Issues for reports in software defects to SQLCipher. If you have additional questions, please feel free to post on the [SQLCipher Community discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
