### ISSUE TITLE
'SQLiteException: file is not a database' after App-Crash

### ISSUE THREAD

**Issue by modsfabio** [sqlcipher/android-database-sqlcipher#497]
### Expected Behavior
App should start normally after a crash

### Actual Behavior
App does not start after a crash and prints the following exception:
```
Fatal Exception: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
```

### Steps to Reproduce
App Crash while async thread is writing to database (hard to do, only happens sometimes)

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by akvashi** [comment]
@modsfabio did you find a solution to this?

**Comment by developernotes** [comment]
Hi @modsfabio 

I'm sorry this was missed previously. Unfortunately, we would need more information to further debug this issue. Can you please provide more context around the error you are receiving? Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? Thanks!
