### ISSUE TITLE
failed build on macOS 

### ISSUE THREAD

**Issue by jfcontart** [sqlcipher/android-database-sqlcipher#499]
Hello , I try to build with tutorial 

### Expected Behavior

success build 

### Actual Behavior

fail build

### Steps to Reproduce

I am using macOS computer (macOS Catalina 10.15.3)
In terminal I do : 
 - checkout project
 - define my SDK and NDK path : 

```
export ANDROID_HOME="/Users/${USER}/Library/Android"
export ANDROID_SDK_ROOT="${ANDROID_HOME}/sdk"
export ANDROID_NDK_HOME="${ANDROID_SDK_ROOT}/ndk/21.0.6113669"
```

I init the make 

```
make init
```

I try to build release

```
make build-release
```

error in build : 

```
BUILD FAILED in 1s
2 actionable tasks: 2 executed
make: *** [check] Error 1
iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$ clear

iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$ make build-debug
./gradlew check

> Task :android-database-sqlcipher:buildOpenSSL SKIPPED
/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/android-libs/armeabi-v7a/libcrypto.a exists SKIPPED

> Task :android-database-sqlcipher:buildNative FAILED
SQLCIPHER_CFLAGS=-DSQLITE_HAS_CODEC -DSQLITE_SOUNDEX -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999 -DSQLITE_TEMP_STORE=3 -DSQLITE_THREADSAFE=1 -DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 -DNDEBUG=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_ENABLE_DBSTAT_VTAB
OPENSSL_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/openssl-1.1.1d
SQLCIPHER_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/sqlcipher
SQLCIPHER_OTHER_CFLAGS=-DLOG_NDEBUG -fstack-protector-all
ANDROID_NATIVE_ROOT_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/android-libs
NDK_APP_PLATFORM=16

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android-database-sqlcipher:buildNative'.
> A problem occurred starting process 'command 'ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
2 actionable tasks: 2 executed
make: *** [check] Error 1
```

I investigate on my side

**Comment by developernotes** [comment]
Hi @jfcontart 

We [currently](https://github.com/sqlcipher/android-database-sqlcipher#building) recommend building with the Android NDK r20, not 21. Would you try adjusting that and rebuild? If you still receive an error please run the gradle task `:android-database-sqlcipher:buildNative` with `--info` or `--debug` to capture additional information. Thanks

**Comment by jfcontart** [comment]
Hi @developernotes 

I try with NDK r20   : 
export ANDROID_HOME="/Users/${USER}/Library/Android"
export ANDROID_SDK_ROOT="${ANDROID_HOME}/sdk"
export ANDROID_NDK_HOME="${ANDROID_SDK_ROOT}/ndk/android-ndk-r20"
export PATH=$PATH:$ANDROID_NDK_HOME

I disable security of my Mac to build

**Comment by developernotes** [comment]
Hi @jfcontart 

Can you try running the gradle command directly to see if there is more output?

```
./gradlew :android-database-sqlcipher:buildNative --debug
```

**Comment by jfcontart** [comment]
:-) too long comment  


15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem occurred configuring project ':android-database-sqlcipher'.
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/jfc-idemobi/Desktop/android-database-sqlcipher/local.properties'.
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:01:21.986 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
15:01:21.986 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
15:01:21.986 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 0s
15:01:21.986 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
15:01:21.986 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
15:01:21.987 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Build Output Cleanup Cache (/Users/jfc-idemobi/Desktop/android-database-sqlcipher/.gradle/buildOutputCleanup)

**Comment by jfcontart** [comment]
I think it's on this line  :  SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable

**Comment by developernotes** [comment]
Hi @jfcontart 

>15:01:21.985 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/jfc-idemobi/Desktop/android-database-sqlcipher/local.properties'.

Can you check your environment to make sure the variable referenced is properly set?

**Comment by jfcontart** [comment]
I Try ./gradlew :android-database-sqlcipher:buildNative --debug --scan


15:23:47.909 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for execution history cache (/Users/jfc-idemobi/Desktop/android-database-sqlcipher/.gradle/5.4.1/executionHistory)
15:23:47.909 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on execution history cache (/Users/jfc-idemobi/Desktop/android-database-sqlcipher/.gradle/5.4.1/executionHistory).
15:23:47.909 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on execution history cache (/Users/jfc-idemobi/Desktop/android-database-sqlcipher/.gradle/5.4.1/executionHistory).
15:23:47.910 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
15:23:47.910 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :android-database-sqlcipher:buildNative FAILED
15:23:47.910 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :android-database-sqlcipher:buildNative' started
15:23:47.910 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':android-database-sqlcipher:buildNative' into context took 0.0 secs.
15:23:47.912 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot task inputs for :android-database-sqlcipher:buildNative' started
15:23:47.912 [INFO] [org.gradle.internal.execution.steps.ResolveCachingStateStep] Caching disabled for task ':android-database-sqlcipher:buildNative' because:
  Build cache is disabled
15:23:47.913 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Snapshot task inputs for :android-database-sqlcipher:buildNative'
15:23:47.913 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot task inputs for :android-database-sqlcipher:buildNative' completed
15:23:47.913 [DEBUG] [org.gradle.internal.execution.steps.SkipUpToDateStep] Determining if task ':android-database-sqlcipher:buildNative' is up-to-date
15:23:47.913 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Task ':android-database-sqlcipher:buildNative' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
15:23:47.913 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':android-database-sqlcipher:buildNative'.
15:23:47.913 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute doLast {} action for :android-database-sqlcipher:buildNative' started
15:23:47.914 [INFO] [org.gradle.api.Script] Executing NDK build command
15:23:47.914 [QUIET] [] SQLCIPHER_CFLAGS=-DSQLITE_HAS_CODEC -DSQLITE_SOUNDEX -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999 -DSQLITE_TEMP_STORE=3 -DSQLITE_THREADSAFE=1 -DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 -DNDEBUG=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_ENABLE_DBSTAT_VTAB
15:23:47.914 [QUIET] [] OPENSSL_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/openssl-1.1.1d
15:23:47.914 [QUIET] [] SQLCIPHER_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/sqlcipher
15:23:47.914 [QUIET] [] SQLCIPHER_OTHER_CFLAGS=-DLOG_NDEBUG -fstack-protector-all
15:23:47.914 [QUIET] [] ANDROID_NATIVE_ROOT_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/android-libs
15:23:47.914 [QUIET] [] NDK_APP_PLATFORM=16
15:23:47.915 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'ndk-build''. Working directory: /Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher Command: ndk-build V=1 NDK_DEBUG=0 --environment-overrides NDK_LIBS_OUT=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/libs32 -C /Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp NDK_APPLICATION_MK=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/cpp/Application32.mk
15:23:47.915 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'ndk-build'': {PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/jfc-idemobi/Library/Android/ndk/android-ndk-r20, JAVA_ARCH=x86_64, TERM=xterm-256color, LANG=fr_FR.UTF-8, ANDROID_HOME=/Users/jfc-idemobi/Library/Android, ANDROID_NATIVE_ROOT_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/android-libs, LOGNAME=jfc-idemobi, TERM_PROGRAM_VERSION=433, PWD=/Users/jfc-idemobi/Desktop/android-database-sqlcipher, XPC_SERVICE_NAME=0, APP_ICON_2800=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/media/gradle.icns, SHELL=/bin/bash, TERM_PROGRAM=Apple_Terminal, OPENSSL_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/openssl-1.1.1d, ANDROID_NDK_HOME=/Users/jfc-idemobi/Library/Android/sdk/ndk/android-ndk-r20, OLDPWD=/Users/jfc-idemobi/Desktop/android-database-sqlcipher, APP_NAME_2800=Gradle, USER=jfc-idemobi, TMPDIR=/var/folders/jb/fxshpfxd6kv3ch96nbyvq31c0000gr/T/, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.JSqZtKZvvL/Listeners, XPC_FLAGS=0x0, TERM_SESSION_ID=0F5033B1-169E-43F5-AF6C-B3B5F1C61468, __CF_USER_TEXT_ENCODING=0x1F8:0x0:0x1, SQLCIPHER_DIR=/Users/jfc-idemobi/Desktop/android-database-sqlcipher/android-database-sqlcipher/src/main/external/sqlcipher, SQLCIPHER_OTHER_CFLAGS=-DLOG_NDEBUG -fstack-protector-all, NDK_APP_PLATFORM=16, com.apple.java.jvmTask=CommandLine, SQLCIPHER_CFLAGS=-DSQLITE_HAS_CODEC -DSQLITE_SOUNDEX -DHAVE_USLEEP=1 -DSQLITE_MAX_VARIABLE_NUMBER=99999 -DSQLITE_TEMP_STORE=3 -DSQLITE_THREADSAFE=1 -DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 -DNDEBUG=1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT3 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_ENABLE_DBSTAT_VTAB, SHLVL=1, HOME=/Users/jfc-idemobi, JAVA_MAIN_CLASS_2800=org.gradle.wrapper.GradleWrapperMain}
15:23:47.915 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
15:23:47.915 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'ndk-build'.
15:23:47.918 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
15:23:47.918 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'ndk-build'' finished with exit value -1 (state: FAILED)
15:23:47.918 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute doLast {} action for :android-database-sqlcipher:buildNative'
15:23:47.918 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute doLast {} action for :android-database-sqlcipher:buildNative' completed
15:23:47.918 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for {} from context.
15:23:47.923 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :android-database-sqlcipher:buildNative'
15:23:47.923 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :android-database-sqlcipher:buildNative' completed
15:23:47.923 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :android-database-sqlcipher:buildNative (Thread[Execution worker for ':',5,main]) completed. Took 0.015 secs.
15:23:47.923 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on :
15:23:47.923 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.13 completed (1 worker(s) in use)
15:23:47.923 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on root.1.13
15:23:47.923 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':',5,main]] finished, busy: 0.015 secs, idle: 0.001 secs
15:23:47.923 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 7,5,main]] finished, busy: 0.0 secs, idle: 0.014 secs
15:23:47.924 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 0.015 secs
15:23:47.924 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 0.015 secs
15:23:47.924 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 0.015 secs
15:23:47.924 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 0.015 secs
15:23:47.923 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 6,5,main]] finished, busy: 0.0 secs, idle: 0.015 secs
15:23:47.923 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Daemon worker Thread 11,5,main]] finished, busy: 0.0 secs, idle: 0.015 secs
15:23:47.924 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 0.017 secs
15:23:47.925 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
15:23:47.925 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
15:23:47.934 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
15:23:47.934 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 11: released lock on root.1
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':android-database-sqlcipher:buildNative'.
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > A problem occurred starting process 'command 'ndk-build''
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
15:23:47.934 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 7s

**Comment by jfcontart** [comment]
iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$ echo $ANDROID_HOME
/Users/jfc-idemobi/Library/Android
iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$ echo $ANDROID_SDK_ROOT
/Users/jfc-idemobi/Library/Android/sdk
iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$ echo $ANDROID_NDK_HOME
/Users/jfc-idemobi/Library/Android/sdk/ndk/android-ndk-r20
iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/jfc-idemobi/Library/Android/sdk/ndk/android-ndk-r20
iMac-2017-de-Jean-Francois:android-database-sqlcipher jfc-idemobi$

**Comment by jfcontart** [comment]
:android-database-sqlcipher:buildOpenSSL works with this NDK
:android-database-sqlcipher:buildAmalgamation works too ... 
and error in task  android-database-sqlcipher:buildNative FAILED

**Comment by jfcontart** [comment]
./gradlew :android-database-sqlcipher:buildNative --debug



15:45:51.229 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
15:45:51.230 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'ndk-build'.
15:45:51.232 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
15:45:51.232 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'ndk-build'' finished with exit value -1 (state: FAILED)

**Comment by jfcontart** [comment]
Find! 

error come from Catalina MacOS security. You need disable all certificats for the NDK and build tools.

**Comment by developernotes** [comment]
Hello @jfcontart 

I am happy to hear you were able to isolate the issue on your machine. The macOS security model on Catalina can be cumbersome for building this software.
