### ISSUE TITLE
CancellationSignal not using inside query method

### ISSUE THREAD

**Issue by aurangzaibumer777** [sqlcipher/android-database-sqlcipher#505]
one of the overloaded method of **query** takes an argument **Cancellation Signal** which has no assignment inside the class 

I'm using this library and need to interrupt the on-going sql queries - I figured Cancellation Signal does that job but since I'm bound to use the android database directly - I cannot be able to do that using this library

Please can anyone help me on this?

**Comment by developernotes** [comment]
Hi @aurangzaibumer777 

I think you are referring to [this](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2952-L2961) method, correct? We can certainly check to see if the signal has been set prior to executing the query itself following [parameter binding](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2959), however it would likely require heavier refactoring to funnel the `CancellationSignal` further into the stack without introducing breaking changes. Would that work for your situation?
