### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by Pymann** [sqlcipher/android-database-sqlcipher#506]
I discovered issue, about configuring the environment:

I added to the Makefile:
export JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64/
export ANDROID_NDK_HOME = /home/xxx/NVPACK (Codeworks from Nvidia)

and he complains about versions and license of android sdk, but thats not the problem:

now I try:
export JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64/
export ANDROID_NDK_HOME = /home/nikolai/ADK/ndk-bundle

but he still uses NVPACK path? So there sustains something in the enviroment, although i redownload the repo.

**Comment by developernotes** [comment]
Hi @Pymann 

Did you leave your modifications in the `Makefile`?

**Comment by Pymann** [comment]
As its written, yes. I can repoen terminal, then ANDROID_NDK_HOME is not set, but still the process uses NVPACK path.

**Comment by developernotes** [comment]
Hi @Pymann 

If you need to provide alternative path values for environment variables that are outside your current configuration, I would suggest including them on the command line directly, not within the `Makefile`.

```
ANDROID_NDK_HOME=/home/nikolai/ADK/ndk-bundle make build-release
```

We reserve GitHub Issues for reporting defects in the software library itself. If you have other build related questions, I would recommend you direct those to the [SQLCipher discuss](https://discuss.zetetic.net/c/sqlcipher) site. Thanks!
