### ISSUE TITLE
How can i be sure that database is successfully encrypted ? Is there any method like SQLCipherUtils.getDatabaseState() given by com.commonsware.cwac:saferoom library ?

### ISSUE THREAD

**Issue by rkkalkii** [sqlcipher/android-database-sqlcipher#510]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @rkkalkii 

We reserve GitHub Issues for reporting defects in the software library itself. This question would be a good fit for the SQLCipher community [discuss site](https://discuss.zetetic.net/c/sqlcipher). Please reconsider posting there. Thanks!
