### ISSUE TITLE
net.sqlcipher.database.SQLiteException  database is locked: BEGIN EXCLUSIVE;

### ISSUE THREAD

**Issue by smallmouse2009** [sqlcipher/android-database-sqlcipher#512]
### Expected Behavior
it will not crash
### Actual Behavior
I see the crash log on the server.
### Steps to Reproduce
I use greenDao with sqlcipher ,my database has several releated tables,  I have tried synchronized, lock，but it does not work. I have uese transaction.
SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
net.zetetic:android-database-sqlcipher:4.2.0
SQLCipher for Android version:
android9.0
[crash log.txt](https://github.com/sqlcipher/android-database-sqlcipher/files/4665893/crash.log.txt)

**Comment by developernotes** [comment]
Hi @smallmouse2009 

Is this a behavior you are able to reproduce using the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) without greenDao? If not, it may be either an issue with greenDao, or your utilization of the greenDao. It appears greenDao provides support via StackOverflow, more info [here](https://greenrobot.org/contact-support/). Thanks!

**Comment by smallmouse2009** [comment]
I uses greenDao in previous version without this issue. it shows after i use sqlcipher.  I guess it relates to the  push  process. When  i   start  push process, the app init twice time and the single Instance may  be useless. I will keep observing the issue next version.

**Comment by developernotes** [comment]
Hello @smallmouse2009 

I am not certain what you are referring to as a "push process", is that specific to your application, or greenDao?

**Comment by smallmouse2009** [comment]
I start a new process to implement the push function, and  the application will be init twice, and it may lead to the database have two connection.

**Comment by developernotes** [comment]
Hi @smallmouse2009 

>I start a new process to implement the push function, and the application will be init twice, and it may lead to the database have two connection.

This sounds like an application issue, rather than an issue with SQLCipher for Android itself. If you can provide additional information that points to SQLCipher for Android as being the cause, we would be happy to reconsider. Thanks!
