### ISSUE TITLE
Can not open the db file in DB Browser for Sqlite when i set the passphase.

### ISSUE THREAD

**Issue by ShshyDevooo** [sqlcipher/android-database-sqlcipher#514]
Can not open the db file in DB Browser for Sqlite when i set the passphase.

**Comment by developernotes** [comment]
Hi @ShshyDevooo 

To use DB Browser for SQLite with the latest versions of SQLCipher, you will need to utilize their nightly builds available [here](https://nightlies.sqlitebrowser.org/latest/). If you have any other questions, please feel free to reach out on the [SQLCipher Discuss community forum](https://discuss.zetetic.net/c/sqlcipher). Thanks!
