### ISSUE TITLE
java.lang.RuntimeException:Exception while computing database live data.

### ISSUE THREAD

**Issue by haohz1987** [sqlcipher/android-database-sqlcipher#515]
net.sqlcipher.database.SQLiteException:file is not a database: , while compiling: select count(*) from sqlite_master;

**Comment by developernotes** [comment]
Hi @haohz1987 

That is a common exception when using SQLCipher and providing the wrong password. We will need you to provide more details regarding the usage situation, code being executing, and possibly the stack trace generated. You may also consider attempting to reproduce the scenario within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Once we have more information, we can provide feedback. Thanks!
