### ISSUE TITLE
sqlite version

### ISSUE THREAD

**Issue by klqxx** [sqlcipher/android-database-sqlcipher#516]
Can sqlcipher @ 4a81bea module depend on sqlite3.31.0 be replaced with 3.32.1
Thanks!

**Comment by developernotes** [comment]
Hi @klqxx 

We update the SQLCipher submodule dependency as we make public SQLCipher core releases. When SQLCipher core is updated, we often rebase the upstream SQLite integration along side. If you have any other questions, please feel free to post in the SQLCipher community [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
