### ISSUE TITLE
Documentation on Encrypting an Existing Database

### ISSUE THREAD

**Issue by JasonCromer** [sqlcipher/android-database-sqlcipher#517]
### Expected Behavior
Documentation on encrypting an existing database should exist. Currently, no documentation or examples exist to show how to encrypt an existing Room database on Android. A lot of the documentation outlined online (and in the forums) points to the old SQL Cipher repository that is now considered deprecated. 
It would be useful to show what steps are necessary to encrypt an existing Room database.

### Actual Behavior
Documentation for this does not exist

### Steps to Reproduce
Check README

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
N/A

SQLCipher for Android version:
N/A

**Comment by developernotes** [comment]
Hello @JasonCromer 

Thank you for your interest in SQLCipher. As we do not directly control the Room/Support API itself, we tend to provide documentation to API specific differences only. For the Room/Support API, this can be found [here](https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-android-with-room) in our README which covers providing key material when creating a connection to the database.

Migrating a plaintext SQLite database to a SQLCipher database is specific to SQLCipher itself, not the client API. We provide all SQLCipher documentation [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/), with instructions on how to migrate a plaintext SQLite database to SQLCipher using `sqlcipher_export(...)` [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export), specifically with [example 1](https://www.zetetic.net/sqlcipher/sqlcipher-api/#example-1-encrypt-a-plaintext-database).

It appears you've [moved this discussion](https://discuss.zetetic.net/t/how-to-encrypt-existing-android-room-db/4547/4) to our SQLCipher Community forum already. We welcome your feedback there. Thanks!
