### ISSUE TITLE
Oppo Android 10 throws native crash

### ISSUE THREAD

**Issue by zerofield** [sqlcipher/android-database-sqlcipher#518]
Firebase console repoted that sqlcipher causes native crash on Oppo Android 10 Model: A9, A9x R15.
 
SQLCipher for Android version: 4.4.0

### crash log

Crashed: Thread :  SIGILL  0x00000000bda9bf28
#00 pc 0xbda9bf28 libsqlcipher.so 
#01 pc 0xbda92a26 libsqlcipher.so 
#02 pc 0xbda90aaa libsqlcipher.so 
#03 pc 0xbd9ef4f5 libsqlcipher.so 
#04 pc 0xbd9ee767 libsqlcipher.so 
#05 pc 0xbd9ee14b libsqlcipher.so 
#06 pc 0xbd9fe449 libsqlcipher.so 
#07 pc 0xbd9ff275 libsqlcipher.so 
#08 pc 0xbd9fe31b libsqlcipher.so 
#09 pc 0xbda0221b libsqlcipher.so 
#10 pc 0xbda01827 libsqlcipher.so 
#11 pc 0xbda17937 libsqlcipher.so 
#12 pc 0xbda14991 libsqlcipher.so 
#13 pc 0xbda16479 libsqlcipher.so 
#14 pc 0xbda0c4e3 libsqlcipher.so 
#15 pc 0xbda107a5 libsqlcipher.so

**Comment by developernotes** [comment]
Hi @zerofield 

Would you mind moving this report over to issue #507? We are tracking the issue related to Oppo devices there. Thanks!
