### ISSUE TITLE
net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;

### ISSUE THREAD

**Issue by android-codekyt** [sqlcipher/android-database-sqlcipher#520]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @android-codekyt 

Thank you for your interest in SQLCipher for Android. Please provide additional information regarding the situation you are reporting. Helpful information such as the following will allow us to help you:

- Steps to reproduce the behavior
- A stack trace with error
- The Android OS you experience the issue on
- The SQLCipher version you are utilizing
- A code sample to showcase the scenario (consider creating a reproduction test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests))

Unfortunately, the exception message you provided in the subject does not provide enough information. We would be happy to assist when further information is provided.

**Comment by markkelina** [comment]
Galaxy note 10
ANDROID Version  : 10
net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
The user throws an exception the first time the app is installed。why?

**Comment by developernotes** [comment]
Hi @markkelina 

When SQLCipher for Android attempts to open a connection to the database, if a password is provided it attempts to use the key material to read the database file. If it fails to decrypt data, a `SQLiteException` is thrown. We do not have enough information to ascertain specifics as to why you are receiving that error within your application. Generally, an invalid password is a common cause of this. I would recommend reviewing your application code first. A few questions to consider:

- Are you creating a new database file, or attempting to open an existing database file? 
- If that file exists, was it already encrypted with SQLCipher? 
- Can you open the database outside of your application?
- What version of SQLCipher was used to create the database file? 
- What version of SQLCipher are you using now?
- Are you able to reproduce the behavior? 

If you can reproduce the behavior, we would be happy to review a sample test case that you can create within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Providing more information about what you are attempting to do within your scenario is always helpful when trying to troubleshoot a scenario that is causing an issue.

**Comment by markkelina** [comment]
> Hi @markkelina
> 
> When SQLCipher for Android attempts to open a connection to the database, if a password is provided it attempts to use the key material to read the database file. If it fails to decrypt data, a `SQLiteException` is thrown. We do not have enough information to ascertain specifics as to why you are receiving that error within your application. Generally, an invalid password is a common cause of this. I would recommend reviewing your application code first. A few questions to consider:
> 
> * Are you creating a new database file, or attempting to open an existing database file?
> * If that file exists, was it already encrypted with SQLCipher?
> * Can you open the database outside of your application?
> * What version of SQLCipher was used to create the database file?
> * What version of SQLCipher are you using now?
> * Are you able to reproduce the behavior?
> 
> If you can reproduce the behavior, we would be happy to review a sample test case that you can create within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). Providing more information about what you are attempting to do within your scenario is always helpful when trying to troubleshoot a scenario that is causing an issue.

 implementation "net.zetetic:android-database-sqlcipher:4.4.0"
 implementation "androidx.sqlite:sqlite:2.0.1"

Galaxy note 10  can reproduce the problem

**Comment by developernotes** [comment]
Hello @markkelina 

While we certainly appreciate the code fragment that is generating the stack trace provided, many of the questions asked above were not addressed. Those questions will help us to understand the situation you are experiencing. Would you please provide answers to the following:

- Are you creating a new database file, or attempting to open an existing database file?
- If that file exists, was it already encrypted with SQLCipher?
- Can you open the database outside of your application?
- What version of SQLCipher was used to create the database file?

Additionally, since you can reproduce the issue on a Samsung Galaxy Note 10 device, can you please attempt to recreate the scenario within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). This will isolate the issue from your application itself and allow others to review the situation in full.

**Comment by arinobade** [comment]
Bonjour,
J'ai le même problème avec sqlcipher. Cependant le problème intervient lorsque j'obsfusque avec proguard rule.
Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)

**Comment by sarahedenyoung** [comment]
Hi,

I am seeing this same issue. Is there a known cause?

**Comment by developernotes** [comment]
Hi @arinobade, @sarahedenyoung,

Please consider reviewing [this](https://github.com/sqlcipher/android-database-sqlcipher/issues/520#issuecomment-710036005) response regarding the error. That specific error is common when an invalid password is provided to the database. If you are able to provide further details regarding the issue, please create a new [issue](https://github.com/sqlcipher/android-database-sqlcipher/issues/new/choose) with those details. Thanks!
