### ISSUE TITLE
net.sqlcipher.database.SQLiteException: database is locked

### ISSUE THREAD

**Issue by android-codekyt** [sqlcipher/android-database-sqlcipher#521]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @android-codekyt 

Thank you for your interest in SQLCipher for Android. Please provide additional information regarding the situation you are reporting. Helpful information such as the following will allow us to help you:

- Steps to reproduce the behavior
- A stack trace with error
- The Android OS you experience the issue on
- The SQLCipher version you are utilizing
- A code sample to showcase the scenario (consider creating a reproduction test within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests))

Unfortunately, the exception message you provided in the subject does not provide enough information. We would be happy to assist when further information is provided.
