### ISSUE TITLE
Why The latest AAR binary package (aar) exclude armeabi ? 

### ISSUE THREAD

**Issue by heyanwuliu** [sqlcipher/android-database-sqlcipher#523]
Why lateset version (aar)  exclude armeabi ? <--https://www.zetetic.net/sqlcipher/open-source/--><br>
 i am developing an app which will run on armeabi android devices, if will crash without  armeabi 

SQLCipher for Android version:  4.4.0

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by heyanwuliu** [comment]
@developernotes

**Comment by developernotes** [comment]
Hi @heyanwuliu 

Support for `armeabi` was dropped in NDK r17 ([ref](https://developer.android.com/ndk/guides/abis)). `armeabi-v7a` continues to be included in our current builds.

**Comment by heyanwuliu** [comment]
could your newest release aar will get armeabi back? because our app may run on earlier ndk version.
@developernotes thanks your reply in advance.

**Comment by heyanwuliu** [comment]
ps: in my view, ur aar can include all types of supported library, and the app can select which type will depend in gradle file. 
![image](https://user-images.githubusercontent.com/9313001/96663196-cc591b00-1382-11eb-8a5f-a31d257e5a93.png)

**Comment by developernotes** [comment]
Hello @heyanwuliu 

Does your application not work in this scenario?

```
ndk {
  abiFilters "armeabi-v7a", "arm64-v8a"
}
```

No, we do not plan to utilize an older NDK for future releases. You could consider creating a custom build from source using [this](https://github.com/sqlcipher/android-database-sqlcipher#building) information, or reach out to us directly for licensing a turnkey solution via Enterprise licensing at [support@zetetic.net](mailto:support@zetetic.net).
