### ISSUE TITLE
[maintenance] update OpenSSL to 1.1.1h

### ISSUE THREAD

**Issue by Skizu** [sqlcipher/android-database-sqlcipher#524]
Update built OpenSSL version to 1.1.1h from 1.1.1g.

### Expected Behavior
No change

### Actual Behavior
N/A

### Steps to Reproduce
N/A

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
N/A

SQLCipher for Android version:
4.4.0

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @Skizu 

We generally include the latest OpenSSL build when we release new versions of SQLCipher for Android which are tied to the public release of SQLCipher core. The next release will likely include 1.1.1h. Thanks!
