### ISSUE TITLE
How to change the encryption mode to another type, such as SM4？Consider supporting this type of encryptio Or open the extension function of encryption type。n，

### ISSUE THREAD

**Issue by jonydan888** [sqlcipher/android-database-sqlcipher#525]
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @jonydan888 

SQLCipher no longer supports runtime cipher changes and defaults to AES-256 in CBC mode. Can you provide additional information as to why you want to change ciphers within the library?

**Comment by jonydan888** [comment]
Due to the needs of the use scenarios and the banking industry, all of them should support the national secret algorithm, so the encryption algorithm needs to be changed，Can we give extended support？

**Comment by jonydan888** [comment]
@developernotes Due to the needs of the use scenarios and the banking industry, all of them should support the national secret algorithm, so the encryption algorithm needs to be changed，Can we give extended support？

**Comment by developernotes** [comment]
Hi @jonydan888 

Please feel free to reach out about Enterprise licensing at [support@zetetic.net](mailto:support@zetetic.net) when you have the opportunity to discuss this further. Thanks.
