### ISSUE TITLE
How can i known is passphrase correct before creating database?

### ISSUE THREAD

**Issue by TarasOryshhij** [sqlcipher/android-database-sqlcipher#529]
### Expected Behavior
It is Android application and Room. 
I wan't create database when user set his password. And i use this password to encrypt my database. This is my DI module:
 single {
        val passPhrase = getKoin().getProperty(PROPERTY_USER_PASSWORD, "")
        val passPhraseBytes: ByteArray = SQLiteDatabase.getBytes(passPhrase.toCharArray())
        val factory = SupportFactory(passPhraseBytes)

        Room.databaseBuilder(androidContext(), MyDatabase::class.java, DB_NAME)
            .openHelperFactory(factory)
            .build()
    }
    factory { get<MyDatabase>().accountsDao() }
}

### Actual Behavior
So now if user change login (or password), i wan't clear database. Because now i have runtime exception in case when user change password:
E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
    Process: com.test.test, PID: 28984
    java.lang.RuntimeException: Exception while computing database live data.
        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;

### Steps to Reproduce
Create database with one passwrod. Close application. Open application, and try create database with another password.

SQLCipher for Android version:
    implementation "net.zetetic:android-database-sqlcipher:4.4.1"
    implementation "androidx.sqlite:sqlite-ktx:2.1.0"

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @TarasOryshhij 

I'm not entirely sure I understand your situation exactly. Do you always have a SQLCipher encrypted database, or do you sometimes have a SQLite plaintext database? If the former, you can only attempt to access the database if you want to validate a given password is correct. If the latter, you can read the first 16 bytes of the database header and look for the [magic string](https://www.sqlite.org/fileformat.html#magic_header_string) identifier as SQLCipher uses this location to store the per-database salt and will not match.

**Comment by malik082009** [comment]
I was getting this  net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master; exception only in obfuscation case. 

I added default constructors for both `ByteArraySerializer` and `ByteArrayDeserializer` classes.

Note: don't add above classes as inner classes. Declare these classes independently add `keep` these classes in `proguard-rules`.
