### ISSUE TITLE
App is crashing after pragma rekey(or change password not working)

### ISSUE THREAD

**Issue by bestMechanic** [sqlcipher/android-database-sqlcipher#535]
Hi there,

Anyone have any idea about this query?
[App crash](https://stackoverflow.com/questions/65590023/how-to-change-the-sqlciper-password-in-android)

**Comment by developernotes** [comment]
Hi @bestMechanic 

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
