### ISSUE TITLE
Transaction listener is not called properly with nested transactions

### ISSUE THREAD

**Issue by oleksandr-semenov** [sqlcipher/android-database-sqlcipher#539]
### Expected Behavior
When using nested transactions listener is called each time when the outer or inner transaction starts and ends/rolls back
### Actual Behavior
The listener is not called in an expected way 
### Steps to Reproduce
Launch code with the nested transaction and observe the behavior 
https://github.com/sqlcipher/sqlcipher-android-tests/pull/39

SQLCipher version (can be identified by executing PRAGMA cipher_version;):
4.4.2 community

SQLCipher for Android version:
4.4.2

Note:
AndroidX SQLite database works as expected and dispatches all callbacks for nested and outer transactions.

**Comment by oleksandr-semenov** [comment]
Android tests: https://github.com/sqlcipher/sqlcipher-android-tests/pull/39

**Comment by developernotes** [comment]
Hello @oleksandr-semenov 

Unfortunately, the current Java implementation used within SQLCipher for Android does not allow nesting `SQLiteTransactionListener` instances (i.e., it only allows for [tracking a single listener](https://github.com/sqlcipher/android-database-sqlcipher/blob/b2be97e7d42e4ff8b755e88ab641159b00dd3eed/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L383), however, nested transactions are allowed). The current Google implementation of `android.database.sqlite` appears to support this via embedding the listener into a transaction object managed via a session connection pool. This may be something we revisit in a future release.

We will leave this ticket open for for review and further discussion in the future.
