### ISSUE TITLE
signal 11 (SIGSEGV) at sqlite3_bind_text16

### ISSUE THREAD

**Issue by eagle518** [sqlcipher/android-database-sqlcipher#543]
### Expected Behavior
03-08 21:00:55.068  4753 10269 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x50 in tid 10269 (Thread-7588), pid 4753 (main)
03-08 21:02:05.412 10438 10438 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-08 21:02:05.413 10438 10438 F DEBUG   : Build fingerprint: 'xiaomi/ginkgo/ginkgo:9/PKQ1.190616.001/V11.0.6.0.PCOCNXM:user/release-keys'
03-08 21:02:05.413 10438 10438 F DEBUG   : Revision: '0'
03-08 21:02:05.413 10438 10438 F DEBUG   : ABI: 'arm64'
03-08 21:02:05.413 10438 10438 F DEBUG   : pid: 4753, tid: 10269, name: Thread-7588  >>> goodcat <<<
03-08 21:02:05.413 10438 10438 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x50
03-08 21:02:05.413 10438 10438 F DEBUG   : Cause: null pointer dereference
03-08 21:02:05.413 10438 10438 F DEBUG   :     x0  0000000000000000  x1  0000000000000015  x2  0000000000004002  x3  0000000000000000
03-08 21:02:05.413 10438 10438 F DEBUG   :     x4  0000000000000000  x5  00000000ffffffff  x6  00000000ffffffff  x7  0000000000000000
03-08 21:02:05.413 10438 10438 F DEBUG   :     x8  0000000000000015  x9  000000002df20da3  x10 0000000000000009  x11 000000700ee0e688
03-08 21:02:05.413 10438 10438 F DEBUG   :     x12 000000700876fba8  x13 0000000000000000  x14 0000000000000004  x15 13e6307000000002
03-08 21:02:05.413 10438 10438 F DEBUG   :     x16 000000709325f328  x17 0000007093181bec  x18 0000000000000008  x19 0000006ff034af88
03-08 21:02:05.413 10438 10438 F DEBUG   :     x20 0000000000000002  x21 0000006ff0171588  x22 ffffffffffffffff  x23 00000070003d6620
03-08 21:02:05.413 10438 10438 F DEBUG   :     x24 0000000000000004  x25 0000000000000002  x26 0000006ff0171588  x27 0000000000000002
03-08 21:02:05.413 10438 10438 F DEBUG   :     x28 0000000000000002  x29 0000006ff0170ab0
03-08 21:02:05.413 10438 10438 F DEBUG   :     sp  0000006ff0170a80  lr  0000007004694b74  pc  0000007004694b9c
03-08 21:02:05.504 10438 10438 F DEBUG   : 
03-08 21:02:05.504 10438 10438 F DEBUG   : backtrace:
03-08 21:02:05.504 10438 10438 F DEBUG   :     #00 pc 0000000000067b9c  /system/lib64/libsqlcipher.so
03-08 21:02:05.504 10438 10438 F DEBUG   :     #01 pc 0000000000067894  /system/lib64/libsqlcipher.so
03-08 21:02:05.504 10438 10438 F DEBUG   :     #02 pc 0000000000068110  /system/lib64/libsqlcipher.so (sqlite3_bind_text16+32)
03-08 21:02:05.504 10438 10438 F DEBUG   :     #03 pc 00000000001b40fc  /system/lib64/libsqlcipher.so
03-08 21:02:05.504 10438 10438 F DEBUG   :     #04 pc 0000000000070a40  <anonymous:000000009fed7000>

### Steps to Reproduce
Hard to reproduce.

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
**"net.zetetic:android-database-sqlcipher:4.4.2"**

SQLCipher for Android version:
**Redmi Note 8 China & Android 9**

**Comment by developernotes** [comment]
Hi @eagle518 

Thank you for your crash report. Can you share some additional information:

- What SQL commands are being run when this crash occurs?
- Are multiple threads accessing the database concurrently?
- Did you build SQLCipher for Android yourself, or are you using a Community or Commercial build?
- Have you tried to [create a separate unit test](https://github.com/sqlcipher/sqlcipher-android-tests#creating-a-new-test) within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by eagle518** [comment]
> Hi @eagle518
> 
> Thank you for your crash report. Can you share some additional information:
> 
> * What SQL commands are being run when this crash occurs?
//TODO...

> * Are multiple threads accessing the database concurrently?
Only signal thread.

> * Did you build SQLCipher for Android yourself, or are you using a Community or Commercial build?
Using Community version.

> * Have you tried to [create a separate unit test](https://github.com/sqlcipher/sqlcipher-android-tests#creating-a-new-test) within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
Did not.
