### ISSUE TITLE
Is there any way to build with dynamic linking of openssl?

### ISSUE THREAD

**Issue by 09ae9c** [sqlcipher/android-database-sqlcipher#546]
Hi,

We have a custom openssl so file in our project and  we want to use it for libsqlcipher, so that can reduce so file size(now the arm64 libsqlcipher.so is 3.3M, we think it is too large), how can I build this project to change openssl as a dynamic linking?

**Comment by developernotes** [comment]
Hi @09ae9c 

Thanks for your interest in SQLCipher. We reserve GitHub Issues for reporting defects in the software library only. Please feel free to post this question to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
