### ISSUE TITLE
App is getting slower

### ISSUE THREAD

**Issue by bhanu-mds** [sqlcipher/android-database-sqlcipher#549]
### update app with the latest gradle dependency and updated version

SQLCipher version (can be identified by executing `PRAGMA 4.4.3@aar;`):

SQLCipher for Android version: 
Application is getting slower after update the lib to the updated versions on android 4 & 5 versions.
badly stuck in that, please look into this.

**Comment by developernotes** [comment]
Hi @bhanu-mds 

What previous version of the library were you using?

**Comment by bhanu-mds** [comment]
Hi, Thanks for the response, I am using this ***@***.***’And if I update lib to latest version, android 4 & 5 versions getting slower. Thanks & Regards_________________________ Bhanu Verma, Sr. Software EngineerMetaDesign Solutions Pvt Ltd.Your Trusted Software Services PartnerISO 9001:2008 Certified Mobile Number: +91- 90451-36276USA Office:     +1 (917) 728-1770UK Office:      +44 (208) 089-9360AUS Office:     +61 (731) 180-0630 Skype : Bhanu_243Email :  ***@***.***Website: www.metadesignsolutions.com  From: Nick ParkerSent: Tuesday, June 1, 2021 5:36 PMTo: sqlcipher/android-database-sqlcipherCc: bhanu-mds; MentionSubject: Re: [sqlcipher/android-database-sqlcipher] App is getting slower (#549) Hi @bhanu-mdsWhat previous version of the library were you using?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by developernotes** [comment]
Hello @bhanu-mds 

What was the previous version of SQLCipher for Android which you were using? I was unable to find an answer in your previous email.

**Comment by bhanu-mds** [comment]
Hi, I am using sqlcipher version - ***@***.***  Thanks & Regards_________________________ Bhanu Verma, Sr. Software EngineerMetaDesign Solutions Pvt Ltd.Your Trusted Software Services PartnerISO 9001:2008 Certified Mobile Number: +91- 90451-36276USA Office:     +1 (917) 728-1770UK Office:      +44 (208) 089-9360AUS Office:     +61 (731) 180-0630 Skype : Bhanu_243Email :  ***@***.***Website: www.metadesignsolutions.com  From: Nick ParkerSent: Wednesday, June 2, 2021 6:37 PMTo: sqlcipher/android-database-sqlcipherCc: bhanu-mds; MentionSubject: Re: [sqlcipher/android-database-sqlcipher] App is getting slower (#549) Hello @bhanu-mdsWhat was the previous version of SQLCipher for Android which you were using? I was unable to find an answer in your previous email.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by developernotes** [comment]
Hello @bhanu-mds 

Would you try replying to the GitHub Issue [here](https://github.com/sqlcipher/android-database-sqlcipher/issues/549) instead of by email? It appears your email is stripping out the version number. We aren't able to read your reply in full.

**Comment by bhanu-mds** [comment]
I am currently using this version - 3.5.7@aar

**Comment by developernotes** [comment]
Hi @bhanu-mds 

Since you are updating from an older major version of SQLCipher, I would recommend reviewing the SQLCipher 4 upgrade document [here](https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283). On Android, the slow down you are experiencing may be attributed to the performance of the memory wiping feature enabled by default in SQLCipher 4. You may wish to review the documentation [here](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_memory_security) which addresses disabling it if desired.
