### ISSUE TITLE
Application is crashing after updated to android 10

### ISSUE THREAD

**Issue by bhanu-mds** [sqlcipher/android-database-sqlcipher#550]
### can't reproduce 

SQLCipher version (can be identified by executing `PRAGMA 3.5.7@aar;`):

SQLCipher for Android version:
Android application is crashing in a higher volume, there is thousands of non-fatal and fatal crashes reported in android 4 & 5 versions. 

Non-fatal Exception: android.database.sqlite.SQLiteException
cannot rollback - no transaction is active (code 1)
android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)

Fatal Exception: android.database.sqlite.SQLiteException
cannot rollback - no transaction is active (code 1) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (cannot rollback - no transaction is active (code 1)) #################################################################
android.database.sqlite.SQLiteConnection.nativeExecute
android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)

**Comment by developernotes** [comment]
Hi @bhanu-mds 

Would you please try recreating the issue you are experiencing within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? We would be happy to look into a reproducible scenario. Thanks!

**Comment by bhanu-mds** [comment]
Hi,  We have only this, We are unable to reproduce it. Fatal Exception: android.database.sqlite.SQLiteExceptioncannot rollback - no transaction is active (code 1)  android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)android.database.sqlite.SQLiteConnection.execute (SQLiteConnection.java:555)android.database.sqlite.SQLiteSession.endTransactionUnchecked (SQLiteSession.java:439)android.database.sqlite.SQLiteSession.endTransaction (SQLiteSession.java:401)android.database.sqlite.SQLiteDatabase.endTransaction (SQLiteDatabase.java:522)androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction (FrameworkSQLiteDatabase.java:90)androidx.work.impl.WorkDatabase$2.onOpen (WorkDatabase.java:169)androidx.work.impl.WorkDatabase_Impl$1.onOpen (WorkDatabase_Impl.java:113)androidx.room.RoomOpenHelper.onOpen (RoomOpenHelper.java:136)androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen (FrameworkSQLiteOpenHelper.java:195)android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:266)android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:163)androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase (FrameworkSQLiteOpenHelper.java:145)androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase (FrameworkSQLiteOpenHelper.java:106)androidx.room.RoomDatabase.beginTransaction (RoomDatabase.java:352)androidx.work.impl.utils.ForceStopRunnable.cleanUp (ForceStopRunnable.java:156)androidx.work.impl.utils.ForceStopRunnable.run (ForceStopRunnable.java:87)androidx.work.impl.utils.SerialExecutor$Task.run (SerialExecutor.java:91)java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)java.lang.Thread.run (Thread.java:818)  Thanks & Regards_________________________ Bhanu Verma, Sr. Software EngineerMetaDesign Solutions Pvt Ltd.Your Trusted Software Services PartnerISO 9001:2008 Certified Mobile Number: +91- 90451-36276USA Office:     +1 (917) 728-1770UK Office:      +44 (208) 089-9360AUS Office:     +61 (731) 180-0630 Skype : Bhanu_243Email :  ***@***.***Website: www.metadesignsolutions.com  From: Nick ParkerSent: Tuesday, June 1, 2021 5:38 PMTo: sqlcipher/android-database-sqlcipherCc: bhanu-mds; MentionSubject: Re: [sqlcipher/android-database-sqlcipher] Application is crashing after updated to android 10 (#550) Hi @bhanu-mdsWould you please try recreating the issue you are experiencing within the SQLCipher for Android test suite? We would be happy to look into a reproducible scenario. Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by developernotes** [comment]
Hi @bhanu-mds 

That exception is just reporting that you are attempting to rollback a transaction that you did not start. That is most likely an application usage issue.
