### ISSUE TITLE
exception  for native_execSQL

### ISSUE THREAD

**Issue by zhangchaojiong** [sqlcipher/android-database-sqlcipher#552]
online log ：
`
#00 pc 000ce5e8 /data/app/com.tct.tctplus-UlzOMJIcvXbhhvUmDg69aA==/lib/arm/libsqlcipher.so
at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native method)
at net.sqlcipher.database.SQLiteDatabase.execSQL(SourceFile:4)
at net.sqlcipher.database.SQLiteDatabase.endTransaction(SourceFile:15)
at com.commonsware.cwac.saferoom.b.endTransaction(SourceFile:1)
at androidx.room.RoomDatabase.endTransaction(SourceFile:1)
`

SQLCipher for Android version:
jetified-android-database-sqlcipher-4.3.0

I don't know what my problem is. Can you guys help me figure it out?

**Comment by zhangchaojiong** [comment]
I try to get the error code line by addr2line. but I get the result is `??:?`
```
/Users/jiong/androidndk/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line
  -e /Users/jiong/Desktop/libsqlcipher.so 000ce5e8
??:?
```

**Comment by developernotes** [comment]
Hi @zhangchaojiong 

What is the exception message that is being thrown? Are you able to recreate the issue with your code within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by wolfrex-666** [comment]
你这个问题解决了不？

**Comment by zhangchaojiong** [comment]
@wolfrex-666 it still exists

**Comment by developernotes** [comment]
Hi @zhangchaojiong 

Would you take a look at [this](https://github.com/sqlcipher/android-database-sqlcipher/issues/552#issuecomment-859597950) and let us know if you are able to recreate the issue? Thanks!

**Comment by zhangchaojiong** [comment]
@developernotes 
It cannot recreate the issue. I have already compiled `sqlcipher.so ` by myself and added the -g CFLAG. 
I ready to check the online log of the next version ，and to find the problem through addr2line
