### ISSUE TITLE
Getting type error on passing SafeHelperFactory to openHelperFactory

### ISSUE THREAD

**Issue by uplamartya** [sqlcipher/android-database-sqlcipher#554]
<img width="1090" alt="Screenshot 2021-06-28 at 5 43 12 PM" src="https://user-images.githubusercontent.com/47631015/123634730-705f6400-d838-11eb-88a3-2ea8c7a1c0e4.png">

**Comment by uplamartya** [comment]
Does, anyone have any idea about what am  I missing?

**Comment by developernotes** [comment]
Hi @uplamartya 

You might compare your Gradle build file with that found in the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests/blob/master/app/build.gradle), along with your imports.

**Comment by uplamartya** [comment]
Hi @developernotes 
Thanks for your quick reply , but I am using support-v7 & don't want to upgrade to android x. And room version is of android x . Is there any other way to fix this?

**Comment by uplamartya** [comment]
This issue still exist

**Comment by developernotes** [comment]
Hi @uplamartya 

If you are using SQLCipher for Android, you will need to use the `SupportFactory` when using the `Room.databaseBuilder` API.
