### ISSUE TITLE
Getting error No implementation found for void net.sqlcipher.database.SQLiteDatabase.dbopen(java.lang.String, int) (tried Java_net_sqlcipher_database_SQLiteDatabase_dbopen and Java_net_sqlcipher_database_SQLiteDatabase_dbopen__Ljava_lang_String_2I)

### ISSUE THREAD

**Issue by moylir** [sqlcipher/android-database-sqlcipher#557]
### Expected Behavior

Database opens and can be managed,

### Actual Behavior

It throws the error mentioned in the title when executing the following instruction:

    database = dbHelper.getWritableDatabase("mypass");

### Steps to Reproduce

This happens if I execute the code in a Redmi device (likely. it also happens in others ), it works nice in Android emulartor.

SQLCipher for Android version:

4.4.3

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

No.

**Comment by developernotes** [comment]
Hi @moylir 

What are your results when you run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the Redmi device?

**Comment by moylir** [comment]
Hi @developernotes, all tests are succesful, except for the encrypt bytes test, which says: net.sqlcipher.database.SQLiteException-, no such function-, sqlcipher_vle_encrypt:, while compiling: select sqlcipher_vle_encrypt(?, ?).

On the other hand, I've checked that for opening the database you use an object in a different way to the one I'm using, your way in the test suite is: 
        final SupportSQLiteDatabase _db = super.getOpenHelper().getWritableDatabase();

The datatabase I'm refering to in the posted code is of the type net.sqlcipher.database.SQLiteDatabase, so maybe that has to do with the problem, anyway, as told, it works nicely in emulatos but not in Redmi device.

**Comment by developernotes** [comment]
Hi @moylir 

>all tests are succesful, except for the encrypt bytes test, which says: net.sqlcipher.database.SQLiteException-, no such function-, sqlcipher_vle_encrypt:, while compiling: select sqlcipher_vle_encrypt(?, ?).

Just to confirm, all tests are successful when you run the test suite on a Redmi device? The the `sqlcipher_vle_encrypt` function is only available via the Commercial/Enterprise builds of SQLCipher for Android.

**Comment by moylir** [comment]
Hi @developernotes

Yes, for all the other ones it said they were OK.

**Comment by developernotes** [comment]
Hi @moylir 

Excellent, this likely means the issue is specific to your project. 

- Are you using the Gradle `splits` behavior to exclude specific ABI's?
- Are you using the prebuilt Community edition of SQLCipher for Android, or building your own version of the library?

**Comment by moylir** [comment]
Hi @developernotes.

I didn't exclude any specific ABI. Indeed I tried to include more, just in case, using ndk.abiFilters command in gradle, but didn't help.

I'm using the prebuilt edition, did that setting these dependencies in gradle:

    implementation (name: 'android-database-sqlcipher-4.4.3', ext: 'aar')
    implementation "androidx.sqlite:sqlite:2.0.1"

Also tried, to change to androidx.sqlite:sqlite:2.1.0 (last version), just in case, but to no avail.
