### ISSUE TITLE
Native crash net.sqlcipher.CursorWindow.close_native

### ISSUE THREAD

**Issue by bagadesh** [sqlcipher/android-database-sqlcipher#559]
### Happening in production. we could not reproduce the issue

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`): 4_4_2

SQLCipher for Android version: 

Device: Huawei HUAWEI Y6 Pro 2019

Android Version: 9

`
backtrace:
  #00  pc 000000000007900e  /system/lib/libc.so (je_huge_salloc+134)
  #00  pc 000000000007e489  /system/lib/libc.so (ifree+260)
  #00  pc 000000000007e827  /system/lib/libc.so (je_free+70)
  #00  pc 00000000000b5869  /data/app/com.zoho.crm-rE9jgbRYSX2eZNix5MVurA==/split_config.armeabi_v7a.apk!lib/armeabi-v7a/libsqlcipher.so (offset 0x4b8000) (sqlcipher::CursorWindow::~CursorWindow()+28)
  #00  pc 00000000000b495f  /data/app/com.zoho.crm-rE9jgbRYSX2eZNix5MVurA==/split_config.armeabi_v7a.apk!lib/armeabi-v7a/libsqlcipher.so (offset 0x4b8000)
  #00  pc 00000000000d483b  /data/app/com.zoho.crm-rE9jgbRYSX2eZNix5MVurA==/oat/arm/base.odex (offset 0xd1000) (net.sqlcipher.CursorWindow.close_native [DEDUPED]+74)
  #00  pc 000000000042e375  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
  #00  pc 00000000004011c1  /system/lib/libart.so (art_quick_invoke_stub+224)
  #00  pc 00000000000a82b9  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
  #00  pc 00000000001f0529  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
  #00  pc 00000000001eb017  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+814)
  #00  pc 00000000003fcc89  /system/lib/libart.so (MterpInvokeDirect+196)
  #00  pc 0000000000421114  /system/lib/libart.so (ExecuteMterpImpl+14484)
  #00  pc 0000000000cd3e62  /data/app/com.zoho.crm-rE9jgbRYSX2eZNix5MVurA==/oat/arm/base.vdex (net.sqlcipher.CursorWindow.finalize+18)
  #00  pc 00000000001cf793  /system/lib/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.589044918)+378)
  #00  pc 00000000001d3dbf  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
  #00  pc 00000000003ebd3d  /system/lib/libart.so (artQuickToInterpreterBridge+880)
  #00  pc 00000000004328ff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
  #00  pc 000000000018fac7  /system/framework/arm/boot-core-libart.oat (offset 0x8d000) (java.lang.Daemons$FinalizerDaemon.doFinalize+86)
  #00  pc 000000000018fd23  /system/framework/arm/boot-core-libart.oat (offset 0x8d000) (java.lang.Daemons$FinalizerDaemon.runInternal+466)
  #00  pc 000000000012b5b3  /system/framework/arm/boot-core-libart.oat (offset 0x8d000) (java.lang.Daemons$Daemon.run+66)
  #00  pc 0000000000270911  /system/framework/arm/boot.oat (offset 0x132000) (java.lang.Thread.run+64)
  #00  pc 000000000042e375  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
  #00  pc 00000000004011c1  /system/lib/libart.so (art_quick_invoke_stub+224)
  #00  pc 00000000000a82b9  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
  #00  pc 000000000035e36d  /system/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
  #00  pc 000000000035f0c5  /system/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+320)
  #00  pc 0000000000380ba3  /system/lib/libart.so (art::Thread::CreateCallback(void*)+866)
  #00  pc 0000000000064975  /system/lib/libc.so (__pthread_start(void*)+22)
  #00  pc 000000000001e875  /system/lib/libc.so (__start_thread+24)`

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @bagadesh 

Thank you for using SQLCipher for Android! Unfortunately, your post does not provide enough additional information to further diagnose the issue you reported. Below are some additional questions to consider regarding the issue you are experiencing:

- Are you using the Community edition, Commercial edition, or a custom build of SQLCipher for Android?
- What code is executing when this crash occurs?
- What Android OS version and architecture type is the crash occurring on?
- Are you using ABI splits when generating your APK?
- Do you have the offending device available for testing purposes?
- Have you run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on the offending device?
- Have you created a new test within the [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) to isolate the behavior of your application and attempt reproduction?
