### ISSUE TITLE
Outdated SQLCIPHER_ANDROID_VERSION in build documentation

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#562]
### Expected Behavior

`SQLCIPHER_ANDROID_VERSION` in `README.md` is consistent with the recent SQLCipher version

Major bonus: build scripts retrieve the correct value from SQLCipher itself if `SQLCIPHER_ANDROID_VERSION` is not defined

### Actual Behavior

`SQLCIPHER_ANDROID_VERSION` has outdated version `4.4.2` in `README.md`

### Steps to Reproduce

Visual inspection of `README.md`

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

`4.4.3`

SQLCipher for Android version:

`4.4.3`

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

N/A

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

### Further notes

Yes it should be extremely easy for me or someone else to raise a PR to fix this in the doucmentation

But I am thinking it would be better if the build could automatically extract the correct value from the SQLCipher sources.

**Comment by developernotes** [comment]
Hi @brodybits 

Thanks for reporting the version discrepancy. While we do have a image tag that renders the current version available published to Maven Central, it would be nice if there was a more automated approach to rendering the latest version as a string value.
