### ISSUE TITLE
Build instructions need some clarification regarding external dependencies

### ISSUE THREAD

**Issue by brodybits** [sqlcipher/android-database-sqlcipher#565]
### Expected Behavior

In <https://github.com/sqlcipher/android-database-sqlcipher#building>:

- It is clear to me whether intermediate build artifacts of OpenSSL & SQLCipher are generated in-place or in some intermediate, temporary build location.
- It is clear to me how to make the build work with external checkouts of OpenSSL & SQLCipher from GitHub, *outside* this project
- ~~It is clear to me what kind of a directory, with relative or absolute path is needed for `OPENSSL_ANDROID_LIB_ROOT`~~ - _now outdated by e4eb1a8982ea4e269985894494ca9830c5362d04_
- _It is clear to me whether or not I need to define anything specific for SQLite / SQLCipher build flags_

### Actual Behavior

- I discovered that the intermediate build artifacts of both OpenSSL & SQLCipher are generated in-place
- _documented SQLCipher build flags lead to features such as FTS5, JSON1, and R-Tree not enabled, leading to failures in sqlcipher-android-tests_

_now outdated by e4eb1a8982ea4e269985894494ca9830c5362d04:_

- ~~After some trial-and-error I had to do the following to get the build and link to work with OpenSSL:~~
  - ~~extract a version of OpenSSL into my local build of this project~~
  - ~~do something like `mkdir android-libs` to get a library build directory I could use for `OPENSSL_ANDROID_LIB_ROOT`~~
  - ~~use absolute path for `OPENSSL_ANDROID_LIB_ROOT`~~

~~I don't want to imply that I am correct, only that this is the only way I was able to get the build to work so far.~~

### Steps to Reproduce

see above

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

`4.4.3`

SQLCipher for Android version:

`4.4.3`

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

N/A

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

### Moving forward

- I would appreciate some feedback if I was missing anything important
- I would like to find a way to improve the documentation, hope to contribute with time permitting
- I think it would be ideal to find a way to support building from external clones of OpenSSL & SQLCipher from GitHub _using temporary build directories for the intermediate build outputs_.

**Comment by developernotes** [comment]
Hi @brodybits 

I just pushed up a change to the `master` branch to help address this. `OPENSSL_ANDROID_LIB_ROOT` is no longer needed for the build. The build requires that you externally provide both a SQLCipher core source directory, an OpenSSL source directory, and some additional metadata around the build such as the version and CFLAGS to use:

```
SQLCIPHER_ROOT=/some/path/to/sqlcipher-folder \
OPENSSL_ROOT=/some/path/to/openssl-folder \
SQLCIPHER_ANDROID_VERSION="4.4.3" \
SQLCIPHER_CFLAGS="-DSQLITE_HAS_CODEC" \
make build-release
```

Please note that both SQLCipher and OpenSSL do not need to exist _within_ the SQLCipher for Android directory tree, but you do have to provide a path to their respective directories. Please let me know if you feel anything else needs clarification. Thanks!

**Comment by brodybits** [comment]
> I just pushed up a change to the `master` branch to help address this.
> [...]

e4eb1a8982ea4e269985894494ca9830c5362d04 - thanks for the update.

I will give it a try together with PR #564 and expect to give my feedback later today or tonight.

(I will likely rebase PR #564 again as well.)

**Comment by brodybits** [comment]
I tried building and running with e4eb1a8 together with PR #564 in the test suite, using external OpenSSL & SQLCipher from GitHub. I would like to report a couple of observations:

- some intermediate, ignored build artifacts are generated in both external `openssl` and `sqlcipher` git projects
- using `SQLCIPHER_CFLAGS` as directed in the README disables features such as JSON1, R-Tree, and FTS5, leading to some failures in the sqlcipher-android-tests

I think the use of `SQLCIPHER_CFLAGS` should be documented as an optional setting, or perhaps even removed from README.md.

**Comment by developernotes** [comment]
Hi @brodybits,

>some intermediate, ignored build artifacts are generated in both external openssl and sqlcipher git projects

Yes, this is expected from the build process.

>using SQLCIPHER_CFLAGS as directed in the README disables features such as JSON1, R-Tree, and FTS5, leading to some failures in the sqlcipher-android-tests

`SQLCIPHER_CFLAGS` is optional. We do not want to remove it as it allows the developer who is build SQLCipher for Android to [override the defaults](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/build.gradle#L81-L105) (if necessary) allowing control over what features SQLCipher includes. I will include additional documentation clarifying that within the README.

Thank you for the feedback.
