### ISSUE TITLE
x64 and Android 11+ support

### ISSUE THREAD

**Issue by terrycom9581** [sqlcipher/android-database-sqlcipher#571]
Does this project support x64 and android 11+? If not, do you plan to update this project?

**Comment by terrycom9581** [comment]
Would you give me a kind of sample configuration for this? for latest version, i mean

**Comment by developernotes** [comment]
Hi @terrycom9581 

Information regarding usage of the latest version is available [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android/).
