### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException cannot rollback - no transaction is active (code 1)

### ISSUE THREAD

**Issue by bhanu-mds** [sqlcipher/android-database-sqlcipher#573]
2 different crash 

Application is crashing in android 4 and android 5 versions, 

1. Fatal Exception: android.database.sqlite.SQLiteException
cannot rollback - no transaction is active (code 1) ################################################################# Error Code : 1 (SQLITE_ERROR) Caused By : SQL(query) error or missing database. (cannot rollback - no transaction is active (code 1)) #################################################################

2. Fatal Exception: android.database.sqlite.SQLiteException cannot rollback - no transaction is active (code 1)

code line - android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)

### Steps to Reproduce
Random issue.

'net.zetetic:android-database-sqlcipher:3.5.7@aar'

SQLCipher for Android version:
android 4 - android 5

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
no

**Comment by developernotes** [comment]
Hello @bhanu-mds,

Thank you for your interest in SQLCipher. Unfortunately, there is not enough information to ascertain a cause. Based on the exception however, it would appear that the client code is attempting to rollback a transaction that has not started. I would suggest evaluating the application usage of SQLCipher for Android and attempt to isolate the scenario that is presenting the issue. At some point, you may consider upgrading to the latest version of SQLCipher For Android, which is currently at 4.5.0.
