### ISSUE TITLE
No implementation found for native Lnet/sqlcipher/database/SQLiteDatabase;.dbopen (Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by pstegegn** [sqlcipher/android-database-sqlcipher#58]
06-26 11:38:53.559: W/dalvikvm(22382): No implementation found for native Lnet/sqlcipher/database/SQLiteDatabase;.dbopen (Ljava/lang/String;I)V
06-26 11:38:53.559: D/AndroidRuntime(22382): Shutting down VM
06-26 11:38:53.559: W/dalvikvm(22382): threadid=1: thread exiting with uncaught exception (group=0x40018560)
06-26 11:38:53.569: E/AndroidRuntime(22382): FATAL EXCEPTION: main
06-26 11:38:53.569: E/AndroidRuntime(22382): java.lang.UnsatisfiedLinkError: dbopen
06-26 11:38:53.569: E/AndroidRuntime(22382):    at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:2030)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:931)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1010)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:236)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at com.viber.voip.contacts.ViberContactsProvider.onCreate(ViberContactsProvider.java:53)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.content.ContentProvider.attachInfo(ContentProvider.java:798)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.app.ActivityThread.installProvider(ActivityThread.java:3706)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:3461)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3417)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.app.ActivityThread.access$2200(ActivityThread.java:123)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:977)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.os.Looper.loop(Looper.java:130)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at android.app.ActivityThread.main(ActivityThread.java:3835)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at java.lang.reflect.Method.invokeNative(Native Method)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at java.lang.reflect.Method.invoke(Method.java:507)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
06-26 11:38:53.569: E/AndroidRuntime(22382):    at dalvik.system.NativeStart.main(Native Method)
06-26 11:38:53.589: W/ActivityManager(224):   Force finishing activity com.viber.voip/.Encrypt
06-26 11:38:54.089: W/ActivityManager(224): Activity pause timeout for HistoryRecord{4057b378 com.viber.voip/.Encrypt}

**Comment by svaithia** [comment]
I forgot to call `SQLiteDatabase.loadLibs(this);` in my MainActivity, which gave me this error.

Once I added it, the code seemed to work fine for me.
