### ISSUE TITLE
native crash signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000007f5c1feed8

### ISSUE THREAD

**Issue by daogepiqian** [sqlcipher/android-database-sqlcipher#580]
i dont know what case will  make this crash, 
version 4.5.0
log:
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000007f5c1feed8
  x0   0000007f589f0eca  x1   0000000000000000  x2   000000000000000c  x3   0000000000000030
  x4   fffffffffffffff0  x5   0000000000000040  x6   000000000000003f  x7   0000000000000000
  x8   0000007f589f0ffc  x9   0000000000000004  x10  0000007f87380000  x11  0000000000000002
  x12  0000000000000001  x13  0000000000000081  x14  0000000000000081  x15  fffffffffffff000
  x16  0000007f62174580  x17  0000007f872f1f00  x18  0000000002f3b000  x19  0000007f589f0eca
  x20  0000000000000132  x21  0000000000102eba  x22  0000007f5c1feed8  x23  0000000000000022
  x24  0000000000000064  x25  0000000000000000  x26  0000000000000000  x27  0000000000000022
  x28  0000000000000003  x29  0000000000000000  x30  0000007f61fc5160
  sp   0000007f57fd3dc0  pc   0000007f61fc5160  pstate 0000000020000000
  v0   8f5c0683ccd7a92c357742fe29e4f631  v1   0ca160cfafb6bb5077ee2cb097eb6129
  v2   8f5c0683ccd7a92c357742fe29e4f631  v3   a63ef166129c515654f62164d37c8dc0
  v4   67697326383134343733373336313d74  v5   ff342e31323933383036313730333861
  v6   52896310d9b1e4cc1347f445cb98d375  v7   b7c554285b59261e76fa5e2a8d6df22b
  v8   00000000000000000000007f57fd4b20  v9   00000000000000000000000000000029
  v10  00000000000000000000007f57fd4b10  v11  00000000000000000000007f843b3408
  v12  00000000000000000000007f843b4320  v13  00000000000000000000007f843b3430
  v14  00000000000000000000000000000004  v15  00000000000000000000000000000000
  v16  abf925ca927b010d72cb2cef068fba1f  v17  11fba54e49c57748220c7f4e5e117feb
  v18  eecf8b7f7bfc4470123a4e796e22478a  v19  52896310d9b1e4cc1347f445cb98d375
  v20  398224c7e0b02de2744496f02f1beb7a  v21  7d7b040e9b2d93d7867588235eb20695
  v22  d932092594f4bb125b5f7d8a4cb2a95c  v23  e65697d91d581bf4d8c78eb6783b9562
  v24  7036ee007036ee007036ee0070b282e0  v25  00000000000000000000000000000000
  v26  0000000000000000ffffffffffffffff  v27  0000000000000000080101011c030303
  v28  00000000000000000000000042340000  v29  00000000000000000000000041f00000
  v30  00000000000000008080808080808080  v31  0000000000000000000000003f000000
  fpsr 0800001b  fpcr 00000000
    #00 pc 0x14c160 libsqlcipher.so (_ZN9sqlcipher12CursorWindow8allocRowEv+92)
    #01 pc 0x149b9c libsqlcipher.so
    #02 pc 0x4014054 data@app@com.shuqi.controller-1@base.apk@classes.dex
    --- --- --- ---
memory near x0:
    0000007f589f0e88 0031003600610066 0039003300320063  f.a.6.1.c.2.3.9.
    0000007f589f0e98 0039003200660062 0063006100300066  b.f.2.9.f.0.a.c.
    0000007f589f0ea8 0038003100340038 0031003700300033  8.4.1.8.3.0.7.1.
    0000007f589f0eb8 0033003800300036 002e003100320039  6.0.8.3.9.2.1...
    0000007f589f0ec8 0000000000000034 0000000000000000  4...............
    0000007f589f0ed8 0000000000000000 0000000000000000  ................
    0000007f589f0ee8 0000000000000000 0000000000000000  ................
    0000007f589f0ef8 0000000000000000 0000000000000000  ................
    0000007f589f0f08 0000000000000000 0000000000000000  ................
    0000007f589f0f18 0000000000000000 0000000000000000  ................
    0000007f589f0f28 0000000000000000 0000000000000000  ................
    0000007f589f0f38 0000000000000000 0000000000000000  ................
    0000007f589f0f48 0000000000000000 0000000000000000  ................
    0000007f589f0f58 0000000000000000 0000000000000000  ................
    0000007f589f0f68 0000000000000000 0000000000000000  ................
    0000007f589f0f78 0000000000000000 0000000000000000  ................
memory near x8:
    0000007f589f0fb8 0000000000000000 0000000000000000  ................
    0000007f589f0fc8 0000000000000000 0000000000000000  ................
    0000007f589f0fd8 0000000000000000 0000000000000000  ................
    0000007f589f0fe8 0000000000000000 0000000000000000  ................
    0000007f589f0ff8 0000000000000000 0000000000000000  ................
    0000007f589f1008 0000000000000000 0000000000000000  ................
    0000007f589f1018 0000000000000000 0000000000000000  ................
    0000007f589f1028 0000000000000000 0000000000000000  ................
    0000007f589f1038 0000000000000000 0000000000000000  ................
    0000007f589f1048 0000000000000000 0000000000000000  ................
    0000007f589f1058 0000000000000000 0000000000000000  ................
    0000007f589f1068 0000000000000000 0000000000000000  ................
    0000007f589f1078 0000000000000000 0000000000000000  ................
    0000007f589f1088 0000000000000000 0000000000000000  ................
    0000007f589f1098 0000000000000000 0000000000000000  ................
    0000007f589f10a8 0000000000000000 0000000000000000  ................
memory near x10:
    0000007f8737ffc0 0000007f8737ffa8 000000557131f790  ..7.......1qU...
    0000007f8737ffd0 000000557131f790 0000007f8737ffc8  ..1qU.....7.....
    0000007f8737ffe0 0000007f8737ffc8 0000005570af9e90  ..7........pU...
    0000007f8737fff0 0000005571516520 0000007f8737ffe8   eQqU.....7.....
    0000007f87380000 0000007f8737ffe8 0000005570f1a080  ..7........pU...
    0000007f87380010 00000055714b9970 0000007f87380008  p.KqU.....8.....
    0000007f87380020 0000007f87380008 0000005570678fd0  ..8.......gpU...
    0000007f87380030 0000005570678fd0 0000007f87380028  ..gpU...(.8.....
    0000007f87380040 0000007f87380028 00000055713fdb10  (.8.......?qU...
    0000007f87380050 0000005570ebc320 0000007f87380048   ..pU...H.8.....
    0000007f87380060 0000007f87380048 00000055713e9050  H.8.....P.>qU...
    0000007f87380070 00000055713e9050 0000007f87380068  P.>qU...h.8.....
    0000007f87380080 0000007f87380068 00000055706a7d50  h.8.....P}jpU...
    0000007f87380090 00000055706a7d50 0000007f87380088  P}jpU.....8.....
    0000007f873800a0 0000007f87380088 00000055718025e0  ..8......%.qU...
    0000007f873800b0 000000557131fa30 0000007f873800a8  0.1qU.....8.....
memory near x16:
    0000007f62174540 0000005563abb938 0000007f8733c860  8..cU...`.3.....
    0000007f62174550 0000007f8732f1b4 0000007f8733da80  ..2.......3.....
    0000007f62174560 0000007f872f237c 0000007f8732df00  |#/.......2.....
    0000007f62174570 0000007f872fc2a8 0000007f8732a6f4  ../.......2.....
    0000007f62174580 0000007f872f1f00 0000007f872f7dd0  ../......}/.....
    0000007f62174590 0000007f875b2c84 0000007f872fc02c  .,[.....,./.....
    0000007f621745a0 0000007f872f9a28 0000007f8733c668  (./.....h.3.....
    0000007f621745b0 0000007f872f7b2c 0000007f8733d1c8  ,{/.......3.....
    0000007f621745c0 0000007f87347290 0000007f872f2ac0  .r4......*/.....
    0000007f621745d0 0000007f8733a880 0000007f872fc06c  ..3.....l./.....
    0000007f621745e0 0000007f8733ac98 0000007f8733dab0  ..3.......3.....
    0000007f621745f0 0000007f87334684 0000007f8733cc78  .F3.....x.3.....
    0000007f62174600 0000007f8732ea4c 0000007f872f9458  L.2.....X./.....
    0000007f62174610 0000007f8732fee0 0000007f8733d018  ..2.......3.....
    0000007f62174620 0000005563abba20 0000007f872f1900   ..cU...../.....
    0000007f62174630 0000007f8758d33c 0000007f872fdd50  <.X.....P./.....
memory near x17:
    0000007f872f1ec0 a90330cba90228c9 91004021a90438cd  .(...0...8..!@..
    0000007f872f1ed0 f240145f910140c6 d65f03c054fff4a1  .@.._.@....T.._.
    0000007f872f1ee0 d503201fd503201f d503201fd503201f  . ... ... ... ..
    0000007f872f1ef0 d503201fd503201f d503201fd503201f  . ... ... ... ..
    0000007f872f1f00 72001c27aa0003e8 2a0720e754000640  ....'..r@..T. .*
    0000007f872f1f10 aa0780e72a0740e7 5400032af101005f  .@.*...._...*..T
    0000007f872f1f20 540001cdf1003c5f 54000100f27c0443  _<.....TC.|....T
    0000007f872f1f30 7100807f8b030108 5400006b54000060  .......q`..Tk..T
    0000007f872f1f40 a93e1d07a93d1d07 92400c42a93f1d07  ..=...>...?.B.@.
    0000007f872f1f50 a93f1d078b020108 36180042d65f03c0  ......?..._.B..6
    0000007f872f1f60 36100042f8008507 36080042b8004507  ....B..6.E..B..6
    0000007f872f1f70 3600004278002507 d65f03c039000107  .%.xB..6...9.._.
    0000007f872f1f80 f2400c84cb0803e4 cb040042540000c0  ......@....TB...
    0000007f872f1f90 8b040108a9001d07 54fffc6df100fc5f  ........_...m..T
    0000007f872f1fa0 d1010042d1004108 a9021d07a9011d07  .A..B...........
    0000007f872f1fb0 a9841d07a9031d07 54ffff6af1010042  ........B...j..T
memory near x18:
    0000000002f3b000 ---------------- ----------------  ................
memory near x19:
    0000007f589f0e88 0031003600610066 0039003300320063  f.a.6.1.c.2.3.9.
    0000007f589f0e98 0039003200660062 0063006100300066  b.f.2.9.f.0.a.c.
    0000007f589f0ea8 0038003100340038 0031003700300033  8.4.1.8.3.0.7.1.
    0000007f589f0eb8 0033003800300036 002e003100320039  6.0.8.3.9.2.1...
    0000007f589f0ec8 0000000000000034 0000000000000000  4...............
    0000007f589f0ed8 0000000000000000 0000000000000000  ................
    0000007f589f0ee8 0000000000000000 0000000000000000  ................
    0000007f589f0ef8 0000000000000000 0000000000000000  ................
    0000007f589f0f08 0000000000000000 0000000000000000  ................
    0000007f589f0f18 0000000000000000 0000000000000000  ................
    0000007f589f0f28 0000000000000000 0000000000000000  ................
    0000007f589f0f38 0000000000000000 0000000000000000  ................
    0000007f589f0f48 0000000000000000 0000000000000000  ................
    0000007f589f0f58 0000000000000000 0000000000000000  ................
    0000007f589f0f68 0000000000000000 0000000000000000  ................
    0000007f589f0f78 0000000000000000 0000000000000000  ................
memory near x21:
    0000000000102eb8 ---------------- ----------------  ................
memory near x22:
    0000007f5c1feed8 ---------------- ----------------  ................
code around pc:
    0000007f61fc5120 f9400e61b4000420 52800002aa1303e0   ...a.@........R
    0000007f61fc5130 8b010c34b9400421 97ffff73aa1403e1  !.@.4.......s...
    0000007f61fc5140 340001c02a0003f5 52800001f9400273  ...*...4s.@....R
    0000007f61fc5150 aa1403e28b204273 97fc9e59aa1303e0  sB .........Y...
    0000007f61fc5160 aa1303e0b90002d5 a9415bf5a94053f3  .........S@..[A.
    0000007f61fc5170 9100c3fff94013fe f9400e62d65f03c0  ..@......._.b.@.
    0000007f61fc5180 b9400041d2800000 b900004151000421  ....A.@.!..QA...
    0000007f61fc5190 a9415bf5a94053f3 9100c3fff94013fe  .S@..[A...@.....
    0000007f61fc51a0 d2800000d65f03c0 d10083ff17fffff0  .._.............
    0000007f61fc51b0 f9000bfea90053f3 f9400c0537f80381  .S.........7..@.
    0000007f61fc51c0 6b06003fb94000a6 37f802e254000302  ..@.?..k...T...7
    0000007f61fc51d0 6b04005fb94004a4 2a0203f354000282  ..@._..k...T...*
    0000007f61fc51e0 97ffff79aa0003f4 b9400000b4000200  ....y.........@.
    0000007f61fc51f0 f9400681340001c0 eb01005f2a0003e2  ...4..@....*_...
    0000007f61fc5200 5280012154000142 f9400bfef9400280  B..T!..R..@...@.
    0000007f61fc5210 9b210a73d503201f a94053f38b130000  . ..s.!......S@.
stack:
    0000007f57fd3d40:  0000007f57fd3d80 0000007f872f13cc 
    0000007f57fd3d50:  0000000000000132 00000055702bbc40 
    0000007f57fd3d60:  0000000000000000 0000000000102fec 
    0000007f57fd3d70:  0000000000000000 0000000000103000 
    0000007f57fd3d80:  0000000000000000 0000007f61fc4fac 
    0000007f57fd3d90:  00000055702bbc40 0000000000000132 
    0000007f57fd3da0:  00000055702bbc40 0000007f5c1feed8 
    0000007f57fd3db0:  0000007f61fc5140 0000000000000738 
    0000007f57fd3dc0:  00000055716612f8 0000000000000000   #sp
    0000007f57fd3dd0:  00000055702bbc40 000000000000034d 
    0000007f57fd3de0:  0000007f61fc2ba0 6982ef7e1df62a69 
    0000007f57fd3df0:  0000000000000053 0000007f61fc29c8 
    0000007f57fd3e00:  0000005571805fd0 0000000013e2f800 
    0000007f57fd3e10:  0000000014313130 0000000000000000 
    0000007f57fd3e20:  0000000070056750 00000000139a8a60 
    0000007f57fd3e30:  0000000013e2f800 0000000014313130 
    0000007f57fd3e40:  0000007f6dd34058 0000000070178cc0 
    0000007f57fd3e50:  000000007fffffff 0000000000102eba 
    0000007f57fd3e60:  00000055714b9a78 000000557180c490 
    0000007f57fd3e70:  0000000000430000 0000007f57fd3e90 
    0000007f57fd3e80:  0000000075b64750 0000000200000000 
    0000007f57fd3e90:  1431313013e2f800 0000000000000000 
    0000007f57fd3ea0:  0000000075b5e2a0 0000000075b649d0 
    0000007f57fd3eb0:  000000007fffffff 0000000013e2f800 
    0000007f57fd3ec0:  0000000014313130 0000000000000000 
    0000007f57fd3ed0:  0000000070056750 00000000139a8a60 
    0000007f57fd3ee0:  0000000013e2f800 0000000014313130 
    0000007f57fd3ef0:  0000000000000000 0000007f6dd34860 
    0000007f57fd3f00:  13e2f80075b649d0 0000000014313130 
    0000007f57fd3f10:  7fffffff00000000 0000000000000000 
    0000007f57fd3f20:  0000000000000000 0000000000000001 
    0000007f57fd3f30:  0000000013e2f600 7fffffff00000000 
    0000007f57fd3f40:  0000000000000000 00000000135ed700 
    0000007f57fd3f50:  0000000075c022a0 0000000013e2f800 
    0000007f57fd3f60:  0000000000000000 0000000014313130 
    0000007f57fd3f70:  000000007fffffff 0000000013e058c0 
    0000007f57fd3f80:  0000000013d53fe0 0000000013d7d220 
    0000007f57fd3f90:  0000000000000000 0000007f6dd50148 
    0000007f57fd3fa0:  0000000075c022a0 0000000013bfb740 
    0000007f57fd3fb0:  0000000013bfb740 00000000135ed700 
    0000007f57fd3fc0:  0000000000000000 00000000135ed700 
    0000007f57fd3fd0:  0000000000000000 0000000075c02700 
    0000007f57fd3fe0:  0000000075c043c0 0000000013770e30 
    0000007f57fd3ff0:  0000000013e2f600 0000007f6dd51fdc 
    0000007f57fd4000:  0000000075c02700 0000000013e058c0 
    0000007f57fd4010:  0000000075b5da40 00000000ffffffff 
    0000007f57fd4020:  00000000135ed700 0000000000000000 
    0000007f57fd4030:  0000000075c042d0 0000007f6dc682fc 
    0000007f57fd4040:  0000000075c043c0 0000000013e058c0 
    0000007f57fd4050:  13b526a013d53fe0 0000000013682c80 
    0000007f57fd4060:  00000000137709e0 0000000000000000 
    0000007f57fd4070:  00000000135ed700 0000000075c042d0 
    0000007f57fd4080:  0000000013e058c0 0000000013770e30 
    0000007f57fd4090:  0000000013e2f600 0000007f6dc68118 
    0000007f57fd40a0:  0000000075c042d0 0000000013d7d220 
    0000007f57fd40b0:  0000000000000000 0000007f6dc77354 
    0000007f57fd40c0:  00000000135ed700 0000000013bfb740 
    0000007f57fd40d0:  000000007030d780 00000000736841f8 
    0000007f57fd40e0:  000000007030d780 0000000075c0a610 
    0000007f57fd40f0:  0000000075c0a610 0000000013e058a0 
    0000007f57fd4100:  0000000013bfb740 0000007f6bbd6d48 
    0000007f57fd4110:  0000000075c0a610 0000000075c0a6b0 
    0000007f57fd4120:  0000000000000001 0000000013b61800 
    0000007f57fd4130:  0000000013e058c0 0000000075c0a6b0 
    0000007f57fd4140:  0000000013e058e0 0000000013b61800 
    0000007f57fd4150:  0000000013e058c0 0000000000000000 
    0000007f57fd4160:  0000000013e2f600 0000007f6bbd73cc 
    0000007f57fd4170:  0000000075c0a6b0 0000000013d53fe0 
    0000007f57fd4180:  0000000014222f00 0000000075bef5d0 
    0000007f57fd4190:  0000000013e2f740 0000000075d971e0 
    0000007f57fd41a0:  0000000013b61800 0000000000000000 
    0000007f57fd41b0:  0000000013e058a0 0000007f6bbf1988 
    0000007f57fd41c0:  0000000075d971e0 0000007f6bffeca8 
    0000007f57fd41d0:  0000000075bef5d0 0000000013d53fe0 
    0000007f57fd41e0:  0000000000000001 0000000075bda0a0 
    0000007f57fd41f0:  0000000013e2f740 0000000013e2f740 
    0000007f57fd4200:  0000000013d7d220 0000000013d53fe0 
    0000007f57fd4210:  0000000014222f00 0000000013e2f600 
    0000007f57fd4220:  0000000013b61800 0000000013e2f600 
    0000007f57fd4230:  0000000013e058c0 0000007f6bbf39a8 
    0000007f57fd4240:  0000000075bda0a0 0000000075bebb20 
    0000007f57fd4250:  0000000013bfb6a0 0000000013e2f600 
    0000007f57fd4260:  0000000013e058a0 0000000013e058a0 
    0000007f57fd4270:  0000000013bfb6c0 0000000014247020 
    0000007f57fd4280:  13d53fe013bfb6a0 13e058c013d7d220 
    0000007f57fd4290:  0000000013e058a0 6982ef7e1df62a69 
    0000007f57fd42a0:  0000000014222f00 0000000075bda550 
    0000007f57fd42b0:  0000000000000000 0000000014222f00 
    0000007f57fd42c0:  0000000013d53fe0 0000000013e2f600 
    0000007f57fd42d0:  0000000013d53fe0 0000000000000000 
    0000007f57fd42e0:  0000000013e2f600 0000000000000000 
    0000007f57fd42f0:  0000000014222f00 0000007f6bbf4e0c 
    0000007f57fd4300:  0000000075bda550 0000000000000000 
    0000007f57fd4310:  0000000070072500 0000007fffffffff 
    0000007f57fd4320:  0000000013ac1b80 0000000000000080 
    0000007f57fd4330:  00000055ffffffff 0000000014614160 
    0000007f57fd4340:  0000000013e2f600 0000000075bd0b20 
    0000007f57fd4350:  0000000014222f00 0000000013d53fe0 
    0000007f57fd4360:  0000000000000000 0000000070005f00 
    0000007f57fd4370:  0000000013fea5f0 0000000000000000 
    0000007f57fd4380:  0000000070072500 0000007f6bec9418 
    0000007f57fd4390:  0000000075bd0b20 0000000000000000 
    0000007f57fd43a0:  0000000070072500 0000007f6bbf0d88 
    0000007f57fd43b0:  0000000075beaf80 0000000014614160 
    0000007f57fd43c0:  0000000013fea5f0 0000000075beb3e0 
    0000007f57fd43d0:  0000000013e2f600 00000000140500b0 
    0000007f57fd43e0:  000000001461fc00 0000007f6bbf0e38 
    0000007f57fd43f0:  0000000075beb3e0 0000000075ffc6c0 
    0000007f57fd4400:  0000000014078b80 0000000075ffc6c0 
    0000007f57fd4410:  0000000013bfb690 0000000013e05660 
    0000007f57fd4420:  0000000000000000 0000007f6d1025fc 
    0000007f57fd4430:  0000000075ffc6c0 000000001461fc00 
    0000007f57fd4440:  0000000013e7d200 0000007f6b0fbca8 
    0000007f57fd4450:  13d5ade013d6eda0 0000000014318cf0 
    0000007f57fd4460:  0000000157fd4b10 70005f0075ffd4e0 
    0000007f57fd4470:  0000000000000003 000000001463d6c0 
    0000007f57fd4480:  000000001461fc00 00000000000003e8 
    0000007f57fd4490:  0000000000000001 00000000140500b0 
    0000007f57fd44a0:  0000000075ffb8c0 000000001463d6c0 
    0000007f57fd44b0:  000000001461fc00 0000000000000000 
    0000007f57fd44c0:  0000000014658120 0000000013dd3080 
    0000007f57fd44d0:  0000000000000001 0000005570b80df0 
    0000007f57fd44e0:  0000000014078040 0000007f6cb1b640 
    0000007f57fd44f0:  0000000075ffb8c0 1461fc001463d6c0 
    0000007f57fd4500:  12c0a78000000000 0000000013e05180 
    0000007f57fd4510:  0000000000000054 0000000000000000 
    0000007f57fd4520:  0000000012c0a780 0000000013e05180 
    0000007f57fd4530:  0000000070279480 00000000761120b0 
    0000007f57fd4540:  0000000000000000 000000001463d6c0 
    0000007f57fd4550:  000000001461fc00 0000000014658120 
    0000007f57fd4560:  00000000140712e0 0000000013dd3080 
    0000007f57fd4570:  000028690000597a 0000005570b80df0 
    0000007f57fd4580:  0000000014078040 0000007f6d2587d0 
    0000007f57fd4590:  00000000761120b0 00000000759c84f0 
    0000007f57fd45a0:  0000000012c0a780 0000000013e05180 
    0000007f57fd45b0:  0000000012c24100 0000007f00000001 
    0000007f57fd45c0:  00000000759c81d0 0000000013dd3080 
    0000007f57fd45d0:  00000000140712e0 0000000013dd5940 
    0000007f57fd45e0:  0000000000000001 0000000013dd3040 
    0000007f57fd45f0:  0000000013e05060 0000007f6a6f473c 
    0000007f57fd4600:  13dd5940759c81d0 00000000759c7eb0 
    0000007f57fd4610:  0000000013dd3040 00000000140712e0 
    0000007f57fd4620:  00000000759c7eb0 0000000000000001 
    0000007f57fd4630:  00000000140712e0 0000000013dd5940 
    0000007f57fd4640:  0000000000000001 0000007f6a6f3b98 
    0000007f57fd4650:  00000000759c7eb0 0000000007b84b64 
    0000007f57fd4660:  0000000070a6fdc0 0000000000000000 
    0000007f57fd4670:  0000000014078040 0000000013dd5940 
    0000007f57fd4680:  00000000759c82c0 00000000759c9a40 
    0000007f57fd4690:  0000000070262740 0000007f57fd4b20 
    0000007f57fd46a0:  0000000000000000 0000007f6a6f49b0 
    0000007f57fd46b0:  00000000759c82c0 0000000073fb8a44 
    0000007f57fd46c0:  6fe3c22070358ac0 0000000013dd5940 
    0000007f57fd46d0:  0000000013d7d400 0000007f6afc49cc 
    0000007f57fd46e0:  00000000759c9a40 0000000072ca0298 
    0000007f57fd46f0:  0000000013d7d400 0000000013ece2c0 
    0000007f57fd4700:  0000000070262700 00000000735fc738 
    0000007f57fd4710:  0000000070262700 000028690000597a 
    0000007f57fd4720:  0000000013d7d400 0000000013ece2c0 
    0000007f57fd4730:  0000000013dd31e0 00000000735fc7bc 
    0000007f57fd4740:  0000000070262740 0000007f57fd4b20 
    0000007f57fd4750:  0000000070d960f3 0000000070264580 
    0000007f57fd4760:  0000000013ece2c0 0000000013d7d3c0 
    0000007f57fd4770:  0000000013dd31e0 0000000073fb2a2c 
    0000007f57fd4780:  0000007f70264580 0000007f84097040 
    0000007f57fd4790:  0000000000000039 0000000013d7d3c0 
    0000007f57fd47a0:  0000000000000039 0000005571805fd0 
    0000007f57fd47b0:  0000000070acb7e0 0000000100000000 
    0000007f57fd47c0:  000000007036ee80 00000000759c9950 
    0000007f57fd47d0:  0000000013d7d3c0 0000000013d7d3c0 
    0000007f57fd47e0:  0000000013dd3180 0000007f57fd4b20 
    0000007f57fd47f0:  0000000070d960f3 0000007f57fd4b0c 
    0000007f57fd4800:  0000000000000040 0000005570b80df0 
    0000007f57fd4810:  0000007f57fd48a0 0000007f6af77984 
    0000007f57fd4820:  13d7d3c0759c9950 0000005571805fd0 
    0000007f57fd4830:  0000007f57fd4840 0000000013dd3180 
    0000007f57fd4840:  0000000013e7c5e0 0000000070133440 
    0000007f57fd4850:  0000007f57fd49d8 0000000072d28e00 
    0000007f57fd4860:  0000000070133440 0000000000000000 
    0000007f57fd4870:  0000007f84465000 0000000000080001 
    0000007f57fd4880:  0000005571806060 0000007f84096a88 
    0000007f57fd4890:  13e7c5e000000000 0000007f842eec0c 
    0000007f57fd48a0:  0000007f57fd48d0 0000007f842744c4 
    0000007f57fd48b0:  0000007f57fd49d8 0000000070d960f3 
    0000007f57fd48c0:  0000007f57fd48d0 0000005571805fd0 
    0000007f57fd48d0:  0000007f57fd4970 0000007f842cd4e4 
    0000007f57fd48e0:  0000000013e7c5e0 0000000000000000 
    0000007f57fd48f0:  000000557180c490 0000000070133440 
    0000007f57fd4900:  0000000000000000 0000007f57fd4b20 
    0000007f57fd4910:  0000000070d960f3 0000007f8731d130 
    0000007f57fd4920:  0000007f57fd4970 0000007f8731d0a0 
    0000007f57fd4930:  0000000000000000 0000000000000000 
    0000007f57fd4940:  0000000000000000 0000000000000000 
    0000007f57fd4950:  0000007f57fd4970 0000007f842cd408 
    0000007f57fd4960:  0000000013e7c5e0 6982ef7e1df62a69 
    0000007f57fd4970:  0000007f57fd4a40 0000007f842eee44 
    0000007f57fd4980:  0000005571805fd0 0000005570b80df0 
    0000007f57fd4990:  0000007f57fd4b08 0000007f84465000 
    0000007f57fd49a0:  0000007f84465000 0000000000000001 
    0000007f57fd49b0:  00000000705c8e5c 0000007f8737f000 
    0000007f57fd49c0:  0000005570b80df0 0000007f84465000 
    0000007f57fd49d0:  0000000184465000 0000000000000000 
    0000007f57fd49e0:  0000000070d960f3 0000000400000001 
    0000007f57fd49f0:  0000007f57fd49f8 0000007f13e7c5e0 
    0000007f57fd4a00:  0000005571805fd0 0000005570b80df0 
    0000007f57fd4a10:  0000007f57fd4b08 0000007f84465000 
    0000007f57fd4a20:  0000007f57fd4a40 0000007f842eee28 
    0000007f57fd4a30:  0000005571805fd0 0000000000000000 
    0000007f57fd4a40:  0000007f57fd4b70 0000007f872f6de4 
    0000007f57fd4a50:  00000055714d38a0 00000055714d3920 
    0000007f57fd4a60:  00000055714d38b0 0000007f57fd4ba0 
    0000007f57fd4a70:  0000005571805fd0 0000007fdb3fddf8 
    0000007f57fd4a80:  0000007f842eeb6c 00000055714d3920 
    0000007f57fd4a90:  0000005571805fd0 0000007f84465000 
    0000007f57fd4aa0:  0000000000000000 0000000000000029 
    0000007f57fd4ab0:  000000000000001d 0000007f843b3408 
    0000007f57fd4ac0:  0000007f843b4320 0000007f843b3430 
    0000007f57fd4ad0:  0000000000000004 0000000000000000 
    0000007f57fd4ae0:  0000000000000000 0000000000000000 
    0000007f57fd4af0:  0000000000000000 0000007f57fd4b18 
    0000007f57fd4b00:  0000000000000000 0000000100550000 
    0000007f57fd4b10:  0000007f00550000 0000007f00430000 
    0000007f57fd4b20:  0000005571805fd0 000000557180c490 
    0000007f57fd4b30:  000000556fdca080 0000005571805fd0 
    0000007f57fd4b40:  0000005500000043 0000007f57fd4b00 
    0000007f57fd4b50:  0000000000000031 000000000000002e 
    0000007f57fd4b60:  0000005570b80df0 6982ef7e1df62a69 
    0000007f57fd4b70:  0000007f57fd4b90 0000007f872f30f4 
    0000007f57fd4b80:  000000000000597a 0000007f875d3e80 
    0000007f57fd4b90:  0000000000000000 0000000000000000 
    0000007f57fd4ba0:  0000007f57fd4ba0 00000055714d38a0 
    0000007f57fd4bb0:  0000000000000016 0000000000000000 
    0000007f57fd4bc0:  0000000000000000 6982ef7e1df62a69 
    0000007f57fd4bd0:  0000000000000000 0000000000000000 
    0000007f57fd4be0:  0000000000000000 0000000000000000 
    0000007f57fd4bf0:  0000000000000000 0000000000000000 
    0000007f57fd4c00:  0000000000000000 0000000000000000 
    0000007f57fd4c10:  0000005571805fd0 0000000000000000 
    0000007f57fd4c20:  0000000000000000 0000000000000000 
    0000007f57fd4c30:  0000000000000000 0000000000000000 
    0000007f57fd4c40:  000000557173b0d0 0000005570f859f0 
    0000007f57fd4c50:  0000000000000000 0000000000000000 
    0000007f57fd4c60:  0000000000000000 0000000000000000 
    0000007f57fd4c70:  0000000000000000 0000000000000000 
    0000007f57fd4c80:  0000000000000000 0000000000000000 
    0000007f57fd4c90:  0000000000000000 0000000000000000 
    0000007f57fd4ca0:  0000000000000000 0000000000000000 
    0000007f57fd4cb0:  0000000000000000 0000000000000000 
    0000007f57fd4cc0:  0000000000000000 0000000000000000 
    0000007f57fd4cd0:  0000000000000000 0000000000000000 
    0000007f57fd4ce0:  0000000000000000 0000000000000000 
    0000007f57fd4cf0:  0000000000000000 0000000000000000 
    0000007f57fd4d00:  0000000000000000 0000000000000000 
    0000007f57fd4d10:  0000000000000000 0000000000000000 
    0000007f57fd4d20:  0000000000000000 0000000000000000 
    0000007f57fd4d30:  0000000000000000 0000000000000000 
    0000007f57fd4d40:  0000000000000000 0000000000000000 
    0000007f57fd4d50:  0000000000000000 0000000000000000 
    0000007f57fd4d60:  0000000000000000 0000000000000000 
    0000007f57fd4d70:  0000000000000000 0000000000000000 
    0000007f57fd4d80:  0000000000000000 0000000000000000 
    0000007f57fd4d90:  0000000000000000 0000000000000000 
    0000007f57fd4da0:  0000000000000000 0000000000000000 
    0000007f57fd4db0:  0000000000000000 0000000000000000 
    0000007f57fd4dc0:  0000000000000000 0000000000000000 
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

**Comment by daogepiqian** [comment]
version 4.5.0

**Comment by developernotes** [comment]
Hi @daogepiqian 

Do you have the device on hand that causes the crash? If so, are you able to run the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) and report the results?

**Comment by daogepiqian** [comment]
yes, it is a table error, i have fix it
