### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sulemankhan4** [sqlcipher/android-database-sqlcipher#582]
In Some Devices, App is crashing and In Our Crashlytics, we are receiving error as followed.

Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/~~Kn2Qwh2bbr172NQZDorbLQ==/in.medibuddy-MnEjK355TPnXCFrnKrFf7Q==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libsqlcipher.so" is 64-bit instead of 32-bit

By going through other issues, i have used apk tool to decompile apk and check lib folder.

In lib folder, we have only **arm64-v8a** folder with 5 files

1. libagora-crypto.so
2. libagora-rtc-sdk.so
3. libagora-rtm-sdk-jni.so
4. libsqlcipher.so
5. libtoolChecker.so

![MB](https://user-images.githubusercontent.com/92019030/150978137-a6170476-3153-4520-ac22-6891814a6e41.png)

libsqlcipher.so is already present in lib folder, than also its giving error.

**Comment by sulemankhan4** [comment]
How can i ship support for all architecture in our application ?
Also do you have an example for obj dump.
It might be helpful or i can share .so files here.

**Comment by developernotes** [comment]
Hi @sulemankhan4,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
