### ISSUE TITLE
After I use SQLCipher in Room, I get error: no to collation sequence: localized:

### ISSUE THREAD

**Issue by zhumj** [sqlcipher/android-database-sqlcipher#584]
After I use SQLCipher in Room, I get error:
`Caused by: net. Sqlcipher. Database. SQLiteException: no to collation sequence: localized:, while compiling: SELECT * FROM contact_data WHERE name LIKE '%' || :queryStr || '%' ORDER BY name collate localized ASC`

**Comment by zhumj** [comment]
Using UNICODE is the same error

**Comment by zhumj** [comment]
`ColumnInfo(collate = LOCALIZED)` is used for Room, but it is not possible to get the same result. Obviously, Room's "LOCALIZED" rule is different from SQL's "LOCALIZED" rule.

**Comment by sjlombardo** [comment]
Hello @zhumj - SQLCipher does not support LOCALIZED or UNICODE collations. You could either remove the use of the collation or investigate one of the workarounds here:

https://discuss.zetetic.net/t/workaround-for-using-androids-localized-collator-after-3-5-0-update/1515/8
