### ISSUE TITLE
net.sqlcipher.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0

### ISSUE THREAD

**Issue by Wackaloon** [sqlcipher/android-database-sqlcipher#585]
### Expected Behavior

use operation "SELECT * FROM" from an interface
code:
```
    @Transaction
    @Query("SELECT * FROM models_table")
    abstract fun getMyModels(): Single<List<MyModel>>
```
another place that throws that error is 
```
    @Transaction
    fun deleteAllAndInsert(models: List<MyModel>) {
        deleteAll()
        insertOrReplace(models)
    }
```
I assume the @Transaction part is what important in such cases

### Actual Behavior
Some users experience crash with a stacktrace
```
Caused by net.sqlcipher.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
       at net.sqlcipher.AbstractCursor.checkPosition(AbstractCursor.java:562)
       at net.sqlcipher.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:222)
       at net.sqlcipher.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:43)
       at android.database.CursorWrapper.getString(CursorWrapper.java:141)
       at net.sqlcipher.database.SQLiteDatabase.getResultFromPragma(SQLiteDatabase.java:3186)
       at net.sqlcipher.database.SQLiteDatabase.isWriteAheadLoggingEnabled(SQLiteDatabase.java:709)
       at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:485)
       at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
       at my.app.feature.MyModelsDao_Impl.getMyModels(MyModelsDao_Impl.java:752)
```

root cause as I understand is
```
  public boolean isWriteAheadLoggingEnabled() {
    Pair<Boolean, String> result = getResultFromPragma("PRAGMA journal_mode;");
    return result.first ? result.second.equals("wal") : result.first;
  }

    private Pair<Boolean, String> getResultFromPragma(String command) {
        Cursor cursor = rawQuery(command, new Object[]{});
        if(cursor == null) return new Pair(false, "");
        cursor.moveToFirst();
        String value = cursor.getString(0);  // <--- this place crashes
        cursor.close();
        return new Pair(true, value);
    }
```

### Steps to Reproduce

We are not able to reproduce that crash on our devices, yet we see it from some users in Firebase, on average it affects 0.5% of our users each month.

SQLCipher version 4.5.0

SQLCipher for Android version: 4.5.0

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)? 
no

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @Wackaloon 

That is a particularly odd situation, `PRAGMA journal_mode` should aways return a value. I have just pushed up a [change](https://github.com/sqlcipher/android-database-sqlcipher/commit/2a8eb64ce037a7007c47f7c8b2312074bf6586b1) to check the result of `moveToFirst()`. You may also wish to verify that the SQLCipher library is properly loaded prior to attempting to query this.

**Comment by Wackaloon** [comment]
Will check database initialisation code, thanks for the suggestion and quick fix for the cursor
