### ISSUE TITLE
SQLiteOpenHelper not calling onUpgrade

### ISSUE THREAD

**Issue by Alexander-Campbell** [sqlcipher/android-database-sqlcipher#59]
Hello,
I have upgraded my version of SQLCipher from 1.1.0 to 2.0.8, in order to get this to work I require to call upgradeDatabaseFormatFromVersion1To2 on the 1.1.0 DBs. How I have tried to implement this is to increase the DB version and then in the onUpgrade function call the upgradeDatabaseFormatFromVersion1To2 function.

The problem I am having is the onUpgrade function is not being called when I create my SQLiteOpenHelper class. I have check the versions of the DB using getVersion(), they are correct. I have also manually called the upgradeDatabaseFormatFromVersion1To2 function on a 1.1 DB and when I import the DB it works fine.

Any ideas why the onUpgrade is not firing, I thought of function template changes, or maybe the order in which I am calling these functions.

**Comment by BharathiKasi** [comment]
hi all actually when you change the database version on
public className extends sqliteOnHelper{

className(Context context){
super(context, // your database name--  DATABASE_NAME, // you cursorFactory -- null, you current version -- 2);
}
}
so the version is match with older version then it won't invoke the method called 
onUpgrade  (SQLitedatase,int olderversion ,int newVersion) 
if suppose you enter the new version then it wil invoke the onUpgrade method.
i am newer to android as of my knowledge i post this .
Thank you.

**Comment by developernotes** [comment]
Hi @BharathiKasi 

Yes, increasing the version number supplied to the constructor argument of the `SQLiteOpenHelper` will trigger `onUpgrade` when requesting the database. If you have any further questions related to SQLCipher, please feel free to post them in our Community Discuss site [here](https://discuss.zetetic.net/c/sqlcipher). Thanks!
