### ISSUE TITLE
Getting UnsatisfiedLinkError error

### ISSUE THREAD

**Issue by mane91** [sqlcipher/android-database-sqlcipher#593]
### Expected Behavior
It should work on all the devices.

### Actual Behavior
I am getting the below issue on Samsung Android 8.1.0

**Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/<Pacakge_Name>-fUSOv9ma3DwZv4eW/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libsqlcipher.so" segment 1: Permission denied**

### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):
**Version:  4.4.3**

SQLCipher for Android version:

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @mane91 

What are the results of running the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests) on this device?

**Comment by maxkohne** [comment]
We have also been experiencing these errors / crashes according to Crashlytics.

### SqlCipher Version
`4.5.1`

### Android OS Versions
- 8, 9, and 12

### Affected Devices
- Redmi 6A
- Galaxy Tab S3
- Galaxy J7 Prime
- Galaxy Tab S8
- Galaxy S22 Ultra
- Galaxy A53 5G

We do not have any of these devices in-house so we cannot replicate ourselves.

### ABI Filters

Here is what we have in `build.gradle`. These should be supported according to the documentation here.
```
ndk { abiFilters 'x86_64', 'x86', 'arm64-v8a', 'armeabi-v7a' }
```

### Some Stacktraces
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/~~6xOJXd8CMivI3P4yKqoyGQ==/<PACKAGE_NAME>-c_RjLwCh_Eh18RFEGVMIPg==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libsqlcipher.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
```

or

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/<PACKAGE_NAME>-lJSaVGaeq_Y-qxkCbIFHBQ==/base.apk"],nativeLibraryDirectories=[/data/app/<PACKAGE_NAME>-lJSaVGaeq_Y-qxkCbIFHBQ==/lib/arm, /system/lib]]] couldn't find "libsqlcipher.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
       at java.lang.System.loadLibrary(System.java:1669)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
```

**Comment by developernotes** [comment]
Hi @maxkohne 

Are you bundling other third-party libraries which contain native libraries supporting architectures beyond your current `abiFilters` list? If not, could you try removing the `abiFilters` from your `build.gradle` to see if that makes a difference?

**Comment by maxkohne** [comment]
Yes we currently use other libs with NDK code

**Comment by maxkohne** [comment]
Hmm actually one coworker has a `Galaxy S22 Ultra` and it appears to work for him -- not sure why there is a crash report for one of our customers out in the wild... Here is a pic of a crashlytics report for that device from a random user.... Nothing seems off.

![Screen Shot 2022-08-15 at 3 48 19 PM](https://user-images.githubusercontent.com/7354768/184733785-7007b37c-5cb7-4b64-a18c-c2198e3b8fc6.png)

**Comment by developernotes** [comment]
Hi @maxkohne 

Thanks for the additional details. We've heard of issues regarding the loading of native libraries on Android. One approach you might consider is utilizing the `LibraryLoader` interface within SQLCipher for Android in conjunction with the [Relinker project](https://github.com/KeepSafe/ReLinker). One you add the relinker dependency, you will just adjust your SQLCipher for Android initialization from this:

```
SQLiteDatabase.loadLibs(this);
```

to something like this:

```
Context context = this;
SQLiteDatabase.loadLibs(context, libraries -> {
    for (String library : libraries) {
      ReLinker.loadLibrary(context, library);
    }
  });
```

If you give that a try, would you report back your findings?

**Comment by maxkohne** [comment]
Yeah. I will try to get this potential solution in this week for our next release. I'll report back my findings in a couple of weeks after we release and give it some time to go out into the wild to our customers.

Thanks for the help!

**Comment by maxkohne** [comment]
I want to report back on the Relinker fix that was proposed above. It appears to have solved our crashes (mostly)! Our crashes have almost been completely eliminated.

We actually got a couple of new crashes with **almost** the same error. It's still an `UnsatisfiedLinkError` with a slight twist.

Here is the new stracktrace:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/[app_id]-pcUR68wvsP3sAv1B/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libsqlcipher.so" segment 1: Permission denied
       at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
       at java.lang.System.loadLibrary(System.java:1669)
       at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:227)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:244)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:223)
       at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:216)
       at net.sqlcipher.database.SupportHelper.<init>(SupportHelper.java:31)
       at net.sqlcipher.database.SupportFactory.create(SupportFactory.java:43)
```

In the previous crash reports (noted above in my previous post), we were getting `Fatal Exception: java.lang.UnsatisfiedLinkError.... not found` but now, after the Relinker code, we are solely getting `Fatal Exception: java.lang.UnsatisfiedLinkError... Permission denied`. So Relinker fixed the "not found" case.

The "Permission denied" crash is only happening on one device, the `Samsung Galaxy J7 V` according to our reports. You can see in the stacktrace that the path starts with `mnt/asec/....` which seems to indicate a mounted disk of some sort rather than internal storage. It's odd because we only allow our app to be installed on internal storage (from my understanding).

All things being said, I would say that the Relinker solution fixed the crash for us though! Thanks so much. I'll have to figure out the "Permission denied" `UnsatisfiedLinkError` case now. I highly doubt it's related to Relinker nor SqlCipher.

**Comment by developernotes** [comment]
Hi @maxkohne 

That's great news, we are happy to hear ReLinker helped alleviate the issue!

**Comment by developernotes** [comment]
Hi @maxkohne,

Quick question: do you deploy your application using [App Bundles](https://developer.android.com/guide/app-bundle)?

**Comment by maxkohne** [comment]
Yes we do. Would that have something to do with this?

**Comment by maxkohne** [comment]
@jae-12 our minSdk is currently 28. I actually never noticed the minSdk README docs. Interesting...

I looked our crashlytic reports again. They have gone down pretty significantly since we introduced Relinker a while ago. However, we still get a small amount of crashes.
