### ISSUE TITLE
Attempt to get length of null array when calling  int update(String table, int conflictAlgorithm, ContentValues values, String whereClause, Object[] whereArgs) with null whereArgs

### ISSUE THREAD

**Issue by mtotschnig** [sqlcipher/android-database-sqlcipher#615]
Similar to #533 
java.lang.NullPointerException: Attempt to get length of null array is still thrown in the following method:
https://github.com/sqlcipher/android-database-sqlcipher/blob/62166f771cd04c6400380add5ceec492cfb87d75/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L2971

SQLCipher for Android version: 4.5.3

**Comment by developernotes** [comment]
Hi @mtotschnig,

I've included a fix for this in `master` which will be included in the next public release. Thanks for the report!
