### ISSUE TITLE
4.5.3, the relevant so file depends on the component version

### ISSUE THREAD

**Issue by android-xujie** [sqlcipher/android-database-sqlcipher#623]
sqlitecpp in  libsqlcipher.so
sqlite in  libsqlcipher.so
sqlcipher in libsqlcipher.so
libc++abi in libsqlcipher.so
Please help me provide the version information of relevant components. It is urgent, please

**Comment by developernotes** [comment]
Hi @android-xujie,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
