### ISSUE TITLE
Your application is using a defective version of the OpenSSL library that may cause the application to crash. 

### ISSUE THREAD

**Issue by luesky25** [sqlcipher/android-database-sqlcipher#624]
Dear technical team,

I have used sqlcipher to encrypt the database, but when I uploaded it to Google Market, it showed the following:
    Defective version of OpenSSL
   Your application is using a defective version of the OpenSSL library that may cause the application to crash. Please update to a fixed 
   OpenSSL version.
    Defective version:
   OpenSSL 1.1d in lib/armeabi-v7a/libsqlcipher.so

I have checked the information and found that openssl needs to be updated to the version above 1.1.1.g to avoid this problem. Please help us check as soon as possible. Thank you.

### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:
4.5.3
Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
![image](https://user-images.githubusercontent.com/5166437/232993705-237543cf-8ab1-4d97-9fa7-950808a5ec91.png)

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hi @luesky25,

You should update your version of SQLCipher for Android. SQLCipher for Android 4.5.3 (the latest version currently) uses OpenSSL 1.1.1s for non-FIPS packages.

**Comment by luesky25** [comment]
ok，thanks
