### ISSUE TITLE
Encrypt Preloaded Database. Is this possible?

### ISSUE THREAD

**Issue by thomasgatt** [sqlcipher/android-database-sqlcipher#63]
I am using a preloaded database (stored in the assets folder) of my android project.

I want to encrypt the already defined database. Is this possible please?

Thanks for your time.

**Comment by developernotes** [comment]
Hello @chitabi 

We use Github Issues to track defects in the SQLCipher library itself. This question is best suited for our community discuss site. Please feel free to post your question in detail [here](https://discuss.zetetic.net/c/sqlcipher). Thanks!
