### ISSUE TITLE
new version not support armeabi

### ISSUE THREAD

**Issue by hhymason** [sqlcipher/android-database-sqlcipher#637]
i'm upgrade this sdk verion 3.5.8->4.5.0，but the application is not launch，because libsqlcipher.so is not found，my project adbFilter only support "armeabi" and "arm64-v8a"，whie use 3.5.8 is no problem，but when i finish the upgrade，the 32-bit device is not support，now，i need the libsqlcipher.so for "armeabi" add to my project，download source code build is failed，the environment has lot of problem，change abifilter will have more risk，so，can you help me？ Thanks
### Steps to Reproduce

SQLCipher version (can be identified by executing `PRAGMA cipher_version;`):

SQLCipher for Android version:

Are you able to reproduce this issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

*Note:* If you are not posting a specific issue for the SQLCipher library, please post your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by developernotes** [comment]
Hello @hhymason,

You should adjust your `abiFilters` to be `armeabi-v7a` instead of `armeabi`. `armeabi` support was removed from the Android NDK in r17 so it would be difficult to build a newer library. `armeabi-v7a` is a 32-bit ABI.

**Comment by hhymason** [comment]
Thanks @developernotes ,

**Comment by hhymason** [comment]
Thanks @developernotes ,
In addition change abiFilters,there are  other solutions?

**Comment by developernotes** [comment]
Hello @hhymason,

No, not that I'm aware of.
