### ISSUE TITLE
Reduce Import Size

### ISSUE THREAD

**Issue by mikebevz** [sqlcipher/android-database-sqlcipher#91]
I know it might be to early to request this but it would be great to think about reducing the size of the jars that have to be imported. 
5+Mb now it's too much imho.

**Comment by AhmadullahSaikat** [comment]
Please reduce the library size..
The size is 7.1 MB.
I don't need to support api<15.
For Api<11 this library uses many codes and libraries.
Which is full of garbage to me.
Please remove the garbage codes and libraries which is used to support api <15.
Or make a library again which will support API >= 15
