### ISSUE TITLE
Error:at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)!

### ISSUE THREAD

**Issue by iamzhx** [sqlcipher/android-database-sqlcipher#92]
03-14 12:23:40.290: E/AndroidRuntime(8447): FATAL EXCEPTION: main
03-14 12:23:40.290: E/AndroidRuntime(8447): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mysql/com.example.mysql.MainActivity}: net.sqlcipher.database.SQLiteException: not an error
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1817)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1833)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.ActivityThread.access$500(ActivityThread.java:124)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1026)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.os.Looper.loop(Looper.java:132)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.ActivityThread.main(ActivityThread.java:4128)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at java.lang.reflect.Method.invokeNative(Native Method)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at java.lang.reflect.Method.invoke(Method.java:491)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at dalvik.system.NativeStart.main(Native Method)
03-14 12:23:40.290: E/AndroidRuntime(8447): Caused by: net.sqlcipher.database.SQLiteException: not an error
03-14 12:23:40.290: E/AndroidRuntime(8447):     at net.sqlcipher.database.SQLiteDatabase.dbopen(Native Method)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at net.sqlcipher.database.SQLiteDatabase.<init>(SQLiteDatabase.java:1956)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:906)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:949)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:107)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at com.example.mysql.MainActivity.onCreate(MainActivity.java:24)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.Activity.performCreate(Activity.java:4397)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1074)
03-14 12:23:40.290: E/AndroidRuntime(8447):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1781)
03-14 12:23:40.290: E/AndroidRuntime(8447):     ... 11 more

![image](https://f.cloud.github.com/assets/3860226/257488/5015d422-8c60-11e2-876b-a7763b465c7e.png)

**Comment by rontho** [comment]
Hello,

did you find a way to fix that issue ? I'm facing the exact same problem right now, and I don't really know why this is happening. 

If you have any clue, please let me know.

Thanks.

**Comment by brodybits** [comment]
Please make sure you have installed the latest version (which is 3.3.1). This looks like an installation problem.

**Comment by ilber** [comment]
Hi @brodybits I have the latest community edition version (3.3.1) and I have the same problem. Is there anyway to know where is the problem? @rontho did you fixed the issue somehow?

Thanks guys.

**Comment by rontho** [comment]
Hi @ilber,

I have actually fixed that issue by following this article https://www.zetetic.net/sqlcipher/sqlcipher-for-android/

You need to be really careful and include all the required so files and the zip file. As long as I can recall the issue was due to mu password. You have to use the same exact password to encrypt and decrypt you database. Try to use something hardcoded first before you add any logic to hide the password somehow. 

Sorry I can't help more but it's definitely an installation issue.
